#+TITLE:       JL work diary record
#+AUTHOR:      辛佳斌(lawrence)
#+DATE:        [2017-02-13 周一 16:31]
#+EMAIL:       lawrencejiabin@163.com
#+KEYWORDS:    the page keywords, e.g. for the XHTML meta tag
#+LANGUAGE:    language for HTML, e.g. ‘en’ (org-export-default-language)
#+TODO:        TODO

#+SEQ_TODO: TODO(T!) | DONE(D@)3  CANCELED(C@/!)  
#+SEQ_TODO: REPORT(r) BUG(b) KNOWNCAUSE(k) | FIXED(f)

* 20171128
** wifi--iis输入
   #+BEGIN_SRC C
   dac_channel_on(MUSIC_CHANNEL, FADE_ON);
	 audio_link_init();
	 //audio_link_close(1);
	 dac_set_samplerate(44100,1);
    #if 1
        dac_write((u8 *)buf_addr0,DAC_BUF_LEN);
    #else
        extern int soft_eq_run(u8 *buf, u32 len);
        soft_eq_run((u8 *)buf_addr0, DAC_BUF_LEN);
		cbuf_write_dac((short*)buf_addr0, DAC_BUF_LEN); //DAC 实时播放
    #endif
    #+END_SRC
* 20171127
** DAB案子
   切模式会串音，是因为自动解mute，ST程序不会一直发送mute导致。
* 20171124
** DAB
   切模式串音问题，BT播放模式，切换一圈后进入FM/DAB，蓝牙播放音乐串音到FM/DAB
** 汉普6902A车充

* 20171123
** DAB
   dac_AmuxGain_en(1);放大linein声音一倍。
   linein声音输入源幅度太小，可设置此项。只能固定放大一倍。
* 20171122
* 20171121
** 汉普车充
   SD和IIC复用，在SD播放高码率的文件，会有掉线情况，此时要限制发送消息的数量。
   避免一下子发送太多，累积在消息池中。
* 20171120
** 汉普车充
   6902A的SD和iic复用，当在sd播放的时候，操作iic时，要等待sd空闲后，才能关闭sd控制器，才操作iic。
* 20171117
** 汉普车充
   12V检测，最多只能做到0.1V的精度。
* 20171116
** BLE发送数据量
   static u32 app_data_send(u8 *data,u16 len)
   底层会有2K的空间，进行分包发送，每包20字节。
   但是不建议使用太大数据量。
   发送速度，跟时间间隔有关。
* 20171115
** 汉普车充
   在调频点的时候，暂停音乐播放。
* 20171114
** 汉普车充
   SD卡和IIC复用，待处理。
** 发射器SDK
   C版晶圆需要打补丁，才能支持无线升级。
* 20171113
** 实捷C26S发射没声音
   QN8027有一分钟自动关闭发射的功能，在初始化的时候会有关闭此功能。
   但是由于I2C同时外挂QN8027和AD2523，发送给QN8027的数据存在AD2523的命令字时，
   data会被AD2523控制到，导致发送给QN8027的数据出错，写错寄存器。
* 20171108
** DAB案子
   切换linein通道，会有上一个通道的尾音，可能底层有个buf没有清除。
   目前改成，在切换通道先发一段静音的buf。
   #+BEGIN_SRC C
   void ladc_isr_callback(void *ladc_buf,u32 buf_flag,u32 buf_len)
   {
      extern u8 switch_aux_channel_flag ;
      if(switch_aux_channel_flag)
      {
        putchar('l');
        for(i=0;i<DAC_SAMPLE_POINT;i++)
        {
            ladc_l[i] = 0;
            ladc_r[i] = 0;
        }
      }
   }
   #+END_SRC
** 威益德死机
   __attribute__((aligned(4)));
   强制地址对齐，方便底层指针转换。

* 20171107
** 伦茨海科46点烟器通话调试
   46配8007，在通话双方同时说话的时候，回声压制不住，会有漏音，听起来有点卡顿的感觉。
   通话回声参数，配3和1400，效果OK
   有一个手机，远端能听到回声尾音，其他手机就没事，此问题客户忽略处理。
* 20171106
** DAB案子
   IIS接收还是不行。
* 20171103
** 汉普音箱
   测试MIX2910功放，3.3V直流偏置正常，没有掉电情况。
** USB-HID
   #+BEGIN_SRC C
   typedef enum
   {
 	     DEVICE_DESCRIPTOR_STR = 0x0,
 	     CONFIG_DESCRIPTOR_STR,
 	     MSD_CONFIG_DESCRIPTOR ,
 	     AUDIO_CONFIG_DESCRIPTOR,
       SPEAKER_CONFIG_DESCRIPTOR,
       MIC_CONFIG_DESCRIPTOR,
 	     HID_CONFIG_DESCRIPTOR,
 	     HID_REPORT_DESCRIPTOR,
 	     LANGUAGE_STRING,
 	     IMANUFACTURE_STRING,
 	     IPRODUCT_STRING,
       ISERIAL_NUMBER_STRING,
 	     AUDIO_VOL,
 	     MIC_VOL,
       MAX_STRING = 14,
   }USB_DES;
   u32 user_set_descriptor(USB_DES index, void * pstring, u32 len);
   ///默认HID按键是调用以下函数：
   {
       os_mutex_pend(&mass_mutex, 0);
       usb_hid_control((u32)*((u32 *)parm));
       os_mutex_post(&mass_mutex);
   } 
   ///函数体是：
   void usb_hid_control(u32 key)
   {
       usb_hid_key(key);//默认发送2byte 码值
       usb_hid_key(0);
   }
   结构体声明：
   extern OS_MUTEX mass_mutex AT(.usb_buf);
   #+END_SRC

* 20171102
** ARGUN
   协议有改动，更改程序，已发出
** 汉普音箱
   触摸按键增加电话控制功能，电量获取换算成百分比，触摸按键灵敏度调到300。
* 20171101
** 汉普音箱
   MIX2909功放会有噗噗声，是在IN脚，维持3.3V的时候，会有1V左右的掉电，后又升回3.3V导致。
   功放产商寄2910的芯片来测试。
* 20171031
** DAB发射器
   出差实捷，调试功能，基本功能都有了，细节问题处理还未解决。
*** 切换模式会有噗声
    切换到DAB模式，会有3声噗声，切换到FM模式，也会有噗声，需要软件处理mute掉。
*** 蓝牙发射突然没有声音，只能重启
    概率很低，很难测试到，其他操作都正常，切换通道都不行。
*** 46的机子回连时，link-key会丢失，导致回连不上
    目前做法是，开机的回连，做成5次。但是会导致进入搜索设备变慢。

* 20171030
** ARGUN
   区分配对状态和连接状态的广播包，修改蓝牙名和MAC地址。
   摇杆数据，没反应，客户更新APP，已OK。
   函数app_data_send()涉及信号量，在没有连接的情况下，会导致调用该函数的线程挂起。
** DAB蓝牙发射器
   选取设备列表，断开重连等功能，还没调试。
* 20171027
** ARGUN
   connect_interval的单位是1.25ms，如果发送太快，可能会导致底层积压数据包，等到间隔时间到了，才一起发送出去。
   adv_interval的单位是0.625ms，
** 汉普BLE音箱
   替换蓝牙库bluetooth_lib.a，不会死机，但是回连不上，手机主动连接，会卡死，取消连接，重新连，能正常。
   替换以前对箱的库cpu_lib_ac690x.a，解决回连不上问题。
* 20171025
** 汉普BLE音箱
*** 汉普音箱在EDR和BLE同时连上后切模式回到蓝牙模式死机
   在初始化蓝牙后，发送蓝牙回连命令死机。
*** 触摸误触
    提高触摸按下门槛，避免干扰。
* 20171024
** 实捷DAB案子
*** 蓝牙再次搜索异常
    __set_inquiry_again_flag(0);///此函数底层没做好，只能置0
    在应用层自己添加，BT_STATUS_INQUIRY_COMPLETE，反馈时，再次搜索就行。
    #+BEGIN_SRC
    case BT_STATUS_INQUIRY_COMPLETE:
		   puts("BT_STATUS_INQUIRY_COMPLETE\n");
		   /*search bluetooth device again*/
       if(BT_STATUS_WAITINT_CONN == get_bt_connect_status()){
          puts("BT_STATUS_WAITINT_CONN\n");
          user_send_cmd_prepare(USER_CTRL_SEARCH_DEVICE,0,NULL);
       } 
		break;
    #+END_SRC
** 汉普车充
*** 在14V供电的情况下打电话时死机
    应该是LDO降压模块，压差太大，从14V降到5V，导致不稳定。
* 20171023
** 实捷DAB案子
*** 蓝牙搜索连接link-key丢失
    第一次连接上后，再次搜索配对连接时，就会出现，重新下载程序，也不行。
    更新振荣发的bluetooth_lib.a，可解决。
** 汉普ble音箱
*** 触摸按键和AD按键分开检测发送
    触摸按键，时不时会反馈，导致AD按键检测不准。
** 飞灵特ARGUN
   更新product-key，生成时用，可用于发行版APP
   #+BEGIN_SRC
   NAME  ：ARGunPro
   VID   ：0xFFFC
   KEY   : 0x3e, 0x9b, 0x7d, 0xb9, 0xbe, 0x69, 0xc2, 0xa5, 0x7c, 0x6c, 0x18, 0x34, 0xb, 0xd9, 0xdf, 0xfe
   MAC   ：FF:FF:00:00:00:01~FF:FF:00:00:00:FF
   #+END_SRC
* 20171020
** 汉普ble音箱
*** 苹果搜索ble名字显示unknown
    由于广播包的数据，不正常导致。
** 实捷DAB案子
*** IIS通信声音不正常
    参考：极性CPOL和相位CPHA，修改IIS的设置。
* 20171019
** 实捷DAB案子
*** IIS通信声音变调
    由于缺失MSCK，DAB自己外挂晶振，和主控自己产生的MSCK，会有相位差，导致声音不同步。
    DAB芯片改用，从主控24M引线，还是不行。

* 20171018
** 实捷DAB案子
*** IIS从机接收不正常
    69系列IIS做从机，必须输出SCLK、LRSCK时钟给其他芯片，不支持输入时钟，
    可理解为只能主动接收数据，不支持被动接收数据。
** 德科创ble部分手机会掉线
   苹果的5、5s、6、6p、红米1s、oppo r11，在连接了2.1后，ble的4.2连接会容易掉线。

* 20171017
** 汉普触摸音箱
   焊点引线到外壳，需要贴块铜皮，增大电容效应的面积，增强抗干扰能力。
** 实捷DAB蓝牙发射
*** 发射伴随哒哒声
    由于串口发送数据太多太过集中，while循环时间过长，导致发射数据卡顿。
*** 蓝牙搜索时获取蓝牙名包出错
    有些方案，在搜索的时候，未连接时，获取的蓝牙名包不正常，振荣处理中。
*** IIS输出板子又有模拟输出
* 20171016
** 实捷DAB蓝牙发射配其他方案音箱会有哒哒声
   寄给振荣分析
*** IIS通信的时钟输出
    目前为stm32输出。可能主控这边不能匹配。16bits数据。
** 汉普6905B蓝牙音箱带触摸
   触摸的引线，经过喇叭和电池，灵敏度会受到影响。
   按键有一个焊盘，应该悬空，但是接地，要改板
   原理图用成6905A的引脚图，DACR对应PA1。
   512K的空间不够，可以修改提示音为单声道，提醒客户后期语音，不能太长。
* 20171014
** 中翔达69蓝牙耳机通话效果
   靓颖电子4款蓝牙耳机通话效果，和建荣的对比。
   比较注重清晰度，音色比建荣较差。
* 20171013
** 汇杰芯蓝牙对箱连接问题
   未连接时，要一直处于能背搜索的状态。
   在匹配过蓝牙对箱后，函数get_total_connect_dev()会一直返回1，导致蓝牙不能被搜索到，
   可改成判断get_bt_connect_status()的蓝牙状态。
* 20171012
** 汉普车充6905C
   在app_server_read_callback()中，会调用2次，第一次调用buffer = 0，buffer_size = 0，要返回buffer_size的大小。
   第二次调用会以上次的buffer_size，填充buffer的内容。
** 狂热者APP开发
   带时钟、闹钟功能的APP。我们提供数据对接，APP开发由客户处理。
   使用TI BLE USB Dongle协议分析抓包，配合电脑端SmartRF Packet Sniffer进行显示。

* 20171011
** 飞灵特6909B用3.3V推灯
   主控3.3V驱动能力较弱，接三极管推灯，可能会影响到电源。
** 汉普车充6905C
   采用新的BLE协议，带频点的设置和读取，电量检测等功能。
* 20171010
** 晶科USB描述符
   区分读卡器名称和声卡名称
   属性--总线已报告设备描述--值
   如果之前识别过，需要先把br17卸载掉，再重启电脑，才就能重新挂载，显示出字符串来。
** 汉普车充
   采用AC6905C + QN8027,带BLE协议。
   耳机检测，电阻改用0R。
** 中翔达i7-6904C对耳蓝牙距离短
   充电座的电线会穿过蓝牙天线，需要用胶纸，将电线紧贴在板子上。
   贴纸刚好盖住蓝牙天线上，不要贴在元件上面。
* 20171009
** 晶科多国语言
   69系列添加多国语言，日语、繁体都可以。
   但是西班牙、阿拉伯的，不行，初始化成功，但是屏幕啥都没显示。
   替换国炜发的font_lib.a，已解决。
   英语之后的语言，采用的都是Unicode小端编码。
* 20170930
** 飞灵特ARGUN
   调试OK
** 飞灵特SuperAR
   增加反馈机制
* 20170929
** 飞灵特ARGUN
   BLE发送是异步操作的，加了个队列发送，上一个发送成功才发送下一个。
   摇杆数据采用AD检测，数据不知道如何组织，发送给APP。
   取值0到0xff，摇杆没动的时候，发的是0x7f。
   采用IO上拉电阻10k,误差比较大。
* 20170928
** 实捷DAB的IIS从机接收
   客户stm32还没有做好，无法调试
** 公司编译器处理中文
   根据.c文件的编码格式，会以文件的编码格式，填充数组。
   可新建文件，保存为Unicode编码，再定义中文数组，就会以Unicode填充该数组。
* 20170927
** 飞灵特ARGUN
   ARGUN协议，没有按照蓝牙标准，发送enable notify给从机，导致我们底层notify通道没有打开。
   而客户用telink主控，支持这样的操作。
*** descriptors
    CHARACTERISTIC_USER_DESCRIPTION     -->0x2901
    CLIENT_CHARACTERISTIC_CONFIGURATION -->0x2902
    SERVER_CHARACTERISTIC_CONFIGURATION -->0x2903

* 20170926
** 下载工具无法升级
   下载工具需要5V供电，笔记本电压可能达不到5V。
   下载工具挂一个大电容，电阻改大2.7R，可防止板子扯到电源。
** 实捷DAB案子
*** IIS从机输入
** 飞灵特ARGUN
   无法获取notify的句柄，无法发送数据
* 20170925
** BLE读回调执行2次
   app_server_read_callback()调用2次是需要的，
   第一次需要返回正确的长度回去，
   第二次判断buffer指针是否为空，不为空才给buffer赋值。
** 动态修改pin码和蓝牙名
   #+BEGIN_SRC c
   static void bredr_name_custom_handle(char *name)
   {
	     printf("bredr name:%s, len:%d\n",name,strlen(name));
   
       name[0] = 'X';
       name[1] = 'I';
       name[2] = 'N';
       name[3] = '\0';
       __set_pin_code("3693");
   }
   #+END_SRC
** APP发起连接蓝牙2.1 
   用了一个反射的方法实现。
   这个方法在国外的贴子上找到的，可以让客户先上网找一找。
** 69_V2012_p2版本SDK对箱连接
*** 开机自动连接从机
    void bt_discon_complete_handle(u8 *addr , int reason)
    ----reason == 0x04
        ----user_send_cmd_prepare(USER_CTRL_START_CONNEC_VIA_ADDR_STEREO,0,NULL);注释此句，即可不自动连接
*** 概率性连接不了从机
    每隔12秒，发送MSG_BT_STEREO_SEARCH_DEVICE消息，即可。
    搜索时间最长为12秒。

* 20170922
** 飞灵特ARGUN
   AES128 ECB加解密，替换br16_ccm_aes.a，添加aes_ecb_encrypt.c文件。
* 20170921
** 汉普乐放音箱ble协议
   ble协议已调通，音箱功能未确认
** 实捷DAB案子BT_ES
   和stm32采用串口1通信，定义了一个通信的简化版本。
   收音还是没有声音。
** 飞灵特ARGUN
   手动修改profile_data[]，每行第一字节为长度，
   如果需要value，可以在行尾自己加十六进制值，同时修改每行第一个字节为相应长度。

* 20170920
** 汉普乐放音箱ble协议
   ble通信调通。
*** 函数app_server_read_callback() 
   每次获取会执行2次，
   第一次buffer_size为0，实际没有发送数据，
   第二次buffer_size为上一次return的值，实际发送数据
** 实捷DAB案子BT_ES
*** SPI2中断号 #define IRQ_SPI2_IDX       44
    没有SPI通信，实际用串口通信
    收音还是没声音

* 20170919
** 汉普乐放音箱Gatt协议
   定义好协议，抓了profile截图给客户
** 实捷DAB案子BT_ES
   采用STM32+SI4684+AC6901A做蓝牙发射器带DAB数字广播
   调通2个linein通道的发射，蓝牙连接功能
   linein蓝牙发射，如果一个通道没声音，会导致发射完全没声音
   板子收音有问题

* 20170918
** 对箱连接手机播歌后无法配对从机
   V2012-p2版本，有此问题
   替换铜霭发的cpu_lib_ac690x.a，可解决
** 汉普酷走车机BLE音箱
   不能按照小精灵的协议开发
   要重新设计新的协议，待验证
** 对耳蓝牙距离短
   减低sbc的码率，可适当提高
** 内置充电IC充不满
   替换库文件，替换charge.c文件
* 20170916
** IIS播第一个提示音噗一声
   由于IIS传输，需要变采样，变采样的开始阶段，buf数据异常。
   IIS默认44.1kHZ
** 酷走车机BLE
   软件不认我们的设备，连接不上
* 20170915
** 源创杰69对象配对
   v2012-p2版本，连接播歌后，无法再配对从机，需要切换模式才行
   v2011版本无此bug
* 20170914
** 汉普--酷走车机--BLE控制
** 菲林特ARGUN
*** 启赋superAR
*** 先智ARGUN
* 20170913
** 永胜泰6904耳机蓝牙断开，灯状态没改变
   调整设置灯的函数，在每个消息的后面，立马执行。
   可能由于任务切换、中断，导致执行丢失。
** 鑫闻达6905机子linein检测不到
   不同芯片VDDIO在3.3V-3.6V之间，一致性不到。
   LDO_ref的电压永远为1.24V左右，而VDDIO电压为，AD满值，即0x3FF
   可通过判断 LDO_ref 的值大小，即可推出VDDIO电压大小。
   VDDIO为3.3V，LDO_ref为0x178左右。
   VDDIO为3.6V，LDO_ref为0x160左右。
   AD复用linein检测时，最好对LDO_ref分4个区间判断。
* 20170912
** 天地宏69系列RGB灯影响红外
   RGB灯用2ms频率pwm波，推动红灯时，会影响到红外接收。

* 20170911
** 晶科46系列PB9在开机时有数个脉冲
    打VM提示音补丁，可以解决。
** 伦茨耳机开机灯不亮
   采用outputchannel0，没有设置DIE寄存器，默认值有时会不一致导致。
** 晶科69获取文件夹数目
   尝试使用循环下个文件夹，累计文件夹数目。
*** 当前文件夹的序号
    ../../tff.h
    ((*(FIL *)((_FIL_HDL *)(music_operate_mapi->fop_api->cur_lgdev_info->lg_hdl->file_hdl))->hdl).fs_msg.musicdir_counter)

* 20170908
** 输出PLL-12M时钟
    JL_IOMAP->CON1 &= ~(BIT(10)|BIT(9)|BIT(8));
    JL_IOMAP->CON1 |=  (BIT(10)|BIT(9));
	  JL_PORTB->DIR &= ~BIT(0);
	  JL_PORTB->PD  |=  BIT(0);
	  JL_PORTB->PU  |=  BIT(0);
	  JL_PORTB->DIE &= ~BIT(0);
** 动态修改蓝牙名
   static void bredr_name_custom_handle(char *name)
   {
	     printf("bredr name:%s, len:%d\n",name,strlen(name));
       name[0] = 'X';
       name[1] = 'I';
       name[2] = 'N';
       name[3] = '\0';
   } 
** 菲林特AR枪协议
*** 协议1：super AR

*** 协议2：AR GUN

* 20170907
** 科普豪6905C
   U盘和SD卡复用，有部分卡不读，容易掉线
*** 优化方法
    检测前开SD-CLK脚 ~下拉~,修改速率为4(原先为5)。
    硬件上 ~复用脚加对地30p~,CLK脚对地10p，均可。
*** 客户采用复用脚加33p电容对地

* 20170906
** 汉欣诺电话本死机
*** 替换铜霭更新的bluetooth_lib.a，测试已OK
** 巴达木EQ调试没效果
   uart_init(UART_BAUD_RAE);不能在audio_init();之后调用，会导致无法中断接收。

* 20170905
** 汉欣诺
*** 获取电话本出现死机和乱码
    只要改动user_ctrl_prompt_tone_play()就会出现，铜霭处理中

* 20170904
** 内置充电IC外挂大容量电池
*** 改精度，调阈值，不起作用
    #define BUILD_POINT_THRESHOLD_VALUE   2
    #define CHARGE_MAX_CNT                110 * 60 * 2
*** 改用充满计数，计数5次以上，才认为充满
    可能电池充电，电压上升不线性导致
    对charge_full_deal();函数的执行，进行计数5次以上，才能执行
** 汉欣诺6901车机
*** 蓝牙获取电话本出现死机和乱码
*** TODO 获取手机拨打电话出去的号码
     - State "TODO"       from ""           [2017-09-04 周一 19:24]

* 20170831
** 笔记本电脑win8win10蓝牙连不上
** 洗刷刷LSM6DS3驱动
*** 静止时的数据，和样机基本一样
*** 摇动的数据，难对比

* 20170830
** 爱瑞声6907C内置充电外挂大容量电池
软件按固定间隔检测电压变化，大容量电池的电压变化很慢，调整电压检测分辨率
** 蓝牙电感料，会影响到sniff的功耗

* 20170829
** 华炬芯6904A耳机
*** 进power down死机问题
PR1做充电唤醒，PR2做按键唤醒，同时开2个唤醒脚，
会导致有些芯片出现进power down死机
*** 开机吱声
振荣修改cpu_lib_ac690x.a解决
*** TODO low_pwr_deal函数在蓝牙没连接时会执行
- State "TODO"       from ""           [2017-08-30 周三 18:54]
但是公版SDK测试，不会执行到

* 20170828
** 华炬芯6904耳机死机、开机吱声
*** 死机是因为 *BT_LOW_POWER_MODE* 模式引起
*** 开机吱声，开机初始化 *dac_init_api* 的电源时引起


* 20170817
** 联巨兴：人声消除，导致低音消失

* 20170818
** 鑫闻达：QN8035收音效果差，功放D类影响，晶振引时钟15p
** 科普豪：1621推屏，模拟SPI，时序延时要加大
** TODO TODO：
- State "TODO"       from ""           [2017-08-19 周六 11:03]
联巨兴：人声消除效果确认？
电影协会
宿舍安排

* 20170819
** TODO 人声消除低音处理
- State "TODO"       from ""           [2017-08-19 周六 11:02]
低音炮内部电路 始终要把双声道输入耦合成单声道的 那样立体感才强
可尝试加入EQ处理生成2.1声道
** 天博智4602按键不起作用
机子用一段时间后，机子开不了机，USB无法识别。
用烧写器重烧后，正常工作。
待查软件问题

* 20170821
** 鑫闻达BLE洗刷刷项目
使用DA380三轴加速度传感器，跟视频的停车守卫采用一样。
搭建DA380的驱动代码
** 华立S36
修改呼吸灯的控制

* 20170822
** 人声消除低音消失
寄机子给影志,山景的机子需要修板
** 鑫闻达BLE洗刷刷项目
抓包，调试BLE连接，BLE连接成功

* 20170823
** 鑫闻达数据包发送
原本使用ST的LSM6DS3芯片，陀螺仪和加速度一体
DA380缺失陀螺仪数据，目前填包处理

* 20170824
** 联巨兴人声消除
板子修好，寄给影志，处理低音效果
** 鑫闻达洗刷刷
调试DA380的采样频率，量程，发送数据的大小，优化效果
6909的板子，已修好

* 20170825
** 鑫闻达洗刷刷
准备2款传感器，ST的LSM6DS3和invensense的MPU6050
调试功耗，和蓝牙名与蓝牙地址处理
*** 功耗注意点
1.系统48MHz
2.DAC关
3.Bredr关，只开BLE
4.FM关
5.DA380设置为低功耗模式
6.电源DCDC模式
7.自动关机处理
8.推灯亮度处理
*** 升级问题
无线升级没有做好
*** 4.2的sleep模式
还没有做好
*** 低压flash
用纽扣电池供电，需认批次，选用低压flash，才能正常

