#+TITLE:       JL work diary record
#+AUTHOR:      辛佳斌(lawrence)
#+DATE:        [2017-02-13 周一 16:31]
#+EMAIL:       lawrencejiabin@163.com
#+KEYWORDS:    the page keywords, e.g. for the XHTML meta tag
#+LANGUAGE:    language for HTML, e.g. ‘en’ (org-export-default-language)
#+TODO:        TODO

#+SEQ_TODO: TODO(T!) | DONE(D@)3  CANCELED(C@/!)  
#+SEQ_TODO: REPORT(r) BUG(b) KNOWNCAUSE(k) | FIXED(f)
   #+BEGIN_SRC c
   #+END_SRC


* 20200102
** 请假1天

* 20191231
** 起华A3
   生产几百个不良
** 科普豪6936D
   对耳打给iPhone11，不说话都有电流声，跑LDO，功率降到6，调通话参数都不起作用，
   PCB走线mic和dac线是相交的，建议客户改板测试，
   而打给其他款手机，改LDO后基本听不出来

* 20191230
** 联巨兴6936D8
   通话电流声，应该是硅mic的问题，尝试降功率跟通话参数
** 恒大充电桩
   调试中

* 20191227
** 请假2个钟
** 起华6936D8
   3代耳机，2版程序已发出
** 组创692X
   PR2上升沿唤醒问题，发了程序给客户测试
** 源创杰692X
   串口1dma接收数据，超时获取数目，处理中
** 组创690X
   ble notify出现导致连接断开，还没支持

* 20191226
** 源创杰692X
   2.6.3蓝牙模块测试盒升级死机，进升级前关闭BLE的广播，测试可以
** 羽恒692X
   timer3定时不准，在客户程序上，验证可以发给客户了
** 起华6936D8
   3代耳机功能修改，还没改完
** 组创692X
   PR口上升沿唤醒不了，发了程序给客户了

* 20191225
** 请假到2点半
** 起华6936D
   3代耳机调试，发给客户测试了

* 20191224
** 请假一上午
** 下午出差博益友
   和少文出差,处理nordic的牙刷没有notify数据

* 20191223
** 博益友692X
   Nordic 52810无法接收notify数据

* 20191221
** 加班一天
   出差一天
** 桑利6925B
   测试盒连接慢,测试盒太多

* 20191220
** 起华6925A
   蓝牙音箱，调试OK，等客户过来烧样片
** 汇杰芯695X
   耳机SDK，获取能量值，测试不行，得珠海确认

* 20191219
** 起华AD135
   生产部分无法检测耳机
   5V控制的三极管焊错，导致5V常在
** 起华6925A
   蓝牙音箱基本功能已完成

* 20191218
** 也杨695X
   测试盒单独升级蓝牙名，程序不能开打印，关打印测试正常
** 华巨芯8006
   通道后，播歌没人声，VCOMO要设置2个地方
** 羽恒692X
   BLE和手机APP通信，能收不能发，在客户程序上改了个版本，客户验证可以
** 联巨兴亚华692X
   下午新的的BLE功能需求，还没加

* 20191217
** 起华AD138
   内置无线充改灯显示,已发出
** 起华6936D  AD138
   功能修改，已发出
** 联巨兴亚华6928B
   蓝牙模块，串口丢数据，spp卡包，加ble功能，没处理完
** 华巨芯8006
   打完电话后播歌没有人声，待测试
** 华巨芯奋达6923
   app获取目录列表，偶现死机，栈检查会满，待处理

* 20191216
** 博益友692X
   做client连接nordic的server，连接流程正常，
   但是nordic的数据没有发出，抓包看不出来，先让客户看下nordic那端的打印再说
** 起华AD138
   内置无线充，调试中

* 20191213
** 起华AD138
   带无线充SDK开3灯，爆ram太多，跟珠海处理中
** 组创692X
   软件模拟spi，跟6936D通信正常，
   跟2.4GHz模块无法通信，未知原因，客户回去处理

* 20191212
** 组创6936D
   有个华为手机播歌暂停后，会超时断开，留手机待处理
** 聆动6928B
   在源代码上固定中翔达key，等吴旭发库
   要改固定key
   电机pwm1到默认输出到PA4

* 20191211
** 中翔达692X
   linein下串口丢数据，改了个程序给客户测试中
** 也杨6936d
   没有改2线flash,导致1拖6烧录部分不开机

* 20191210
** 8009
   dsp有3个电源,一般由PB8供电，关机后掉电，dsp不工作，
   开机后才能使用关键字“嘿，siri”做唤醒
** 威益德690X
   连测试盒测试容易出现复位
   开了频偏测试功能，如果在这个时候出现异常就会复位，没有做退出流程
   关了频偏测试，连接非常快
   
* 20191209
** 伦茨682X
   ble连上瞬间丢串口数据，开发板测试10ms接收，没有问题
** 组创693X
   ble单耳使用广播左右相反，客户测试ok
** 芯运6936D
   生产有2百多个不良不开机，打全电压段校准mic补丁OK

* 20191206
** 起华6936D
   新案子3个问题，处理，发给客户测试
** 中翔达695X
   PB0做按键被充电仓的uart1默认第一组口修改，重新初始化可以
** 新时代692X
   无法被cc2541的client端连接，修改UUID为16bits，测试可以
** 聆动692X
   BLE案子基本可以，等走完商务，才能发出

* 20191205
** 聆动6928
   BLE案子调试中
** 起华6936d
   改了2个案子，还有一个没改
** 中翔达6956D
   反馈PB0做按键，无法识别双击，会变成长按，待测试

* 20191204
** BLE参数
   Adv_int_min 广播 interval 的最小值，  单位 0.625ms
   Adv_int_max 广播 interval 的最大值，  单位 0.625ms
   CONN_INTERVAL_MIN 最小 interval 值， 单位 1.25ms
   CONN_INTERVAL_MAX 最大 interval 值， 单位 1.25ms
   CONN_SUPERVISION_TIMEOUT 超时值 ，   单位 10ms
** 新时代692X
   抄机,692x做server，CC2541做client，连接不上，支持中
** 聆动6928
   带了个机子过来这边，待调试的案子

* 20191203
** 692X串口升级
   改用UART1需要换uboot
** 威益德690X
   文件浏览器获取文件接口改了3个地方。其他问题没有测试到

* 20191202
** 8006推灯
   用硬件模块PR口推灯,才能做成693X的效果,时钟初始化有问题
** 威益德690X
   BLE发送卡死机,写回调发送事件,会卡住不返回,改成发消息
   文件浏览器出现有重复文件,丢失文件,点播wma失败,wma文件后缀变成mp3

* 20191129
** 科普豪693X
   SPI收发例子，客户测试OK，
   不过开发板偶现收不到数据，暂时找不到原因
** 组创6933C
   生产几百个不良，客户直接联系珠海，在珠海处理了
** 汉欣诺692X
   华为mate10配对BLE偶现出现失败，测试发现mate10无法搜索到48号通道的数据，
   暂时让客户测试下之前抄的方案，是否有一样问题，再决定是否寄手机给珠海

* 20191128
** 威益德692X
   几个问题处理完成
** 组创6933C
   后续生产还是出现不良，有几百个，处理中
** 科普豪693X
   spi用dma方式，测试中
** 汉欣诺692X
   BLE做HID，用mate10经常出现配对不上，处理中

* 20191127
** 奋达
   出差一天
   和棉鸿、荣均出差奋达
   处理小芦双mic降噪测试标准

* 20191126
** 起华6936D8
   苹果功能加广播问题，珠海说暂时无解
   改成默认带入耳检测,安卓可以使用
** 潮元6936D
   通话调试中
   硬件问题很多,才榜处理

* 20191125
** 请假1天

* 20191123
** 加班一天
** BLE连接间隔
   苹果的连接间隔默认为30ms，
   如果要更新，需要满足如下要求，且最小可以申请到20ms，
   如果蓝牙服务带HID服务，则可以申请的最小连接间隔为11.25ms，
   另外，苹果从来不会读取设备端偏爱的连接间隔的character值。
** BLE修改gatt
   当从端有能力改变自身服务时， GATT服务必须包含Service Changed characteristic，
   因为苹果可能会根据该特征值判断原来读取的从端设备的service list等信息是否还可以继续使用。

* 20191122
** 693X音箱SDK
   开PC关机功耗大
   JL_USB->CON0 = 0;
   JL_USB->CON1 = 0;
   JL_USB_IO->CON0 = 0;
   JL_USB_IO->CON1 = 0;
** 起华6936D8
   广播电量有时出现乱跳，改了个版本给客户测试
** 中翔达德芯成
   关机后VDDIOW有误差，珠海改库后，发给你客户测试了

* 20191121
** 华巨芯692X
   AI_V2.4关HFP出现U盘概率升级死机，暂不改库，给客户3种方式选择避免
   1.做个vm，复位后直接进音乐模式升级，不要进蓝牙。
   2.开HFP，把BT_HFP_EN_SCO_DIS打开，把__bt_set_update_battery_time(0);参数清0。
   3.升级前关后台的，你再仔细测试看看，看看行不行

** 汉欣诺692X
   BLE做HID设备，手动回连出现延时大问题，改了个程序给客户，
   反馈三星S10可以，华为mate 10还不行，处理中

* 20191120
  出差一天
** 德芯成6936D
   关机后VDDIO电压偏低，有2.4V-2.7V
   导致触摸芯片不工作
   珠海秉铨和建城在看

* 20191119
** AD转IIS芯片
   立体声单/双路ADC
   ES7241
   CS4344 
   ES7243
** BLE主从机数据加快实现
   #+BEGIN_SRC c
   case HCI_SUBEVENT_LE_CONNECTION_COMPLETE: {
       if (tc_state != TC_W4_CONNECT) {
           client_printf("CONN ACTIVE err,%d\n", tc_state);
           break;
       }
  
       if (packet[3] != 0) {
           client_puts("client creat_conn fail!\n");
           client_put_buf(packet, size);
           if (packet[3] != 0x0c) {
               tc_state = TC_IDLE;//;
               ACT_SET_FLAG(CLI_SCAN_ENABLE);
           }
           break;
       }
       client_puts("client conn sucess\n");
       /* client_put_buf(packet, size); */
       gc_handle = little_endian_read_16(packet, 4);
       log_info("HCI_SUBEVENT_LE_CONNECTION_COMPLETE : %0x\n", gc_handle);
       tc_state = TC_CONNECTED;//TC_W4_ENCRYPTED_CONNECTION;
       set_ble_work_state(BLE_ST_CONNECT);
       /* ACT_SET_FLAG(CLI_SEARCH_PROFILE_START);//debug */
       att_send_init(gc_handle);
       att_regist_client_callback(s_client_gatt_event);
       test_record_data_cnt = 0;
       index_record = 0;
       client_search_profile_complete();
       break;

    const u8 indicate_enable_data[] = {0x02,0x00};
    static void client_search_profile_complete(void)
    {
        u16 mtu;
    
        le_characteristic_t tmp_characteristic;
        if (service_count == 0) {
            log_info("find no services!!!\n");
        }
    
        gatt_client_get_mtu(gc_handle, &mtu);
        log_info("ATT MTU = %u\n", mtu);
        att_send_set_mtu_size(mtu-3);
    
        client_puts("\n-target_handle:");
        client_put_buf((void *)&target_handle, sizeof(target_handle_t));
        set_ble_work_state(BLE_ST_SEARCH_COMPLETE);
        log_info("client_search_profile_complete\n");
    
        tc_state = TC_W4_ACC_DATA;
        client_operation_send(0x11,(void *)indicate_enable_data,2,ATT_OP_WRITE);
    
        tmp_characteristic.value_handle = 0x10;///indicate uuid handle
        gatt_client_listen_for_characteristic_value_updates(&notification_registration[0],
                                                            s_client_gatt_event, gc_handle, &tmp_characteristic);
    }
   #+END_SRC
** 华巨芯奋达692X
   U盘升级死机，还没找到原因，处理中
** 迈瑞693X
   改写flash任意地址任意长度的数据
   而擦除要4K擦除，需要4K读回到ram，改写ram，再写回

* 20191118
  请假半天
** 华巨芯693X
   双模SDK等问题，验证好已发出
** 华巨芯692X
   奋达带测试模式升级死机，开发板没测到，客户测试中
** 威益德690X+1082
   USB和linein来电死机，已处理
** 汉欣诺692X
   BLE做HID，让手机更新profile，和珠海确认过，实现不了
** 联巨兴690X
   传统蓝牙HID本地更新report，没空测试，先发给客户测试

* 20191115
** 威益德690X+1082
   做4通路dac
   DAC中断解码数据通过串口DMA发送给1082
   插播linein采样数据，dac中断不能停
   #+BEGIN_SRC c
   u8 dac_int_flag = 0;
   void dac_int_enable(void)
   {
       dac_int_flag = 0;
       dac_read_en = 0;
       dac_ie_api(1);
   #if BT_TWS
       dac_mute(0,0);
   #else
       dac_mute(0,1);
   #endif
   
   }
   extern u8 aux_st;
   void dac_int_disable(void)
   {
       if(aux_st){
           dac_int_flag = 2;
           return;
       }else{
           dac_int_flag = 1;
       }
   #if BT_TWS
       dac_mute(1,0);
   #else
       dac_mute(1,1);
   #endif
   
       dac_ie_api(0);
   }
   u32 USE_AMUX = DAC_AMUX0;
   u8 aux_st = 0;
   void aux_open(void)
   {
       puts("aux_open\n");
       aux_st = 1;
       dac_mute(1,1);
       set_sys_vol(0,0,FADE_ON);
       /* ladc_adcude(1); */
       //init mic IO
       if(USE_AMUX == DAC_AMUX0){
           JL_PORTA->DIR |=  (BIT(1)|BIT(2));
           JL_PORTA->DIE &= ~(BIT(1)|BIT(2));
       }
       else if(USE_AMUX == DAC_AMUX1){
           JL_PORTA->DIR |=  (BIT(4)|BIT(3));
           JL_PORTA->DIE &= ~(BIT(4)|BIT(3));
           JL_PORTA->PD  &= ~(BIT(3));//PA3 default pull_down
       }
       else if(USE_AMUX == DAC_AMUX2){
           JL_PORTB->DIR |=  (BIT(11)|BIT(12));
           JL_PORTB->DIE &= ~(BIT(11)|BIT(12));
       }
       void ad2da_init(void);
       ad2da_init();
       digit_auto_mute_set(0,-1,-1,-1); // 关自动mute
       printf("dac_get_samplerate:%d\n",dac_get_samplerate());
       ladc_reg_init(ENC_LINE_LR_CHANNEL,dac_get_samplerate());
       amux_channel_en(USE_AMUX,1);
       /* amux_ch_combine(1,1); */
       /* dac_AmuxGain_en(1); */
       /* JL_AUDIO->DAA_CON2 |= (BIT(12)|BIT(7)); */
       /* JL_AUDIO->DAA_CON2 &= ~(BIT(13)); */
       os_time_dly(20);//wait amux channel capacitance charge ok
       set_sys_vol(30,30,FADE_ON);
       dac_mute(0,1);
       /* ladc_adcude(0); */
       printf("JL_AUDIO->DAC_CON :0x%08x\n",JL_AUDIO->DAC_CON);
       printf("JL_AUDIO->DAA_CON0:0x%08x\n",JL_AUDIO->DAA_CON0);
       printf("JL_AUDIO->DAA_CON1:0x%08x\n",JL_AUDIO->DAA_CON1);
       printf("JL_AUDIO->DAA_CON2:0x%08x\n",JL_AUDIO->DAA_CON2);
       printf("JL_AUDIO->DAA_CON3:0x%08x\n",JL_AUDIO->DAA_CON3);
       printf("JL_AUDIO->DAA_CON4:0x%08x\n",JL_AUDIO->DAA_CON4);
       printf("JL_AUDIO->DAA_CON5:0x%08x\n",JL_AUDIO->DAA_CON5);
   }
   extern u8 dac_int_flag;
   void aux_close(void)
   {
       puts("aux_close\n");
       aux_st = 0;
       amux_ch_combine(0,0);
       if(dac_int_flag == 2){
           void dac_int_disable(void);
           dac_int_disable();
       }
       ladc_close(ENC_LINE_LR_CHANNEL);
       void ad2da_free(void);
       ad2da_free();
       amux_channel_en(USE_AMUX,0);
       JL_AUDIO->DAA_CON2 &= ~(BIT(12)|BIT(7));
       digit_auto_mute_set(1,-1,-1,-1); // 开自动mute
   }
   
   typedef struct __AD_TO_DA_STREAM {
       cbuffer_t 	cbuf;
       u8 * 		ram;///[DAC_BUF_LEN];		//double buffer
       u8 			enable;
   } AD_TO_DA_STREAM;
   
   #define AD2DA_BUF_LEN  5*1024
   static AD_TO_DA_STREAM ad2da_obj;
   
   void ad2da_init(void)
   {
       u32 ram_len = AD2DA_BUF_LEN;
       ad2da_obj.enable = 1;
       ad2da_obj.ram = malloc(AD2DA_BUF_LEN);
       ASSERT(ad2da_obj.ram);
       cbuf_init(&ad2da_obj.cbuf, ad2da_obj.ram, ram_len);
   }
   void ad2da_free(void)
   {
       if(ad2da_obj.enable){
           if(ad2da_obj.ram){
               free(ad2da_obj.ram);
               ad2da_obj.ram = NULL;
           }
           ad2da_obj.enable = 0;
       }
   }
   s32 ad2da_write(u8 *buf, u32 len)
   {
       s32 ret;
       if (ad2da_obj.enable == 0) {
           ret = 0;
       } else {
           ret = cbuf_write(&ad2da_obj.cbuf, buf, len);
           if (len != ret) {
               putchar('x');
           }
       }
       putchar('w');
       return ret;
   }
   
   s32 ad2da_read(u8 *buf, u32 len)
   {
       s32 ret;
       if (ad2da_obj.enable == 0) {
           ret = 0;
       } else {
           ret = cbuf_read(&ad2da_obj.cbuf, buf, len);
           if (len != ret) {
               putchar('s');
           }
       }
       putchar('r');
       return ret;
   }
   
   void ladc_stereo_ad2da(void *buf_l,void *buf_r,u32 len)
   {
       if(ad2da_obj.enable){
           u16 sr_reg;
           sr_reg=dac_get_samplerate();
           if(sr_reg != ladc_sr_get())
           {
               printf("sr:%d\n",sr_reg);
               ladc_sr_set(sr_reg);
           }
       }else{
           return;
       }
   
       u8 l2d_buf[DAC_DUAL_BUF_LEN*2];
       s16 * sp_l = buf_l;
       s16 * sp_r = buf_r;
       s16 * dp = (s16 *)l2d_buf;
       u8 cnt;
       for(cnt = 0; cnt<(len/2); cnt++)
       {
           dp[cnt*2]=sp_l[cnt];
           dp[cnt*2+1]=sp_r[cnt];
       }
       ad2da_write((u8 *)dp,len*2);
   }
   #+END_SRC

** 华钜芯693X
   双模SDK问题，未验证

* 20191114
** 迈瑞693X
   处理2个，还剩IO中断切换边沿唤醒，有概率失效，还没看
** 威益德690X
   任意模式下，插播linein的RDS声音，公版测试正常，客户那边不行
** 威益德692X
   录音加混响，爆13K的ram，回客户处理不了
** 起华6936D
   苹果特殊功能调试，要配合充电仓使用才正常，还差mic动态调节没搞，先发给客户测试了

* 20191113
** 华钜芯693X
   双模SDK问题，珠海没回应
** 起华6936D8
   功能调试，还有点问题
** 迈瑞693X
   电量检测流程
   #+BEGIN_SRC c
   static int vbat_timer = 0;
   static u8 vbat_check_idle = 1;
   static u16 bat_val = 0;
   void vbat_check(void *priv);
   void vbat_check_init(void)
   {
       r_printf("vbat_trim:%d...vbg_trim:%d\n",get_vbat_trim(),get_vbg_trim());
       if (vbat_timer == 0) {
           vbat_timer = sys_timer_add(NULL, vbat_check, 2);
           vbat_check_idle = 0;
       }
   }
   void vbat_timer_update(u32 msec)
   {
       if (vbat_timer) {
           sys_timer_del(vbat_timer);
           vbat_timer = sys_timer_add(NULL, vbat_check, msec);
       }
   }
   u16 get_vbat_level(void)
   {
       return (adc_get_voltage(AD_CH_VBAT) * 4 / 10);
   }
   void vbat_check(void *priv)
   {
       static u8 switch_cnt = 0;
       if(switch_cnt++ > 10){
           log_info("bat_val:%d\n", bat_val);
           vbat_timer_update(10 * 1000);///10s
           switch_cnt = 0;
           vbat_check_idle = 1;///不检测vbat,允许进sniff
           return;
       }
       if(vbat_check_idle){
           vbat_timer_update(2);///2ms
           vbat_check_idle = 0;///要检测vbat,不允许进sniff
       }
       if (!bat_val) {
           bat_val = get_vbat_level();
       } else {
           bat_val = (get_vbat_level() + bat_val) / 2;
       }
       /* log_info("bat_val:%d\n", bat_val); */
   }
   static u8 vbat_check_idle_query(void)
   {
       return vbat_check_idle;
   }
   REGISTER_LP_TARGET(vbat_check_lp_target) = {
       .name = "vbat_check",
       .is_idle = vbat_check_idle_query,
   };
   #+END_SRC
   唤醒口没有设置DIE,导致read失效
   power_wakeup_init(&wk_param);
   gpio_set_die(port0.iomap,1);
   gpio_set_die(port1.iomap,1);
   gpio_set_die(port2.iomap,1);

* 20191112
** 华钜芯693X
   AC693X_bt_data_transfer_soundbox_sdk_release_v0.1.0反馈6个问题，
   验证了4个，3个存在，一个不存在，准备发邮件给珠海
** 迈瑞693x
   反馈IO中断，充电等问题，还没看
** 威益德692X
   睡眠后唤醒RTC不跑
   set_lowpower_keep_32K_osc_flag(1);
   enter_sys_soft_poweroff();
   睡眠前都要调用下，前面的函数，才能睡眠。

* 20191111
** 迈瑞693X
   开辟10区域开不了机，超4K读写异常，已经发给客户了
** 联巨兴亚华6928B
   spp串口透传，基本功能有，客户回去测试
   设置搜索为普通蓝牙图标
   #define BD_CLASS_BLUETOOTH			0x800000//0x040610
    __change_hci_class_type(BD_CLASS_BLUETOOTH);

* 20191108
** 693X的VM做法
   一开机有个vm的打印
   [Info]: [SDFILE]VM size: 0x57000 @ 0x27000
   [Info]: [VM]vm_info addr:0x27000, len:0x4000, mode:0x0
   就是VM的起始地址和长度
   代码里面会定一个最大长度，改isd_config.ini没用的，而且公版SDK不一定会对应上
   len：0x4000 = 16K,要除以2,因为要做备份，这样才是最大可保存的最大长度8K
** 美师傅8006
   读EQ配置文件出错，要把eq的bin文件放到tools\resource文件夹里
   不需要修改download.bat
** 德科创693X
   BLE超低功耗出现100mA大电流，这边量出来只有40mA，初步判定是唤醒电源电容充放电的大电流

* 20191107
** 汇杰芯6933C
   生产开不了机，是flash问题，2线机制
** 美师傅693X
   064的开ACC立体声播歌会卡音，提高系统频率到64M，能优化
   卓添小米手机连上播歌瞬间会卡3声，暂时无解
** 汉欣诺690X
   带BLE开了1拖2之后，会出现回连连不上现象
** 美师傅8006
   在线调EQ，连不上，测试正常
** 华钜芯奋达692X
   改AI版本，音频输出对不上，修改应用的流程
** 德科创6939D
   改了一个100uA的BLE蓝牙库，客户反馈1分钟会有2-3次有50us的100mA大电流
   还没搞
** 迈瑞693X
   指定内部flash地址写数据，还没看
   
* 20191106
** 汇杰芯692X
   音乐播歌变速变调第一声没有变音
   要改初始化时的默认值

** 迈瑞693X
   BLE案子支持，内部flash的文件系统sdfile不支持写，指定地址写方式也没有接口
   #+BEGIN_SRC c
     #include "system/includes.h"
     #include "app_config.h"
     #include "fs.h"
     
     #define FILE_SIZE   20 * 1024 * 1024
     
     static u8 write_buf[32 * 1024 + 500];
     
     #define SDFILE_NEW_FILE1 	SDFILE_RES_ROOT_PATH"user/file1.txt"///
     #define SDFILE_NEW_FILE2 	SDFILE_RES_ROOT_PATH"user/file2.txt"///
     /* #define SDFILE_NEW_FILE1 	SDFILE_RES_ROOT_PATH"file1.txt"///user/ */
     /* #define SDFILE_NEW_FILE2 	SDFILE_RES_ROOT_PATH"file2.txt"///user/ */
     
     #define SDFILE_NEW_FILE3 	SDFILE_RES_ROOT_PATH"RESERVED_CONFIG/btif"
     
     #define SDFILE_READ_LEN 	9///0x20
     
     static int sdfile_test(const char *name)
     {
         log_d("SDFILE file path: %s", name);
         FILE *fp = NULL;
         u8 buf[SDFILE_READ_LEN];
         u8 len;
         int ret;
     
         fp = fopen(name, "rw+");
         if (!fp) {
             log_d("sdfile open file ERR!");
             return -1;
         }
     
         //char str_buf[] = "test user file write";
         //fseek(fp, 0, SEEK_SET);
         //ret = fwrite(fp, str_buf, sizeof(str_buf));
         //if (ret == sizeof(str_buf)) {
         //    printf("file write succ\n");
         //}else{
         //    printf("file write ERR\n");
         //}
         memset(buf,0x00,sizeof(buf));
         len = fread(fp, buf, sizeof(buf));
         if (len == 0) {
             log_d("read file ERR!");
             goto _end;
         }
         printf("read cnt:%d",len);
         put_buf(buf, len);
     
         memset(buf,0x00,sizeof(buf));
         fseek(fp, 5, SEEK_SET);
         len = fread(fp, buf, sizeof(buf));
         if (len == 0) {
             log_d("seek read file ERR!");
             goto _end;
         }
         printf("senk read cnt:%d",len);
         put_buf(buf, len);
     
         memset(buf,0x00,sizeof(buf));
         char str_buf1[] = "test over write";
         printf("%s",str_buf1);
         put_buf(str_buf1, sizeof(str_buf1));
         fseek(fp, 0, SEEK_SET);
         ret = fwrite(fp, str_buf1, sizeof(str_buf1));
         if (ret == sizeof(str_buf1)) {
             printf("file write succ\n");
         }else{
             printf("file write ERR\n");
         }
     
         memset(buf,0x00,sizeof(buf));
         fseek(fp, 0, SEEK_SET);
         len = fread(fp, buf, sizeof(buf));
         if (len == 0) {
             log_d("write read file ERR!");
             goto _end;
         }
         printf("write read cnt:%d",len);
         put_buf(buf, len);
     
         log_d("SDFILE ok!");
     _end:
         if (fp) {
             fclose(fp);
         }
         return 0;
     }
     
     void file_test(void)
     {
         r_printf("-------SDFile test Start------");
         //void *mnt = (void *)mount(SDFILE_DEV, SDFILE_MOUNT_PATH, "jlfs", 0, NULL);
         //if (mnt == NULL) {
         //    r_printf("mount jlfs failed");
         //}
     
         sdfile_test(SDFILE_NEW_FILE1);
         sdfile_test(SDFILE_NEW_FILE2);
         /* sdfile_test(SDFILE_NEW_FILE3); */
     
         r_printf("-------SDFile test END------");
     }
     
     static void fs_test_task(void *p)
     {
         OS_SEM sem;
         os_sem_create(&sem, 0);
         while (1) {
             //if (!storage_device_ready()) {
             //    os_time_dly(10);
             //    continue;
             //}
             /*fs_write_test();*/
             /*fs_write_test2();*/
             //exfat_read_test();
             os_sem_pend(&sem, 0);
         }
     }
     static int fs_test_init()
     {
         task_create(fs_test_task, NULL, "fs_test");
         return 0;
     }
     /* late_initcall(fs_test_init); */
     
     #define USER_ADDR  400*1024
     void test_wirte_protect()
     {
         void *dev = dev_open("spiflash", NULL);
         if (!dev) {
             r_printf("\n <<<<spi_flash no_open>>>>\n");
             return ;
         }
         /* dev_ioctl(dev, IOCTL_SET_WRITE_PROTECT, 0); */
         dev_ioctl(dev, IOCTL_ERASE_BLOCK, USER_ADDR);
         u8 buf[256];
         memset(buf, 0xdd, sizeof(buf));
         dev_bulk_write(dev, buf, USER_ADDR, sizeof(buf));
         memset(buf, 0xbb, sizeof(buf));
         dev_bulk_read(dev, buf, USER_ADDR, sizeof(buf));
         put_buf(buf, sizeof(buf));
         dev_close(dev);
         dev = NULL;
         // cpu_reset();
     }
   #+END_SRC

* 20191105
** 迈瑞693X
   指纹识别智能锁BLE案子开发

* 20191104
** 组创6933C
   改高阻防止部分芯片功耗高，但是整机下，手拿着功耗会逐渐增大，
   外围有个三极管没有下拉截止电阻导致，需要主控输出0或下拉处理
** 奋达692X
   AI版本自动化测试，已发出

* 20191101
** 组创6933C
   生产有部分芯片关机功耗500uA，是PA7设置成输出0，改成高阻就可以

* 20191031
** 华钜芯奋达
   收音存台，默认50，改成100，会导致超u8，改动太大，客户暂时先限制80个。
   自动化测试，珠海安排到下周搞
** 伦茨693X
   连接小米8出现连接成功又断开现象，反馈珠海

* 20191030
** 汉欣诺6905C
   生产出现死机，目前怀疑是地回路引起，全志C200S的芯片一通电就会搞死6905C
** 奋达692X
   AI的V2.4收音下100个台，会出现APP闪退。

* 20191029
** 拜瑞6901A
   解答客户一些问题
** 联创视听690X
   蓝牙伴侣暂停状态，微信来个信息，蓝牙伴侣就自动播歌，公版就有问题，
   固件半秒会反馈A2DP播放状态，APP收到信息就会启动播歌
** 汉欣诺6905C
   生产出现部分开不了机，怀疑是硬件问题，客户先验证中

* 20191028
** 奋达692X
   挪了一些样机工程代码，有库函数冲突，暂没改库，编译处理先,
   要改uboot，要等棉鸿出差回来，再改
** 组创6933C
   客户用了旧的SDKV1.0.0生产了，生产没法测试频偏，SDK问题,
   暂时还得等客户跟工厂沟通，再确定怎么个处理方式
** 联巨兴693X
   耳机带APP的通信问题，已处理
** 起华
   AD135和耳机，功能修改中
** 重定义底层库函数
   #+BEGIN_SRC c
       void set_sys_vol(u32 l_vol, u32 r_vol, u8 fade_en);
       extern u32 vol_map[32];
       #define  set_sys_vol(x,y,z)     set_sys_vol(vol_map[x],vol_map[y],z);
   #+END_SRC
** APP端获取已连接设置的EDR地址
   #+BEGIN_SRC C
    AVAudioSessionRouteDescription *nowRoute = [[AVAudioSession sharedInstance] currentRoute];
    NSArray * outArr = nowRoute.outputs;
    AVAudioSessionPortDescription *outPort = outArr[0];
    NSString *addr_lower = [outPort.UID lowercaseString];
    addr_lower = [addr_lower stringByReplacingOccurrencesOfString:@":" withString:@""];
    addr_lower = [addr_lower stringByReplacingOccurrencesOfString:@"-tacl" withString:@""];
    NSDictionary *dict = @{@"ADDRESS":addr_lower?:@"",
                           @"TYPE"   :outPort.portType,
                           @"NAME"   :outPort.portName?:@""};
    return dict;
   #+END_SRC
   #+BEGIN_SRC java
   /**
     * 检查指定的蓝牙设备是否已连接
     *
     * @param device 蓝牙设备
     * @return 结果
     */
    public static boolean isBTConnected(BluetoothDevice device) {
        boolean isConnected = false;
        if (device != null) {
            try {
                Class<BluetoothDevice> bluetoothDeviceClass = BluetoothDevice.class;
                Method isConnectedMethod = bluetoothDeviceClass.getDeclaredMethod("isConnected", (Class[]) null);
                isConnectedMethod.setAccessible(true);
                isConnected = (boolean) isConnectedMethod.invoke(device, (Object[]) null);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return isConnected;
    }
    /**
     * 获取系统已连接的蓝牙设备列表
     */
    public static List<BluetoothDevice> getSystemConnectedBtDeviceList() {
        List<BluetoothDevice> mSystemConnectedList = new ArrayList<>();
        BluetoothAdapter adapter = BluetoothAdapter.getDefaultAdapter();
        try {//得到连接状态的方法
            int state = getBtAdapterConnectionState(adapter);
            if (state == BluetoothAdapter.STATE_CONNECTED || state == BluetoothAdapter.STATE_DISCONNECTED) {
                Set<BluetoothDevice> devices = adapter.getBondedDevices();
                 //筛选已配对的设备列表
                for (BluetoothDevice device : devices) {
                    boolean isConnected = isBTConnected(device);
                     if (isConnected) {
                        mSystemConnectedList.add(device);
                    }
                }
            }
            //TODO:获取游离状态的BLE设备(为了兼容BLE不配对连接的情况) ，不需要获取连接的ble设备择注释这个if代码块即可
            if (!BluetoothConstant.BLE_BOUND_WAY) {
                BluetoothManager mBluetoothManager = (BluetoothManager) CommonUtil.getMainContext().getSystemService(Context.BLUETOOTH_SERVICE);
                if (mBluetoothManager != null) {
                    List<BluetoothDevice> mConnectList = mBluetoothManager.getConnectedDevices(BluetoothProfile.GATT);
                    //筛选已连接的设备列表
                    if (mConnectList != null) {
                        for (BluetoothDevice device : mConnectList) {
                             if (!mSystemConnectedList.contains(device)) {
                                 mSystemConnectedList.add(device);
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (mSystemConnectedList.size() > 0) {
            return mSystemConnectedList;
        } else {
            return null;
        }
    }
   #+END_SRC

* 20191026
** 加班1天
** 三力
   改了一个HID切换ios和Android的demo程序
** 起华6936D
   FF209改了一个056的版本

* 20191025
** 起华6936D
   改了2款案子和AD135仓功能，还有一款209还没改
** 奋达692X
   自动化测试改AI版本，处理中，下周还要找珠海多个大佬，改usb，audio，exe，uboot等功能

* 20191024
** 新时代692X
   BLE做主机获取RSSI，珠海在V2.6.3改了个库给客户测试了
   typedef struct {
       u8   event_type;
       u8   address_type;
       u8   address[6];
       s8   rssi;///u8 reserve;
       u8   length;
       u8   data[1];
   } adv_report_t;
** 汇杰芯692X
   发射器带混响，发射出去无混响效果
   调整ladc的中断函数流程，客户测试可以

* 20191023
** 汇杰芯692X
   发射器开混响，改了一个版本给客户能用，但是程序流程上，需要改动，暂时没空帮客户看
** 中翔达大康693X
   多款案子多个问题，处理中

* 20191022
** 得辉达6932A
   带gsensor关机功耗高，需要拆掉IIC的外部上拉电阻，
   更新程序，功耗在2.7uA
** 国华693X
   生产5%开不了机，flash问题，改为2线
** 起华693X
   2款案子修改

* 20191021
** 请假1天
   
* 20191018
** 伦茨692X
   BLE当主机,连接后，到打开notify需要1.5s的时间
   客户想要加快,需要珠海处理

* 20191017
** AD135
   一共10K的ram，flahs 是512k的
   还有1k不到，大概是950byte
** 起华6936D
   入耳提示音,没有单击功能
** 得辉达TX01-6932A
    5个板子各有各的问题，修不好，跟客户说了，更新新的程序给客户
** 国华6936D
   案子开发，支持中

* 20191016
** 起华AD135
   25%对应3.8V的电压
   修改灯的状态
** 组创6933C
   目前烧录器的trim有问题，会把vbat烧成0档
   喜增说，烧录不要勾选trim，出现配置错误的单独拿出来,后面再处理
** 中翔达6936D
   对耳靠近回连不了，焕辉跟立辉、余鑫,改了个库给客户测试。
   bredr_normal_pwr_set(frame,15);库里加了这个调整

* 20191015
** 国华693X
   案子开发培训
** 中翔达6936D
   对耳靠近回连不了，处理中
   062公版就会,063公版不会
** 组创6933C
   电量检测不准，打印trim值，不正常，处理中

* 20191014
** 美师傅693X
   音箱SDKmusic关机不了，公版就有，暂时加个变量处理，VCOMO无法保持，测试多个版本SDK，没有一个是正常的，反馈珠海
** 伦茨693X
   mic设成省电容，关不了机，还没看
** 中翔达693X
   对耳靠近回连不了，还会断开，客户寄机子过来分析

* 20191012
** 也杨693X
   没有按键只有gsensor
** 伦茨692X
   蓝牙播歌后，串口数据异常，暂时找不到原因，客户尝试改uart1
** 伦茨6939B2
   做音响，mic当IO用开机有脉冲，按键和灯复用，功放噗声等问题支持，客户测试中
** 也杨6936D
   用SC7A20有个别机子，会一直初始化不过，怀疑是用了最高的波特率导致，
   不用最高波特率蓝牙播歌又卡音，客户和sensor的工程沟通

* 20191011
** 中翔达693X
   2个耳机靠近回连不了，拿远可以回连，重新靠近又断开。
   打了晶振的补丁，一直跑晶振不跑LRC的，客户测试可以
   不停的充电拿起来，操作50次出现一次死机，LDOIN焊103电容，客户测试可以

* 20191010
** 起华H3-6936D
   功能修改，已发出
** 也杨6936D+SC7A20
   敲击失效，改成注册定时器，半秒初始化一次，知道初始化成功，终端回去测试50台再看情况
** 汉欣诺692X
   BLE连接失败，珠海改了个库，还没测试

* 20191009
** 威益德690X
   linein扩音
   #+BEGIN_SRC c
   u8 aux_st = 0;
   void aux_open(void)
   {
       puts("aux_open\n");
       aux_st = 1;
       dac_mute(1,1);
   
       /* ladc_adcude(1); */
       //init mic IO
       JL_PORTA->DIR |=  (BIT(1)|BIT(2));
       JL_PORTA->DIE &= ~(BIT(1)|BIT(2));
       digit_auto_mute_set(0,-1,-1,-1); // 关自动mute
       amux_channel_en(DAC_AMUX0,1);
       amux_ch_combine(1,1);
       dac_AmuxGain_en(1);
       JL_AUDIO->DAA_CON2 |= (BIT(12)|BIT(7));
       JL_AUDIO->DAA_CON2 &= ~(BIT(13));
       os_time_dly(20);//wait amux channel capacitance charge ok
       set_sys_vol(20,20,FADE_ON);
       dac_mute(0,1);
       /* ladc_adcude(0); */
       printf("JL_AUDIO->DAC_CON :0x%08x\n",JL_AUDIO->DAC_CON);
       printf("JL_AUDIO->DAA_CON0:0x%08x\n",JL_AUDIO->DAA_CON0);
       printf("JL_AUDIO->DAA_CON1:0x%08x\n",JL_AUDIO->DAA_CON1);
       printf("JL_AUDIO->DAA_CON2:0x%08x\n",JL_AUDIO->DAA_CON2);
       printf("JL_AUDIO->DAA_CON3:0x%08x\n",JL_AUDIO->DAA_CON3);
       printf("JL_AUDIO->DAA_CON4:0x%08x\n",JL_AUDIO->DAA_CON4);
       printf("JL_AUDIO->DAA_CON5:0x%08x\n",JL_AUDIO->DAA_CON5);
   }
   
   void aux_close(void)
   {
       puts("aux_close\n");
       aux_st = 0;
       amux_ch_combine(0,0);
       amux_channel_en(DAC_AMUX0,0);
       JL_AUDIO->DAA_CON2 &= ~(BIT(12)|BIT(7));
       digit_auto_mute_set(1,-1,-1,-1); // 开自动mute
   }
   extern u8 aux_st;
   if(aux_st) {
        memset(read_buf,0x00,DAC_BUF_LEN);
   }
   #+END_SRC

* 20191008
** 天罡微693X
   063音量同步，提示音卡音杂音等问题，客户确认可以
** 起华AD135
   功能调试，客户回去装机测试
** 摩天693X
   手机播歌耳机没声音问题，还没看
** 威益德690X
   蓝牙音乐模式插播RDS声音，在线讲不通，最好让客户来一趟
** 汉欣诺692X
   BLE连接在设置界面上，回连出现连接失败，部分手机百分百，同个手机其他方案正常，敏贤处理中

* 20190930
** 汉欣诺692X
   BLE做HID链接在设置界面上，手动断开后点连接出现连接失败，需要珠海看，发程序给敏贤了
** 巴达木693X
   KXD068芯片死机，一开始sniff模式死机，后面是poweroff模式下死机
   一定要用IO口供电，不能用VDDIO供电
   进充电等，可以关掉触摸IC的供电

* 20190929
** 博建690X
   录音死机，栈被改了，函数返回死机，公版p4的不会，让客户换SDK
** 汉欣诺692X
   HID触摸，安卓的多点触控，横竖屏自适应都可以，
   但是苹果的7P不行，其他型号又可以，没手机测试
** 艾尔曼692X
   BLE死机，还是能出现，看客户log，暂时看不出问题

* 20190927
** 得辉达6932A
   USB当硬件IIC死机问题，DM内部上拉电阻太大，电阻越大波特率越小
   改为外部上拉就可以
** 科普豪692X
   音乐太短，无法单曲循环，新的SDK也会，SDK加了过滤时间为0的歌曲
   小于1s的歌曲认为是0

* 20190926
** 得辉达TX01-6932A
   调了一版程序，给中翔达装机。
** 693X
   USB当硬件IIC会死机，无法产生pend，while住了，镊子点IO口就正常，处理中
** 艾尔曼692X
   BLE死机问题，改了一版程序给客户测试，未反馈

* 20190925
** 得辉达TX01-32A
   DMDP用做硬件IIC,开机会死机,波特率不能高，400000就会死机
   主要插播一个配对提示音，区分回连模式跟配对模式

* 20190924
** 组创693X
   关机前留函数接口做复位功能，珠海改库，测试不能用，珠海还在改，等库测试
** 起华H3-6936D
   入耳离耳调试，基本能用，发给客户测试
** 得辉达TX01-32A
   调试中
** 汇杰芯693X
   老鼠BLE案子开发，支持中，测试盒问题，珠海处理

* 20190923
** 组创693X
   BLE用测试盒无法升级，要开EDR才可以，关机留接口，改了个库，还没试
** 汇杰芯693X
   BLE无法用测试盒测试，得看珠海怎么说
** 起华H3-6936D
   对耳入耳功能调试中
** 威益德690X
   linein杂音，客户在adc_scan里操作寄存器，
   虽然没有设置PA3，但是还会引起杂音，改成了库函数操作方式。

* 20190920
** 汇杰芯693X
   MCPWM映射任意IO，没有关掉原先的硬件IO
   *JL_MCPWM_CHx_CON0[arg->pwm_ch_num] &= ~BIT(2);

* 20190919
** 威益德692X
   睡眠后无法唤醒，降频成120M就可以唤醒，但是开发板一直正常
   可能跟芯片的flash有关
*** 获取目录号
   #+BEGIN_SRC c
   typedef struct _FSAPIMSG {
       u32	    musicdir_counter;    // 包含指定文件的文件夹序号
       u32     dir_counter;			// 文件夹序号
       u32     file_total_indir;     // 当前目录的根下有效文件的个数
       u32     file_total_outdir;	// 当前目录前的文件总数，目录循环模式下，需要用它来计算文件序号
       u32	    file_number;			// 当前文件序号
       u32     file_counter;		//用于搜索文件计数
       u8	    deepth;				// dir deepth for search
   } FSAPIMSG;
   #+END_SRC

** 羽恒692X
   用PA12检测不了linein,越界u8，被256整除
   #+BEGIN_SRC c
   #define AUX_IO_BIT    BIT(12)
   #define AUX_DIR_SET   (JL_PORTA->DIR |= AUX_IO_BIT)
   #define AUX_PU_SET    (JL_PORTA->PU  |= AUX_IO_BIT)
   #define AUX_IN_CHECK  ((JL_PORTA->IN  &  AUX_IO_BIT)>>12)
   #+END_SRC

* 20190918
** 威益德690X
   BLE蓝牙名回连后出错，已OK，
   linein下DACL杂音问题，应该是lineinL的问题，还没处理好

* 20190917
** 天地宏690X
   卡里只有flac文件，不读卡，公版没问题
   按路径字符串点播歌曲，要ANSI编码字符串，不能用Unicode
   无法点播flac歌曲，SDK有问题，未修改。
** 威益德692X
   进入sleep睡眠后，普通IO唤醒不了，电压又是正常的，协助中

* 20190816
** 元征693X
   BLE传大包卡最后一个小包，珠海改库，没出现卡的现象，但是有丢包现象，空中抓包分析应该是APP的问题
** 芯运6936D
   生产出货到用户手里开不了机，寄回来的机子都耗没电，重新充电又无法复现，只能先用最新的SDK，改DVDD最大给客户测试，看还能否复现，跟进中
** 尚凌693X
   音箱022反馈3个问题，已经回客户，已OK
** 天地宏690X
   2012-p4的SDK，flac反馈2个问题，还没看
** 科普豪693X
   之前改的左右耳不同蓝牙名，反馈2个问题，还没看
** 美师傅692X
   AI的V2.4需要IOS音量同步，要珠海改

* 20190912
** 伦茨6939B
   充满死机，测试不到，让客户打DVDD库给工厂测试
** 元征693X
   大包卡几秒，协助敏贤处理中，2边现象不一样
** 尚凌693X
   音箱0.2.2版本反馈3个问题，还没看
** 组创693X
   BLE的SMP协议，没有交换加密key，看一半，处理中
** 联创视听690X
   要去读取蓝牙连过的所有手机的MAC地址，来做循环回连，
   说是炬力有的功能，杰理要有，建议他不要做这个功能

* 20190911
** 元征693X
   BLE的SDK，接收大包时，会卡最后一个包，珠海处理中
** 汇杰芯692X
   录音模式下，删除文件，串口接收，栈死机问题，改了个程序，暂时客户没反馈有问题
** 中翔达692X
   BT168测试盒，连接后，刚开始A2DP是连上的，后面又会断开

* 20190910
** 起华H3-6936D
   双触控IC，反应有点慢，双击不了，易受电池印象，客户约触控IC原厂的人，过来搞
** 汇杰芯692X
   录音模式和串口接收，资源冲突死机，已OK
** 元征693X
   BLE大包传输，最后小包会卡机，要改个APP给客户测试，处理中

* 20190909
** 荣勤692X
   频偏大，影响速率，让客户换用12pF晶振再试试
** 也杨693X
   单独升级蓝牙名工具，我这边生成的，那边测试能升级，他自己生成的升级不了，原因未知
** 彩荣6925A
   生产开不了机，1/4分压电阻出错，寄珠海分析
** 中翔达6925F
   生产开不了机，断电后复现不出，原因未知，让客户加8s复位功能，看客户测试能否接受
** 中翔达6925F
   关机状态下，8s复位后，复位源出错，测试中
** 起华K3-6936D
   入耳检测脉冲，还没搞

* 20190907
** 加班一天

* 20190906
** 新智造6936C
   BLE案子开发，改了个程序给他们，OK
** 科普豪6936D
   左右耳不同名字，改成测试盒固定左右耳，测试正常给客户
   void lmp_hci_write_local_name(const char *name);
   lmp_hci_write_local_name((char *)(bt_cfg.edr_name));
   搜索的名字修改后，要重新注册EDR的名字，才不会连接后显示原来的名字
** 也杨6936D
   SC7A20敲击，卡音已OK，偶然性失效，测试不到，有可能是误判，客户测试中

* 20190905
** 也杨6936D
   加SC7A20敲击会导致蓝牙播歌卡，处理中
** 科普豪6936D
   左右耳不同蓝牙名，处理中

* 20190904
** 汉欣诺690X
   三星手机触摸，没搞好，珠海没空支持，跟进中
   690X的BLE做不了HID，接口没做好
** 也杨692X
   PC杂音，珠海说是同步问题，改了个库，这边测试正常
** 中天微693X
   mesh开发支持
** 汇杰芯6933C
   BLE案子开不了机
   修改isd_config.ini的flash配置
   SPI=3_3_0;	#data_width,clk,mode;

* 20190903
** BLE
   AC693X_bt_data_transfer_sdk_release_v1.0.0
   系统定时器用了Timer1，目前timer0/2/3都可以用
   #+BEGIN_SRC c
   u8 can_enter_lp = 1;
   static u8 custom_idle_query(void)
   {
       if(can_enter_lp){
           return 1;///可以进入low_power
       }else{
           return 0;
       }
   }
   
   REGISTER_LP_TARGET(custom_lp_target) = {
       .name = "custom_lp",
       .is_idle = custom_idle_query,
   };
   #+END_SRC
** 组创693X
   支持BLE案子开发，完成
** 汉欣诺690X
   三星手机HID触摸兼容性问题，用691X走BLE通道，测试正常，而690X要走传统蓝牙却不行，处理中
** 也杨692X
   PC模式侦听mic通道有哒哒声，珠海泽强处理中

* 20190902
  请假到下午2点半
** 科普豪693X左右耳固定不同蓝牙名
   #+BEGIN_SRC c
   #include "bt_tws.h"
   const char *bt_get_local_name()///单耳连接手机后,会执行一次，打印看不到
   {
       u8 channel = 'U';
       channel = tws_api_get_local_channel();
       if ('L' == channel) {
           bt_cfg.edr_name[3] = '-';
           bt_cfg.edr_name[4] = 'L';
           bt_cfg.edr_name[5] = 0;
       }
       else if ('R' == channel) {
           bt_cfg.edr_name[3] = '-';
           bt_cfg.edr_name[4] = 'R';
           bt_cfg.edr_name[5] = 0;
       }
       else{
           bt_cfg.edr_name[3] = '-';
           bt_cfg.edr_name[4] = 'U';
           bt_cfg.edr_name[5] = 0;
       }
       if (get_bt_tws_connect_status()) {
           bt_cfg.edr_name[4] = 'R';
       }
       r_printf("channel:%c..tws_connect_status:%d...bt_name:%s\n",channel,get_bt_tws_connect_status(),(const char *)(bt_cfg.edr_name));
       return (const char *)(bt_cfg.edr_name);
   }
   #+END_SRC

* 20190827-20190901
  日本旅游

* 20190826
** 也杨692X
   PC模式监听mic通道，一段时间后会变有哒哒声

* 20190823
** 起华
   i10、A3、i9S功能修改，已发出
** 威益德690X
   fm珠海改库，有改善，不达标
** 汇杰芯693X
   VDDIO抖，还没测
** 汉欣诺690X
   三星手机HID有兼容性问题，珠海改库，目前还不行

* 20190822
** 源创杰690X
   开隐藏文件无法播放录音文件，珠海改库，客户测试OK
   有个变量没有清零
** 尚凌693X
   开PC功耗高，珠海改了一个库，客户测试可以，但是珠海感觉很奇怪，后续还得看是否有反馈
** 也杨690X
   接串口RX后检测不准，还在测试中
** 汉欣诺690X
   HID触摸屏三星手机不行，还没看
** 起华AD135
   功能异常还没看
   LDOIN的电容拆掉

* 20190821
** 圣威泰690X
   第3方测试盒无法挂断电话，处理中
   测试盒很快就进入通话中，这个时候再发获取电话号码命令就会导致测试盒卡住
   无法挂断电话
** 起华A3-6936D
   功能修改，发给客户测试
** 尚凌693X
   开PC功耗问题，这边测试正常，客户那边还是不行
** 威益德690X
   收音问题，珠海库，不行，已反馈

* 20190820
** 鼐(nai)峰693X
   问题支持，剩魅族note5会死机，让客户写邮件过来，再看
** 也杨692X
   触摸受到D类功放的影响，让客户改板
** 起华
   A3-6936D i10-6936D AD135 程序修改，修改中
   A3改成没播歌5s闪蓝灯，播歌不闪灯

* 20190819
** 德科创693X
   BLE的功耗，珠海改库后，能达到100uA，发给客户测试
** 尚凌693X
   音箱SDK开PC后，关机功耗高，珠海改库，测试可以，但珠海说有其他问题，还要继续优化
** 荣勤692X
   SPP导致ram爆，测试剩余ram，已OK
** 起华A3-6936D
   功能修改，修改中

* 20190817
** 加班1天
** 汉欣诺
   客户带了一个手机投屏的电视，调试同时多点触控的HID
   样机是BLE的HID设备
   
* 20190816
** 尚凌693X
   音箱版本开了PC关机后，功耗会无端上升，珠海已复现
** 元征693X
   BLE数据发送，最后一包经常性出现卡，还没处理
** 新智造693X
   BLE案子ram不够，建任务，外部IO中断，PWM等功能，支持中
** 慧杰690X
   发射器连接不上苹果耳机，没有耳机测试，也有其他客户反馈，后续再看
** 汉欣诺690X
   HID触摸屏，三星手机异常，暂时没法处理，跟进中

* 20190815
** 起华
   A3-6936D、H3-6936D、i10-6936D案子调试
** 德科创693X
   纯BLE的待机功耗只能到250uA
   客户有板子能到100uA

* 20190814
** 威益德6905
   连苹果手机HID有概率性出现断连，已解决，
   FM干扰旁边信道，珠海IC暂时没招，要走邮件

* 20190813
** 尚凌693X
   调换声道后，自动mute发的声道会错误，要换算过来
   开了PC，程序睡眠功耗不一样，待处理
** 德科创693X
   BLE的SDK，关了EDR的可发现可连接后，不进低功耗，功耗有2mA左右，处理中
   const int config_btctler_modules        = (BT_MODULE_LE);///BT_MODULE_CLASSIC | 
   功耗在0.7mA左右

* 20190812
** 打印长文件名
   #+BEGIN_SRC C
   void puts_lfn(u8 *lfn,u32 lfn_cnt)
   {
       u32 i;
       for(i = 0; i < lfn_cnt/2; i++){
           extern u8 unicode_to_utf8(u32 unic, u8 *pOutput, u8 outSize);
           u16 tmp = (u16)lfn[i*2+1] << 8 | lfn[i*2];
           u8 utf[6];
           memset(utf, 0, 6);
           u16 len = unicode_to_utf8((u32)tmp, utf, 6);
           /* put_buf(utf,6); */
           for(u8 i = 0; i < len; i++){
               putchar((u8)utf[i]);
           }
       }
       puts("\n");
   }
   u8 unicode_to_utf8(u32 unic, u8 *pOutput, u8 outSize)
   {
       /* assert(pOutput != NULL); */
       /* assert(outSize >= 6); */   
       if ( unic <= 0x0000007F )
       {
           // * U-00000000 - U-0000007F:  0xxxxxxx
           *pOutput     = (unic & 0x7F);
           return 1;
       }
       else if ( unic >= 0x00000080 && unic <= 0x000007FF )
       {
           // * U-00000080 - U-000007FF:  110xxxxx 10xxxxxx
           *(pOutput+1) = (unic & 0x3F) | 0x80;
           *pOutput     = ((unic >> 6) & 0x1F) | 0xC0;
           return 2;
       }
       else if ( unic >= 0x00000800 && unic <= 0x0000FFFF )
       {
           // * U-00000800 - U-0000FFFF:  1110xxxx 10xxxxxx 10xxxxxx
           *(pOutput+2) = (unic & 0x3F) | 0x80;
           *(pOutput+1) = ((unic >>  6) & 0x3F) | 0x80;
           *pOutput     = ((unic >> 12) & 0x0F) | 0xE0;
           return 3;
       }
       else if ( unic >= 0x00010000 && unic <= 0x001FFFFF )
       {
           // * U-00010000 - U-001FFFFF:  11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
           *(pOutput+3) = (unic & 0x3F) | 0x80;
           *(pOutput+2) = ((unic >>  6) & 0x3F) | 0x80;
           *(pOutput+1) = ((unic >> 12) & 0x3F) | 0x80;
           *pOutput     = ((unic >> 18) & 0x07) | 0xF0;
           return 4;
       }
       else if ( unic >= 0x00200000 && unic <= 0x03FFFFFF )
       {
           // * U-00200000 - U-03FFFFFF:  111110xx 10xxxxxx 10xxxxxx 10xxxxxx 10xxxxxx
           *(pOutput+4) = (unic & 0x3F) | 0x80;
           *(pOutput+3) = ((unic >>  6) & 0x3F) | 0x80;
           *(pOutput+2) = ((unic >> 12) & 0x3F) | 0x80;
           *(pOutput+1) = ((unic >> 18) & 0x3F) | 0x80;
           *pOutput     = ((unic >> 24) & 0x03) | 0xF8;
           return 5;
       }
       else if ( unic >= 0x04000000 && unic <= 0x7FFFFFFF )
       {
           // * U-04000000 - U-7FFFFFFF:  1111110x 10xxxxxx 10xxxxxx 10xxxxxx 10xxxxxx 10xxxxxx
           *(pOutput+5) = (unic & 0x3F) | 0x80;
           *(pOutput+4) = ((unic >>  6) & 0x3F) | 0x80;
           *(pOutput+3) = ((unic >> 12) & 0x3F) | 0x80;
           *(pOutput+2) = ((unic >> 18) & 0x3F) | 0x80;
           *(pOutput+1) = ((unic >> 24) & 0x3F) | 0x80;
           *pOutput     = ((unic >> 30) & 0x01) | 0xFC;
           return 6;
       }   
       return 0;
   }
   #+END_SRC
** 德科创693X
   最新BLE的SDK，连接参数修改，已OK
** 元征693X
   BLE做主机应用，旧的SDK有demo，最新的没有，先让客户用旧的开发
** 慧杰692X
   通话保留功能，珠海说暂时没有做过，不支持
** 昂晖6905C
   profile认证pbap协议版本V1.0过低，需要支持到V1.1或V1.2，珠海反馈没支持，得后续再看

* 20190725-20190809
  24号下午开始，请陪产假

* 20190724
** 也杨6939F
   贴的是6939B，
   软件改成单声道会变调
   李超改了个库，测试OK

* 20190723
** 起华B218-6936D
   生产需要改成一直回连的操作，改了给客户测试
** 中翔达6936D
   同步关机提示音，改好给客户，提示音偶尔不同步能测到，不知道怎么改
** 也杨6939F
   生产2%底噪大，板子寄到，准备看

* 20190722
** 中翔达6936D
   改同步关机死机问题
** 华炬芯尧顺
   出差半天

* 20190719
** 威益德690X
   后台下回连后，A2DP连不上，导致没声音
** 中翔达693X
   关机提示音同步，改了例子给客户了

* 20190718
** 中翔达693X
   大康G71样机功能调试
   远距离断开，回连3分钟内，不能被搜到
   有2款手机对打电话有白噪声，其他方案也有

* 20190717
** 广播
   BLE广播文档编写
   
* 20190716
** 华炬芯客户
   支持客户调试AD135和061的广播弹窗

* 20190715
** 出差国华一天
   培训693X

* 20190412
** 伦茨
   2款中控耳机都有回音
   layout接地不好
** 恒大692X
   串口AT协议，写了一个demo

* 20190711
** 起华H3-6936D
   程序发出给客户测试
** 威益德690X
   2款样机，
   一款开不了机已解决，
   另一款死机，目前有3种情况，vm_write_api(),蓝牙断开连接，ID3解析后，处理中

* 20190710
** 联巨兴693X
   音箱linein单声道，测试板测试OK，让客户自己查硬件
** 爱尚692X
   调节sniff slot需求，要改库，要珠海处理
** 起华6936D
   A3和H3，需求修改中

* 20190709
** 威益德690X
   触摸屏HID，安卓手机偏移，已弄好，有一个苹果手机，配对不上HID通道，其他手机正常，暂不处理
** 起华A3-6936D
   通话调试中
** 美师傅693X
   插卡开机，读不了卡，SDK问题，已OK

* 20190708
** 中翔达6936D
   生产出现充电异常，是外壳导电导致，充电功耗异常导致充电仓芯片检测出错
** 中翔达6936D
   360手机有回声，目前还没测试到，怀疑客户板子的问题
** 起华i9S-6936D
   通话有回声，分地后，还是不行，还是有回声，原因还未知

* 20190705
** 威益德690X
   进不了PC模式，客户程序bug，已OK
** 博益友693X
   2016晶振死机，打补丁即可，测试OK
** 中翔达693X
   删除配对后又自动配对上，给客户修改，客户测试中
   部分手机，msbc关掉就可以

* 20190704
** 威益德6900A
   升级死机，PR2连接的芯片，会拉低IO，导致4s复位
** 中翔达693X
   060的SDK不支持三方通话，需要置位more_hfp_cmd_support变量

* 20190703
** 起华i9S-6936D
   硬件处理，回声除不掉
** 693X的DUT测试
   测试EDR灵敏度，output power要设置Apply Impairments

* 20190702
** 起华i9S-6936D
   功能调试，通话有一整串回音

* 20190701
** 请假1天

* 20190628
** 出差巴达木好唛
   处理6937A的案子
   双击回拨通话，连续回拨会死机，要做个处理判断是否已经通话break
   硬件LDO方式，软件用DCDC会导致距离很短。

* 20190627
** 华炬芯690X
   HID描述符动态注册，要改库，暂时给客户改成了切换模式
** 欣瑞声692X
   点阵屏菜单死机，还在看
** 起华I9S-6936D
   案子功能还没调
** 新时代690X
   发射器SDK用spp发数据会卡住导致丢包，还没看
** 中翔达693X
   BLE广播改不了充电仓电量，还没看

* 20190626
** 起华B218-6936D
   4个问题修改已发出
** 内部693X
   DUT测试，灵敏度测不过，和珠海验证中
** 中翔达693X
   微信语音嗡一声，已OK
   #include "media/includes.h"
   extern struct adc_platform_data adc_data;
   if(adc_data.mic_capless == 0){
      SFR(JL_AUDIO->ADC_CON,12,4,8);
   }

* 20190625
** 693X
   调换声道，
   .output = DAC_OUTPUT_LR+3
   #define AUDIO_OUTPUT_MODE   AUDIO_OUTPUT_STEREO
** 中翔达693X
   通话发语音会嗡一声，振荣在看
   音量同步兼容性问题，针对三星手机，样机无法设置手机

* 20190624
** 威益德690X
   HID触摸屏，按照海华修改，发给客户
** 中翔达693X
   055的SDK，3个问题
   BLE广播，回连手机的时候默认没有打开
   通话发语音会嗡一声
   音量加减兼容性问题，vivo，三星S8，红米手机音量加减没有作用

* 20190622
** 加班1天
** 美师傅690X
   p4的SDKpitch_coff()会死机
** 科普豪690X
   V2013通话插播提示音会导致mic没声音，没测到

* 20190621
** 出差巴达木1天

* 20190620
** 出差巴达木1天

* 20190619
** 出差巴达木1天

* 20190618
** 威益德690X
   传统蓝牙HID触摸屏针对IOS12.2以上，不起作用
   寄给海华分析
** 起华693X
   FF216-6936A，升级工具的拨码要拨2档
* 20190617
** 慧杰692X
   文件浏览器功能，在AI的V2.4版本添加完成发给客户了
** 威益德690X
   传统蓝牙HID触摸屏针对IOS12.2以上，不起作用

* 20190614
** 华炬芯奋达692X
   自动化测试挪用V2.6.2版本，已经发了个版本给客户试用
** 中翔达德芯成8006
   多个问题，整理了一个版本，已发出，给客户测试用

* 20190613
** 请假一天

* 20190612
** 693X性能测试
   耳机的SDK没有相关的代码
   音箱的SDK有代码，但是测试不了
   验证692X的是正常的。
** 起华693X
   i9机子无法充电，帮客户安装电脑工具。

* 20190611
** 也杨692X
   数码管显示，改好发给客户
** 科普豪693X
   054的SDK没法在线调EQ，关掉TCFG_TEST_BOX_ENABLE即可

* 20190610
** 请假一天

* 20190606
** 也杨
   692X断不开华为手机蓝牙
   U盘和SD卡，切换显示设备图标
** 德芯成8006
   dac杂音问题，
   测试是AUTO_UMUTE出来的，mute的时候也有

* 20190605
** 中翔达德芯成
   出差1天
   和耀聪去德芯成验证6936D的D版晶圆的距离

* 20190604
** 中翔达6936A
   中控耳机，2个按键组合使用，通话回声问题，客户测试中
** 起华FF216-6936A
   中控耳机，2%出现开关机死机，需要更新SDK，增加复位功能
** 美师傅6905
   推RGB灯，会有电流声，换个升压IC的电感，就变得很小，只能这样处理

* 20190603
** 中翔达德芯成8006
   dac杂音问题，用客户的EQ文件，就会出现。
   公版的默认全0就不会
** 起华B218-6936D
   更新053的SDK,按键音有问题

* 20190531
** 中翔达8006
   珠海在处理
   带BLE和不带BLE的，发个版本给客户测试
* 20190530
** 中翔达德芯成
   出差半天，处理8006配对慢
* 20190529
** 中翔达德芯成
   充电仓BLE的工程过来处理弹窗
* 20190528
** 中翔达德芯成
   出差中翔达半天，晚上去德芯成

* 20190527
** 嘉兴科美
   692X和690X，dac吱声和调音量哒哒声，
   改成dac_vcm_rsel_set(1);mode == 1{delay(0xAFFF*300);//600ms}
   改成dac_power_on quickly,但是时间拉的比较长，就可以解决

* 20190525
** 中翔达德芯成
   出差1天
   在科迈捷工厂，升级0.5.3版本测试6936A
   800X打珠海发过来的补丁，测试死机问题
   修改方式：
   把异常中断的代码挪到ram里面，确保flash死机后，还能执行
   看门狗，不清楚
   8s复位失效原因未知

* 20190524
** 中翔达德芯成
   出差下午
   在翔翔宇测试693X和800X的死机问题

* 20190523
** 中翔达德芯成693X
   出差一天
   还有开机死机，测试盒死机，测试盒提示音之后音量变小

* 20190522
** 嘉兴科美692X
   频谱死机，和VM冲突
   中断计算频谱时，要加入    if (0 == get_vm_statu())
   automute高频吱吱声，改成VCM_RSEL_1,delay_2ms(400);///70

* 20190521
** 中翔达德芯成
   693X充电死机，抓到一个异常死机，给珠海
   800X充电死机，测不到

* 20190520
** 中翔达德芯成693X
   出差一天

* 20190518
** 起华B218-6936A
   功放mute，现在剩一点点噗噗声
   有电流声，白噪声大
** 693X加大dac驱动电流
   JL_ANA->DAA_CON3 |= ((u32)0xf << 8);

* 20190517
** 科普豪692X-AI
   串口通信，杰理智能APP通信，小度
   3个问题，客户测试中
** 慧杰692X
   BLE的mtu修改，测试正常

* 20190516
** 德科创690X
   串口波特率1200会卡蓝牙播歌，新建任务来发送
   6908C做BLE功耗大，降到8mA
** 科普豪6939B
   上电冲击声大，6939B没有VCOM脚，没有这个电容，上电波形会在5us
   有这个电容，上电就会50ms时间的缓冲

* 20190515
** 中翔达6936A
   客户嫌弃微信语音声音大，在aec建立，重新获取下通话音量，重新设置下音量
   客户红米手机，微信语音声音会变小，手机问题
   我的华为手机，连接后获取音量都为15，要手机调节音量之后，获取才正常

* 20190514
** 台德6905C
   开不了机
   出差一天
* 20190513
** 起华FF216-6936A
   生产不良
   通话没声音，声音小，时大时小

* 20190511
** 汇杰芯志康6904D
   对耳通话调试
   给了客户原先中翔达的程序
** 中翔达6939M
   功耗大，客户耳机阻抗是3.2R，用32R的喇叭功耗正常

* 20190510
** 博益友692X
   BLE连IOS出现断开不了，APP闪退，
   由于profile定义了HID导致
** 源创杰692X
   进入不了异步唤醒的sleep，
   由于客户enter_sleep_mode重定义了此函数导致。

* 20190509
** 台德6905C
   开不了机，主控停在uboot下，DP有个定期的脉冲波
   AC6901A空片也有一个相同的波形，其他芯片又不一样。

* 20190508
** 出差台德一天
   
* 20190507
** 起华B218-6936A
   有耳机功放，自己加不了mute控制，等珠海在看
** 联巨兴692X
   录音文件按文件名排序播放，会出现解码错误，由于没有停解码就改写文件指针导致
** 科普豪693X
   需要操作功放mute，让他们等珠海处理

* 20190506
** 摩天6936A
   提示音同步，要自己加流程
   打电话要播提示音前，会嘶一声
   打电话第一声会不同步
* 20190505
** 请假1天
* 20190430
** 天浪690X
   玩具的SDK开音乐音量同步会死机，远强处理
** 永泰胜6904D
   6904D替换6916A，距离短
   换用双通的SDK，也没提升

* 20190429
** 起华FF216-6936A
   音量同步异常，已发出
** 摩天6936A
   回连问题，是串口设置成115200导致
   灯抖动，pdown_keep_pw_gate()函数直接返回true，表示不降电压档

* 20190428
** 起华FF216-6936A
   开关机死机，播歌下插USB死机，改硬件电容为106
   改了一个mic省料的版本给客户选择
** 中翔达6936A
   通话音量不同步，rebuild一下就好，杂音问题，振荣说只能等下一个版本才能更新

* 20190427
** 充电流程
*** 涓流充电
    电压低于3V，采用20mA档位进行涓流充电
*** 恒流充电
    电压大于3V，才转成设定的恒流档
*** 恒压充电
    电压接近4.2V后，由硬件自动转成恒压充电
** 中翔达
*** 台德6905C
    读了2个芯片，芯片的程序跟客户给的程序对应不上，是另外的校验码
*** 澳特爱6901A
    读了2个芯片，程序是错乱
    flash型号为5E6014为2.6Vflash，需要对LVD低电复位做2.6V
    还有关机，改成进低功耗形式。

* 20190426
** 起华FF216-6936A
   开关DAC有杂音，振荣在看
** 起华B218-6916A
   带功放的中控耳机，改好给客户了
** 华炬芯692X
   播放flac的某首歌会卡顿，公版2.6.1正常
** 瑞荣达690X
   有些安卓手机打开sco链路后，会导致BLE断开
   690X的音箱和AI版本都会
   692X会有优化，但是无法避免
   靠业务去解释了

* 20190425
** 华瑞微692X
   BLE主从通信，写了个流程给客户了
** 科普豪691X
   小米MAX1，在耳机端回拨电话，会导致手机断连。
   库打印多了LMP_REMOVE_ESCO_LINK_REQ命令导致，具体原因未知
   珠海测试部，MAX3没有问题。
** 联巨兴692X
   录音文件中间有文件删除掉，会导致录音文件排序有问题
   建议客户将录音文件序号记VM，然后以路径形式去播歌。

* 20190424
** 6936充电
*** 充满后
    耗充电仓150uA-200uA，耗耳机20uA左右
    正常关机后功耗是1uA-5uA之间
*** 充满硬件判断
    充满电流档，是比如你设置充满电压是4.2V，一开始我们是恒流充电，接近充满电压，
    硬件会自动转成恒压，恒压充电过程，充电电流会一直变小，
    当充电电流接近这个充满电流，就认为充满了。
    charge这个中断，是当充满电流接近设置值，就会一直起中断。
*** LDOIN中断
    ldoin那个中断，是用来检测插入和拔出的。小于0.6V，认为拔出，
    大于1.3V，认为插入，这两种情况，都能起ldoin中断
*** 最大电流档
    BR18最大是300mA，但是没有测试过200mA以上的充电
    可能会引起芯片过热。建议预留外部充电。
*** 开机充电
    开着机充电，是跑LDO模式的，不能进低功耗。
    有这个要求的，建议不用内部充电。
** 联巨兴6936A
   播提示音会咋咋声，声道要设置对，没有启用的声道就有
   左右耳的按键功能区分。
   #+BEGIN_SRC C
   if ((tws_api_get_role() == TWS_ROLE_MASTER)&&(u32)event->arg == KEY_EVENT_FROM_TWS)) {
   }else{
   }
   #+END_SRC
** 美师傅6936A
   电量检测异常，烧录也会，原因未知
   可以打印 get_vbg_trim(),正常为1
   
* 20190423
** 也杨6936B
   客户的驻极体mic头，改不了，换个其他的mic就OK
   具体那种mic有啥特殊，未知
** 中翔达6936B
   17个问题，大部分要珠海解决，等明天新版本
   
* 20190422
** 中翔达科迈通6904
   出差1天
   开机后从机打开可发现可连接后，被测试盒连接了
   改成不可发现不可连接，几秒钟后，再打开可发现

* 20190420
** 也杨6936
   升级一半死机，USB下载也跑不起来，要加-format vm
   通话咋咋响，改了偏置没用，换用我们的mic就可以，客户回去换用mic验证。

* 20190419
** 中翔达6936A
   几个问题，剩一个充电死机的，接打印一直测不到，处理中
   主控由2个trim，VBG和VBAT
   电量检测，用VBG的trim，vbg value 414
   充电4.2V电压档，extern u16 get_vbat_trim()，15为没有trim，正常是8左右

** 天罡微6936B
   功耗60mA，是BTAVDD没有接到AVDD上导致，已OK
   693X主控的AVDD和HPVDD是输入电压，电压有外围决定，可以由VDDIO/BTAVDD/TF_VDD供电
   sdpg_config(1);设置芯片内部TF_VDD接到AVDD上，那板子就不用接线
   6936B有绑定AVDD引脚出来,需要由板子决定，芯片内部就不能开sdpg_config(1);

** 美师傅6936A
   SCO切换问题用8K也不行，让客户等新版SDK，
   （开机之后不松手再按2S进配对态，也就是不回连。不可发现，只可连接）功能，还没看

* 20190418
** 普利金6921A
   linein下白噪声随音量变大而变大，公版SDK也这样
   但是蓝牙下就不会，暂时无解
** 美师傅6936A
   换PA8、PA9无法推灯，是开发板顶板没有短接
** 博建6936A
   双击断开对箱会死机，新发的SDK，公版不用改，就能测到

* 20190417
** 汉欣诺690X
   通话死机，会看门狗复位
   PCB的AGND过孔不通，没接地导致
** 天浪6919D
   手机APP用BLE同时拖7个样机，数据异常，在APP发送数据加入同步锁，避免数据被改，
   把连接间隔调小，避免卡数据，客户测试正常
** 联巨兴和伦茨
   发射器的SDK，加音乐音量同步和pin_code，测试OK，都已发出

* 20190416
** 爱瑞声6905
   K歌宝加对箱，连接有些连不上，程序流程问题，客户在测试
   公版SDK在半秒里面切换可发现/不可发现
   针对某些手机配对比较慢，会导致配对失败

** 联巨兴692X
   发射器死机问题，客户测试OK，音量同步问题，要珠海做

* 20190415
** 联巨兴691X
   电池电压低于3.0V时，充电会使用涓流充电，这个时候会拉低LDOIN的电压成3.6V
   充电充一会，电压升上来后，正常电流充电后，LDOIN的电压才变成4.7V以上
** 中翔达6916A
   lightning耳机高频声
   修改软件优化一些，但是dac_mute之后手机的4G信号干扰声还是有，就改不了

* 20190413
** 出差
   科迈通6916A回连不了，客户程序问题
   科迈通6916A对耳，播歌一段时间后，会卡然后断开，又重连，应该是蓝牙功率最小值被调成0导致
   三杰鑫6916A的lighting耳机，电流声，未解决

** 异常中断
   http://192.168.8.211:8000/ 看sdk.exe的符号信息
   从RETI和RETS可以看出，RETS就是中断地方

* 20190412
** 联巨兴692X  
   对箱播歌，插播最大声提示音，提示音播完后，会卡几声。
   志英改库，加大包数阀值，已解决
** 联巨兴691X
   充电异常，是1.2V参考电压检测异常，还没搞定，这边复现不了
** 联巨兴692X
   发射器7个问题，找到3个死机原因了，还在处理中
   发射器不可以开可发现可连接，690X也一样
   插pc异常中断，执行fat_read()死机。
   插拔SD卡软复位，fat_init()断言复位
** 华炬芯691X
   OTP升级，测试可以，已发出
** 168公司
   690X带HID开pin_code，无法连接，还没处理
   还没测试HID的dev class
** 源创杰692X
   对箱连接后卡音，跟联巨兴用同一个库测试，客户反馈还有一点点卡音

* 20190411
** 联巨兴692X
   对箱问题，4个问题，还有一个在搞
   a2dp_media_play会调用2次
   第一次会卡音，直到第二次之后才正常
** 联巨兴691X
   参考电压1.2V，正常开机模式正常，一进充电，就变成3-4V，
   导致电池电压检测异常

* 20190410
** 下午请假
** 天浪690X
   玩具的SDK，在蓝牙下点播外部flash提示音，测试OK

* 20190409
** 上午请假
** 源创杰692X
   V2.6.1对箱开混响，有杂音
   志英改库，测试可以

* 20190408
** 港芯微691X
   开启125us中断，需要把调用的函数都指定到AT_RAM里面去
** 天罡微691X和692X
   针对12.2版本的IOS，音量同步有问题，测试应该是底层有点问题，处理中
** 华炬芯691X
   OTP的SDK，V202之后配置文件工具变了，导致之前的bfu工具不能用，要珠海处理
** 源创杰692X
   从机断电后，主机数据包发不出去，会堆积，导致声音卡，处理中
** 天浪690X
   玩具SDK开外部flash，播提示音申请不到ram，会复位，先发A2DP-STOP之后再播也不行，还没看

* 20190404
** 692X发射器
   珠海发来程序，音箱重新开机回连是会reason=0x05
   关掉SD卡和USB，回连变死机

* 20190403
** 起华
   FF216-6904D，上样机后，蓝牙距离短，卡音
   socket板子正常
** 华立
   S36-4601，检测7.4V电池电压
   采用1M+330K的分压电阻

* 20190402
** 早上请假半天
** 起华
   R208-6904D双通对耳调试中
** 美师傅
   6905C发射器连接慢，客户发起搜索打断了回连的命令导致的
** 徳凯芯692X
   HID Home键功能，苹果不兼容，得珠海看

* 20190401
** 联巨兴692X
   发射器SDK，统计了下，有6个问题发给珠海了
** 皇马
   690X的车充，晶振频偏大，不稳定，负载电容应用12pF的

* 20190330
** 中翔达800X
   充电为恒流充电，充电电流可调
   充电电压随电池电压上升而上升。

* 20190329
** 起华
   FF216-6916A换用6904D

* 20190328
** 源创杰692X
   开机单独回连对箱不回连手机功能，已OK
** 威益德690X
   开机回连要1分钟，协助客户已解决
** 国华691X
   客户需要双模修改底层，这边支持不了，让客户自己找珠海协助
** 起华FF216-6916A
   中英文双语音切换，已发出

* 20190327
** 科普豪6925B
   AI的SDK带混响，BLE的广播会影响到mic的采样数据
   板子改板
** 图然劲卓
   690X触摸屏HID，培训客户，给了个demo
** 威益德690X
   回连要1分钟，客户改出来的问题，给客户方式测试
** 羽恒692X
   m4a会死机，要换库

* 20190326
** 汉欣诺690X
   触摸屏HID，苹果手机正常，但是安卓手机，开启旋转，坐标系尺寸变化有问题，暂时找不到办法处理
** 科普豪692X
   百度AI带K歌宝功能，喊话有轻微的哒哒声，和客户对接中
** 华炬芯690X
   iPhone连3个音箱，第3个回连后无法控制，发给珠海解决
** 威益德690X
   蓝牙模式下，动态切换linein声音和蓝牙声音

* 20190325
** 港芯微
   691X-BLE设置us级定时中断
** 汉欣诺690X
   触摸屏HID枚举，能使用发给客户了
** 华炬芯乐百川
   6928B对箱主副机大小声，EQ模式变量问题
** 威益德
   690X在蓝牙模式下，切换蓝牙声音和linen的声音
   参照蓝牙和linein耦合输出

* 20190324
** 华炬芯乐百川
   6928B对箱主副机大小声
   是硬件EQ的参数被改导致，志英和振荣在看。

* 20190323
** 华炬芯乐百川
   6928B对箱，从机EQ有可能被改动过
   导致主副机功率不一致。
** 华炬芯
   691X-BLE的SDK，长按4s复位。告知客户
   换个开发板可以了
** 源创杰692X
   linein和蓝牙同时出声音
   #+BEGIN_SRC C
   void aux_open(void)
   {
       puts("aux_open\n");
       if (LINEIN_CHANNEL == DAC_AMUX0) {
           JL_PORTB->DIR |= BIT(4) | BIT(5);
       } else if (LINEIN_CHANNEL == DAC_AMUX1) {
           JL_PORTA->DIR |= BIT(3) | BIT(4);
       } else if (LINEIN_CHANNEL == DAC_AMUX2) {
           JL_PORTB->DIR |= BIT(6) | BIT(3);
       }
       dac_mute(1, 0);
       sound_automute_set(0, -1, -1, -1); // 关自动mute
       linein_channel_open(LINEIN_CHANNEL, 1);
       linein_gain_en(1);
       /* ladc_mic_gain(mic_gain, mic_gx2); */
       aux_2_dac(1, 1);
       extern void delay_2ms(u32 delay_time);
       delay_2ms(100);
       dac_mute(0, 0);
   }
   void aux_close(void)
   {
       puts("aux_close\n");
       dac_mute(1, 0);
       sound_automute_set(AUTO_MUTE_CFG, -1, -1, -1); // 开自动mute
       linein_channel_close(LINEIN_CHANNEL, 0);
       aux_2_dac(0, 0);
       delay_2ms(100);
       dac_mute(0, 0);
   }
   #+END_SRC

* 20190322
** 源创杰690X
   蓝牙下和linein同时出声音
   #+BEGIN_SRC C
   void aux_open(void)
   {
       puts("aux_open\n");
       if(LINEIN_CHANNEL == DAC_AMUX0) {
           JL_PORTA->DIR |=  (BIT(1)|BIT(2));
           JL_PORTA->DIE &= ~(BIT(1)|BIT(2));
           JL_AUDIO->DAA_CON2 |= (BIT(0)|BIT(1));
       }
       else if(LINEIN_CHANNEL == DAC_AMUX1) {
           JL_PORTA->DIR |=  (BIT(4)|BIT(3));
           JL_PORTA->DIE &= ~(BIT(4)|BIT(3));
           JL_PORTA->PD  &= ~(BIT(3));//PA3 default pull_down
           JL_AUDIO->DAA_CON2 |= (BIT(2)|BIT(3));
       }
       else if(LINEIN_CHANNEL == DAC_AMUX2) {
           JL_PORTB->DIR |=  (BIT(11)|BIT(12));
           JL_PORTB->DIE &= ~(BIT(11)|BIT(12));
           JL_AUDIO->DAA_CON2 |= (BIT(4)|BIT(5));
       }
   
       dac_mute(1, 0);
       digit_auto_mute_set(0, -1, -1, -1);
       amux_channel_en(LINEIN_CHANNEL,1);
       /* linein_gain_en(1); */
       /* aux_2_dac(1, 1); */
       JL_AUDIO->DAA_CON1 |= (BIT(6)|BIT(7));
       JL_AUDIO->DAA_CON1 &= ~(BIT(13));
       JL_AUDIO->DAA_CON2 &= ~(BIT(13)|BIT(10));
       JL_AUDIO->DAA_CON2 |= (BIT(6)|BIT(7)|BIT(12));
       JL_AUDIO->DAA_CON3 &= ~(0xff);
       JL_AUDIO->DAA_CON3 |= (BIT(8)|BIT(9));
       /* dac_AmuxGain_en(1); */
   
       /* extern void delay_2ms(u32 delay_time); */
       /* delay_2ms(100); */
       os_time_dly(20);
       dac_mute(0, 0);
   }
   void aux_close(void)
   {
       puts("aux_close\n");
       dac_mute(1, 0);
       digit_auto_mute_set(AUTO_MUTE_CFG, -1, -1, -1);
       amux_channel_en(LINEIN_CHANNEL,0);
       JL_AUDIO->DAA_CON1 &= ~(BIT(6)|BIT(7));
       /* JL_AUDIO->DAA_CON2 |= (BIT(6)); */
       /* aux_2_dac(0, 0); */
       /* delay_2ms(100); */
       os_time_dly(20);
       dac_mute(0, 0);
   }
   #+END_SRC

* 20190321
** 华炬芯乐百川
   6928B对箱，客户程序输出幅度比公版SDK偏低200mV
   暂时找不到原因
** 华立S36-4601
   关升压后出不来声音，功放的10R贴成了100R

* 20190320
** 华炬芯乐百川
   出差一天，处理6928B对箱问题
   输出功率不一致，带回处理
** 联巨兴6901A
   DAC有嗡嗡声底噪
   清零VCM_RSEL，VCOM偏置电压电阻选择，高时缩短DAC稳定时间。
   JL_AUDIO->DAA_CON1 &= ~BIT(13);

* 20190319
** 起华R208-6916A
   对耳调试，充电仓会掉电到0V

* 20190318
** 汉欣诺691X
   车机触摸屏HID report枚举OK，已发出
** 华立S36-4601
   增加低电提示音，已发出

* 20190316
** 华炬芯692X
   对箱从机断电后，主机会死机，而且有杂音，查不出来
   音量同步发给客户参考

* 20180315
** 新欧微691X
   修改BLE显示图标，已告知
*** characteristic.gap.appearance
    https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.characteristic.gap.appearance.xml
    Name: Appearance
    Assigned Number: Ox2A01
*** 广播包
    #define EIR_GAP_APPEARANCE   0x19  /* GAP appearance */
    值跟特征设置成一样
** 源创杰690X
   插拔U盘，会导致BLE断连，让客户同时双模再关EDR，测试OK
** 华炬芯692X
   苹果手机连3台设备，第3台无法控制APP，得珠海处理
** 联巨兴6901A
   生产不良，新的批次芯片DAC底噪问题，移交珠海
** 汉欣诺691X
   枚举触摸屏HID，调试中

* 20190314
** 联巨兴690X
   dac有底噪声，VCOM加大到106可以解决
   软件商降低HPVDD、提高VDDIO有改善。
   需要珠海给函数原型
** 科普豪692X
   APP单独连接spp，会有弹框
** 鑫凌波8006
   酷狗提示音“hello 酷狗”前面会被截少一段
   瑞昱的不会
** 起华
   FF216-6916A，FCC认证
   只有一个机子杂散不会超标
** 华立
   S12B-4601已发出
** 伦茨
   6916A双通对耳升级复位后初始化VM死机，已OK
   extern s32 vm_eraser(void);
   vm_eraser();

* 20190313
** 691X-BLE-HID
   缺失MCPWM的库
   缺失LDO_ref的参考电压
** 彩荣
   690X对箱连接瞬间有杂音，客户找出是linein能量采集引起
   692X循环播放号码提示音，已解决
** 联巨兴691X
   充电充不满，修改充电检测流程，测试OK
** 鑫凌波
   8006问题
   微信语音杂音的，是在安卓测试的，苹果没测
   酷狗的，对耳连上后，“hello酷狗”，前半段不响，测试的也是2台安卓手机 

* 20190312
** 巴达木6916A  
   对耳通话断开，自动配对，都OK
** 彩荣690X
   对箱有杂音，开发板没测试到，让他们清buf都说还有，建议他们试试硬件
** 中翔达690X
   APP需求修改，西班牙语等其他功能好改，
   主题颜色底层和安卓原生主题交叉引用，森华在加一个多渠道配置，珠海处理中
** 联巨兴6916A
   对耳充电检测一直没检测到充满，他的程序问题，已改好，
   至于充不满就检测到充满，让他调阈值测试中

* 20190311
** 博建691X
   EQ文件没有加载，ram不够
   用串口调试后，把数值写到软件的数组里
** 汉欣诺触摸屏HID
   样机搜不到连不上，无法使用
** 伦茨691X
   充电充不上4.1V
   由于电池内阻存在，充电电压被电池内阻分压后，
   实际充进电池的电压会降低。

* 20190309
** 800X通话大小声
   通用691X的丢包修复库
   lib_esco_repair.a-V105
** 博建800X
   对箱连接，固定主副机
   当副机被手机连上，主机回连从机是page不上的。
   不支持

* 20190308
** 800X充电
   有一个机子充电充不满
   [TRIM VDD]Bluetooth VBG enable
   [TRIM VDD]VBG trim value : 0(每个芯片trim的不一样，0x3f是没有trim)
   [TRIM VDD]VBG value : 1200(mV)
   沈沛先找IC查trim的流程
** 威益德690X
   p2的SDK，先打印蓝牙名后打印地址。
   保留打印蓝牙名的指针即可。

* 20190307
** 源创杰692X
   不要通话但要微信语音，改好给客户测试
** 起华i9-8006
   对耳目前有2个板子软件功能正常。
   但是一个板子有点发热，DAC短路
   装机后，无法配对，容易断开，天线焊错
   另外2个板子da230有点问题
   
* 20190306
** 800X微信语音会渣一声
   通话是实时的，12个slot一个周期，在规定时间要去对齐收数
   msbc暂时没有做好，先关闭
   先用CVSD测试用，690X，691X，692X都是这个
** 800X通话效果
   通话不同步，棉鸿发库给博建测试
** 博创昱6916A
   底层有个tone_pwr，播提示音的时候会下降功率到4，之后靠手机提升到9
   软件设置的最大最小功率，给手机参考用
*** 800X的打印
    [info] :[LMP]LMP_INCR_POWER_REQ(手机发过来加功率的请求)
    power :7
** 科普豪692X
   AD检测电压不了，发程序过来检查是编译问题
** 源创杰692X
   想要微信语音，但是不要通话
   还需要测试下流程
** 起华
   W02-6916A 功放接电池电压，会削顶失真
   4V电池电压，播1K 0dB，主控只能26级输出，暂时设置成27级
   i9-8006 有一个机子能读DA230，一个机子不行。
** 华立
   S36-4601添加CJ-B提示音，已发出

* 20190305
** 华炬芯690X
   咨询传统蓝牙HID
** 威益德690X
   用vivo Y97挂断电话命令卡几秒
   替换海华改的蓝牙库,和加下面2句
   __set_esco_packet_type(1);
   __set_esco_repair_en(1);
** 博创昱6916A
   通话距离短
   让珠海改库，V203-p3提升2db和设置最小功率接口的蓝牙库

* 20190304
** 威益德690X
   fm下录音，已OK，通话挂断卡几秒，珠海协助中
** 内部691X
   BLE-HID的SDK，烧录对烧写器版本有要求，
   部分功能不完善，调试中，再补个文档说明，进行中

* 20190302
** 鑫凌波8006
   在sniff状态下，低电同步关机会死机，棉鸿给了个修改，测试无效，已反馈珠海
   已更新蓝牙库，已OK

* 20190301
** 起华
   FF206-6916A功放解mute有噗声
   是在DAC中断里dac_hp_toggle(DAC_CHANNEL_SLECT)直流偏置才会打开
** 鑫凌波8006
   对耳音量无法同步苹果，SDK默认没有打开音乐同步的注册
   sniff关机会死机，棉鸿给的方式，无作用。
** 天罡微691X
   AUX检测脚接在VCOMO上，进sniff之后，VCOMO被关掉为高阻态，检测不到
   建议客户，定时，每隔1s退出sniff，打开DAC后，才能检测。

* 20190228
** 拜瑞6905A
   BLE透传功能，帮客户加了缓冲
** 联巨兴6916A
   串音，代码有问题，socket测试可以
** 起华
   FF208-6916A程序OK，
   FF206-6916A加PA会有噗声，待调

* 20190227
** 鑫凌波8006
   低功耗后，从机同步主机关机时，主机死在LMP的while循环里，刚转给立辉看，
   充满电关机后拔起开不了机，公版正常，客户发程序过来测试,开机有按键过滤操作
** 起华
   6916A-FF208对耳双通程序，有问题，还没改，
   6916A-FF206带功放解mute会有噗声，有空再继续看

* 20190226
** 测试盒认证码烧写
   6、自动烧写认证码使能：不用双击按键烧写，测试盒连接上样机后，自动分配烧写认证码到样机。
   7、认证码强制升级功能：检测到已烧写过认证码的样机，会再次强制重新烧写认证码
*** 自动烧写认证码
    这个选项如果被使能，会在测试盒连接上设备便烧写认证码， 不管
    产品功能是否已测试通过，如果产品测试不通过，有可能导致该认证码浪费掉。
*** 认证码强制升级使能
    选项被使能，在烧写产品认证码的过程中将不会检查产品是否已经升级过认证码，将强制升级，
    如果产品之前已有验证码，将会被覆盖，有可能导致认证码丢失，
    除非确认认证码已经烧写错误，需要重新烧写。所以在正常烧写流程不允许开启该使能开关。

** 羽恒690X
   RTCVDD的宏置一，会导致timer的PWM没有输出
   未验证

* 20190225
** 中翔达芯连心
   6916A对耳双通，通话大小声，用105的SDK也会
   用安卓手机，不同手机效果不太一样
** 培训
   Android抓包和bluez协议栈
** 起华
   R208-6916A对耳双通调试

* 20190223
** 华立 S12-4601
   已发出
** 中翔达46 APP
   升级API，转给森华
** 羽恒692X
   簇号获取，和指定簇号播放，V2.6.1写了demo给客户

* 20190222
** 羽恒  692X故事机
   文件夹播放记忆，不能以文件序号，要改成簇号记忆，让客户自己先搞搞
** 起华  6916D-FF216
   通话音量记忆，已发出
** 华立  S12-4601
   功能修改中
* 20190221
** 欣瑞声 6905D
   出差处理认证问题，已OK
** 羽恒 692X故事机
   创建文件夹，指定文件夹，文件夹文件序号，支持中
   #+BEGIN_SRC c
     static u8 cnt = 0;
     printf("cnt:%d\n",cnt);
     if(cnt == 0){
         cnt++;
         static u8 *path1 = (u8 *)"/A/";
         puts("/A          /\n");
         ret = music_player_play_path_file(obj,path1,1);
     }
     else if(cnt == 1){
         cnt++;
         static u8 *path2 = (u8 *)"/b/";
         puts("/B          /\n");
         ret = music_player_play_path_file(obj,path2,1);
     }
     else if(cnt == 2){
         cnt = 0;
         static u8 *path3 = (u8 *)"/C/";
         puts("/C          /\n");
         ret = music_player_play_path_file(obj,path3,1);
     }
   #+END_SRC

* 20190220
** 羽恒692X故事机
   在音乐模式下，需要新建文件夹
   中文文件夹创建失败,加个\0好了
   #+BEGIN_SRC c
    tbool music_player_create_path(MUSIC_PLAYER *obj)
    {
        if (obj == NULL) {
            return false;
        }
        music_player_save_break_point(obj);
        music_decoder_stop(obj->dop);
    
        const char folder_name[] = "/JL_XIN";
        /* err = file_operate_rec_file_api_creat(fop_api); */
        music_player_printf("fun = %s, line = %d\n", __func__, __LINE__);
        /* if (!err) */
        {
            bool ret;
            s16 make_dir_status;
            make_dir_status = file_operate_op(obj->fop, FOP_CREAT_FOLDER, (void *)folder_name, NULL);
            if (make_dir_status < 0) {
                music_player_printf("FILE_OP_ERR_NOT_INIT\n");
                /* return -FILE_OP_ERR_NOT_INIT; */
            } else {
                if (FR_EXIST == make_dir_status) {
                    music_player_printf("FR_EXIST\n");
                    /* return FR_EXIST; */
                }
                music_player_printf("make_dir_OK\n");
                /* return make_dir_status; */
            }
        }
        file_operate_set_file_sel_mode(obj->fop, PLAY_BREAK_POINT);
        return music_player_play(obj, NULL, 1);
    }
   #+END_SRC
** 泰奇通691X对耳
   修改呼吸时隙

* 20190219
** 华炬芯昂晖
   690X打PR补丁通话断音问题，让客户查dac中断函数的调用函数指定ram，和通话下不要操作vm，客户改后已寄样
** 联巨兴
   691X 对耳从机连过手机后，再开机变成2个耳机都连手机了，给了客户修改方式
   初始化之后，不要回连直接进入可发现可连接(避免回连手机，无法避免被手机回连)
   初始化之后，删除手机地址，可避免被手机回连，但会导致手机重新配对

* 20190218
** 华炬芯昂晖
   690X 
   打PR补丁后，再打通话单工库，会有概率出现断音，测试中
** 测试692X剩余ram
   sdk.map 占用ram的大小：ram_end = (. - ORIGIN (ram0))
   #+BEGIN_SRC C
     #include "sdk_cfg.h"
     #include "cpu/rand64.h"
     u8 test_buf[0x10E00-0xffb6] = {0};
     static void half_second_msg()
     {
         static u8 half_sec_cnt = 0;
         task_post_event(NULL, 1,  EVENT_HALF_SECOND);
         if (++half_sec_cnt == 2) {
             half_sec_cnt = 0;
             task_post_event(NULL, 1, EVENT_ONE_SECOND);
         }
         test_buf[1024] = get_u8_random_number();
         g_printf("test_buf[1024]:%d\n",test_buf[1024]);
         r_printf("test ram0 buf ptr:0x%x\n",test_buf);
         r_printf("test ram0 buf sizeof:%d\n",sizeof(test_buf));
     }
     LOOP_DETECT_REGISTER(half_second_det) = {
         .time = 250,
         .fun  = half_second_msg,
     };
   #+END_SRC

* 20190215
** 录制BLE讲解视频
   
* 20190214
* 20190213
** BLE广播参数
   广播相关的参数大致有以下几种：
   1.Advertising interval（广播间隔）
   2.Advertising_Type（广播类型）
   3.Own_Address_Type（自身地址类型）
   4.Direct_Address_Type（定向地址类型）
   5.Direct_Address（定向地址）
   6.Advertising_Channel_Map（广播信道）
   7.Advertising_Filter_Policy（广播过滤策略）
   8.Advertising Data（广播数据）
   9.ScanReponse Data（扫描回应数据）
** 拜瑞口腔
   培训使用AC690X系列

* 20190212
* 20190211
* 20190210



* 20190125
** 德科创690X
   107发射器配对获取不到手机名，
   民宗发库测试可以，转给客户了
** 益丰690X
   支持开发BLE案子
** 科美692X
   支持AI案子和APP开发

* 20190124
** 692X
   AI自定义命令操作文档，已写好。
** 华立S45-4601
   阿斯星，改EQ，改连接成功提示音，滴一声

* 20190123
** 692X设置搜索符
   要先关闭可发现可连接，设置搜索符之后，再开启可发现可连接
   主从机是同时发起搜索的，连接也很快
** 起华FF216-6916A
   691X进低功耗的时钟源选择，要改成BT_OSC，24M
   不能用LRC时钟，
   有些芯片会断开。
** 新时代692X
   BLE需要pin_code配对
   目前SDK，EDR和BLE的HCI参数是分开的，BLE无法修改
   看珠海安排
** 690X取消回连状态
   hci_page_control(0);

* 20190122
** 威益德690X
   BLE传ID3死机问题，客户代码数组越界导致，已OK
** 源创杰690X
   BLE案子，替换炬力方案，已OK

* 20190121
** 起华FF216-6916A
   低功耗断开蓝牙，代码看不出来
   进低功耗的时候，时钟源的选择，改成24M，不能用LRC
** 嘉兴科美690X AI
   APP编译不过,定义ID而已不至于编不过
   客户重编OK
** 中翔达691X对耳双通
   荣耀6X测试双通正常，已发出
** 威益德690X
   死机
** 伦茨692X
   AI加自定义命令

* 20190118
** 中翔达科迈通志康
   出差一天。
   6904D生产不良，28对只有6对是好的，测功率能有-6dB以上。对应距离在8米左右。
   22对在-12dB至-6dB之间，距离不达标。

* 20190117
** 联巨兴692X
   linein对箱，其他问题修改好，
   有一个功能，拔linein后回连手机，会带出另外2个问题，
   表现为概率性出现断开又回连，
   原因是同步消息，有个状态丢失导致，应用层跟不了这个问题，
   等珠海有空，在补这个功能

* 20190116
** 拜瑞口腔
   过来学习RTC的使用
** 威益德6905C
   连BLE搜不到EDR，BLE动态改名对手机兼容性问题，BLE传ID3死机，今晚搞定
** 伦茨692X
   腾讯叮当，影志回复，商务没谈好，不支持
** 科普豪691X
   AI耳机，影志回复，不支持，让客户等80系列

* 20190115
** 拜瑞口腔
   今天继续过来学习
** 691X-BLE
   测试焕辉SDK，烧录，配置文件，MAC地址，睡眠，唤醒唤醒源正常
   连接概率复位，低功耗模式，珠海在改
** 中翔达6916A4双通对耳
   听话时，概率出现一瞬间大小声，或者声音不集中，不稳定
   感觉是声音在中间，又同时跑到两边
   直接用104都会

* 20190114
** 拜瑞口腔
   培训690X的使用
** 691X双通对耳
   通话丢包标志
   6：表示手机发给主机，主机发给从机同时出错标志(这种情况不好处理)
   4：表示接收的手机的出错
   2：表示从机接收到主机的出错,或主机的接收到手机的出错,硬件接收错误
   同步上相差是135us

* 20190112
** 出差中翔达科迈通
   691X双通对耳，通话时大小声问题

* 20190111
** 伦茨6916A4中控耳机
   目前终端不接受，伦茨芯隆沟通中
** 联巨兴692X linein对箱
   改了一个版本，改动较多
** 鑫闻达691X对耳不同步
   刚开始播歌，由于dac充满条件有点延迟作用
   无法解决

* 20190110
** 692X的RTC闹钟
   唤醒后有pending没有清除，V2.6.0以上的都要打补丁
** 联巨兴linein对箱
   V2.6.0改临时补丁后，下载后第一次插linein后无声音。
   发邮件给志英了
** 伦茨691X中控耳机
   有蓝牙电流声和白噪声
   白噪声，可以做mute，然后自动解mute，升音量盖住声音
   电流声，方法1：改差分，可以不用降功率，方法2：硬件加3个10pF对地，方法3：降功率到2

* 20190109
** 科普豪国威692X
   AI_V2.0的SDK在苹果上授权码传不上去APP，客户明天带样机去珠海找李放
** 华炬芯690X
   珠海改了混响库，客户还是能测出问题，
   没办法只能改优先级到最高了，还在测试中
** 联巨兴692X
   V2.6.0的linein对箱都是杂音，看不出啥问题，明天志英有空再看看

* 20190108
** 羽恒690X
   690X没有处理bt_discon_complete_handle(),reason=0x0d的情况，按照692X加就行
** 华炬芯690X玩具
   混响出现while之后，会出现cbuf满的情况
** AI
   690X的AI---使用杰理AI蓝牙  
   692X的AI---使用杰理智能  
   两个APP的通讯协议换了 是两个独立的APP
** 联巨兴692X
   V2.6的linein对箱，都是杂音，还没看出问题点
** 汉欣诺690X
   AI的SDK，不识别bfu文件，还在看
   MSG_UPDATE的顺序不能修改
** 科普豪692X
   V2.0的AI，IOS不识别语音，还没空试
   试了就是没有资源，公版就会
** 华炬芯690X
   玩具SDK混响杂音，是库有while行为，导致混响线程被卡，具体怎么优化，还没确定
** 德科创690X
   想改字库字体大小，让客户自己加运算函数，不支持改字体文件
** 联巨兴691X
   BLE的烧录文件，烧录器不认，程序要替换C版的链接文件

* 20190107
** SDK擦除VM
   无线升级看isd_tools.cfg
   usb线下载，同时看isd_tools.cfg和-format vm
** 伦茨691X对耳
   对耳的sdk跑120，所以在uboot不能做擦除，flash高于cpu？？？
   isd_tools.cfg的vm不能写0，要写1，BT的可以写0

* 20190104
** 源创杰692X
   V2.5.1，混响和点阵，无法共用，ram超太多
   和客户沟通，不要混响，做成单纯的扩音器。
** 威益德690X动态修改BLE名称
   广播包和profile都要一起修改，修改后要切模式
   iPhone设置界面连接过ble之后，有个cache记忆，测试时要修改MAC地址
   广播包数组要先清0，再重新赋值，防止出现尾部数据不对，导致搜不到蓝牙名
   profile的device name要改成dynamic,然后在回调里重新填写底层ble的name数组

* 20180103
** 汉普皇马车充
   搜不到BLE，是频偏太大。
   晶振正常：set_bt_osc_internal_cfg(0x0F,0x11);/*internal capacitor range:0x00~0x1F,时钟初始化前调用*/
	 晶振不正常：set_bt_osc_internal_cfg(0x1F,0x1F);/*internal capacitor range:0x00~0x1F,时钟初始化前调用*/
** 华炬芯690X玩具SDK
   混响时，dac_mute(1,1)，开启fade之后，就会噗噗响。
   打印寄存器也一样。
   珠海鲁长政在帮忙分析
** 昂立友692X蓝牙后台
   在idle待机下，要关闭EDR和BLE，不可关后台
   EDR关闭可发现可连接，BLE关闭广播包
** 伦茨691X对耳双通
   替换蓝牙库之后，改善很大，还有其他问题
   1.左右耳超距离后回来声音不平衡，左右有延时
   2.通话偶尔有“pala”声音，近端和远端都会有
   问题1测试不到，问题2，得IC有办法，才会更新
** 新时代spp主模式
   用690X的发射器，spp有主模式

* 20180102
** 692X通话dac消噪
   #define AEC_EN_BITMAP	(AEC_BITMAP_BT_CALLING | AEC_BITMAP_SYNC_IN | AEC_BITMAP_SPEECH_DET)
** 伦茨691X
   对耳双通，有杂音，打印一直出现丢包异常，判断是丢包引起，珠海暂时没途径优化这个
** 华炬芯690X
   玩具混响杂音，查看中
** 汉普690X
   有新款手机搜不到BLE，明天要过来

* 20181229
** 博建6928B音箱
   博建6928B硬开关音箱，开不了机，客户拿了12个机子。
   11个插充电线，就能开机，拆机5个，电压均在3.2V一下。
   剩余1个，开不了机，板子VDDIO和RTCVDD接一起，对地短路，是SD卡座电源脚短路，芯片换到其他板子，正常开机。
   隐患：拨码开关，OFF档会卡住，导致有时关不了机，直到耗完电。
** 广利达692X
   在V2.5.1上SD卡复用AD，ADK复用灯，有杂音,
   灯会闪，需要将adc_soft_irq_resume中断频率改快。
   
* 20181228
** 博建 691X和692X
   获取linein能量谱，改好，已发出
   如果linein只有一边有声音，就会采不到能量值。
** 羽恒 690X
   在idle模式下，一直循环播放提示音会出现没声音，改好，客户确认ok

* 20181227
** 692X的IIS
   //PA7(MCLK) PA9(SCLK) PA10(LRCLK) PA11(CHL0) PA13(CHL1) PA7(CHL2) PA8(CHL3)
   //PB6(MCLK) PB0(SCLK) PB1(LRCLK)  PB2(CHL0)  PB3(CHL1)  PB4(CHL2) PB5(CHL3)
** 华炬芯692X对箱
   是澳特爱的机子，需要业务沟通确认
** 威益德690X
   切模式回来获取音乐总时间为0，替换MP3库。
   flac下无法操作ble，是p2和p3的问题，p4的没问题，得找珠海改对应SDK的库

* 20181226
** 源创杰692X蓝牙和linein同时出声音
   #+BEGIN_SRC C
   void aux_open(void)
   {
       puts("aux_open\n");
       if (LINEIN_CHANNEL == DAC_AMUX0) {
           JL_PORTB->DIR |= BIT(4) | BIT(5);
       } else if (LINEIN_CHANNEL == DAC_AMUX1) {
           JL_PORTA->DIR |= BIT(3) | BIT(4);
       } else if (LINEIN_CHANNEL == DAC_AMUX2) {
           JL_PORTB->DIR |= BIT(6) | BIT(3);
       }
       dac_mute(1, 0);
       sound_automute_set(0, -1, -1, -1); // 关自动mute
       linein_channel_open(LINEIN_CHANNEL, 1);
       linein_gain_en(1);
       /* ladc_mic_gain(mic_gain, mic_gx2); */
       aux_2_dac(1, 1);
       extern void delay_2ms(u32 delay_time);
       delay_2ms(100);
       dac_mute(0, 0);
   }
   
   void aux_close(void)
   {
       puts("aux_close\n");
       dac_mute(1, 0);
       sound_automute_set(AUTO_MUTE_CFG, -1, -1, -1); // 开自动mute
       linein_channel_close(LINEIN_CHANNEL, 0);
       aux_2_dac(0, 0);
       delay_2ms(100);
       dac_mute(0, 0);
   }
   #+END_SRC
** 汇杰芯6919B
   烧录问题，已OK
   6919B顶板V1.1能用，新的烧录器加入校验芯片是OTP还是flash版。
   OTP的程序只能烧otp的芯片，用flash会报版本错误。

** 博益友690X
   linein下混响各种问题，硬件问题，已OK
   左右声道幅值一致，左右声道串音是共地原因。

** 羽恒690X
   AI的SDK，用华为荣耀10、华为畅想8P、华为A10连接不上，
   无手机验证，先跟客户沟通，让他确认情况先再说

* 20181225
** 对箱连接状态
   BT_STATUS_BT_TWS_CONNECT_CMD
   第一条lmp命令就来这里了，如果需要立马断开，直接发送
   user_send_cmd_prepare(USER_CTRL_DISCONNECTION_HCI, 0, NULL);
   就会走reason 0x13
   有时会失灵。
** 伦茨692X
   蓝牙通话录音，只能录一边，需要在ladc耦合到dac那边去，再录音。
** 源创杰692X
   蓝牙下开linein通道，待调。

* 20181224
** 起华对耳双通
   调691X双通的版本
** 起华R208-6916A
   对耳双通版本调试，基本能用，细节没测
** 科普豪新时代690X
   BLE连接比别的方案慢，珠海解释说，芯片蓝牙IP本身限制，导致发现服务比较慢，无法优化，让客户换用692X
** 港芯微691X
   开发板的flash和芯片都坏了，给客户修板了，待寄客户
** 联巨兴691X
   公版SDK红外用不了，默认优先级没有设置最高导致
** 鑫闻达691X对耳
   提起开机有唤醒源不对问题。

* 20181221
** 华立S11C-4603
   低电会死机，芯片绑定的是恒硕5E6014，电压要在2.6V以上正常
   低电的时候，功放会扯到VMCU电压到2.6V一下。
   后续要修改串连电阻为2.7R或4.1R
** 芯运692X
   RTC有时唤醒不了，系统跑192M，进入睡眠之前，先降频为120M，再进入RTC睡眠。

* 20181220
** 铭源 6911A
   异常死机问题，寄给珠海处理
** 华立S11C-4603
   明天客户寄机子过来处理
** 联巨兴691X
   需要很准的50us中断，由于底层会关中断原因，回客户没法做到很准
** 威益德46
   需要加一个播放模式，播放设备所有文件后停住，告知客户，客户验证中
** 美师傅692X
   连电脑卡音，客户测试，改善很大，先这样
** 汇杰芯690X
   发射器保留所有搜索设备，支持中

* 20181219
** 692X的mic有-12dB衰减
   MIC_NEG12：MIC -12dB增益放大控制位
   当mic的增益0时，声音还是很大，可以设置这个
** 宇恒692X
   AMR格式可以播放
** 铭源6911A
   蓝牙手柄，异常死机，找志彬在看，堆栈被改，处理中，后续还要加个低功耗idle模式
** 广利达6925E
   有IO异常出现PWM波，和呼吸灯功能没做好，已改好
** 港芯微691X
   开发板一直跑不起来，让客户寄板子来看
** 宇恒692X
   有些wav播不了，是32bits，回客户支持不了
** 中兴达  692X  
   linein左右声道画反，还在和珠海沟通中
   无法调换DAC左右声道
** 科普豪  692X   
   AI识别英文，能识别英文，但是能不能拿到英文的资源，就是资源提供商的问题了

* 20181218
** 港芯微691X
   开发板不正常，对了下电压，应该在uboot状态，一直进不去flash，估计要客户寄板子过来修
** 铭源691X
   蓝牙手柄，有几个需求和问题，在看
** 起华FF216-6916A
   改通话和音量，给客户，最大了还闲低，软件没得改
** 汇杰芯691X
   BLE的SDK，UART DMA例子，已发出，SDK的串口结构体定义有bug
** 汉欣诺690X
   BLE HID苹果手机触摸，支持中

* 20181217
** 出差恒颖超一天
   改6926A的案子。
   噗噗声，功放mute，按键，EQ，提示音已解决

* 20181215
 加班一天
** 巴达木恒颖超6926A
*** 音质问题
    最大声播歌，低频有杂音。
    最大声之后，增益不能加太多，只能降增益，再往上补
    要不然越界的频点，就会有杂音。

* 20181214
** 请假2个钟
** 巴达木恒颖超6926A
*** 插卡或频繁按按键死机
    复现不出，静电不过-4K

* 20181213
** 威益德6901
*** 文件列表的问题
    短文件名也在长文件名的buf，但是长度为0
*** 录音完成后立即播放录音的文件
    通过文件路径去播放
    记录的都是文件句柄
    usb:00099eb0
    sd0:00082fc0
*** BLE蓝牙名称长度问题
    现在长度超过12个字符就会显示不出来
    改成DYNAMIC，会以广播包去填充。不用在profile_data里面去写死。

* 20181212
** 源创杰46
   1.4.1ms升级复位，珠海改库，客户测试OK
** 彩荣690X
   HFP下BLE容易掉线，改了连接超时，测试OK，已送样
** 培训港芯微
   培训客户691X的BLE，客户要做蓝牙信标，得找珠海支持
** 出差汉欣诺
   客户想做手机投屏后，车机触摸板坐标能回传手机，Android能通过USB，苹果得走BLE，他们有客户能做这个，培训他们怎样使用690X的BLE
** 威益德690X
   蓝牙库获取电话号码，有问题，发邮件给珠海了
** 铭源691X 蓝牙手柄
   有个蓝牙状态抓不对，支持中

* 20181211
** 彩荣690X
   ac690x_toy_sdk_v211 启用HFP会导致BLE断线，
   改大连接参数，现在是要10s以上才会断，有优化但还是会断，
   APP端是可以优化这个问题，让他们改改APP，加入自动重连机制
** 源创杰46
   升级复位，珠海国炜改的库不行，测试OK
** 铭源6921a
   蓝牙手柄，有消息堆积现象。改了程序，给客户测试。

* 20181210
** 铭源6911A 蓝牙手柄
   支持客户开发，目前硬件有问题，那边在修板验证中
   关不了机
** 联巨兴 
   支持开发691X的BLE和692X的AI
** 源创杰460X
   1.4.1MS卡升级复位，要找珠海改库

* 20181107
** 起华JD212
   6919A修改按键功能和充电灯，已发出
** 铭源691X
   加了一个消息机制，用于本地的消息推送处理
   广播状态和蓝牙连接，测试正常
** 通话噪音
   如果推灯和mic地没分好，推灯会有电流变化时，
   会干扰低，导致mic有噪音。

* 20181206
** 奋达691X
   自动化程序，已发出
** 科普豪692X
   小度蓝牙的百度，不开放，由珠海开发。
   要开发版的APP，测试后，向百度认证才能使用。
** 铭源691X
   蓝牙手柄，功能调试，协助中
** 威益德690X
   蓝牙状态设置，客户已验证OK
** 联巨兴691X
   BLE案子开发，支持中
** 汉普6902A
   华为Android 8.0的手机搜不到蓝牙
   修改广播包已发出

* 20181205
** 奋达691X
   自动化程序，添加晶振VM
   MAC地址没有依赖配置文件，要下载时，要加-format cfg擦除
   蓝牙MAC地址没有VM记忆
** 汇杰芯6916A   
   老鼠APP修改连接参数，改善时延，客户测试中。
** 威益德690X
   修改获取电话号码，会有空格符号(16进制0x20)出现，要过滤

* 20181204
** 铭源6911A
   蓝牙手柄出了一个版本
   默认有2个HID通道，consumer通道为0x0043

* 20181203
** 威益德690X
   有一个手机拨号，获取电话号码只有前3位。
** RTC复位时间
   判断12月不应该有等于号，所有SDK都有问题

* 20181130
** 爱尚692X文件浏览
   要开点阵屏。才能用文件浏览的接口
   开BLE和后台，编译不过。
** 奋达691X   
   自动化调试

* 20181129
** 威益德690X
   待机下断开蓝牙，并关闭蓝牙可发现可连接
   有一个手机获取不到电话号码
   换曲信息，通过判断ID3信息，处理
   有一个开机死机问题，是malloc问题，还难复现，改了dac的buf给客户测试
** 奋达691X
   自动化调试

* 20181128
** 联创视听
   6901A搭配原先炬力的APP。
   spp通信需要新建一个任务来做处理。
   要不然会卡住蓝牙和main。
** 起华FF216-6916A
   在FF221上修改管脚改动：音量减PB5改为DP，音量加是PC5
   在V204上开发，低功耗下要修改VDDIO档位高于2.6V
** 华炬芯奋达
   691X自动化工程
** 汉普酷走皇马
   Android 8.0搜不到蓝牙

* 20181127
** 起华R208-6904D  
   提起开机问题，硬件接错
** 起华JD212-6919A  
   灯异常，硬件没焊好，调了通话参数给客户测试了
** 永泰胜6919A  
   重烧问题，寄机子给棉鸿处理
** 起华JD1903A-6919A  
   珠海改过充满电灭灯，原本加起华的key，
   客户想下单给中翔达，但是珠海找不到程序了，无法改变key，客户生产自己安排了
** 铭源6921A蓝牙手柄
   寄机子给柏康调HID了，目前案子比较急，这边还得验证硬件环境
   客户将VBAT和VDDIO接在一起了，得割线飞线处理，影响AD功能。

* 20181126
** 起华JD212-6919A   
   案子开发，还有个问题，这边正常，明天客户过来
** 起华R208-6904D
   提起开机，PR1拉不低，还没找到问题点
** 铭源6911A蓝牙手柄
   调试中

* 20181124
  加班
** 鑫闻达6916A死机
   有2款机子，
   1款是开机死机，在board_main()里任意加函数就会好，问题点未知
   另一款power_down死机，怀疑是低功耗下，VDDIO为2.0V，有操作flash可能。

* 20181123
** 永泰胜6919A0
   修改key过滤机制，VDDIO和RTCVDD电压提到1，给客户测试了
   测试OK。
** 起华FF206
   用V203版本的SDK，通话有杂音，要打补丁。
   V203-p2比较稳定。

* 20181122
** 永泰胜6919A0
   生产发现最大声播歌，会自动跳下一曲。
   AD检测不准，软件处理key流程有bug。
** 铭源6911A
   蓝牙手柄调试

* 20181115
** 692X对箱功能
   消息同步有个bug。
   typedef struct {
    u8 idx;
    volatile u8 busy;
    volatile u16 mask;///这个16bits要改成u32
    } tws_cmd_var;
** 编译器
   新版的编译器只有更新包，没有完整包。
** 中翔达6905A AI音箱
   BT127案子功能暂时OK，先移交给施强。

* 20181114
** 芯运690X
   发射器在linein下，本地也出声音。
   在插播提示音时，ladc和dac的采样率对不上，会搞死提示音播放。
   music播放和发射模式死机问题，ladc close传参出错。
   linein发射和music切换，导致没声音，要加打开蓝牙通道的操作
** 广利达 6928B
   U盘挂载超时，卡住延时太久，暂时只能缩减到20s左右

* 20181113
** 得辉达
   和剑锋、卓添出差

* 20181112
** BTMate带葡萄牙语
   已发出。
** 天罡微6905音箱
   打电话没声音，修改音量设置成FADE_OFF，测试没出现
** 天罡微6903B
   头戴式耳机关不了机，P管电压不正常，原因未知，换管正常
** 鑫闻达691X
   连接后，酷狗播放器底下，会有一个弹窗，会导致PP键响应慢。

* 20181109
** BTMate带葡萄牙语
   修改中
** 伦次6904D
   充电开不了机问题。
   系统时钟跑192M，设置DVDD为1.0V会死机。
   要在降频后才能设置DVDD电压低一点。
** 鑫闻达6916A
   中控耳机VCOMO串音，进入power_down之后出来，重新设置dac_on
   而串音函数里有些标志没有清除。

* 20181108
** 华炬芯6921A无线充
   用料过于苛刻。
   换了线圈，换了NOP电容，换了采样电阻0.05R，效率才正常。
** 威益德690X
   电话本用在IOS 12.0上，有个联系人允许框有问题。不弹出。
   RDA没问题。给珠海处理。

* 20181107
** 华炬芯6921A无线充
   硬件上更换3个料，无线充距离灵敏度能达到5mm。
   等珠海的板子，再来验证接收器的灵敏度。
** 鑫闻达691X
   连接后按PP键，有延迟，对比690X慢1-2s，692X没有此问题。
** 得辉达小米音箱
   用新的1拖6工具升级，静置10分钟，没有出现开不了机的。
   但是用读版本的工具，还是能出现，更新了新的工具。

* 20181106
** 源创杰690X
   按键音固定音量大小
   改用数字音量，将添加按键音的函数，放到数字音量控制之后。
   客户验证中。
** 德科创690X点阵屏
   点阵屏显示，用西班牙之类，要换font_lib.a库。
** 汇杰芯6916A
   电压检测在低电不准。
   主控供电VMCU低于3.3V之后，VDDIO也会跟着变，导致电压检测不准。
** 联创视听690X用spp
   改了一个demo给客户，测试spp传输，未出现连接断开的现象。
   用客户的APP，就会出现断开现象。

* 20181105
** 得辉达
   出差处理烧录问题。
   升级后摆一会才能开机，国炜修改loader，减少检测时间。
   1拖6工具升级默认擦除flash，利龙修改工具，去掉默认选型
   遇见1次，停留在loader不复位，长按8S能复位，后面测试1百多次，复现不了
   明天工厂要拉一条产线测试2千台，统计之前问题改后的几率

* 20181103
** 加班
   搞得辉达小米音箱升级开不了机问题。

* 20181102
** 华炬芯6921A无线充
   SDK有指针没有4个字节对齐，修改sdk.ld即可。
   接收器功率不高，充电电流小，会导致苹果手机拒绝充电。
** 联巨兴6905A发射器
   刘行修改usb.a库，去掉mic_class和speaker_class的音量控制，测试OK
   客户测试OK
* 20181101
** 爱尚690X用IIC从机
   在从机接收时，发送地址后，读数据之前，中间插入START信号，
   会被误读取成一位。
   正常的话，如果在CLK为高时，DAT脚有变化，要舍弃之前的采样位，硬件没有这个机制。
   现改成iic关了，延时40us，在重起，现在勉强可以通讯了。
** 鑫闻达6905B插linein会重启
   苹果手机最大声播放时，插入过程中，DAC声道接触检测脚。
   相当于给检测脚接了一个负电压。
   导致产生上电复位。
** 华炬芯6921A无线充板子
   SDK跑不起来。

* 20181031
** 联巨兴690X发射器
   通过type-C连接Android手机，进PC模式，发射音频
   mic会导致，手机通话时，转换成发射器上面，但是样机不带mic，出现通话没声音，
   USB枚举要去掉这个mic的class。
   speaker默认带音量控制，导致存在HID的描述。
   手机有些系统会误认为有HID键盘，导致手机界面输入法无法弹出键盘，speaker_class要去掉这个功能。
** 华炬芯690X—tws-2013
   打PR补丁编译不过。海杨改个新补丁。

* 20181030
** 文件浏览补丁
   修改music模式下，共用MUSIC_OP_API变量。
** 爱尚智慧
   692X测试盒ble补丁已发出
** 睿博690X
   文件浏览功能，处理了music模式冲突问题，已发出
** 华炬芯691X
   对耳，单耳使用搜索慢，会影响对耳连接，跟客户解释不能太小，
   通话参数，调了一版，客户说效果好，回去再验证
** 华立S11B和S33B
   46程序修改需求，发给客户了

* 20181029
** 华立  
   改S11B和S33，46的程序，已发出
** 内部691X-ble
   发现的bug，都已修复，新版本待发
** 汇杰芯HLX18142-6916A
   改用flash版，已挪好，测试正常，已发给客户使用
** 爱尚智慧692X
   测试盒测试BLE，SDK根本没有做这个功能，测试都无法连接上，志彬处理中
* 20181026
** 起华R208-6904D
   提起开机，功能OK，功耗OK，等赖工改板
** 起华FF165-6919A
   客户烧的芯片，距离只有3米不到，这边烧芯片验证，板子，程序都对比过，正常，
   客户芯片烧出来的距离超短，原因未知，后续让客户再继续测试
** 汇杰芯HLX18142-6916A
   程序挪到flash版SDK，测试功能正常，等SDK的bug修复
** 内部691X-BLE  
   BLE-flash版SDK，加key无法升级，
   珠海找到，是烧写器的bug，那边还在改
   无法更新蓝牙名，原先是读配置文件，后面改成读配置区

* 20181025
** 源创杰  690X AI加频谱
   没有改成5段，改为dac中断50次，才算一次频谱，基本听不到杂音，客户暂时先送样
** 起华FF206
   死机问题，用我台式机就会，用笔记本下载，测试不到，找不到原因
   改用V203版本的SDK。
   用V204进低功耗之后，有可能异常中断，或软复位，或看门狗复位。
** 起华FF165
   蓝牙距离短，初步怀疑芯片问题，拿我们的芯片烧录，距离正常
** 汇杰芯  
   691X  flash版本SDK，还有2个问题，志彬在处理中

* 20181024
** 691X进power_down死机问题
   V204版本会死机，晓威的又不会
   改用V203版本了

** 蓝牙伴侣APP开发
   #+BEGIN_SRC Java
   public static final byte JL_COMMAND_MUSIC_DEV = -94; 
   mJLBluetoothRcsp.sendCommandToDevice(
        new byte[]{JL_COMMAND_MUSIC_DEV}, new byte[]{1,JL_COMMAND_MUSIC_DEV,1},
        new JL_BluetoothRcspRespond(){
            @Override
            public void onRespond(int ret, int data) {
                Log.e(TAG," onRespond" + " ret:" + ret + " data:" + data);
                super.onRespond(ret, data);
            }
            @Override
            public void onRespond(byte[] data) {
                Log.e(TAG," onRespond2" + data);
                super.onRespond(data);
            }
        }
        );
        jlBluetoothRcsp.sendCommandToDevice(
            new byte[]{JL_COMMAND_MODE_SET, (byte) (index - 1)}, new byte[]{2,JL_COMMAND_MUSIC_DEV,2},
            new JL_BluetoothRcspRespond() {
                    @Override
                    public void onRespond(int ret, int data) {
                        super.onRespond(ret, data);
                        Dbug.e(TAG,"sendCommandToDevice switch mode onRespond");
                        if (0 == ret) {
                            setCurrentMode(index, false);
                        } else {
                            if (0x20 == data) {
                                JL_MessageBox.showConfirmation(view, R.string.msg_no_device);
                            } else {
                                // JL_MessageBox.showConfirmation(view, R.string.msg_switch_mode_failed);
                            }
                        }
                    }

                    @Override
                    public void onRespond(byte[] data) {
                        super.onRespond(data);
                        Dbug.e(TAG,"sendCommandToDevice switch mode onRespond data");
                    }
                });
    import java.util.Arrays;
    private JL_BluetoothRcspCallback mCommandCallback = new JL_BluetoothRcspCallback() {
            @Override
            public boolean onDeviceCommand(byte[] command, byte[] data) {
                Log.e(TAG,"JL_BluetoothRcspCallback:" +"command:"+ Arrays.toString(command)
                      +"data"+ Arrays.toString(data));
                      }
    }
   #+END_SRC

* 20181023
** 源创杰691X
   ble可以控制进不进低功耗模式。
   柏康支持，已改好。
** 天地宏
   培训AI用法

* 20181022
** 奋达
   出差奋达，处理蓝牙测试仪测试问题

* 20181019
** 得辉达小米音箱
   出差得辉达，处理小米音箱连接BT168测试仪
   一直重复连接，由于复位后，link-key对应不上
   通话没声音现象

* 20181018
** 源创杰691X-ble
   低电检测要打开ADkey，才会扫描检测。
   不需要AD-key，要做下处理。
** 奋达6923A
   合并的程序，能测试。
   但是客户每次进蓝牙都要重新写一遍osc的VM。
   客户自己要加的。
** 起华FF206-6916A
   耳机的底噪经过功放会放大，出现白噪声。
   要调低功放的增益档次，不能用最高。
** 起华FF165-6919A   
   进入低功耗后，容易跟苹果手机断开连接
   RTCVDD加入退耦电容即可。

* 20181017
** 德科创690X
   AI的SDK，调试问题。
   客户用SCO链路，APP又是翻译软件。
   建议不要用AI的SDK，改用p4的音箱程序。
** 德科创690X
   有个BLE案子，配对苹果会出现，断开后重新回连。
   SDK没有问题，客户程序有问题。
** 奋达6923A
   发了个程序给客户合并了。

* 20181016
** 奋达6923A
   出差珠海，找立辉
   处理8852B仪器问题。
   需要替换bluetooth_lib.a
   测试灵敏度时，要加屏蔽罩，避免蓝牙干扰，导致错包。

* 20181015
** 奋达6923A
   蓝牙测试仪8852B，无法测试，计划明天拿给立辉分析
** 博建6928B
   低电影响ADkey，没有按键却检测有按下，和长按变短按，
   暂时无法同时解决2个问题。
   等客户板子，再看是否有优化空间
   天师已解决
** 德科创690X  
   AI音箱，自定义命令导致死机，程序问题，已解决
** 嘉兴科美692X
   对箱连接问题，已OK
** 彩荣692X  
   对箱aux，插入无声音问题
   SDk测试没问题。

* 20181013
** 加班
   搞奋达

* 20181012
** 汇杰芯6916A
   老鼠APP玩具，改了一个版本给客户，客户测试中
** 美师傅6916A
   耳机功耗大，改了程序。目前正常播歌，功耗基本一致，
   但是测试1KHz，0dB时，比不了BK方案，BK方案测出有特殊处理，
   在和珠海沟通中
** 爱迪尔690X
   固件上传给APP，给客户方法，客户验证中

* 20181011
** 源创杰
   建立线程处理功耗
   客户验证OK。
** 物联网
   AT指令的GPRS模块（SIM800和SIM900系列、安信可的GA6、GA7）

** 奋达
   频偏校正，+偏差，电容值往大的调，偏差减小
              -偏差，电容值往小的调，偏差减小

* 20181010
** 得辉达华庄
   出差一天
   处理一拖8工具，蓝牙名乱码和蓝牙地址跳码等问题。
   等利龙更新工具

* 20181009
** 请假
* 20181008
** 请假

* 20180930
** 奋达6923A
   linein通道打开后，没有关闭，只关闭ladc。
** 汇杰芯6916A
   改成只有2个PWM，通过映射，映射到4个IO上。
** 源创杰6919B
   ble关闭广播包后，功耗高。
   比较难改，珠海改不完，节后再发。
** 伦茨692X
   Timer用作PWM，要关闭Timer_CON的PWM_EN位。
   默认IO才不会有波形输出。
   芯片内部上拉10K误差有正负20%，做AD_key，无法做太多按键。

* 20180929
** 源创杰6919B
   ble关闭广播包之后，无法进入sleep，维持高功耗。
   广播广播包后，蓝牙不跑了。
   而power_down依赖于蓝牙中断，导致无法进入。
** 691X增加晶振强驱
   SFR(WLA_CON8, 8, 5, 0x8);
   时钟初始化之后调用。
** 起华FF165
   修改按键功能
** 起华FF226
   案子调试，给客户测试了。

* 20180928
** 汇杰芯6916A
   老鼠APP，PWM会影响到蓝牙性能
   和客户说明改板
** 起华FF165
   用6919A省料，改LDO_2声音小。
   SFR(JL_AUDIO->DAA_CON0, 2, 2, 2);
** 奋达6923A
   出差奋达，处理自动化机台，
   机台电源无法一直供电，得上位机工程配合改
   节后再处理

* 20180927
** 金康特发射器
   出差金康特，演示发射器demo
** 汇杰芯6916A
   PWM影响到蓝牙性能，导致ble都搜不到

* 20180926
** 691X-ac691x_sdk_le_v101_C_release无法下载
   ble的V101版本SDK，只能下载空片，下载目录多一个文件br20loader.bin，
   删除掉才能刷新程序
** 金康特发射器
   换用6905A  发射器demo，调试中
** 奋达6923A
   检测进test.app
   要在uboot里面做检测才行，避免软开关机的操作。

* 20180925
** 691X电机PWM
   MCPWMCH0_H  PA0    MCPWMCH0_L   PA3
   MCPWMCH1_H  PC1    MCPWMCH1_L   PC5
   MCPWMCH2_H  PB5    MCPWMCH2_L   PB0
   设置MCPWMCH1_H_OPPOSITE就变成两个都是反向
   设置MCPWMCH1_L_OPPOSITE就变成两个都是同向
   设置0的话就是H为正向，L反向
   底层bug导致。
** 汇杰芯6916D
   老鼠APP，程序开发
** 金康特6904发射器
   加入串口，demo演示

* 20180921
** 奋达6923A
   已发出测试版本给客户
*** 检测U盘是否有test.bfu
    开机挂载的时候就要检测，不能进音乐模式扫描才检测    
** 起华FF165
   用AC6919A，省物料
   改用LDO_1供电，在开发板会没有声音。
** 巴达木6925D
   生产20K，概率出现自动开机，插拔SD卡无反应，升级无反应等情况
   程序bug，已改好。

* 20180920
** 慧杰6929C 
   音质调试，音量31会失真
   DACVDD只有3.05V，DAC的输出要控制在3V以下
   音箱版，要用DAC_ISEL5U,否则隔直后，低音不过
** 起华R208
   玩吃鸡游戏，开启通话语音，背景音效会被削。
   aec_interface.argv_params(2 ,1000, 0 , 64 , 256, 0 , 0 , AEC_REDUCE);//Advance
   第三个参数，原本50，会削dac出来的声音，改成0，就不会。
** 奋达6923A
   测试工程和样机工程
*** 测试工程
    需要修改sdk.ld
    code0(x)        : ORIGIN = 0x1000000+0x7D000,       LENGTH = 16M
    修改代码的分布。
    样机工程的sdk.app，不能超过500K
*** 样机工程
    替换使用isd_download_with_test_app.exe
    -test_app test.app
    -faline sdk.app,0,0x7d000,0
    #+BEGIN_SRC C
    static const u8 test_mode_str[] = {"test_mode"};
    void enter_test_mode(void){
        u8 *updata_backup = UPDATA_FLAG_ADDR;
        ///RAM 变量传递
        //step 1: disable irq
        irq_global_disable();
        irq_clear_all_ie();
        OS_ENTER_CRITICAL(); //关总中断， 防止 back_up 内存被修改
        memcpy(updata_backup, test_mode_str, sizeof(test_mode_str));
        #if 1
        updata_enter_jump(0); //跳到 MASKROM， IO 口状态不变
        #else
        updata_enter_reset(0); //芯片复位， IO 口状态改变
        #endif
    }
    #+END_SRC

* 20180919
** 奋达6923A
   自动化协议bug修改
*** IO输出设置
    高低相反
*** 挂载SD卡和USB
    会死机，去掉task_common的调用
*** mic、linein、FM的能量值
    修改能量值范围，mic接地的时候，软件开启mic，要5s的时候稳定，采样数据
    才会变为0
*** 蓝牙名和地址
    加入配置文件的读取，去掉VM的操作
*** 串口脚RX和TX都要映射
    TX为PA12，RX为PC2
*** ADC检测无效
    AD-key引脚设置

* 20180918
** 天浪6905C
   PC4和PC5口上电有1V尖波脉冲，vdd上电慢于VDDIO导致
   软件不发修改，让客户加电阻分压，处理
** 义语AI的APK
   打包少jar包，编译不过，珠海已重新发新的
** 威益德690X
   文件浏览死机问题，已改好
   在music模式下，用task_music的mapi变量。
** 源创杰691X  
   ble的SDK，没有PR口函数，PR1拉不高，在处理中
** 起华FF206
   软件加入EQ，处理高音重问题

* 20180917
** APP
   图灵的不做，换成义语的APP
   义语，英文名叫deepbrain
   故事机APP
** 起华JY115
   用6919A-OTP版本，已发出
** 起华E23
   改用中翔达的key，烧录厂就不会换烧录架
** 欣瑞声6905A
   带义语APP，已发出一版，给客户测试

* 20180914
** 奋达6923A
   最小工程，只能到172K，达不到ram：128K的限制。
   目前不知道该怎么弄。
** 天地宏6905A带AI
   改了一版UI给客户试用
** 德科创690X带老树APP
   用旧版的APP，在进入设备连接界面，会自动断开现有的蓝牙连接。
   新版的APP，没有此问题。
** 欣瑞声6902A-Q1带义语APP
   珠海还在整理资料
   先搞一版老树的。

* 20180913
** 天地宏6905A带AI样机
   触摸一直输出高，触摸太灵敏。
** 德科创690X带APP
   客户自己写的APP，蓝牙连接要重新刷新服务，不断重连
   writeCharacteristic要检查返回值，重复写。
** 奋达6923A
   串口选脚出错，要映射RX。

* 20180912
** 中翔达6925D
   在2.5的sdk上修改
   在FM模式下，插卡，功耗降不下来。
   重新初始化蓝牙，功耗才降下来。
   沈沛修改fm_lib.a即可，通用库。

** 巴达木6919C
   做蓝牙音箱，无DCDC下，开power_down，功耗在0-7mA左右。
   PR1进低功耗后，维持不住，会变成输出0

* 20180911
** 出差奋达AC6923A
   自动化程序需求。
   应用程序与自动化程序，分离。
   启动进入测试模式，改用U盘
   增加频偏纠正。
** 中翔达690X
   开启对箱，打开ladc采样mic
   采样率不能高，44.1kHz就会导致从机卡音。设置16kHz
   由于DAC和LADC共用一个中断，导致暂停后再播歌，dac默认以16kHz播放。
   都是杂音，需要清数据。
   在dac_int_disable();dac_int_enable()设置标志，在中断里面清除数据。

* 20180910
** 692X的V2.5版本
   在DAC加入串音mute的动作。
   函数内的局部变量，要定义成u32，要不然会死机。
** 中翔达690X扩音器限幅
   mic有接收的dB值限幅，超过即失真。
   最大声压级
   
* 20180907
** 690X文件路径指针
   #+BEGIN_SRC C
   r_printf("fs_hdl:%d\n",d_mapi->fop_api->cur_lgdev_info->lg_hdl->fs_hdl);
   r_printf("file_hdl:%d\n",d_mapi->fop_api->cur_lgdev_info->lg_hdl->file_hdl);
   r_printf("ui_fhdl:%d\n",d_mapi->fop_api->cur_lgdev_info->lg_hdl->ui_fhdl);
   /* _FIL_HDL *f_h = (_FIL_HDL *)(d_mapi->fop_api->cur_lgdev_info->lg_hdl->file_hdl); */
   /* FIL *pf = (FIL *)(f_h->hdl); */
   /* _FS_HDL *f_h = (_FS_HDL *)(d_mapi->fop_api->cur_lgdev_info->lg_hdl->fs_hdl); */
   /* FATFS *pf = (FATFS *)(f_h->hdl); */
   _FIL_HDL *f_h = (_FIL_HDL *)(d_mapi->fop_api->cur_lgdev_info->lg_hdl->ui_fhdl);
   FIL *pf = (FIL *)(f_h->hdl);
   r_printf("FIL:%d\n",pf);   
   r_printf("cur_path:%s\n",pf->fs_n.tpath);
   r_printf("cur_sclust:%d\n",pf->dir_info.dj.clust);
   r_printf("deepth:%d\n",pf->fs_msg.deepth);
   r_printf("cur_sclust:%d\n",pf->f_dj[1].clust);
   r_printf("start_sclust:%d\n",pf->f_dj[1].sclust);
   #+END_SRC

** 威益德690X
   文件浏览接口，封装OK，已发出
   蓝牙灯效，只发一个demo，给客户参考
** 起华6926A声霸
   已确认，改了2个提示音版本，已发出。
** 巴达木DAC串音
   691X按照天师方式，已解决
   692X用V2.5的SDK，测试没问题
** 汉欣诺690X电话本
   打来电补丁，获取手机蓝牙名，会多出6个字节的长度。
   电话本蓝牙名长度，不限长，为UTF8编码。

* 20180906
** 汉普车机回声
   客户的车机，延时有100ms左右，只能改成单工。
** 起华FF221-6916A
   做一版中文的提示音，已发出
** 起华R208-6904D
   做一个中英文提示音切换的功能,三击下切换

* 20180905
** 起华6926A声霸
   修改假关机挂载设备
** 天地宏6905A
   AI音箱调试完成
** 起华FF221
   要改中文提示音
** 威益德6901A
   文件浏览，接口封装

* 20180904
** 嘉兴科美BTMate
   连接后无法跳入蓝牙界面。

* 20180903
** 690X文件浏览器功能
   已完成一版，已发出，等客户测试再完善。
** 欣瑞声6902A带BLE传文件
   工厂工程有一个小米手机，有兼容性问题：
   1.服务获取有一定概率为空。
   2.蓝牙上传数据到app，小米手机读取第二个文件时中断。
** 起华FF221-6916D
   VCOMO开启，通话时，差分输出无声音。
** 起华6926A声霸
   改了一版问题点。

* 20180901
** 起华6926A声霸
   功放开mute会噗一声，无解，客户找功放厂商。
   改了问题，发出一版程序。

* 20180931
** 起华R208-6904D
   修改2版提示音，开机声音，有2个处理。
   要看终端客户取舍哪一版
** 起华6926A声霸
   修改问题点

* 20180830
** 中翔达692X断点记忆
   在半秒处，每隔5秒记忆，有时断电后，重新开机读不到断点。
   公版做法，播歌后都会清除秒的记忆，只记忆首，改成把秒也记忆。
   低电U盘会掉线，让客户把声音降1-2级，是听不出来的。

* 20180829
** 起华FF206
   板子虚焊导致噪声
** 欣瑞声6902A带BLE
   传输一段时间后，会出现BLE断开的现象。

* 20180828
** 起华声霸6926A
   完成，等客户测试。
** 默认红外表
   #+BEGIN_SRC C
   const u8 IRTabFF00[] = {
   NKEY_00, NKEY_01, NKEY_02, NKEY_03, NKEY_04, NKEY_05, NKEY_06, NKEY_07, NKEY_08, NKEY_09, NKEY_0A, NKEY_0B, NKEY_0C, NKEY_0D, NKEY_0E, NKEY_0F,
   NKEY_10, NKEY_11, NKEY_12, NKEY_13, NKEY_14, NKEY_15, NKEY_16, NKEY_17, NKEY_18, NKEY_19, NKEY_1A, NKEY_1B, NKEY_1C, NKEY_1D, NKEY_1E, NKEY_1F,
   NKEY_20, NKEY_21, NKEY_22, NKEY_23, NKEY_24, NKEY_25, NKEY_26, NKEY_27, NKEY_28, NKEY_29, NKEY_2A, NKEY_2B, NKEY_2C, NKEY_2D, NKEY_2E, NKEY_2F,
   NKEY_30, NKEY_31, NKEY_32, NKEY_33, NKEY_34, NKEY_35, NKEY_36, NKEY_37, NKEY_38, NKEY_39, NKEY_3A, NKEY_3B, NKEY_3C, NKEY_3D, NKEY_3E, NKEY_3F,
   NKEY_40, NKEY_41, NKEY_42, NKEY_43, NKEY_44, NKEY_45, NKEY_46, NKEY_47, NKEY_48, NKEY_49, NKEY_4A, NKEY_4B, NKEY_4C, NKEY_4D, NKEY_4E, NKEY_4F,
   NKEY_50, NKEY_51, NKEY_52, NKEY_53, NKEY_54, NKEY_55, NKEY_56, NKEY_57, NKEY_58, NKEY_59, NKEY_5A, NKEY_5B, NKEY_5C, NKEY_5D, NKEY_5E, NKEY_5F,
   };
   #+END_SRC

** 中翔达692X断点记忆一直记
   有人做过5s,但是有风险
   
* 20180827
** 起华FF221-6916A
   底噪和距离都不行
** 起华声霸6926A
   调试中
** 起华FF206-6916A
   开关机按键有问题，导致开机后按键不正常。

* 20180824
** 起华FF221-6916A
   更新SDK到V204版本，解决底噪问题
** 起华FF206-6916A
   带功放,按键有问题
** 源创杰6901A   
   CD机挂载有问题。
   第一次挂载失败后，以后每次都可以
   第一次挂载成功，以后都不行

* 20180823
** 起华6916A-R208
   高频声处理中。
** 修改BLE的MTU
   JL_Bluetooth的库
   setBleDataBlockSize()
   默认是20B，可以适当调大。
   #+BEGIN_SRC java
    protected int setBleDataBlockSize(final BluetoothDevice device, final int blockSize) {
        final BluetoothGatt gatt = getDeviceGatt(device);
        if (null == gatt) {
            XLog.e(TAG, "--setBleDataBlockSize-- 11111");
            return ErrorCode.SUB_ERR_BLE_NOT_CONNECTED;
        }
        CommonUtil.getMainHandler().post(new Runnable() {
            @Override
            public void run() {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                    // 需要加上3个字节的数据包头部信息
                    XLog.e(TAG, "--setBleDataBlockSize-- 22222");
                    if (!gatt.requestMtu(blockSize + 3)) {
                        XLog.e(TAG, "--setBleDataBlockSize-- 33333");
                        onBleDataBlockChanged(device, WRITE_DATA_BLOCK_SIZE, ErrorCode.SUB_ERR_CHANGE_BLE_MTU);
                    }
                } else {
                    XLog.e(TAG, "--setBleDataBlockSize-- 44444");
                    onBleDataBlockChanged(device, WRITE_DATA_BLOCK_SIZE, ErrorCode.SUB_ERR_CHANGE_BLE_MTU);
                }
            }
        });
        return ErrorCode.ERR_NONE;
    }
   #+END_SRC
** 欣瑞声带BLE
   在传送notify的时候，会出现Fail。
   有可能是内存泄漏。

* 20180822
** 得辉达6926C
   给客户去掉mute，测试板子底噪
   CSR发射器，旧款连不上，海华买了个新款，连接一直正常。
   反馈一些不稳定现象问题，珠海处理
** 起华6916A-Q5
   程序修改，还有通话回声问题。
** 中翔达691X
   flash版本的SDK，播放otp提示音app.res文件
   出了一个版本给客户了。
   
* 20180821
** 得辉达6926C
   用CSR的蓝牙发射器，连过手机之后一直连不了。
   修改长按4s功能。
** 起华FF202  
   出了一个版本可以测试，没有加入音量同步。
** 华钜芯690X电话本
   phonebook_packet_handler回调函数有个type，里面有类型的区分。0是电话号码，1是拨出号码。2是来电，3是未接来电
   void __set_phone_history_call_num(u8 num);可以设置获取通话记录的条数
   USER_CTRL_PBAP_READ_PART命令获取通话记录条数

** 起华6916D对耳
   有概率性出现收不到蓝牙

* 20180820
** 欣瑞声6902A带BLE
   底层notify的反馈机制，有些手机有兼容性问题。
   现在多加了2种方式，一个超时，一个判断streamer，一个notify反馈，
   3者都起作用。主要是streamer，是否能接收消息的反馈。
** 威益德6905C概率不开机
   同一批次概率出现，烧写会出现 Flash Id Error。
   将RTCVDD的电容，由105改成104就可以了。
** 起华6916D
   对耳程序基本OK，卡音mute，声音渐变没有。
** 起华6904D
   对耳视频延时，会影响到蓝牙距离，不敢改太多。

* 20180817
** 得辉达小米音箱
   调试一版UI给客户测试，发给吴旭了。
** 合科芯690X
   蓝牙伴侣APP，在点播APE和FLAC的时候，会退出。
   p3版本就有，p4已改好，与APP无关。

* 20180816
** 爱瑞声6902A带BLE传文件
   完整流程OK，已发出测试程序，和文档。
** 起华6904D对耳
   要改三击siri功能，拿起开机等功能，待改
** 起华6916D对耳
   距离测试，bd_set_max_pwr(rf_power_max);貌似有调用的限制。
** 合科6901用APP点播无损APE/PLAC
   APP有退出设备播放现象

* 20180815
** 得辉达6926C小米
   EQ调试基本OK。
** 爱瑞声6902A带BLE
   调试上传接口。基本OK。
** 中翔达科迈通6916D对耳
   pin2pin，贴上，距离不行。
** 起华6916D对耳
   功率调节，距离测试

* 20180814
** 得辉达小米BM1120
   客户反馈加入EQ后，播歌会忽大忽小
** 合创SPI录蓝牙正常播歌声音
   调试OK，发给客户了。
** 芯运692X--SPDIF
   做输入，是否需要单独开一个模式

* 20180813
** 得辉达小米BM1120
   去客户那里调试

* 20180810
** 联创视听6901A带APP
   给客户搭了个框架，客户回去，继续调试。

* 20180809
** 也杨
   lighting耳机，在手机锁屏后，隔几分钟后会断电，测试其他的方案的不会。
*** ble在设置界面连上后，APP无法连接
    可以调用rcsp_check_app_connection()判断APP是否连接，累积一段时间，
    就调用ble_hci_disconnect(ble_conn_handle);断开ble的连接。
** 天浪690X获取文件名
   没有打开UI，默认是无法没有获取文件名
   要参考lcd_music_ui重新，为tpath分配空间
** 汇杰芯发射SDK
   在linein下无法调节音量，需要自己加数字音量的处理，参考BT14的程序。
   
* 20180808
** 合创外挂flash录音
   外挂flash的SDK，在蓝牙下录音，底层会内存泄漏。
   这个SDK不维护，让客户改用玩具的SDK。

* 20180807
** 爱瑞声6902A蓝牙音箱带BLE传文件
   上板程序已OK，可以正常工作。
   发给客户使用了。

* 20180806
** 爱瑞声6902A
   修板，板子一定要预留PC模式。

* 20180803
** 请假半天
** 威益德处理底噪
   收音芯片的音频输出脚，走过屏，如果音频脚偏置掉电，
   干扰就会盖不住
   在其他模式下，收音芯片的复位脚不能复位，收音也不能进入睡眠模式。
   
* 20180802
** 威益德6901车机
*** USB在standby之后电流没降低
    不能操作USB口为普通IO口
*** VM_write写申请不到空间死机
    加个判断，id3的大小，大于6K不分配。
    #+BEGIN_SRC c
    if(len < 6 * 1024)
    	id3_buf = malloc(len);
    #+END_SRC
*** 抄机软件有噪音
    在linein下，有高频声。

* 20180801
** 中翔达
   mic扩音器限幅，发了个版本给客户。

* 20180731
** 起华FF206
   换用6916D的芯片。
** 中翔达反馈问题
*** 获取第一次连接
   BT_STATUS_CONNECT_WITHOUT_LINKKEY:
   info[4] == 1,第一次配对
*** 删除蓝牙信息操作 
   USER_CTRL_DEL_ALL_REMOTE_INFO :删除手机，不包括对箱
   USER_CTRL_TWS_CLEAR_INFO:删除对箱
   要删除所有就要2个都调用。

* 20180730
** 小米音箱
   替换提示音，把回声算法去掉。
** 巴达木
   培训691X的BLE
** 中翔达
   问题点跟进中

* 20180728
** 小米音箱
   出差得辉达。
   BM2110有硬件问题。
   
* 20180727
** 起华J8耳机
   修改红蓝灯的方式
** 小米音箱
   出差得辉达
   完善BM2110的功能。
* 20180726
** 小米音箱
   修改BM1120的bug。
   提供一个BM2110的版本调EQ。
* 20180725
** 小米音箱
   完善BM1120的功能。

* 20180724
** 得辉达小米音箱
   调试一个版本
   出差客户，提供一个版本调EQ。

* 20180723
** 实捷DAB
   修改删除蓝牙连接后，还会自动重连的问题
   开机回连还是有，难修改。
** 汇杰芯690X
   用错EQ工具版本，导致连接测试盒，有很大的噪声。
** 起华V8
   在J8上面修改。
   中文的开机，是截取的，导致2个声音，有点停顿。

* 20180721
** 芯运692X
   linein转AD后，无法左右分离。
** 澳特爱692X
   三星手机，以前缺失HFP有一项属性Voice recognition，
   导致使用的是手机的mic。
** 也杨690X带APP
   EQ前五段有作用，后五段无作用，振荣修改中
   其他APP问题，让客户测试最新的APP。
** 中翔达微信语音
   安卓的微信语音走的是HFP
   苹果走的是音乐
   而后台返回时，对音乐有过滤包处理，导致短的语音难返回。
   打补丁“AC690N音箱耳机V2012-P4后台时间跳转可调节-V2”
** 起华J8案子
   调换红蓝灯，长按2s启动siri，长按4s关机

* 20180720
** 澳特爱6925B对箱
   三星手机S voice语音识别差
   ac69_sdk_v2012 这个可以，后面的SDK就不行。
** 微信语音
   苹果手机走的是音乐链路，底层有自动mute判断，导致有判断延时问题
   692X的没问题
   extern void set_mask_a2dp_data_time(u32 time);

* 20180719
** 嘉兴格优69调EQ
   EQ的Normal只有前面5段有效果，后面5段无效。
   振荣处理中
** 澳特爱6925B
   启动siri会关自动mute，关闭siri又没有打开。
** 起华6904D-J8
   改一版程序，调换红蓝灯。
** 69玩具SDK支持中文路径点播
   目前测试中文名和中文路径点播都不行。
   待远强确认。
   文件编码问题。
** 获取目录信息
   file_bs_entern_dir()
   参考点阵屏的接口
   func_browser_reflash()

* 20180718
** 起华6904D对耳
   ram-buf定义了2组，导致一播歌就ram不够，复位
** 起华6919A
   修改蓝牙名，烧录100PCS
** 本脉蓝牙伴侣
   fm模式点播频点有问题
   修改APP的源码，即可。
** 691X的BLE程序
   在初始化PR2的引脚上，要放在后面，底层会初始化唤醒IO，
   导致之前的设置被改，static void bt_task_init(void);函数尾就不会

* 20180717
** 澳特爱6925B对箱
   和志英出差一天，问题基本确认
   剩一个充电检测问题，少鸿跟进中。

* 20180716
** 澳特爱6925B对箱
   和志英在深圳办，处理主机回连从机的问题

* 20180714
** 奥特爱6928B对箱
   在深圳办和志英，处理对箱连接问题。差一种状态，要回连手机和从机。
   目前只能回连一个设备。
   设置idle时间问题，不是很合理。
** 泰奇通6919B
   BLE能用测试盒，测试按键。

* 20180713
** 澳特爱6925B对箱
   和志英出差澳特爱，处理对箱问题。

* 20180712
** 澳特爱6925B对箱
   和耀聪出差澳特爱，硬件性能OK。

* 20180711
** 起华对耳
   修改测试模式下，蓝牙名和MAC地址，和正常模式一样。
   改成红灯常亮指示为测试模式。
* 20180710
** 跟中翔达出差奥特爱
   处理对箱连接问题
   主机一直处于回连状态，从机处于可发现可连接，避免主从切换问题。
   志英修改底层没有地址，回连对箱会自动发起搜索。
   打完电话，主机不回连，底层修改，应用层就不需要延时处理了。

* 20180709
** 起华J8耳机
   修改提示音。
** 中翔达692对箱
   回连问题，有2个回连命令，有不同的问题。

* 20180706
** BLE传文件
   整理了一个SDK给客户了。
** 起华J8耳机
   同时长按音量+-，删除设备信息。

** 下午请假半天

* 20180705
** 华炬芯客户对箱连接
   开机不回连对箱，回连手机，要2个机子都按配对键，才会进行配对处理。
   替换铜霭改的2个库，程序代码也对应修改。
** 威益德6901车机
*** 录音死机
    客户原本V2012-p1版本的SDK，有此问题
    替换成p4的版本的encode_lib.a库。可以编译。
*** 69的PR口复位电平
    软复位：PR0为输入高阻，PR1口为输出0。
    RTC睡眠：RTC电压不掉电，寄存器值会保留，不为复位为默认值。
** 欣瑞声BLE传文件
   fat12_lib.a库有问题，对512B的数据时，会出现写不进的情况。
   新发了个库spifat1_lib.a库，待测试。

* 20180704
** 起华J8耳机
   蓝灯和红灯，共电阻接地。
   PWM推蓝灯时，红灯会有交流电通过，导致很微弱的亮度。
   改成了高低电平推。亮度偏大。
** 起华对耳
   刚开机有概率性会大声一声，突然间变低。
   修改了判断对耳数据量低的条件。
** 欣瑞声BLE传文件
   远强发了个fat12_lib.a库
   可以写文件了。
   写了个BLE传文件的文档。

* 20180703
** 华炬芯触摸板
   USB数据量太大，ble有时发不过来。
** 威益德6901车机
*** 快退到文件头
    暂停播放，松开播放当前文件。
*** 软复位后malloc无法对齐
    dac环形缓冲获取6912B失败，改成固定数组形式。强制对齐。
*** 卡带模式录音
    linein转AD，music通道，dac中断获取录音接口，ladc判断任务模式合进dac
** 源创杰6901-AI音箱
   很低概率出现搜不到EDR蓝牙，只能在半秒里面一直打开可发现可连接接口。
** 中翔达692X从机沙沙声
   志英发了个蓝牙库，替换即可。

* 20180702
** 中翔达6925B 
   打电话挂断后，有概率性出现EQ表被改的情况，导致沙沙声。
   志英在看。
** 徳凯芯6925B
   混响模式，要在每个模式下，单独开启
   linein支持混响功能。
** 徳凯芯6901
   低电声音在充电下，不播放。加标志位。

* 20180630
** 中翔达6925B
   开EQ之后，不停打电话，会出现从机变成沙沙声。
   V2.2版本的SDK，就有这个问题。
   //user_send_cmd_prepare(USER_CTRL_TWS_START_CONNECTION, 0, NULL);///会有配对过程
   user_send_cmd_prepare(USER_CTRL_START_CONNECTION, 0, NULL);///没有配对过程
   user_send_cmd_prepare(USER_CTRL_START_CONNEC_VIA_ADDR, 6, addr);///有配对过程

* 20180629
** 中翔达692X对箱
   音量同步会跳变
   因为在播提示音的时候，采用默认音量导致。
   #+BEGIN_SRC C
    static int get_dac_vol()///样机同步手机
    {
        printf("get_dac_vol:%d\n",sound.vol.sys_vol_l);
        printf("sound.tmp_sys_vol_l:%d\n",sound.tmp_sys_vol_l);
        if((sound.vol.sys_vol_l == TONE_DEFAULT_VOL)&&
        ((sound.tmp_sys_vol_l == MAX_SYS_VOL_L)||(sound.tmp_sys_vol_l == 0))){
            puts("tmp_sys_vol_l\n");
            return (sound.tmp_sys_vol_l * 127 / MAX_SYS_VOL_L) ;
        }else{
            puts("sys_vol_l\n");
            return (sound.vol.sys_vol_l * 127 / MAX_SYS_VOL_L) ;
        }
    }
        case BT_STATUS_CALL_VOL_CHANGE:
    #if BT_PHONE_VOL_SYNC
            sound.vol.sys_vol_l = (info[4] * aec_param.dac_analog_gain / 15) ;
            sound.phone_vol = info[4];
            log_printf("CALL_VOL:%d,phone_vol:%d\n", sound.vol.sys_vol_l, info[4]);
            sound.vol.sys_vol_r = sound.vol.sys_vol_l;
            set_sys_vol(sound.vol.sys_vol_l, sound.vol.sys_vol_r, FADE_OFF);
    #endif
        case MAD_ERROR_FILE_END:
            music_player_puts("music_tone END ok\n");
            if (tone_var.rpt_mode == 0) {
                mutex_resource_release("tone");
                msg = SYS_EVENT_PLAY_SEL_END;
                task_post_msg(NULL, 1, msg);
            } else {
                tone_var.status = 0;
            }
            printf("sys_vol_l:%d\n",sound.vol.sys_vol_l);
            printf("sound.tmp_sys_vol_l:%d\n",sound.tmp_sys_vol_l);
            if(sound.vol.sys_vol_l == TONE_DEFAULT_VOL){
                sound.vol.sys_vol_l = sound.tmp_sys_vol_l;
                sound.vol.sys_vol_r = sound.tmp_sys_vol_r;
                sound.tmp_sys_vol_l = 0xFF;
//                dac_channel_on(DAC_DIGITAL_CH, FADE_ON);
            }
            printf("sys_vol_l:%d\n",sound.vol.sys_vol_l);
            printf("sound.tmp_sys_vol_l:%d\n",sound.tmp_sys_vol_l);
//            music_tone_end();
           break;
   #+END_SRC

* 20180628
** BLE传文件
   接口s16 rec_file_delete(RECORD_OP_API *rec_op_api);
   在p4下不能使用，玩具的SDK，可以用
   #+BEGIN_SRC C
    typedef void (*btstack_packet_handler_t)(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size);
    extern void s_att_server_register_packet_handler(btstack_packet_handler_t handler);
    #define HCI_EVENT_PACKET                            0x04
    #define ATT_EVENT_CAN_SEND_NOW                      0xB7
    #define HCI_EVENT_NUMBER_OF_COMPLETED_PACKETS       0x13
    #define DAEMON_EVENT_HCI_PACKET_SENT                0x6C
    static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size)
    {
        int mtu;
        switch (packet_type) {
        case HCI_EVENT_PACKET:
    //        printf("HCI:%x\n",packet[0]);
            switch (packet[0]) {
            case ATT_EVENT_CAN_SEND_NOW:
                puts("N--\n");
                //streamer();
                break;
            case DAEMON_EVENT_HCI_PACKET_SENT:
                puts("+");
                break;
            case HCI_EVENT_NUMBER_OF_COMPLETED_PACKETS:
                puts("-");
                break;
            }
        }
    }
   #+END_SRC
   接口extern u16 rec_file_write(RECORD_OP_API * rec_op_api, u8 *buf, u32 len);
   在写SD卡是正常的，但是写flash不正常。

* 20180627
** BLE传文件
   目前可以传文件。
   AI音箱不能初始化flash文件系统。
   只能用玩具的SDK。
* 20180626
** 源创杰6919B
   蓝牙一靠近电机旁边，就会出现蓝牙信号被覆盖，导致播歌卡，甚至搜不到。
   将天线焊到机子外壳上。
** BLE传文件
   改APP源码测试中

* 20180625
** 华炬芯6908A触摸板
   没有解析触摸板的report
   用keyboard变量写立即数为2
** 源创杰6919B
   电机影响到蓝牙性能

* 20180622
** 科普豪6908C耳机通话效果
   软件改参数，听起来一直很闷
   最后在mic那个多焊了个102的电容，通话就清晰了。

** BLE传文件
   在github找了个APP的源码，来测试
   可以分包发送，不限于只有20个字节。

* 20180621
** BLE传文件
   在公版的SDK-V2012-p4版本上加，先用SD卡测试，

* 20180620
** 获取手机时间
   user_send_cmd_prepare(USER_CTRL_HFP_DATE_TIME,0,NULL);
   void get_phone_time(char *data , u16 len)
   {
       puts("get_phone_time:\n");
	     put_buf((u8 *)data , len);
	     puts(data);
   }

* 20180619
** 起华J8中控耳机
   加入充电关机
   音乐跟通话的音量同步，做了个音量映射表。
   可调节只有16级，但是实际音量有25级。

** 爱瑞声692X
   播提示音会抖动，关掉打印
   用SD卡升级，要改成调地址形式，不能用复位形式。

** 爱瑞声6901用ble传音频
   要珠海沟通，是否做传音频文件的操作。

* 20180615
** 威益德6901用ID3内存不够
   修改ID3编码统一为Unicode
   改ID3的内存为malloc(),
   要不然内存不够，在播music的时候，打电话会死机。

* 20180614
** 触摸板
   抓包给日新分析。
** 起华6904D中控耳机FF209
   带功放，

* 20180613
** 起华6904D中控耳机J8
   基本OK，给客户测试了
** 威益德6901
   判断长文件名不为0，长文件名为Unicode
                  为0，为ASCII
   ID3信息编码有问题。
** 起华对耳测试回连距离异常
   手机回连样机，手机当主机，距离远
   样机回连手机，样机当主机，距离近

* 20180612
** 科普豪69获取电话本
   获取电话本时，来电会导致btmsg线程挂起，原因是播放提示音时，
   需要资源申请时失败导致。
** 起华6904D中控耳机J8
   调试中。

* 20180611
** 金华AI音箱
   储存speex语音的spx文件，应该没有文件头的。
   调用public static void setIsLog(boolean log);可以开启底层库的打印。
** 其他方案的对耳
   络达AB1526
   风动WT200M/S
   炬力ATS2829
   都是class 1的功率。

* 20180609
** 起华6904D对耳问题
   出差华强北测试69对耳的问题。
   见邮件
** 金华AI音箱
   修改static u16 speex_encode_write_cbk(void *hdl, u8 *buf, u16 len);里的发送函数，
   为自定义属性的发送函数。
   打开void ladc_isr_callback(void *ladc_buf,u32 buf_flag,u32 buf_len);里的
   speex_encode_ladc_isr_callback(ladc_buf, buf_flag, buf_len);函数执行，才会有发送语音。
   APP端,new SpeechAiManager()，就会新建一个spx文件，用于储存speex的语音数据。
   speex和通用的开源不一样，珠海修改过。
   再调用mSpeexManager.decodeFile()解码成16kHz 16bits的PCM数据。

* 20180608
** 无线云图6904D出现机子开不了机
   有4种情况。见邮件。
** 金华AI音箱
   将le_server_smart.c替换为le_server_module.c文件，写回调才能上抛。
   le_server_smart.c只能用于杰理的AI的APP。要连接正常后，才能上抛数据。
   le_server_module.c用于自定义gatt profile。

* 20180606
** 690X设置对耳播放声道
   __set_soundtrack_compound(1);///主机播放左声道
   __set_soundtrack_compound(2);///主机播放右声道

** 博建6908C
   目前测试VMCU换成226，才行。
   VDDIO的电压，比VBAT的电压，上升比较慢。

** 联巨兴6904D充电LDOIN漏电
   以后强制LDOIN要加二极管，和对地2M的电阻。

* 20180605
** 博建6908C开不了机
   停在uboot 1.0里出不来，插USB，弹出盘符，下载时，提示读不到flash。

* 20180604
** 芯运6902用MAC电脑拷贝会出现2个文件
   一个是原文件，一个是AppleDouble，文件名后缀名都一样，但是是隐藏文件，无法播放
   默认SDK，没有去掉隐藏文件，会显示出来，但是播放不了，会跳过。
   extern void hidden_file(u8 flag);
   hidden_file(1);///在进music_task设置一下就行。
** 起华6904D改sbc码率
   sbc码率改成27后，距离能达到水果那边的窗口。
   要是54的时候，只能在老板的门口。

* 20180601
** JBL 串口协议
   基本能用，写了一些基本的命令，后续需要测试再加新的命令。
** 起华6904D对耳
   信号差，就mute，测试可以，
   加了出声音，慢慢变大的操作。

* 20180531

* 20180530
** 科普豪6908C对耳
   iPhone X手机，所有样机都卡。

** JBL音箱自动化测试协议
   目前切换测试模式正常。

* 20180529
** 新子K歌宝SD卡掉线
   CMD脚的检测，可以直接放到key_drv_ad.c文件里，直接检测。
   扫描函数里要开上拉才行。
** 起华6904D对耳先回连从机再回连手机
   铜霭发了2个库，做了版V2013版本的程序
** 起华W302对耳固定左耳当主机
   软件已改好，V2013版本的。

* 20180528
** 新子K歌宝播放SD卡卡音
   由于SD的CMD脚和DATA脚复用做AD检测导致，想办法优化。
** 起华6904D-W302固定左右耳
   可以检测，功能还没做。
** JBL音箱
   开LDO模式，SW脚的电感要换成0R电阻。

* 20180525
** 测试692X普通IO推灯效果
   PB口只有8mA，推屏不行。
   PA口可以。
** JBL程序兼容正常模式和测试模式
   修改成变量，不用宏包含。
** 6919的BLE的程序广播包参数
   修改广播包参数，不起作用，一直是5ms以内。
   69的SDK是可以的。
** 起华6904D对耳
   先回连从机再回连主机，铜霭发了2个库，测试OK。

* 20180524
** 起华6904D--R208对耳
   通话效果，只能把增益调高，声音变清晰，但会引入环境噪音，
   在嘈杂的环境下，无法使用。
** 起华6904D改先回连从机再回连手机
   铜霭发了个蓝牙库，测试还是不行。

* 20180523
** 源创杰46歌词加密无法点播MP3
   通过目录项里的簇号，无法找到文件。
   刘行发了补丁库dev_mg_lib.a，客户测试OK。
** 起华6904D对耳
   客户想改成先回连样机，再回连手机，测试不行
   铜霭说，底层做了限制，不能这样操作，具体原因未说明。

* 20180522
** 芯运6902外挂flash播放
   播报提示音有间隙。德科创的程序，就可以，但是是用提示音播放的。
   
** 华炬芯6901用IIC从机接收
   主机iic是5V输出，要改成3.3V供电才行。
   iic的打印要去掉，影响时序。

* 20180521
** 无线云图6904D
   耳机通话，客户确认中。
   充电问题，解决不了。
** 源创杰4601点播MP3
   通过簇号，播放不了。国炜处理
** 芯运69玩具
   无间隙播放，mp3文件剪切不干净。明秋说，怎能听效果。
* 20180518
** 出差三诺
   处理JBL音箱的认证，仪器问题，立辉处理

* 20180517
** 6919-BLE用sniff模式
   默认SDK会复位，要改成PWR_DCDC15模式。

* 20180516
** 出差无线云图6904D对耳
   测试盒连接慢，要避免测试盒进入搜索设备状态，会导致测试盒连接慢。
   板卡测试，只需要快速测试即可。

* 20180515
** 无线云图6904D对耳
   5V充电唤不醒问题，不能在充满电之后，调用soft_poweroff()函数，有隐患。
   串连问题，复现不了。

* 20180514
** 出差无线云图6904D对耳
   5V充电唤不醒，是有问题，待会分析。
   串连复现不了。

* 20180511
** 691X的开发板
   PR0是短接到地的，flash口是PB0-PB4
** 中翔达wav 32bits断电播放异常
   从头播放正常，断点播放异常。
** 692X按键音播放哒哒响
   69的按键音，比较小声，比较难听出来。
* 20180510
** 威益德69系列spp发送
   放在main线程，因为会pending住，会导致死机
   放在优先级低的，就不会有事，但会卡住当前线程。
   建议新建一个线程，专门用于发送spp数据。
   底层是会pend，发送完之后再返回的。
** 科普豪69推大屏的数码管
   由于每一段都有2个灯，需要修改驱动。
** 芯运69玩具SDK单曲无间断播放
   伟文发了一个库，发给客户测试了。

* 20180509
** 威益德69获取收音立体声
   printf("get_fm_stereo:%d\n",get_fm_stereo());
** 微源功放
   mute脚控制脉冲要大于60ms，才能正常。

* 20180508
** 小霸王6905A升级成图灵APP
   用测试盒烧录认证码，显示AU超时，吴旭处理中
   改用USB工具烧录
** 艾玛威6901A点阵屏耳机
   调试界面，基本OK。
* 20180507
** 威益德用恒大智通蓝牙测试盒
   第一次连接，通话会出现卡5s左右，才有反应，海华分析中。
   由于“AT+CMEE”指令，测试盒没有响应。
** 威益德spp发送数据给APP
   在main线程发送，由于main线程优先级较高，会卡死蓝牙线程。
   在music模式下测试，不会卡死，会卡住一段时间，只能减少发送频率。
   客户写的编码器，会累积一堆音量加减消息，等待执行，需要去掉这一部分。
** 泰芯为69带BLE
   特征同时带读写属性，句柄是一样，需要同时在read、write回调执行。
** 艾玛威6901A带点阵屏
   调试中，修改界面。
* 20180505
** 联巨兴6901A
   点阵屏点不亮，配置IO口不对。
** 联巨兴6904D对耳
   快速插拔充电，会无法充电。
   在关机的时候会有一段时间，关闭了充电唤醒，如果在这期间，产生上升沿，会导致电平丢失。
** 艾玛威6901A带点阵屏耳机
   屏点亮，板子硬件调通。界面待改。
** 科普豪6901A收音底噪
   用QN8035收音，用升压5V给HT1628芯片供电，会带来底噪滋滋声。
   分析是因为升压5V供电不足，多并了一个芯片4004，但是客户测试还是不行。

* 20180504
** 宇恒69AI想兼容其他APP
   之前有“火火兔讲故事”的APP，想做到69AI上面。
** 69点播MP3
   #+BEGIN_SRC C
 	 u32  music_play_by_path(MUSIC_OP_API *mapi)
 	 {
		u32 err;
	//    u8 *path;
		const char path[]="/1*.mp3";
		puts("1\n");
	//    path="/音乐/";
		mapi->fop_api->fop_init->filepath = (u8*)path;
	//    printf("file path : %s  \n",path);
	//    err = music_play_api(mapi,DEV_SEL_CUR,0,PLAY_FILE_BYPATH,&(mapi->dop_api->file_num));
		err = music_play_api(mapi,DEV_SEL_SPEC,0,PLAY_FILE_BYPATH,&(mapi->dop_api->file_num));
		return err;
   }
   #+END_SRC
** 科普豪6901-8035收音底噪
   4004的升压IC，推灯的亮度，电池的电源位置，都有点影响。

* 20180503
** 秦齐发射器死机
   发射器切模式进idle，再回到发射模式，会死机。
   让客户改用SDK的流程，不要自己自定义流程。

* 20180502
** 天罡微69系列vivo X6A无法连接pin code
   用p4测试过，也会，其他vivo没有问题。
   不设置pin code就能连接。
** 宇恒69系列普通SDK回连导致BLE异常
   之前AI的SDK，回连样机当主机，手机当从机，会影响BLE的发送。
   普通的SDK，也会有这样的问题。
** 源创杰69019B-BLE烧录不了C版晶圆
   替换otp_ver.bin，修改日期为20171201，就可以烧录。
   原先A版晶圆为20170701
** 诚谦LC6904C低电LVD复位
   客户用纽扣电池供电，没有加升压iC，后续生产可能会有问
   
* 20180428
** 源创杰6919B烧录不了
   升级烧写器到2.11.1版本
   BLE的SDK不支持C版晶圆的问题。

** 692X异步唤醒问题
   异步唤醒底层库都为空函数，没有执行。
   
* 20180427
** 博益友6905B K歌宝
   推RGB灯，会有底噪声。
   客户板子没分地，mic的电路距离主控太远。
   改板处理。

* 20180426
** 博建6901A生产不良
   VMCU有4V供电，但是其他电压都没有。
   正常情况下，VMCU有供电，那RTCVDD电压就一定要有输出。
   问题是批次不良，换主控。
** 德科创6904D待机功耗高
   耳机要连上手机，手机不播歌，隔一段时间才会进入power_down模式。
   功耗为1mA-1.5mA之间。
   DAC输出频响不好，失真度高，无解。
   
* 20180425
** BLE标志
   indicate比notify多了一个应用层的GATT_MSG_EVENT通知。
   Notification快，因为indication要等回复才能发下一个包。
   indicate本来就是耗时的，担心耗时就用notify。
** 起华FF208调音质
   调试一个低音版本给客户。
** 巴达木692X非PR口唤醒
   SDK有对应函数，但是和690X一模一样，钧仟先对数据手册。
** 诚谦LC6904C
   生产一百个，有一个会LVD复位，
   客户不会焊板子，要过来，让他五一之后再来。

* 20180424
** 不同手机BLE发包数据间隔
   安卓最低7.5ms，苹果是20ms。
** 也杨翁工linein录音
   69系列在linein单声道模式下，录音成双声道，会出现左右声道不对称。
   测试没有发现。
** 6919-BLE的SDK
   OTP只剩余6-7K空间。
** 69系列浮点运算
   不支持，只有52支持。
** 天罡微69-p3开启pin code
   用vivo X6A手机连接不上，目前找不到该手机。

* 20180423
** BLE传输速度，不同手机的速率
   Android 4.3 设备： < 2KB/s
   Android 4.4 设备: 4-5KB/s
   Android 5、 6、 7 设备: 5-8KB/s（ 部分手机可超过 20kB/s）
   IOS 8.3 设备: 3-4KB/S
   IOS 10、 11 设备:6-8KB/s

* 20180421
** 博建6901开不了机
   LDOIN有电池供电3.8V，但是其他电压都没有。
   RTCVDD电压一定要有，晶振才能起振。

* 20180420
** 69系列消息池
   void key_msg_sender(char *name, u32 msg);中
   os_taskq_count(name, &cnt);获取的是消息池的剩余空间

* 20180419
** 69系列修改pin code
   #+BEGIN_SRC C
    extern void bt_pin_code_spec_deal_handle_register(void (*handle)(char *pin_code));
    void set_bd_pincode(char *pincode)
    {
        char tmp[] = "1279";
        printf("len:%d\n",sizeof(tmp));
        memcpy(pincode,tmp,sizeof(tmp));
        printf("pincode:%s\n",pincode);
    }
   #+END_SRC
** 起华6904D对耳充电
   设置了80分钟充满，但是电池如果电量太低，80分钟充不到4.3V。
   会导致一直在耗电，关不了机。
** 起华6908C--FF108
   使用p4的SDK，没有测试通话效果。
** 针对对某个按键做长按时间处理
   #+BEGIN_SRC C
    void key2msg_filter(u8 key_status, u8 back_last_key);中添加
    {
        ///长按3s关机。///
        static u8 key_delay = 0;
//        printf("key_status:%d...back_last_key:%d\n",key_status,back_last_key);
        if(((KEY_LONG == key_status)||(KEY_HOLD == key_status))&&(0 == back_last_key))
        {
            if(0xFF != key_delay){
                if( key_delay > 11){
                    key_delay = 0xFF;
                    key_status = KEY_LONG;
                    back_last_key = 0;
                }else{
                    key_delay++;
                    return;
                }
            }else {return ;}
        }else{
            key_delay = 0;
        }
    }
   #+END_SRC

* 20180418
** 宇恒69AI回连APP出现兼容性问题
   APP主动连接对箱，手机EDR做主机
   样机重启回连APP，样机EDR做主机
   解决办法，要将回连后，将样机主机调整为从机，才不会影响到BLE。
** 针对对延时时序控制严格
   在临界区内，不要出现调用函数，尽量在临界区外，获取索引，
   转换成指针形式，才能控制好时序不会跳动。
** Android打印byte[]
   #+BEGIN_SRC java
   public static void printHexString(String hint, byte[] b)
   {
        Log.d(TAG, hint);
        for (int i = 0; i < b.length; i++)
        {
            String hex = Integer.toHexString(b[i] & 0xFF);
            if (hex.length() == 1)
            {
                hex = '0' + hex;
            }
            Log.d(TAG, hex.toUpperCase() + " ");
        }
   }
   #+END_SRC

* 20180417
** 69系列PB3引脚
   开机就输出高，没有上拉。
   maskrom程序写死，无法修改。

* 20180416
** 玩具SDK挂载外置Flash
   spifat1_ctrl_open(1, 1);///第一个参数设置成1，每次进PC，会格式化Flash的文件系统。
   生产一定要改成0.
** 出差中翔达-科迈通处理对耳
   客户用音魅电子的测试盒，有一个测试盒连不上，要机子连接手机之后才能连接。
   高频声，要装壳之后，就会有，小概率性出现。
   带触摸的机子，灵敏度不是很好。
* 20180413
** 69APP通信机制
   设置发送数据的心跳包mJLBluetoothRcsp.setDeviceInquireTimeInterval(500);单位ms。
   小机这边无法发送数据给手机，必须有手机发送命令，样机再回应数据给手机。
   小机发送流程：
   1.rcsp_report_status(x)
   2.u8 rcsp_event_cbk_send_process(int send_allow_flag)
   3.自定义填充数据函数，post_....(),参考Post_Radio_StartInfo_to_rcsp()
** 宇恒69AI要做常连接状态低功耗
   不支持。要等智能耳机SDK。

* 20180412
** 汉普功能
   固件没有连接手机的时候，发起siri,通过HFP发送一段语音“打开酷走车机”，
   由系统识别，并打开软件，连接样机。

* 20180411
** 69系列连接BLE获取MAC地址
   在连接成功有buffer反馈，16字节。
	 前面2byte是handle，接着1byte的role，1byte的addr_type，然后就是6byte的peer_addr。
   手机蓝牙MAC地址可以改的，EDR和BLE的地址是不一样的。
* 20180410
** 宇恒69AI
   V100版本，部分安卓手机APP重连后，固件发送数据后，APP没有回调。
   卓成分析，语音数据没有产生回调，具体原因分析中。
** 汇杰芯69对箱
   主机100ms发送消息给从机，在连接从机后，发这些消息会导致底层同步丢失。
   后面客户删除提示音后，又会出现这个问题。
   铜霭反馈，是有这样的问题，无法修改。
   让客户自己修改应用层的流程。

* 20180409
** 芯运69玩具SDK
   外挂flash，要CS定义好，接上IO，初始化识别要用到
** 实捷BT15、BT65D
   修改频点881-1079。
** 宇恒69AI
   AI_SoundBox_v100修改过IOS重连重启的bug后的软件,
   在OPPO_A79的机型上装客户端软件,在手机不操作时,
   板子开机重连后出现对话无法识别的bug。
 
* 20180408
** 老树开花6901A
   RGB用定时器去推，调不好，播歌之后，会有问题。
   改用延时推灯，目前半秒推1次9盏灯，测试正常，播歌也不会卡。

** 汇杰芯69对箱
   主机以100ms发送消息给从机。在从机关机后，主机会有延时断开，导致消息池累积消息，
   下次连接有导致消息同步问题。
   如果以500ms发送就不会有事。
** 嘉兴科美69对箱
   对箱连接不上，频偏有很大影响。
   其他程序问题，修改软件问题。
** 光交锁
   日新新发的uboot.bin，测试正常，可以升级。

* 20180404
** 汇杰芯69对箱
   从机关机后，主机发送数据，会卡死在底层，导致下次连接后，同步有问题。
** 嘉兴科美69对箱
   下载程序之后，很难连接对箱。
    #define    TWS_SLAVE_WAIT_CON         0

* 20180403
** 光交锁Uboot工程
   日新发的库，测试还是不行，错误码为-12，后面又发了一个新的，还没测试。
** 老树开花XR871-H2案子
   基本功能都OK，剩下灯还没推，灯的效果未定义。
** 汉普6904D耳机
   开启回声消除，通话会突然间没声音。
   进不了低功耗，珠海还没整。

* 20180402
** 起华6908C单耳调试
   E23采用6908C，调试功能，基本正常。
   E25有一个机子不行，通话很模糊，一个机子通话正常。
* 20180330
** 宇恒69AI-V100
   V100-SDK和V200-SDK不通用，V100在重启连接APP，打开发送speex语音，会导致重启。
   初步判断，是库有个断言导致重启。
   吴旭知道，在改库。
** 69AI的SDK
   V100用于客户自己有资源，自己开发APP。
   V200专用于连接老树服务器。
** 起华69对耳
   修改提示音。
* 20180329
** 起华R208对耳音质调试
   样机原本没低音，声音太散。
   喇叭厂，更换喇叭，喇叭前后密封(音量变大，低音变重)，前面加防尘网，人声变清晰，不失真。
   目前播放告白气球，时不时会有很小的噗声。
* 20180328
** 起华69对耳
   修改双击上一曲，三击下一曲，关机提示音，双击上一曲和搜索设备同时起作用。
** 光交锁安卓手机usb升级
   需要在uboot 2.0加2个命令。
** 威益德6905C
   电话本获取sim卡的联系人，会发2次，一个是名字和号码，一个是序号和名字。
   目前建议客户判断号码是否为数字，进行过滤。
   开机默认进蓝牙，关闭蓝牙可发现可连接，会导致蓝牙栈卡死。

* 20180327
** 出差国华
   broadcom20738 ble低功耗
   EDR支持4M包
   ble有分真ble，和假ble
   假ble为软件协议层模拟。
** 光交锁6905D
   测试USB升级apk，荣耀6X点击下载没有反应。
   测试发现在maskrom的uboot1.0是可以，在Uboot2.0不行。
** 69系列擦除flash
   -format 0-1024
* 20180326
** 起华69对耳进入低功耗哒哒声
   进入低功耗模式，DAC和VCOMO会随DCDC产生1秒2次电平跳动噪声。
   跳动大概80mV电压。
   解决办法：
   #+BEGIN_SRC C
		case MSG_DAC_ON:
			puts("main_dac_on\n");
			set_pwrmd(PWR_DCDC15);
			dac_on_control();
			break;
		case MSG_DAC_OFF:
			puts("main_dac_off\n");
			dac_off_control();
			set_pwrmd(PWR_LDO15);
			break;
   #+END_SRC
** 汉普6904D耳机带ble
   功能正常，开不了power_down状态。
* 20180323
** 中翔达69发射器录音
   SDK的录音流程是缺失的，参照p4添加，有部分函数，连接不到。
   替换库，又会导致其他函数，没定义。
   目前有文件，有声音，但都是杂音。p_ladc_rec变量获取不到。
** 光交锁6905D连测试盒死机
   是因为晶振原因，频偏太大就会。
** 起华对耳V2013通话调试
   远端近端，都有哒哒声。
** 69AI的V200APK
   V200.apk安装到手机刷新不出资源。
* 20180322
** 中翔达发射器录音
   没空看。
** 光交锁6905修板子
   测试盒，畅玩6X，华为Novo，连接不上，其他手机可以。
   测试盒连接会导致重启。
   没有pcb，无法查看。
** 起华6904D对耳
   通话时，就算不说话，也会哒哒声。
   用V2012-p2版本，就不会。
   通话参数，2个版本是一样，不同的是dac的中断改动，处理延时加的。

* 20180321
** 华炬芯6904D耳机改用数字音量
   改用数字音量，会有底噪声。使用数字音量，模拟音量默认最高，导致的。
   可以降低模拟音量的最大等级，要降到21级才可以，但是这时整体音量会变低。
** 杰飞达69系列spp协议
   客户测试发现，p4版本，如果按照公版，关闭1拖2，就会导致，手机拿远之后，再回来，就搜索不到蓝牙。
   打开1拖2，就正常。
**  汉普X8-6901A
   U盘接口，兼容有充电功能。
   屏幕接反，180度反向。
   晶振频偏大，晶振太远，蓝牙天线太长，绕了屏幕。
   发射底噪大，杂音、电流声太强。

* 20180320
**  天浪
   工程交流。
** 光交锁tea加密库
   测试新的加密库，正常。
** 杰飞达69用spp
   客户用spp和APP通信，走远回来后，会导致蓝牙搜索不到。
   测试p4版本，正常。
** 鑫闻达调节按键音大小
   #+BEGIN_SRC C
    void key_voice_init(void)
    {
        memset(&key_voice,0,sizeof(_key_voice));
        key_voice.vol = 2000;
    }
   #+END_SRC
* 20180319
** 美师傅6919B死机问题
   buf没有溢出检查，会死机。
** 光交锁tea加密库
   存在类型转换，会死机。
* 20180316
** 起华6904D中控耳机
   带3个按键。
** 69系列
   	芯片序号标签  printf("chip index =%x \n",get_chip_index());  开发板打印chip index =7
	  芯片ID         printf("CHIP_ID =%x \n",JL_SYSTEM->CHIP_ID);   开发板打印CHIP_ID =5300
    内核电压      SFR(JL_SYSTEM->LDO_CON, 15, 3, 0b101);     // 3.3 -> 1.2 DVDD set to 1.0v
                   110(0.9V)/101(1.0V)/011(1.2V)/010(1.3V)/001(1.4V)
** 起华6904D耳机测试蓝牙距离
   DVDD、BTAVDD、VDDIO电压改动，对蓝牙距离影响不大，差不了一步的距离。
** 6919耳机SDK
   开关DACVDD，调用LDO1_EN(0/1);
* 20180315
** 69临界区操作
   临界区代码，如果cache命中不了，会从flash中读取，会导致执行时间不一样。
   #+BEGIN_SRC C
     //接下来的函数代码存放段测试。
     //不要内联
    void open_critical(u8 cfg) __attribute__((section(".ramx_code"))) __attribute__((noinline));
    void open_critical(u8 cfg)
    {
    //    puts("open_critical\n");
        CPU_SR_ALLOC();
        OS_ENTER_CRITICAL();
        JL_PORTB->DIR &= ~BIT(0);
        JL_PORTB->OUT |=  BIT(0);

        u8 i = 50;
        while(i--){
            __asm__ volatile ("nop");
            __asm__ volatile ("nop");
            __asm__ volatile ("nop");
            __asm__ volatile ("nop");
            __asm__ volatile ("nop");
        }
        JL_PORTB->DIR &= ~BIT(0);
        JL_PORTB->OUT &= ~BIT(0);

        OS_EXIT_CRITICAL();
    }
   #+END_SRC
** 汉普6904D耳机
   调试OK，距离可以。
** 汉普6901煲机异常
   未测试到。
* 20180314
** 小树开花RGB灯环
   RGB灯WS2812B，单线控制协议。纳秒级精度。
   http://blog.csdn.net/tangxing1212/article/details/42964417
   http://blog.csdn.net/zoomdy/article/details/54730618
   http://blog.csdn.net/darren2015zdc/article/details/52262197
** 69系列一拖2不支持ble
   天师说，固件开1拖2，不支持ble。
   测试发现，开机进入蓝牙后，蓝牙栈就卡死了。
   耳机SDK，不支持ble，没有包含对应的C文件。
** 69系列蓝牙获取手机的ID3信息
   在V2012-P3版本测试，可以获取到，但是兼容性问题无法保证。
** 69蓝牙对讲机
   只支持A2DP协议，单向发送，不支持同时的双工。
** 宙心WiFi-9601
   耳机座子和linein座子，接法是，其他一个音频接1K下拉，没插入检测脚跟他短路为低。
   插入之后，开路，检测脚上拉，检测为高。
** 6919-ble使用USB当串口
   搬耳机版的程序，测试OK。
   #+BEGIN_SRC C
	 #ifdef UART_USBP_USBM
		JL_USB->CON0 = 0;
		JL_USB->CON1 = 0;
		JL_USB->IO_CON0 = 0;
		JL_USB->CON0 |= BIT(0) ;
		JL_USB->IO_CON0 |= BIT(11) ; //USB_IO_MODE

		JL_IOMAP->CON1 |= BIT(3) | BIT(2);
		JL_USB->CON0 = BIT(0) ;
		JL_USB->IO_CON0 = (BIT(11) | BIT(10) | BIT(9)); //USB_IO_MODE	//DMDIE	//DPDIE
		JL_USB->IO_CON0 |= BIT(0); //TX DP
		JL_USB->IO_CON0 |= BIT(3);//RX DM
		JL_USB->IO_CON0 &= ~BIT(2);//tx dp

		JL_USB->IO_CON0 &= ~BIT(5);//DM下拉
		JL_USB->IO_CON0 &= ~BIT(7);//DM上拉
	//    JL_USB->IO_CON0 |=  BIT(4);//DM下拉
	//    JL_USB->IO_CON0 |=  BIT(6);//DM上拉
   #endif/*UART_USBP_USBM*/
   #+END_SRC
* 20180313
** 源创杰6919B测试盒升级不了蓝牙名
   蓝牙名测试盒升级不了，是因为程序写死了。
   #define ADV_NAME_EN         1            //广播包是否填充名字信息
   宏置1后，才会使用配置文件。
** 汉普6904D耳机
   进入power_init()函数出不来，BTAVDD电压5V，VDDIO电压为0.7V。
   查不出其他原因，板子废了。
* 20180312
** 华炬芯6904D挂脖式耳机
   开关机，播提示音切dac通道，有噗噗声。
   将VCOM换成104电容，软件上用加大dac上电时间，dac_power_on_time()。
   蓝牙通道使用数字通道，在执行dac_channel_off(BT_CHANNEL, FADE_ON);会有杂音。
   可以通过dac_mute处理掉。
   但是有一些杂音，播提示音，概率性出现。
** 宙心WIFI-6901
   RGB灯，是共阳，板子是共阴
   linein和耳机，检测拉低不了。
** 伦茨6919A隔推会有噗噗声
   6919默认用直推，使用了dac开关dac_toggle(1)，所以在dac关，就有噗声
   可以改成dac_mute();
   DACVDD控制高mute功放，关机会噗声，加电容处理掉，过滤脉冲。
* 20180309
** 源创杰6919B蓝牙名升级不了
   铜霭发的测试盒程序，客户测试会出现conerr。
   铜霭说是，升级相同的蓝牙名，就会出现这样。
   客户星期一拿样机给我测试。
** 中翔达6908C单耳通话调试
   机内有腔体，会有震荡回声。通话声音小，不清晰。
   改通话效果就可以。
** 芯运69--IIS调EQ
   程序有问题，重新初始化eq导致，
   开启软件EQ，会死机。
** 美师傅6919B-ble使用UART2的PA3打印不了
   AD-key默认使用PA3，需要注释掉，开启IO-key即可。
** 宙心WiFi
   IIS的格式改为通道数：2，通道位宽：16，采样频率：44.1
   设置为每帧32bits。
* 20180308
** 宙心WiFi
   添加WiFi模式播放iis。
   添加串口协议。
** 彩荣测试盒替换sbc语音
   转成wav文件Windows PCM，格式32K， 16bits， 单声道。
* 20180307
** 益丰6904C烧录不了&&IIC从机
   晶振封装搞错，接地了。
   刘行，发资料，测试一下。
** 美师傅6919B串口通信
   串口接收要用hex显示，发送要以ASCII格式发送。
** 起华科技69对耳
   升级SDK到p4版本，待测试。
* 20180306
** 宙心MTK-WIFI和BT
   板子修好，串口和IIS，待调试。
   DAC单声道，耳机却双声道。
   2个RGB灯，没法推，无法输出6个PWM。
** 起华科技死机
   6904有概率性在power_init死机
   要更新到V2012-p4版本才行
   优化程序，一直打印，方便以后生成问题跟踪。
* 20180305
** 6919-ble
   做了一个ble蓝牙模块的例子。
** 源创杰6919B升级蓝牙名
   测试盒要升级到AC690x_1T2 测试盒 V1.0.7 版本，才能使用6919的。
** 汉普6905A电池电压检测异常
   电池4V，但是LDOIN的电压检测是8V。
   因为电量检测的宏，没有打开。
** 起华科技开不了机
   跟民宗确认，开机的时候，power_init会初始化所有电源，导致电源都存在。
   DCDC电源SW脚，和BTAVDD电源短路在一起。

* 20180302
** 飞灵特Novolink蓝牙模块
   支持ble模块开发，UART通信。
* 20180301
** 瑞知光交锁
   ADC的检测，放在电磁铁之后，电磁铁电阻30R左右，会耗光5V的压降。
   关锁状态，电压3.0V，开锁状态，电压0V。
   USB和蓝牙的开关锁，功能正常。
** 汉普6905A
   LDOIN测量出来的电压，是8V，误差太大。具体原因未知。


* 20180228
** 诚谦LC6904A
   socket板子，USB的限流电阻，2.4R变成100R，导致供流不足，会不停复位。
   有一颗芯片，初始化电源之后，就跑不下去。
* 20180227
** 4110直播声卡
   影志说，寄回给振荣搞。
* 20180226
** 光交锁
   USB的通信，熟悉USB的协议流程
** 4110直播声卡
   linein通道和LADC的采样通道，对应不上。
   钧仟帮忙看看。
* 20180224
** 光交锁
   蓝牙的通信，可以，待发给客户测试。
* 20180223
** 4110直播声卡
   开会讨论，在music模式下，耦合linein和mic的采样，再输出。
** 光交锁
   调试客户协议程序流程。
* 20180222
** 4110直播声卡
   调试led，按键功能。



* 20180208
** 起华69对耳
   改用PR1，上升沿唤醒，测试正常，双击OK。
** 直播声卡4110
   用玩具的SDK，能开机正常工作。

* 20180207
** 起华69对耳触摸
   触摸电压高，接近电池，要3.9V，会导通bangding的二极管，造成20uA的耗电。
   PR2不支持默认下拉到地，uboot下升级不了。

* 20180206
** 总结问题点
*** ble切模式死机
    死机问题，是切换的链表释放问题，与ble无关。
    FAT16，也能测试出来，ble连接之后切模式，也能测试出来。
*** ble回调死机问题
    ble回调函数，不能处理延时操作，会导致蓝牙栈卡死。
*** ble发送notify数据
    需要由其他线程调用，不能由回调函数调用。
*** 充电问题
    充电充不满问题。
*** power_down引起乱中断
    6919B--ble power down，会改动引脚，引起乱中断现象。

* 20180205
** 博建69对耳iPhone X通话
   通话隔个头，对线放后裤袋，就会卡。

* 20180202
** 源创杰6919B
   烧录不了，是因为用release版本的fw文件，大小为66K。
   烧录器无法烧录flash。
   旧的样片，bangding有问题，180度反向了。
** 源创杰6905C
   EDR、ble的蓝牙名和MAC地址一样，有问题。
   广播包的flags设置，
   flags为0x06正常，但是赖工手机搜不到。
   flags为0x0A不正常，安卓手机都无法连接ble。

* 20180201
** 蓝牙游戏手柄
   一定要进入安卓模式，才可以用。
** 光交锁
   spp和ble定时收发数据。
** 诚谦69车机
   空间不够，会导致能下载，但是跑的不正常。
** 6919-ble
   图标显示，显示成HID，是因为广播包的字段填充导致。
   //    0x03, 0x03, 0x12, 0x18,
   1812是HID的UUID.
* 20180131
** 光交锁
   插着下载器，隔一会会复位重启，是因为PR2接1K电阻到地。
** 源创杰6919B
   蓝牙MAC地址，有otp工具生成的cfg文件。debug版本复制release版本的文件。
   选择随机地址后，由烧录器自动改写cfg文件。
** 伦茨69对耳
   修改功能，固定右耳为主机，参考灼坤程序编写。
* 20180130
** 6919--串口通信
   频繁的中断，是因为sleep模式导致，进入sleep后引脚状态被改。
   每次接收中断，会有2个中断，一个是接收，一个是超时。
   JL_UART1->CON0 |= BIT(10);///超时中断
   要么设置超时计数，JL_UART1->OTCNT = 0xffffffff;
** AI-69SDK添加自定义命令
   命令定义参考 CBW_CMD_SPEEX_WAIT_OK， 范围在 0xA0 以上没有被使用的值， 
   并要求接收 到 app 的 命 令 不 要 在 bt_smart_rcsp_command_recieve 中 直 接 处 理 ， 
   通 过 发 送 消 息 中 转 到bt_smart_msg_deal 中处理。
   安卓APP修改 mJLBluetoothRcsp.sendCommandToDevice(new byte[]{(byte) 0xa5}, null);
** AI-69添加传统蓝牙判断手机系统
   extern void feedback_manufacturer_handle_register(void (*handle)(char *msg,u8 len));
   void manufacturer_handle(char *msg , u8 len )
   {
       puts(msg);
       putchar('\n');
   }
   在static void bredr_handle_register() 中调用feedback_manufacturer_handle_register(manufacturer_handle);
** 中翔达46在U盘播放下开混响，拔出U盘后混响停止不了
   err = os_sem_pend(echo_sem,0) ;///0改成1，作为超时释放信号量。
   待考量是否正常。是否有隐患。
** 光交锁PCB
   使用Allegro，以 brd 文件结尾

* 20180129
** DAB案子
   开机噗声。加默认上拉mute，延时1.5s开机。
** 6919--串口通信
   PB0-PB1是SPI flash的通信脚。
   UART1，频繁的中断，掺杂很多异常数据。

* 20180126
** DAB案子
   改板，加mOS管mute声音。
** 源创杰6919-ble
   串口通信未整。
** 汉普6902A播提示音
   播提示音会死机。
   函数music_prompt_play()和music_play_api()有冲突，嵌套执行会死机。
** 小树开花WiFi音箱
   低电关机，加入开机计时后，才执行。

* 20180125
** 起华科技69对耳通话音量同步
   华为荣耀6x，打电话不会同步，按音量才会同步，如果最大音，音量+，不会同步。
   华为Nova，如果上次电话音量为0，会同步一个音量0，导致样机音量设为0，再次调节音量，无法再加大声音。
   游总iPhone 7，手机配对连接，就会回调通话音量同步，此时不是通话状态，导致误改了音乐的音量。
   赖工iPhone 6，手机配对，每次打电话不会音量同步，断开回连，每次打电话就会音量同步。
** 小树开花WiFi音箱
   添加WiFi模式休眠
   关机会有pop声，怀疑断电瞬间，mute不受控，功放放电导致。
* 20180124
** 起华科技69对耳
   iPhone 7 连接蓝牙就会回调一次call_vol_change()，导致系统音量被改变。
** 小树开花WiFi音箱
   处理反馈问题
** 实捷
   S33B修改手动播放。
   BT58修改通话下一分钟关闭发射问题。
** 光交锁
   安卓手机枚举USB
* 20180123
** 小树开花WiFi音箱
   蓝牙、music、linein下功放mute功放。

* 20180122
** 起华科技69对耳
   通话的时候，调音量没声音。
   设置音量的时候，不能用FADE_ON，突变设置会没声音。
   开始打电话，要判断VM通话音量，是否为0，会导致没声音。
** 汉普6901A车充
   蓝牙收不到，查不出啥原因。屏幕显示不正常，还没搞定。
** 小树开花wifi音箱
   uart协议增加PAmute控制，供WiFi主控使用，能mute掉开始的爆破音。
   音频播完的掉电，无法mute，需要改板。

* 20180119
** 小树开花WiFi
   增加WiFi模式，增加协议WiFi状态。
** 汉普6901A车充
   支持邓工调试。
* 20180118
** 起华科技对耳
   充电板拔出USB，充电电压会有掉电现象，掉电到4.0V一下，会导致误判充电线拔出。
** ble描述符
   不会生成0x2901
   CHARACTERISTIC_USER_DESCRIPTION, READ,
** ble的notify配置
   notify不能和write_without_response一起配置，会导致notify配置handle时，没有回调产生。
** 小树开花WiFi和蓝牙
   利用“我要长大机器人”公众号，连接WiFi音箱
   还差WiFi——up脚，不让输出串口TX波形。
   创建linein任务。
** 合成语音
   百度语音在线合成
   http://tsn.baidu.com/text2audio?tex=wifi%E6%A8%A1%E5%BC%8F&lan=zh&cuid=f6532074500827f24995f36699b11abc&ctp=1&tok=25.d440799ee39656414071490090cce5ae.315360000.1817018727.282335-9279783
   http://tsn.baidu.com/text2audio?tex=wifi模式&lan=zh&cuid=f6532074500827f24995f36699b11abc&ctp=1&tok=25.d440799ee39656414071490090cce5ae.315360000.1817018727.282335-9279783
   替换tex=的文本即可
   
* 20180117
** 起华科技69对耳
   拔出USB，直充变成升压，会导致LDOIN电压掉电到4.0V以下，软件判断为拔出充电线。
   软件需要做过滤操作。
   检测到掉电后，调低电流档为0档。
   延时检测5V拔出，1秒多，再关机，会导致，开机时间变长。
* 20180116
** 起华科技充电充不满
   电池在3.9V-4.0V之间，电压不会有波动，判断阈值0x7400L
   电池在4.08V-4.10V之间，电压不会有波动，增大判满时间。
** 汉普6902A
   支持邓工调试。

* 20180115
** 起华科技外置充电
   充电IC的charge点灯脚，一接主控脚，就会拉低。
   在2ms中断，不能调用太多PR口的函数，会导致延时过长，超过2ms。
** 彩荣反馈69发射器连接1拖2耳机有哒哒声
   验证发射器105的SDK，连接1拖2的公版程序，播放1KHz的音频，很容易听到哒哒声。
** 汉普6902A
   支持邓工调试。
* 20180112
** 发射器连不上炬力对耳
   连接认证失败。
** 起华科技
   出烧录程序版本。
** 鑫闻达洗刷刷
* 20180111
** 出差充电IC公司
   调试对耳充电和充电板的检测。
   充满之后，降低VBAT的电压档。为0档。
* 20180110
** 天博智4602
   代码区末尾有部分被修改，怀疑是VM操作错误，误修改了。
* 20180109
** wifi加69bt案子开发
** 源创杰修改ble
   帮客户修改ble协议，未改。
** 天博智4602样机开不了机
   之前分析过，无法弹出uboot，烧录器可以重新烧写。
** 起华通信
   69对耳调试，我的手机荣耀6X，通话距离特别短，手机有问题。
   系统频率跑160M，通话数字增益放大，加大mic的声音。
*** 切记不可用新的编译器编译，通话效果有差异
** 天地宏蓝牙能量灯
   闪频太快，get_dac_energy_value()函数只能获取瞬间能量值，需要自己做过滤取平均值。
   否则会造成切换颜色太快。
** 汉普69车充样机
   借客户一个升级工具。
** 源创杰朗琴开EQ功能
   协助卓添
* 20180108
** 串口通信
   460800波特率，在蓝牙下播歌，会丢数据。
   受蓝牙中断影响，导致中断被阻塞。
   9600波特率就不会出现丢数据。
** 中断优先级
   board.c里的irq_index_2_prio_tab数组，定义了优先级0-3。
   3为最高。
   但是底层可能有关中断的操作，导致中断的丢失。
** 起华69对耳
   在太多人和设备的环境下，从机会卡。
   在空旷的地方，通话不行。         
* 20180105
** 对箱闪灯方式
   #+BEGIN_SRC C
	void stereo_led_deal()
	{
	//    printf("get_total_connect_dev:%d\n",get_total_connect_dev());
	#if BT_TWS
	   if(BT_CURRENT_CONN_PHONE==get_bt_current_conn_type())//当前只有手机连接上，对箱没有连接
	   {
		   puts("BT_CURRENT_CONN_PHONE\n");
			if(BT_MUSIC_STATUS_STARTING == a2dp_get_status()){
				puts("BT_MUSIC\n");
				led_fre_set(0xFF,0);
			}
			else if(BT_STATUS_TAKEING_PHONE == get_bt_connect_status()){
				puts("bt_phone\n");
				led_fre_set(0,0);  ///常亮
			}
			else{
				 puts("bt_other\n");
				led_fre_set(30,1);
			}
	   }
	   else if((BT_CURRENT_CONN_STEREO_MASTER==get_bt_current_conn_type()))//||(BT_CURRENT_CONN_STEREO_SALVE==get_bt_current_conn_type()))
	   {  //当主机，只在没有连接手机进
		   puts("BT_CURRENT_CONN_STEREO_MASTER\n");

	//      puts("master\n");
			led_fre_set(30,1);
	   }
	   else if(BT_CURRENT_CONN_STEREO_SALVE==get_bt_current_conn_type())//当从机，任何状态都进
	   {
		   puts("BT_CURRENT_CONN_STEREO_SALVE\n");
			if(BT_MUSIC_STATUS_STARTING == a2dp_get_status()){
				puts("BT_MUSIC\n");
				led_fre_set(0xFF,0);
			}
			else if(BT_STATUS_TAKEING_PHONE == get_bt_connect_status()){
				puts("bt_phone\n");
				led_fre_set(0,0);
			}
			else{
				 puts("bt_other\n");
				led_fre_set(60,0);
			}
	   }
	   else if(BT_CURRENT_CONN_STEREO_MASTER_PHONE==get_bt_current_conn_type())//当主机，先连对箱，再连手机
	   {
		   puts("BT_CURRENT_CONN_STEREO_MASTER_PHONE\n");
			if(BT_MUSIC_STATUS_STARTING == a2dp_get_status()){
				puts("BT_MUSIC\n");
				led_fre_set(0xFF,0);
			}
			else if(BT_STATUS_TAKEING_PHONE == get_bt_connect_status()){
				puts("bt_phone\n");
				led_fre_set(0,0);
			}
			else{
				 puts("bt_other\n");
				led_fre_set(60,0);
			}
	   }
	   else if(BT_CURRENT_CONN_STEREO_PHONE_MASTER==get_bt_current_conn_type())//先连手机，在连对箱，当主机
	   {
		   puts("BT_CURRENT_CONN_STEREO_PHONE_MASTER\n");
			if(BT_MUSIC_STATUS_STARTING == a2dp_get_status()){
				puts("BT_MUSIC\n");
				led_fre_set(0xFF,0);
			}
			else if(BT_STATUS_TAKEING_PHONE == get_bt_connect_status()){
				puts("bt_phone\n");
				led_fre_set(0,0);
			}
			else{
				 puts("bt_other\n");
				led_fre_set(60,0);
			}
	   }
	   else
	   {
		   puts("BT_CURRENT_CONN_else\n");///手机，对箱都没有连接
		   led_fre_set(7,1);
	   }
	#endif
	}
   #+END_SRC
** 汉普6902车充
   协助邓工修改程序。
** 威益德69串口丢数据
   采用波特率460800做通信接口，接收数据会丢失。
   是否支持全双工，待验证。
** 起华科技
   蓝牙功率改为9。
** 联巨兴
   RGB和白灯，要用一个电机的PWM。
** 降低系统时钟
   20M可以，低于20M就不行。
* 20180104
** 美师傅69K歌宝喊话有嘶声
   通过改mic的模拟增益，微调数字增益。
** 变声变调
   pitch_coff(128);//原声模式
   pitch_coff(64);//男声
   pitch_coff(160);//女声
   pitch_coff(200);//童声
   pitch_coff(90);//变音
** 起华科技对耳
   关机红灯亮，替换振荣的cpu_lib_ac690x.a改善通话效果。
** 天罡微spp测试
   一次接收448字节可以，bt_spp_send_data()发送也可以。
** 博益友iPod搜索不到HID设备
   #+BEGIN_SRC C
	 __change_hci_class_type(BD_CLASS_WEARABLE_HEADSET);/*改变蓝牙设备类型，可以改变连接成功显示图标*/
	 extern void __change_hid_class_type(u32 class);
	 __change_hid_class_type(BD_CLASS_WEARABLE_HEADSET);
   extern void __bt_set_hid_independent_flag(u8 flag);
   __bt_set_hid_independent_flag(0);
   #+END_SRC

* 20180103
** 汉普6905B乐放音箱
   修改蓝牙设备图标
** 起华科技对耳
   修改对耳的闪灯方式
** iPod无法搜索到HID设备
   电量图标也无法显示
* 20180102
** IIS文档
   已发出
** 汉普6902A车充底噪
   对比样机360车充，采用的是QN8007发射，底噪会小很多，发射功率弱很多。
** 起华科技69对耳
   客户采用络达的芯片，声音有渐变的过程。
   播歌的时候，灯原本会闪亮，改为灭灯。
* 20171229
** SPP蓝牙串口数据量
   SPP返回数据量，最多一次性500字节。
** 起华通信对耳
   单键触摸IC，TTP233D，TTP233D-HA6，直接高低电平控制。
** 艾玛威69调EQ
   #+BEGIN_SRC C
	///软件EQ模式
	void eq_mode_change(int mode)
	{
		tbool ret;
		switch(mode)
		{
			case 0:
				///标准
				///puts("eq_0\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE,sizeof(eq_dbg_online_t));
				break;
			case 1:
				///摇滚
				///puts("eq_1\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_ROCK,sizeof(eq_dbg_online_t));
				break;
			case 2:
				///puts("eq_2\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_COUNTRY,sizeof(eq_dbg_online_t));
				break;
			case 3:
				///puts("eq_3\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_POP,sizeof(eq_dbg_online_t));
				break;
			case 4:
				///puts("eq_4\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_CLASSIC,sizeof(eq_dbg_online_t));
				break;
			case 5:
				///爵士
				///puts("eq_5\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_JAZZ,sizeof(eq_dbg_online_t));
				break;
			case 6:
				///重低音
				///puts("eq_6\n");
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_LOW,sizeof(eq_dbg_online_t));
				///eq_set_eq_bypass_flag(0);
				break;
		}
		///printf("EQ_Read_ret:%d\n",ret);
		///printf("EQ config file,eq_type:%d\n",eq_dbg_online->eq_type);
		eq_config_api( eq_dbg_online->eq_filt_0 ,
					   eq_dbg_online->eq_filt_1 ,
					   eq_dbg_online->eq_filt_2 ,
					   eq_dbg_online->eq_filt_3 ,
					   eq_dbg_online->eq_filt_4 ,
					   eq_dbg_online->eq_filt_5 ,
					   eq_dbg_online->eq_filt_6 ,
					   eq_dbg_online->eq_filt_7 ,
					   eq_dbg_online->eq_filt_8 ,
					   (int (*)[10])eq_dbg_online->eq_freq_gain ,
					   eq_dbg_online->eq_gain ,
					   !USE_SOFTWARE_EQ);
		soft_eq_set_segment_num(eq_dbg_online->eq_cnt);
		eq_mode_sw(eq_dbg_online->eq_type );
	}
   #+END_SRC
** 众芯达69设置成数字音量
   音量设置成0时，底层貌似会调用dac_mute(1,1);
** 科普豪69的IIS
   音乐模式播放歌曲，音量调大，声音会断断续续。
** 博润威69播提示音滋滋声
   由于dac的隔直电容太大，导致上电时间长，从而影响dac校准。
   通过延长dac上电时间，可以解决这个问题。
   //dac_vcm_rsel_set(0);
   这个函数影响dac上点速度，0为上电慢，1为上电快。默认为快速上电。
   #+BEGIN_SRC C
	void dac_power_on_time(u8 mode) 
	{ 
		if(mode == 2) { 
			puts("dac_off_delay\n"); 
			os_time_dly(15); 
			//delay(0xAFFF*70);//120ms 
		} 
		else if(mode == 1) { 
			puts("dac_power_on quickly\n"); 
			//delay(0xAFFF*70);//120ms 
			os_time_dly(40); //这个值跟进实际调整，经测试目前这个值应该比较合适
		} 
		else { 
			/*如果打开了dac_vcm_rsel_set(0);则需要延长这里的时间，增加250ms即可*/
			puts("dac_power_on slowly\n"); 
			//delay(0xAFFF*300);//600ms 
			os_time_dly(70); 
		} 
	}   
   #+END_SRC
* 20171228
** 瑞荣达BLE培训
   APP端BLE升级，不行。
   蓝牙自组网，不行。
   蓝牙地址滚式递增地址，待确认。
** 汉普乐放音箱
   增加通话功能。
** 众芯达69扩音器
   开ladc，做检测，mic的自动mute，背景音自动调低。

* 20171227
** 科普豪鑫和乐4602插linein死机
   测试不出来，打静电，打地线都死机。
   46死机有3种现象：
   1.不能复位
   2.一直不断复位
   3.复位后正常开机，但是电池电压会被拉到3.3V以下，芯片发烫。

* 20171226
** 博润威6905A做耳机
   在播放提示音的时候，会有滋滋声。
   VCOM用106,就有杂音出现了,换用105,部分芯片有,换用104,会好点。
* 20171225
** 串口代码
   #+BEGIN_SRC C
    __uart_handle *user_uart_handle;
    #define USER_UART        uart2_handle
    #define USER_UART_PORT   UART_TXPA3_RXPA4
    #define USER_UART_NAME   UART2_HARDWARE_NAME
    #define USER_UART_BAUD   115200
    static void user_uart_isr_callback(u8 uto_buf, void *p ,u8 isr_flag)
    {
        putchar('S');
        if(UART_ISR_TYPE_DATA_COME == isr_flag)
        {
            put_u8hex(uto_buf);
        }
    }
    void user_uart_init(void)
    {
        u32 status = 0;
        puts("-----user_uart_init\n");
        user_uart_handle=NULL;
        status=uart_module_open(&USER_UART,USER_UART_NAME);
        if(!status)
        {
           __uart_param uart_param;
           memset(&uart_param,0,sizeof(__uart_param));
           uart_param.baud_rate=USER_UART_BAUD;
           uart_param.io=  USER_UART_PORT;
           uart_param.workmode=UART_WORKMODE_NORMAL;
           uart_param.custom |= (BIT(14)|BIT(3));
           status=uart_module_init(&USER_UART,&uart_param);
           uart_reg_isr_callback_fun(&USER_UART,5,user_uart_isr_callback);
           if(status)
           {
               puts("uart_module_init err\n");
           }
           if(!status)
           {
               status=uart_module_start(&USER_UART);
               if(!status)
                   user_uart_handle=&USER_UART;
           }
        }
    }
    void user_uart_write(char a)
    {
        if(user_uart_handle)
        {
            user_uart_handle->putbyte(user_uart_handle,a);
        }
        else
        {
            puts("user_uart_write err\n");
        }
    }
    void user_uart_write_repeat(u8 *data,u8 len)
    {
        u8 tmp;
        if((len == 0)||(data == NULL)) return;
        for(tmp = 0;tmp < len; tmp++)
        {
            user_uart_write(*(data+tmp));
        }
    }
   #+END_SRC
   接收串口中，调用打印串口，打印数据时，2组串口的波特率不能一样，
   会导致误以为接收数据丢失。
   打印串口的波特率，要大于接收串口的波特率才行，差距越大越好。

** DAB案子 
   串口接收没有判断数组越界，存在死机风险。

* 20171222
** 源创杰扩音器开关mic
   void microphone_open(u8 mic_gain,u8 mic_gx2);
   void microphone_close(void);
** 实捷BT66-8027
   改用linein音量21级。
** 威益德客户处理问题
   USB串口中断，软件要选择成ASCII发送。
   通话关闭mic声音，通过清空ladc的buff。

* 20171221
** 爱瑞声6905A卡掉线死机
   卡掉线，是layout拉线太长，导致波形不稳定，卡座CLK脚加10K上拉。
   卡上下曲死机，替换志彬cpu_lib_ac690x.a库，解决切模式链表没有清干净。
** 实捷BT66
   替换蓝牙库，空间超了，修改图片资源文件。
   替换VM补丁库，蓝牙会死机，未替换，用回原先的。
   linein失真杂音，未处理，25级。
   #+BEGIN_SRC C
   降音量做法。
            case MSG_SET_LOW36V_MAXVOICE:
                puts("MSG_SET_LOW36V_MAXVOICE\n");
                set_max_analog_vol(MAX_SYS_VOL_L-2,MAX_SYS_VOL_R-2);
                printf("maxl=%0d\n",dac_var.max_analog_vol_l);
                set_sys_vol(dac_var.cur_sys_vol_l, dac_var.cur_sys_vol_r, FADE_OFF);
                break;
            case MSG_SET_HIGH36V_MAXVOICE:
                puts("MSG_SET_HIGH36V_MAXVOICE\n");
                set_max_analog_vol(MAX_SYS_VOL_L,MAX_SYS_VOL_R);
                printf("maxl=%0d\n",dac_var.max_analog_vol_l);
                set_sys_vol(dac_var.cur_sys_vol_l, dac_var.cur_sys_vol_r, FADE_OFF);
                break;
   #+END_SRC
** 汉普6905A样机
   功能修改，培训客户邓工，客户要用新板。
** 鑫闻达69闹钟不醒
   闹钟设置后，不唤醒，复位后才行。
* 20171220
** 爱瑞声6905A插卡死机
   卡为FAT16，格式化之后就可以。
   卡掉线，波形不正常，待查。
** 科普豪U盘挂载失败
   69下正常，46下等待30s后，挂载失败，查不出打印。寄给钧仟。
* 20171219
** 汉普6902A音箱
   测试功能正常，寄给客户了。
** 实捷BT66-8027添加RDS个Siri
   参考灼坤程序，修改，数据为小端。
   替换蓝牙库，可以用。
** 科普豪4602耳机插拔linein死机
   静电原因，软件无法处理。
* 20171218
** 实捷BT66-8027添加RDS和siri
   添加好了，等机子测试，还要加Siri界面。
* 20171215
** 汉普6905A音箱
   出了一个版本给客户测试。
** 华炬芯6905D插充电线唤醒不了
   #+BEGIN_SRC C
   void set_poweroff_wakeup_io()
   {
	     u8 wakeup_io_en = 0;
	     u8 wakeup_edge = 0;
       wakeup_io_en |=  WAKE_UP_PR2;
       wakeup_edge |= EDGE_PR2;     //failling edge
	     soft_poweroff_wakeup_io(wakeup_io_en , wakeup_edge);      
	     charge_mode_detect_ctl(1);///此句会影响到睡眠后，插充电线，唤醒不了
   }
   #+END_SRC
* 20171214
** 汉普6905A音箱
   调试一半
** FCC测试
   V2012-p3版本，BLE测试，频点会偏移2M。替换志彬的库，测试OK。
   公版的FCC，发射功率会小于-6dB，不符合标准，用起华的下载包，能达到接近0dB。
** 汉普乐放音箱
   include_lib文件夹，头文件被改了。
   修改程序，添加BLE特征，用作授权认证。

* 20171213
** 汉普6905A音箱
   鑫凌波--博建--开发。
** 嘉兴格优6901对箱
   第一次开机，配对不上从机。
   改成一定进入配对状态，不能发起回连命令，会导致搜索不到设备。
** 汉普语音识别BLE唤醒APP
   添加语音识别。
** 汉普6905音箱
   添加UUID属性。
* 20171212
** 鑫闻达洗涮涮
   调试摇动灵敏度，
   牙刷摆放，没有固定位置，无法确定固定坐标系。
** 巴达木PC麦
   1.音量值16位，要调整大小端位置，发下来是0x15cf,上传改为mic_vol = 0xcf15;
   2.对局部变量取值，VM的函数，取值一定要是全局变量。

* 20171211
** 尚凌69对箱音质问题
   量DAC输出频响，幅值dB，会有变化。

* 20171208
** 尚凌69对箱
   做全功能蓝牙对箱音箱，第一次连接对箱播歌正常，切模式回连后，音质就会变。
   原本充实变得散了。
** 源创杰ble地址获取错误
   原因是蓝牙配置工具，ble的地址分配配成了random，
   应该用public，这时ble的地址参考EDR地址，才能用程序获取并打印出来。
* 20171207
** 测试盒更新音频文件
   测试盒更新音频文件,wav,32K,16bits,单声道。
** 调节数字音量
   #+BEGIN_SRC C
   #define BT_CHANNEL         DAC_DIGITAL_DVOL///DAC_DIGITAL_AVOL
    void custom_digital_vol_tab(u8 flags)
    {
        u8 i = 0;
        if(flags == 1){
            for( i = 0; i <= DIGITAL_VOL_MAX_L; i++){
                digital_vol_tab_dynamic[i] = digital_vol_tab[i];
            }
    //        memcpy(digital_vol_tab_dynamic, digital_vol_tab, DIGITAL_VOL_MAX_L+1);
        }else{
            for( i = 0; i <= DIGITAL_VOL_MAX_L; i++){
                digital_vol_tab_dynamic[i] = digital_vol_tab[i] * 3;
                ///最大4倍，用5倍时，31级的值会溢出，变为0///
            }
    //        digital_vol_tab_dynamic[30] = 46384;
        }
        for( i = 0; i <= DIGITAL_VOL_MAX_L; i++ ){
            printf("digital_vol_tab_dynamic[%d]:  ",i);
            put_u16hex(digital_vol_tab_dynamic[i]);
            puts("\n");
        }
    }
//    reg_digital_vol_tab((void *)digital_vol_tab);
    reg_digital_vol_tab((void *)digital_vol_tab_dynamic);
   #+END_SRC
* 20171206
** 汉普6902A
   如果定义函数和底层库函数重名，会导致覆盖库里的函数，调用成应用层的函数。
   crc16();底层就有一个。
** 测试盒没有NFC功能
   硬件环境有留，软件没有做。
** APP
   V2.0之后，安卓APP走的是BLE通道，之前走的是SPP通道。
** 海科通话
   蓝牙通话的声音，在30级的时候，还是偏小。
   改用数字音量表
* 20171205
** 威益德获取电话本
   使能pin code之后，配对连接获取不到，回连可以。
   铜霭，改了一个库。
* 20171204
  请假
* 20171201
** 汉普6902
   修板3块
* 20171130
** 汉普6902A车充
   发射芯片没焊好。
** DAB
   蓝牙发射，切换同一个通道，会有POP声，需要添加延时，清空LADC数据。
* 20171129
** 汉普6902A车充
   添加BLE电话功能，17字节校验码存储功能
* 20171128
** wifi--iis输入
   #+BEGIN_SRC C
   dac_channel_on(MUSIC_CHANNEL, FADE_ON);
	 audio_link_init();
	 //audio_link_close(1);
	 dac_set_samplerate(44100,1);
    #if 1
        dac_write((u8 *)buf_addr0,DAC_BUF_LEN);
    #else
        extern int soft_eq_run(u8 *buf, u32 len);
        soft_eq_run((u8 *)buf_addr0, DAC_BUF_LEN);
		    cbuf_write_dac((short*)buf_addr0, DAC_BUF_LEN); //DAC 实时播放
    #endif
    #+END_SRC
* 20171127
** DAB案子
   切模式会串音，是因为自动解mute，ST程序不会一直发送mute导致。
* 20171124
** DAB
   切模式串音问题，BT播放模式，切换一圈后进入FM/DAB，蓝牙播放音乐串音到FM/DAB
** 汉普6902A车充

* 20171123
** DAB
   dac_AmuxGain_en(1);放大linein声音一倍。
   linein声音输入源幅度太小，可设置此项。只能固定放大一倍。
* 20171122
* 20171121
** 汉普车充
   SD和IIC复用，在SD播放高码率的文件，会有掉线情况，此时要限制发送消息的数量。
   避免一下子发送太多，累积在消息池中。
* 20171120
** 汉普车充
   6902A的SD和iic复用，当在sd播放的时候，操作iic时，要等待sd空闲后，才能关闭sd控制器，才操作iic。
* 20171117
** 汉普车充
   12V检测，最多只能做到0.1V的精度。
* 20171116
** BLE发送数据量
   static u32 app_data_send(u8 *data,u16 len)
   底层会有2K的空间，进行分包发送，每包20字节。
   但是不建议使用太大数据量。
   发送速度，跟时间间隔有关。
* 20171115
** 汉普车充
   在调频点的时候，暂停音乐播放。
* 20171114
** 汉普车充
   SD卡和IIC复用，待处理。
** 发射器SDK
   C版晶圆需要打补丁，才能支持无线升级。
* 20171113
** 实捷C26S发射没声音
   QN8027有一分钟自动关闭发射的功能，在初始化的时候会有关闭此功能。
   但是由于I2C同时外挂QN8027和AD2523，发送给QN8027的数据存在AD2523的命令字时，
   data会被AD2523控制到，导致发送给QN8027的数据出错，写错寄存器。
* 20171108
** DAB案子
   切换linein通道，会有上一个通道的尾音，可能底层有个buf没有清除。
   目前改成，在切换通道先发一段静音的buf。
   #+BEGIN_SRC C
   void ladc_isr_callback(void *ladc_buf,u32 buf_flag,u32 buf_len)
   {
      extern u8 switch_aux_channel_flag ;
      if(switch_aux_channel_flag)
      {
        putchar('l');
        for(i=0;i<DAC_SAMPLE_POINT;i++)
        {
            ladc_l[i] = 0;
            ladc_r[i] = 0;
        }
      }
   }
   #+END_SRC
** 威益德死机
   __attribute__((aligned(4)));
   强制地址对齐，方便底层指针转换。

* 20171107
** 伦茨海科46点烟器通话调试
   46配8007，在通话双方同时说话的时候，回声压制不住，会有漏音，听起来有点卡顿的感觉。
   通话回声参数，配3和1400，效果OK
   有一个手机，远端能听到回声尾音，其他手机就没事，此问题客户忽略处理。
* 20171106
** DAB案子
   IIS接收还是不行。
* 20171103
** 汉普音箱
   测试MIX2910功放，3.3V直流偏置正常，没有掉电情况。
** USB-HID
   #+BEGIN_SRC C
   typedef enum
   {
 	     DEVICE_DESCRIPTOR_STR = 0x0,
 	     CONFIG_DESCRIPTOR_STR,
 	     MSD_CONFIG_DESCRIPTOR ,
 	     AUDIO_CONFIG_DESCRIPTOR,
       SPEAKER_CONFIG_DESCRIPTOR,
       MIC_CONFIG_DESCRIPTOR,
 	     HID_CONFIG_DESCRIPTOR,
 	     HID_REPORT_DESCRIPTOR,
 	     LANGUAGE_STRING,
 	     IMANUFACTURE_STRING,
 	     IPRODUCT_STRING,
       ISERIAL_NUMBER_STRING,
 	     AUDIO_VOL,
 	     MIC_VOL,
       MAX_STRING = 14,
   }USB_DES;
   u32 user_set_descriptor(USB_DES index, void * pstring, u32 len);
   ///默认HID按键是调用以下函数：
   {
       os_mutex_pend(&mass_mutex, 0);
       usb_hid_control((u32)*((u32 *)parm));
       os_mutex_post(&mass_mutex);
   } 
   ///函数体是：
   void usb_hid_control(u32 key)
   {
       usb_hid_key(key);//默认发送2byte 码值
       usb_hid_key(0);
   }
   结构体声明：
   extern OS_MUTEX mass_mutex AT(.usb_buf);
   #+END_SRC

* 20171102
** ARGUN
   协议有改动，更改程序，已发出
** 汉普音箱
   触摸按键增加电话控制功能，电量获取换算成百分比，触摸按键灵敏度调到300。
* 20171101
** 汉普音箱
   MIX2909功放会有噗噗声，是在IN脚，维持3.3V的时候，会有1V左右的掉电，后又升回3.3V导致。
   功放产商寄2910的芯片来测试。
* 20171031
** DAB发射器
   出差实捷，调试功能，基本功能都有了，细节问题处理还未解决。
*** 切换模式会有噗声
    切换到DAB模式，会有3声噗声，切换到FM模式，也会有噗声，需要软件处理mute掉。
*** 蓝牙发射突然没有声音，只能重启
    概率很低，很难测试到，其他操作都正常，切换通道都不行。
*** 46的机子回连时，link-key会丢失，导致回连不上
    目前做法是，开机的回连，做成5次。但是会导致进入搜索设备变慢。

* 20171030
** ARGUN
   区分配对状态和连接状态的广播包，修改蓝牙名和MAC地址。
   摇杆数据，没反应，客户更新APP，已OK。
   函数app_data_send()涉及信号量，在没有连接的情况下，会导致调用该函数的线程挂起。
** DAB蓝牙发射器
   选取设备列表，断开重连等功能，还没调试。
* 20171027
** ARGUN
   connect_interval的单位是1.25ms，如果发送太快，可能会导致底层积压数据包，等到间隔时间到了，才一起发送出去。
   adv_interval的单位是0.625ms，
** 汉普BLE音箱
   替换蓝牙库bluetooth_lib.a，不会死机，但是回连不上，手机主动连接，会卡死，取消连接，重新连，能正常。
   替换以前对箱的库cpu_lib_ac690x.a，解决回连不上问题。
* 20171025
** 汉普BLE音箱
*** 汉普音箱在EDR和BLE同时连上后切模式回到蓝牙模式死机
   在初始化蓝牙后，发送蓝牙回连命令死机。
*** 触摸误触
    提高触摸按下门槛，避免干扰。
* 20171024
** 实捷DAB案子
*** 蓝牙再次搜索异常
    __set_inquiry_again_flag(0);///此函数底层没做好，只能置0
    在应用层自己添加，BT_STATUS_INQUIRY_COMPLETE，反馈时，再次搜索就行。
    #+BEGIN_SRC
    case BT_STATUS_INQUIRY_COMPLETE:
		   puts("BT_STATUS_INQUIRY_COMPLETE\n");
		   /*search bluetooth device again*/
       if(BT_STATUS_WAITINT_CONN == get_bt_connect_status()){
          puts("BT_STATUS_WAITINT_CONN\n");
          user_send_cmd_prepare(USER_CTRL_SEARCH_DEVICE,0,NULL);
       } 
		break;
    #+END_SRC
** 汉普车充
*** 在14V供电的情况下打电话时死机
    应该是LDO降压模块，压差太大，从14V降到5V，导致不稳定。
* 20171023
** 实捷DAB案子
*** 蓝牙搜索连接link-key丢失
    第一次连接上后，再次搜索配对连接时，就会出现，重新下载程序，也不行。
    更新振荣发的bluetooth_lib.a，可解决。
** 汉普ble音箱
*** 触摸按键和AD按键分开检测发送
    触摸按键，时不时会反馈，导致AD按键检测不准。
** 飞灵特ARGUN
   更新product-key，生成时用，可用于发行版APP
   #+BEGIN_SRC
   NAME  ：ARGunPro
   VID   ：0xFFFC
   KEY   : 0x3e, 0x9b, 0x7d, 0xb9, 0xbe, 0x69, 0xc2, 0xa5, 0x7c, 0x6c, 0x18, 0x34, 0xb, 0xd9, 0xdf, 0xfe
   MAC   ：FF:FF:00:00:00:01~FF:FF:00:00:00:FF
   #+END_SRC
* 20171020
** 汉普ble音箱
*** 苹果搜索ble名字显示unknown
    由于广播包的数据，不正常导致。
** 实捷DAB案子
*** IIS通信声音不正常
    参考：极性CPOL和相位CPHA，修改IIS的设置。
* 20171019
** 实捷DAB案子
*** IIS通信声音变调
    由于缺失MSCK，DAB自己外挂晶振，和主控自己产生的MSCK，会有相位差，导致声音不同步。
    DAB芯片改用，从主控24M引线，还是不行。

* 20171018
** 实捷DAB案子
*** IIS从机接收不正常
    69系列IIS做从机，必须输出SCLK、LRSCK时钟给其他芯片，不支持输入时钟，
    可理解为只能主动接收数据，不支持被动接收数据。
** 德科创ble部分手机会掉线
   苹果的5、5s、6、6p、红米1s、oppo r11，在连接了2.1后，ble的4.2连接会容易掉线。

* 20171017
** 汉普触摸音箱
   焊点引线到外壳，需要贴块铜皮，增大电容效应的面积，增强抗干扰能力。
** 实捷DAB蓝牙发射
*** 发射伴随哒哒声
    由于串口发送数据太多太过集中，while循环时间过长，导致发射数据卡顿。
*** 蓝牙搜索时获取蓝牙名包出错
    有些方案，在搜索的时候，未连接时，获取的蓝牙名包不正常，振荣处理中。
*** IIS输出板子又有模拟输出
* 20171016
** 实捷DAB蓝牙发射配其他方案音箱会有哒哒声
   寄给振荣分析
*** IIS通信的时钟输出
    目前为stm32输出。可能主控这边不能匹配。16bits数据。
** 汉普6905B蓝牙音箱带触摸
   触摸的引线，经过喇叭和电池，灵敏度会受到影响。
   按键有一个焊盘，应该悬空，但是接地，要改板
   原理图用成6905A的引脚图，DACR对应PA1。
   512K的空间不够，可以修改提示音为单声道，提醒客户后期语音，不能太长。
* 20171014
** 中翔达69蓝牙耳机通话效果
   靓颖电子4款蓝牙耳机通话效果，和建荣的对比。
   比较注重清晰度，音色比建荣较差。
* 20171013
** 汇杰芯蓝牙对箱连接问题
   未连接时，要一直处于能背搜索的状态。
   在匹配过蓝牙对箱后，函数get_total_connect_dev()会一直返回1，导致蓝牙不能被搜索到，
   可改成判断get_bt_connect_status()的蓝牙状态。
* 20171012
** 汉普车充6905C
   在app_server_read_callback()中，会调用2次，第一次调用buffer = 0，buffer_size = 0，要返回buffer_size的大小。
   第二次调用会以上次的buffer_size，填充buffer的内容。
** 狂热者APP开发
   带时钟、闹钟功能的APP。我们提供数据对接，APP开发由客户处理。
   使用TI BLE USB Dongle协议分析抓包，配合电脑端SmartRF Packet Sniffer进行显示。

* 20171011
** 飞灵特6909B用3.3V推灯
   主控3.3V驱动能力较弱，接三极管推灯，可能会影响到电源。
** 汉普车充6905C
   采用新的BLE协议，带频点的设置和读取，电量检测等功能。
* 20171010
** 晶科USB描述符
   区分读卡器名称和声卡名称
   属性--总线已报告设备描述--值
   如果之前识别过，需要先把br17卸载掉，再重启电脑，才就能重新挂载，显示出字符串来。
** 汉普车充
   采用AC6905C + QN8027,带BLE协议。
   耳机检测，电阻改用0R。
** 中翔达i7-6904C对耳蓝牙距离短
   充电座的电线会穿过蓝牙天线，需要用胶纸，将电线紧贴在板子上。
   贴纸刚好盖住蓝牙天线上，不要贴在元件上面。
* 20171009
** 晶科多国语言
   69系列添加多国语言，日语、繁体都可以。
   但是西班牙、阿拉伯的，不行，初始化成功，但是屏幕啥都没显示。
   替换国炜发的font_lib.a，已解决。
   英语之后的语言，采用的都是Unicode小端编码。
* 20170930
** 飞灵特ARGUN
   调试OK
** 飞灵特SuperAR
   增加反馈机制
* 20170929
** 飞灵特ARGUN
   BLE发送是异步操作的，加了个队列发送，上一个发送成功才发送下一个。
   摇杆数据采用AD检测，数据不知道如何组织，发送给APP。
   取值0到0xff，摇杆没动的时候，发的是0x7f。
   采用IO上拉电阻10k,误差比较大。
* 20170928
** 实捷DAB的IIS从机接收
   客户stm32还没有做好，无法调试
** 公司编译器处理中文
   根据.c文件的编码格式，会以文件的编码格式，填充数组。
   可新建文件，保存为Unicode编码，再定义中文数组，就会以Unicode填充该数组。
* 20170927
** 飞灵特ARGUN
   ARGUN协议，没有按照蓝牙标准，发送enable notify给从机，导致我们底层notify通道没有打开。
   而客户用telink主控，支持这样的操作。
*** descriptors
    CHARACTERISTIC_USER_DESCRIPTION, READ,

    CHARACTERISTIC_USER_DESCRIPTION     -->0x2901
    CLIENT_CHARACTERISTIC_CONFIGURATION -->0x2902
    SERVER_CHARACTERISTIC_CONFIGURATION -->0x2903

* 20170926
** 下载工具无法升级
   下载工具需要5V供电，笔记本电压可能达不到5V。
   下载工具挂一个大电容，电阻改大2.7R，可防止板子扯到电源。
** 实捷DAB案子
*** IIS从机输入
** 飞灵特ARGUN
   无法获取notify的句柄，无法发送数据
* 20170925
** BLE读回调执行2次
   app_server_read_callback()调用2次是需要的，
   第一次需要返回正确的长度回去，
   第二次判断buffer指针是否为空，不为空才给buffer赋值。
** 动态修改pin码和蓝牙名
   #+BEGIN_SRC c
   static void bredr_name_custom_handle(char *name)
   {
	     printf("bredr name:%s, len:%d\n",name,strlen(name));
   
       name[0] = 'X';
       name[1] = 'I';
       name[2] = 'N';
       name[3] = '\0';
       __set_pin_code("3693");
   }
   #+END_SRC
** APP发起连接蓝牙2.1 
   用了一个反射的方法实现。
   这个方法在国外的贴子上找到的，可以让客户先上网找一找。
** 69_V2012_p2版本SDK对箱连接
*** 开机自动连接从机
    void bt_discon_complete_handle(u8 *addr , int reason)
    ----reason == 0x04
        ----user_send_cmd_prepare(USER_CTRL_START_CONNEC_VIA_ADDR_STEREO,0,NULL);注释此句，即可不自动连接
*** 概率性连接不了从机
    每隔12秒，发送MSG_BT_STEREO_SEARCH_DEVICE消息，即可。
    搜索时间最长为12秒。

* 20170922
** 飞灵特ARGUN
   AES128 ECB加解密，替换br16_ccm_aes.a，添加aes_ecb_encrypt.c文件。
* 20170921
** 汉普乐放音箱ble协议
   ble协议已调通，音箱功能未确认
** 实捷DAB案子BT_ES
   和stm32采用串口1通信，定义了一个通信的简化版本。
   收音还是没有声音。
** 飞灵特ARGUN
   手动修改profile_data[]，每行第一字节为长度，
   如果需要value，可以在行尾自己加十六进制值，同时修改每行第一个字节为相应长度。

* 20170920
** 汉普乐放音箱ble协议
   ble通信调通。
*** 函数app_server_read_callback() 
   每次获取会执行2次，
   第一次buffer_size为0，实际没有发送数据，
   第二次buffer_size为上一次return的值，实际发送数据
** 实捷DAB案子BT_ES
*** SPI2中断号 #define IRQ_SPI2_IDX       44
    没有SPI通信，实际用串口通信
    收音还是没声音

* 20170919
** 汉普乐放音箱Gatt协议
   定义好协议，抓了profile截图给客户
** 实捷DAB案子BT_ES
   采用STM32+SI4684+AC6901A做蓝牙发射器带DAB数字广播
   调通2个linein通道的发射，蓝牙连接功能
   linein蓝牙发射，如果一个通道没声音，会导致发射完全没声音
   板子收音有问题

* 20170918
** 对箱连接手机播歌后无法配对从机
   V2012-p2版本，有此问题
   替换铜霭发的cpu_lib_ac690x.a，可解决
** 汉普酷走车机BLE音箱
   不能按照小精灵的协议开发
   要重新设计新的协议，待验证
** 对耳蓝牙距离短
   减低sbc的码率，可适当提高
** 内置充电IC充不满
   替换库文件，替换charge.c文件
* 20170916
** IIS播第一个提示音噗一声
   由于IIS传输，需要变采样，变采样的开始阶段，buf数据异常。
   IIS默认44.1kHZ
** 酷走车机BLE
   软件不认我们的设备，连接不上
* 20170915
** 源创杰69对象配对
   v2012-p2版本，连接播歌后，无法再配对从机，需要切换模式才行
   v2011版本无此bug
* 20170914
** 汉普--酷走车机--BLE控制
** 菲林特ARGUN
*** 启赋superAR
*** 先智ARGUN
* 20170913
** 永胜泰6904耳机蓝牙断开，灯状态没改变
   调整设置灯的函数，在每个消息的后面，立马执行。
   可能由于任务切换、中断，导致执行丢失。
** 鑫闻达6905机子linein检测不到
   不同芯片VDDIO在3.3V-3.6V之间，一致性不到。
   LDO_ref的电压永远为1.24V左右，而VDDIO电压为，AD满值，即0x3FF
   可通过判断 LDO_ref 的值大小，即可推出VDDIO电压大小。
   VDDIO为3.3V，LDO_ref为0x178左右。
   VDDIO为3.6V，LDO_ref为0x160左右。
   AD复用linein检测时，最好对LDO_ref分4个区间判断。
* 20170912
** 天地宏69系列RGB灯影响红外
   RGB灯用2ms频率pwm波，推动红灯时，会影响到红外接收。

* 20170911
** 晶科46系列PB9在开机时有数个脉冲
    打VM提示音补丁，可以解决。
** 伦茨耳机开机灯不亮
   采用outputchannel0，没有设置DIE寄存器，默认值有时会不一致导致。
** 晶科69获取文件夹数目
   尝试使用循环下个文件夹，累计文件夹数目。
*** 当前文件夹的序号
    ../../tff.h
    ((*(FIL *)((_FIL_HDL *)(music_operate_mapi->fop_api->cur_lgdev_info->lg_hdl->file_hdl))->hdl).fs_msg.musicdir_counter)

* 20170908
** 输出PLL-12M时钟
    JL_IOMAP->CON1 &= ~(BIT(10)|BIT(9)|BIT(8));
    JL_IOMAP->CON1 |=  (BIT(10)|BIT(9));
	  JL_PORTB->DIR &= ~BIT(0);
	  JL_PORTB->PD  |=  BIT(0);
	  JL_PORTB->PU  |=  BIT(0);
	  JL_PORTB->DIE &= ~BIT(0);
** 动态修改蓝牙名
   static void bredr_name_custom_handle(char *name)
   {
	     printf("bredr name:%s, len:%d\n",name,strlen(name));
       name[0] = 'X';
       name[1] = 'I';
       name[2] = 'N';
       name[3] = '\0';
   } 
** 菲林特AR枪协议
*** 协议1：super AR

*** 协议2：AR GUN

* 20170907
** 科普豪6905C
   U盘和SD卡复用，有部分卡不读，容易掉线
*** 优化方法
    检测前开SD-CLK脚 ~下拉~,修改速率为4(原先为5)。
    硬件上 ~复用脚加对地30p~,CLK脚对地10p，均可。
*** 客户采用复用脚加33p电容对地

* 20170906
** 汉欣诺电话本死机
*** 替换铜霭更新的bluetooth_lib.a，测试已OK
** 巴达木EQ调试没效果
   uart_init(UART_BAUD_RAE);不能在audio_init();之后调用，会导致无法中断接收。

* 20170905
** 汉欣诺
*** 获取电话本出现死机和乱码
    只要改动user_ctrl_prompt_tone_play()就会出现，铜霭处理中

* 20170904
** 内置充电IC外挂大容量电池
*** 改精度，调阈值，不起作用
    #define BUILD_POINT_THRESHOLD_VALUE   2
    #define CHARGE_MAX_CNT                110 * 60 * 2
*** 改用充满计数，计数5次以上，才认为充满
    可能电池充电，电压上升不线性导致
    对charge_full_deal();函数的执行，进行计数5次以上，才能执行
** 汉欣诺6901车机
*** 蓝牙获取电话本出现死机和乱码

* 20170831
** 笔记本电脑win8win10蓝牙连不上
** 洗刷刷LSM6DS3驱动
*** 静止时的数据，和样机基本一样
*** 摇动的数据，难对比

* 20170830
** 爱瑞声6907C内置充电外挂大容量电池
软件按固定间隔检测电压变化，大容量电池的电压变化很慢，调整电压检测分辨率
** 蓝牙电感料，会影响到sniff的功耗

* 20170829
** 华炬芯6904A耳机
*** 进power down死机问题
    PR1做充电唤醒，PR2做按键唤醒，同时开2个唤醒脚，
    会导致有些芯片出现进power down死机
*** 开机吱声
    振荣修改cpu_lib_ac690x.a解决
*** TODO low_pwr_deal函数在蓝牙没连接时会执行
- State "TODO"       from ""           [2017-08-30 周三 18:54]
但是公版SDK测试，不会执行到

* 20170828
** 华炬芯6904耳机死机、开机吱声
*** 死机是因为 *BT_LOW_POWER_MODE* 模式引起
*** 开机吱声，开机初始化 *dac_init_api* 的电源时引起


* 20170817
** 联巨兴：人声消除，导致低音消失

* 20170818
** 鑫闻达：QN8035收音效果差，功放D类影响，晶振引时钟15p
** 科普豪：1621推屏，模拟SPI，时序延时要加大
** TODO TODO：
- State "TODO"       from ""           [2017-08-19 周六 11:03]
联巨兴：人声消除效果确认？
电影协会
宿舍安排

* 20170819
** TODO 人声消除低音处理
- State "TODO"       from ""           [2017-08-19 周六 11:02]
低音炮内部电路 始终要把双声道输入耦合成单声道的 那样立体感才强
可尝试加入EQ处理生成2.1声道
** 天博智4602按键不起作用
机子用一段时间后，机子开不了机，USB无法识别。
用烧写器重烧后，正常工作。
待查软件问题

* 20170821
** 鑫闻达BLE洗刷刷项目
使用DA380三轴加速度传感器，跟视频的停车守卫采用一样。
搭建DA380的驱动代码
** 华立S36
修改呼吸灯的控制

* 20170822
** 人声消除低音消失
寄机子给影志,山景的机子需要修板
** 鑫闻达BLE洗刷刷项目
抓包，调试BLE连接，BLE连接成功

* 20170823
** 鑫闻达数据包发送
原本使用ST的LSM6DS3芯片，陀螺仪和加速度一体
DA380缺失陀螺仪数据，目前填包处理

* 20170824
** 联巨兴人声消除
板子修好，寄给影志，处理低音效果
** 鑫闻达洗刷刷
调试DA380的采样频率，量程，发送数据的大小，优化效果
6909的板子，已修好

* 20170825
** 鑫闻达洗刷刷
准备2款传感器，ST的LSM6DS3和invensense的MPU6050
调试功耗，和蓝牙名与蓝牙地址处理
*** 功耗注意点
1.系统48MHz
2.DAC关
3.Bredr关，只开BLE
4.FM关
5.DA380设置为低功耗模式
6.电源DCDC模式
7.自动关机处理
8.推灯亮度处理
*** 升级问题
无线升级没有做好
*** 4.2的sleep模式
还没有做好
*** 低压flash
用纽扣电池供电，需认批次，选用低压flash，才能正常

