#+TITLE:       JL work diary record
#+AUTHOR:      辛佳斌(lawrence)
#+DATE:        [2017-02-13 周一 16:31]
#+EMAIL:       lawrencejiabin@163.com
#+KEYWORDS:    the page keywords, e.g. for the XHTML meta tag
#+LANGUAGE:    language for HTML, e.g. ‘en’ (org-export-default-language)
#+TODO:        TODO

#+SEQ_TODO: TODO(T!) | DONE(D@)3  CANCELED(C@/!)  
#+SEQ_TODO: REPORT(r) BUG(b) KNOWNCAUSE(k) | FIXED(f)
   #+BEGIN_SRC c
   #+END_SRC


* 20200602
** 起华6936D
   带光感的板子，有部分机子，无法开盖开机，处理中
   起华下面方案商培训
** 易路发6303
   自拍遥控器，抓包，发的是音量加的命令

* 20200601
** 631X
   启动电压要用烧录器烧录，LVD用1.85V档位
   要不然要2.8V才能启动
   LDO的功耗，只能做到250uA级别
   DCDC才能改到60uA级别
** 起华6936D
   2款机子，功能功能修改，已发出
** 羽恒695X
   006的SDKBLE功能开发，改了个demo给客户
** 德科创6318
   功耗问题，hid的工程较低，透传的工程很高，还在查找中
* 20200530
** 请假1天
* 20200529
** 德科创6318
   功耗问题，需要珠海协助，处理中
** 汉欣诺695X
   电话本问题，已ok，普通hid是可以的，hid触摸问题，还在支持中，
** 西米697X
   讯飞AI，opus编码复位，需要珠海处理
** 华巨芯693X
   双模的SDK，几个问题，还没看
** 起华6936D
   A3功能修改，还没改
** 伦茨6936D
   mic频响曲线，067加了限幅器，改库可以，天使改
   DAC等响度等问题，自动mute有问题，少文改
* 20200528
** 威益德690X
   字符串转UTF编码，分包串口发送，客户测试可以
** 德科创6318
   广播工作低功耗只能到700uA，6303A却正常，让客户寄板子过来
** 汉欣诺695X
   006的SDk多个问题，还没看
* 20200527
** 动态传profile数据
   void att_set_db(uint8_t const *db);//change profile_data
   也可直接修改profile的数据,重新连接会自动更新
** 起华6936D
   2款功能修改，已发一款，还有一款还没改
** 西米6972A
   科大讯飞AI耳机，功能调试，支持中
** 德科创、汇杰芯
   63的案子  支持开发中
** 汉欣诺695X
   在电话本回调函数，调用串口，会导致电话本中断，和发送数据不对，试了几个改法，客户都说不行，还没空看
* 20200526
** 出差恒大一天
   处理6926A低温-20°C下BLE丢包断连问题，现场未复现
   留了2套方案给客户测试，
   一个改软件提高内核电压，晶振强驱
   二是改硬件，改用外部电容
** 德科创、汇杰芯
   6303A  工作低功耗的改法
   USB有2组口，要设置成高阻态，要不然漏电400uA
** 爱尚6318
   瞬态电流大，珠海改库后
   6303A跑LDO第一次上电52mA，第二次上电14mA
* 20200525
** 爱尚6318
   瞬态电流大，刚开始说DCDC可以，改成LDO又说不行了，还没测
** 德科创6303
   动态修改profile，连接参数等，还空搞，让客户自己先试
** 汇杰芯6956
   提示音后sbc卡音，更新SDK019可以解决
** 伦茨6936D
   充电一直没充满，6959灵敏度差，dac左右不平衡，通话杂音等，还没处理
   充满电流截止电流5mA，有3%机子永远无法充满
* 20200523
** 盛鑫源6903A
   sniff断言失败，改了一个流程给客户，未反馈
** 德科创6303A
   动态修改广播间隔参数，异常中断，解决
** 爱尚6318
   瞬态功耗高，测试数据跟珠海一致，目前只能到21mA，达不到客户需求
* 20200522
** 锦芯6936D
   没有放关机提示音,导致没有提示音结束的消息，导致没有实际关机，把机子耗没电
** 摩天6936D
   关机流程：先提示音结束，灯才灭，等按键松手，再关机
* 20200521
** 630X
   硬件复位,PB2有个短按即复位的功能
    //< close short key reset
    p33_and_1byte(P3_PR_PWR, ~BIT(3));
    //< close long key reset
    p33_and_1byte(P3_PINR_CON, 0);
** 盛鑫源6303A
   sniff和串口通信，冲突死机，给了一个方法给客户，客户还没测试
** 爱尚6318
   瞬态电流大，秉铨改了几个库，测试都不行
** 尚凌692X
   录音大容量U盘有问题，测试到2个问题，得珠海协助
** 联巨兴690X
   linein录音丢音，测试1K测试不到，测试音乐歌曲能测到，不知道客户要怎么对比，暂不处理
* 20200520
** 串口
   波特率9600,电脑端的发送间隔不能太小,理想是50ms
   要不然容易出现,超时时间未到,导致几个包合在一起
** 锐一690X
   id3死机问题，已处理，又提了几个播歌异常的歌曲等问题，拒绝客户处理，让客户换695X
** 恒鼎荣692X
   BLE随EDR一起断开，串口0的B口死机等问题，改了个版本给客户
** 科普豪6956A
   串口升级不了，ota.bin读取key时，固定有一个bit读错，寄珠海
** 博建6936
   充电仓左右反，已支持
* 20200519
** 盛鑫源6303A
   串口双向流控，已OK
** 联创视听692X
   无线遥控syn480R波形解析，借用红外模块处理，
   客户抓逻辑分析仪波形，给建议处理中
* 20200518
** 晶振
   负载电容应用12pF的
** 起华6966A
   I22程序已发出
** 盛鑫源6303A
   串口流控demo，调试中
* 20200516
** 起华6966A
   I22调试中
** 羽恒692X
   改繁体库后小写字母文件名出错，是FAT只认大写，而繁体的编码值落在小写字母上，让客户自己应用层小写转大写，已解决
** 德科创6303A
   串口不稳定，sniff模式造成，暂时先关掉处理，后面再看怎么优化
** 春苗695X
   双SD卡同时启用，目前SDK不支持，等006再说
* 20200515
** 起华6936D
   连苹果，不进低功耗，已OK，充电仓左右反，耳机程序还没改好
** 起华6966
   案子调试，还没调
** 羽恒692X
   繁体乱码，珠海改库OK
** 恒大692X
   蓝牙断连，珠海改库，发给客户抓log
** 德科创6303A
   串口接收不稳定，偶尔乱码，支持中
* 20200514
** 起华6936D
   程序进入sniff后，功耗还有2mA，是功能上加了个10ms的定时器导致，已处理
** 春苗695X
   蓝牙发射器死机，复位等问题，已处理
** 美师傅693X
   光感驱动调试，支持中
** 铬元692X
   Beacon主机扫描，获取rssi需求，支持中
** 羽恒692X
   创建繁体的文件夹，乱码问题，还没看
* 20200513
** 起华6936D
   R5部分机子无端耗电，充不满，改了2个地方给客户测试
** 起华6936D
   搭配F95充电仓，改了一版程序给客户
** 盛鑫源6303A
   周立功替换模块，调试中
** 科普豪690X
   ble广播包，动态填充，已OK
** 也杨692X
   ble蓝牙名显示不完整，buf溢出问题，去掉不必要广播字段，已ok
* 20200512
** 起华6936D
   R5板子异常，已完成
** 盛鑫源6303A
   周立功替换模块，调试中
** 源创杰6936D
   SC7A20敲击异常，不灵等问题，偶尔还会异常，让客户找敲击原厂
** 尚凌692X
   发射器连BK耳机，声音卡，寄珠海
* 20200511
** 猫王6926C
   P1、P5、PVX都出现重启后状态对不上，是因为APP协议有改动，
   没有告知，客户还没确定是否要改，待确定
** 盛鑫源630X
   周立功BLE模块，串口能接收，协议功能还没时间搞
** 尚凌692X
   BLE notify发送大量短包，偶尔会出现卡30ms，处理中
* 20200509
** BLE长包
   const int config_btctler_le_features = LE_ENCRYPTION | LE_DATA_PACKET_LENGTH_EXTENSION;
   const int config_btctler_le_acl_packet_length = 251;///27;
** 灵奥690X
   发射器机子出现死机无法长按8s复位，107公版rtc睡眠后无法长按复位，
   SDK的bug，看客户沟通，再看是否要找珠海处理
** 组创6933C
   死机问题，客户不接受解释
** 猫王6926C
   P1功放噗声，P5重启后APP获取状态对不上，都在处理中
** 科普豪695X
   LE层长包，已告知珠海
* 20200508
** 起华6936D
   A3没声音，和H3-LW620触摸，2款程序已发出
** 猫王6926C
   P1添加配对提示音，已发出
** 组创6933C
   BLE按摩器死机，只有客户的代码在他的电脑编译才能复现，无法处理，
   只关了总打印处理，死机后能立马复位
** 天地宏695X
   音箱调试3个问题，处理中
* 20200507
** 猫王6926C
   PVX、P5、P1，3款机型程序已发出，还有个低电复位的，处理中
** 组创6933C
   BLE按摩器，出现死机，目前只有客户的烧录文件会出现，
   重新编译后复现不了，客户想过来验证
** 中翔达6936D8
   VDDIO没贴电容，导致开机一直复位，开机前设置PB5输出0，客户测试可以
** 汉欣诺6951A
   底噪问题，新的SDK，客户测试改善很大，待测试完整功能程序再确认
* 20200506
** 猫王6926C
   P5生产2个问题，改了个程序给客户测试
** 组创6933C
   死机的机子，收到，还没处理
** 汉欣诺6951A
   4声道DAC底噪问题，处理中
** 威益德690X
   推IC波形，导致卡音，改了个demo给客户
** 盛鑫源6303A
   SDK引脚设置有问题，珠海还没回，基本还没调
* 20200505
** 起华6956A
   T905反馈7个问题，已改好发出
** 猫王6926C
   P5反馈断连问题，协助远强测试中
* 20200504
** 起华A3-6936D
   通话没声音，用056的程序生产，没有自动校准，偏置都到1V以上，改软件配置可以
** 汉欣诺6951A
   4路dac车机做法，底噪大，声音失真等，公版SDK就能测到，需珠海处理
** 晶一692X
   pincode太简单，有部分手机，会自动连上，因为手机有默认密码组表，无法处理
* 20200430
** 猫王6926C
   P5淘宝出货机子，10几个用户投诉蓝牙断连问题，这边跟猫王都测试不出，等猫王寄机子
** 组创6933C
   按摩器，有一个机子从国外寄回，估计会死机，
   开了打印就不死机，原因未知，处理中
** 汇杰芯692X
   发射器发射主机插播提示音，发给音箱，由于解码接口要做互斥，
   SDK默认没做，不好搞，跟客户说做不了
** 源创杰692X
   华为跑步机，BLE连接调快后，卡到传统蓝牙播歌，又把时间间隔调低回来
** 联巨兴690X
   linein录音wav格式，第一次录30s会卡音，换个库，客户测试不到，
   但是终端反馈还是有，建议客户换U盘
* 20200429
** 起华6956A
   JWT01案子调试，已发出
** 新联芯695X
   AD按键检测，组合键，长按过滤，已改一版程序给客户
** 汉欣诺690X
   vivo iQOO Neo手机A2DP链路已连接，但是声音从手机出来，协助中
** 华巨芯692X
   BLE主机要做1拖4连接，做不了，已拒绝
* 20200428
** 源创杰692X
   BLE跑步机对接华为运行健康APP，出现卡3s读不到数据现象，改了一版程序，
   现象还是有，能砍到接近参考样机的水平，卡1s多一点，客户觉得可以发给终端测试
** 春苗695X
   玩具案子，识别不到外挂flash，播歌复位，播歌杂音，指定路径播放复位等问题，均已处理
** 雄思692X
   NTC检测，电池电量检测，波动很大，支持中
** 起华6956A
   对耳案子JWT01，未调

* 20200427
** 猫王6926C
   PVX项目，调灯效果，已发软件
** 源创杰692X
   BLE对接华为APP读取信息不完整，处理中

* 20200425
** 起华6956A
   T905已发一版给客户测试
** 欣瑞声696X
   013的SDK不开TWS，没声音，已解决

* 20200424
** 起华6936D
   FF216功能修改，已发出
** 起华6936D
   R5光感驱动检测，已OK
** 起华6956A
   T905案子，调试中
** 猫王6926C
   呼吸灯效果，改一版程序已发出
** 威益德690X
   指令延时做法，各模式不准，给客户开定时器延时
** 源创杰692X
   BLE read回调在刚连接卡3s左右，还没看

* 20200423
** 猫王6926C
   出差一下午
   呼吸灯效果，声音失真，EQ效果，出差处理中

* 20200422
** 芯连心6956A
   中控耳机开发支持
** 中翔达6956A
   中控耳机一边没声音，改了一组参数给客户，SDK库有问题，珠海还没改库
   自动mute的参数,应用层定义是u16,底层是u8
** 美师傅6951C
   SD0用A组口，读不了卡，公版原理图就有问题
** 猫王6926C
   PVX音量大失真，呼吸灯效果等，改了2版程序，明天还出差客户调试
** 欣瑞声6901
   48K-wav死机，没看
   替换wav_dec_lib.a测试OK

* 20200421
** 蜜连695X
   动态修改蓝牙名跟pin_code，已发出
** 春苗695X
   MIC当AD-key按键，可以用，但是ADC满值电压跟其他IO不一样，
   建议客户不要用
** 中翔达695X
   中控立体声输出，音量小容易被mute，珠海改的库，
   就算自动mute阈值改很低，还是不行，得珠海处理

* 20200420
** 起华6936D
   H3客户UI修改，还有个没改
** 汇杰芯AI8009
   修板唤醒功能，客户测试OK回去
** 猫王6926C
   P1新项目，在P5上修改，已发出

* 20200418
** 695X反汇编
   const int config_asser         = 1;//打开异常中断
   #if 0//def CONFIG_RELEASE_ENABLE ///开启log_e的打印
   #undef __LOG_LEVEL
   #define __LOG_LEVEL 0xff
   #endif
   log_e和log_info，是不一样的打印
   异常中断看下面2个打印,对应反汇编位置
   rets : 0x01E56E44 
   reti : 0x01E56E14 
** 起华6936D
   R5出货有6个问题，蓝牙名被误改，单边没声音，测不到，其他的问题，改了一版给客户
** 威益德690X
   双工通话，远端听到有断音，无法解决，车机的回声大，就是这样子
** 鑫凌波692X
   对箱带混响，只能做到跟精博德一样的做法，对箱一连上，只能改成喊话功能，断开才能切换成混响
** 中翔达695X
   最小音量提示音，改了个程序给客户测试
** 汉欣诺695X
   异常复位问题，还没定位到问题点

* 20200417
** 蜜连695X
   SPI推刷卡机，系统会死机，改了一个demo给客户
** 威益德690X
   不同苹果手机系统，Siri状态异常，客户手中苹果手机问题，重启后正常
** 起华6936D
   去掉特殊功能，做一版普通对耳，已发出
** 汉欣诺695X
   切换fm模式会软复位，还没看
** 汇杰芯692X
   已出货机子，开不了机，软件误判复位源，部分芯片会这样，已出国机子得看客户怎么沟通处理
** 新联芯695X
   中控耳机开发，支持中

* 20200416
** 联巨兴695X
   蓝牙ID3获取，已处理
** 汉欣诺695X
   电话本，系统时间，珠海改库中，串口升级，HID触摸，有待珠海评估后续怎么处理
** 汇杰芯692X
   发射器SD卡bfu升级不了，客户程序问题，公版没问题
** 雄思692X
   客户工程SDK培训，已完成
** 老树开花692X
   发射器SCO对接功能，mic没声音，需要关闭之前sbc通道，改了一个版本给客户
** 起华6936D-KXD368
   批量生产，测出6个问题，还没改，6936D-FF216，案子调试，已发出
** 科普豪693X
   AISDK无后台，切模式，蓝牙异常，还在测试中
   耳机的SDK只能关机，没做切换模式，搬音箱的代码后，多切几次会死机
   无法处理
** 威益德690X
   测试siri对多款苹果的兼容性

* 20200415
** 汉欣诺695X
   4声道调数字音量和模拟音量
   #+BEGIN_SRC c
   void user_volume_set(u8 volume)
   {
       g_printf("user_volume_set:%d  %d",volume,dig_vol_table[volume]);
       audio_dac_set_volume(&dac_hdl, volume, volume, volume, volume);
       audio_dac_set_analog_vol_support4way(&dac_hdl, volume, volume, volume, volume);
       __this->digital_volume = dig_vol_table[volume];
       audio_dac_set_L_digital_vol(&dac_hdl,  dig_vol_table[volume]);
       audio_dac_set_R_digital_vol(&dac_hdl,  dig_vol_table[volume]);
       audio_dac_set_RL_digital_vol(&dac_hdl, dig_vol_table[volume]);
       audio_dac_set_RR_digital_vol(&dac_hdl, dig_vol_table[volume]);
   }
   #+END_SRC
** 汇杰芯692X
   动态调节传统蓝牙名，珠海改库可以
   memset(host_name,0x00,LOCAL_NAME_LEN);
   #define NAME2  "2X-modify"
   memcpy(host_name,NAME2,strlen(NAME2));
   puts(host_name);puts("\n");
   __set_host_name(host_name, sizeof(host_name));
   user_send_cmd_prepare(USER_CTRL_CMD_RESERVE_INDEX3, 0, NULL);
   临时使用那个命令做改功能，不标准
** 起华6936D
   56F芯片没货，FF216换36D，调试中

* 20200414
** 威益德690X
   升级p4-opp版本，蓝牙断连无声已解决，
   播歌爆ram跳曲等问题，处理中

* 20200413
** mic增益
   AC695x，AC696x以及以后的系列，无特殊说明，mic的增益级数只有14级，每级2dB
   而AC693x及之前的是31级，每级0.9dB左右
** 695X--EQ版本
   0.4.1.0 才有drc
** 起华6936D-LW620
   客户UI修改，已发出
** 新时代692X
   BLE被CC2640连，没有profile扫描过程，
   直接对某个handle做操作不兼容问题，已处理
** 威益德690X
   升级p4-opp版本，爆ram问题，已解决，
   但是出现蓝牙断连无声音等问题，客户明天过来处理
** 汉欣诺695X
   车机做法，多通道EQ，动态EQ调节，等响度，环绕声等需求，
   让客户先了解全志跟凌阳的做法，再看怎么跟珠海沟通

* 20200411
** 反汇编
   新版编译器的llvm-objdump.exe已经不支持输出反汇编信息。
   file:c:/Users/Administrator.PCOS-1707211525/Desktop/objdump/
   目录里有llvm-objdump.exe
   拷贝工程下载目录的汇编文件,到本目录
   ./llvm-objdump.exe -print-imm-hex -d 695X/sdk.elf >> 695X/005-1.txt
   就可以把反汇编信息导出到txt文件
** 起华6936D
   2款程序，已发出
** 源创杰692X
   输出us级波形，代码指定到ram，用delay的方式，客户测试OK
** 威益德690X
   爆ram问题，给的建议，客户测试不行

* 20200410
** 猫王6926C
   PVX项目，升级异常，偶尔断连，偶尔回连不上等问题，处理中
** 鑫闻达693X
   外部中断，065国斌改库测试可以
** 汇杰芯8009
   耳机无法唤醒，已OK回客户了
** 源创杰692X
   5us控制功放,把代码放在ram用delay做延时翻转IO

* 20200409
** 猫王6926C
   PVX跟P5，升级界面跟音箱流程对不上，对接中，
   死机问题，一直测不到，还不知道怎么处理
** 起华6936D-LW620
   2代提几个需求，还没改
** 汉欣诺692X
   HID触摸，iPhoneX以上版本，不起作用，让客户测试原先抄机的机子先
   
* 20200408
** 起华6936D-H3
   客户UI修改，已发出
** 猫王6926C
   PVX项目，反馈4个问题，改了2个，另外2个还没测到

* 20200407
** 起华R5-6936D
   通话电流声问题，改了一版程序给客户，6936D助听器案子，调试中
** 灵奥695X
   获取长文件名，珠海改库，测试OK
** 汉欣诺695X
   串口接收变成0数据，接收数据长度超帧长度后，就会出现，客户测试OK
** 猫王6926C
   PVX项目，煲机24h出现死机，客户寄机子过来测试

* 20200403
** 起华H3-6936D
   改2版程序，FF216-6956F，通话回音，已发出，还有一个助听器没搞
** 猫王6926C
   PVX项目改几个问题，已发出，剩一个进sleep后死机，要珠海远强协助，还没搞
** 汉欣诺695X
   车机串口，发送频率小于10ms后，会出现，一直0数据，还没验证

* 20200402
** 696X
   DCDC需要配合 CLOCK_MODE_IGNORED
   ldo 就设置   CLOCK_MODE_ADAPTIVE 
** 起华6936D-R5
   通话电流声问题，处理中
** 猫王6926C
   PVX项目3个问题，和煲机死机问题，还没看

* 20200401
** 696X
   PB4，PC3，PC4，USBDP，USBDM。
   在芯片开机系统复位起来过程中会默认输出0状态，导致G-sensor供电拉低，无法触摸开机。
** 起华
   6936D-F8 程序已发出，AD138 UI修改已发出
** 猫王6926C
   PVX项目，提示音跟失真问题，客户还在测试
** 汉欣诺692X-HID
   安卓back键部分手机失效，由ESC改成AC back，只剩荣耀6不兼容，暂时这样处理
** 汉欣诺695X
   串口接收数据变成全0问题，还在测

* 20200331
** spp修改UUID
   /*128 bit uuid:  11223344-5566-7788-aabb-8899aabbccdd  */
   const u8 sdp_test_spp_service_data[96] = {
   0x36, 0x00, 0x5B, 0x09, 0x00, 0x00, 0x0A, 0x00, 0x01, 0x00, 0x04, 0x09, 0x00, 0x01, 0x36, 0x00,
   0x11, 0x1C, 
   0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0xaa, 0xbb, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, //uuid
   0x09, 0x00, 0x04, 0x36, 0x00, 0x0E, 0x36, 0x00, 0x03, 0x19, 0x01, 0x00, 0x36, 0x00,
   0x05, 0x19, 0x00, 0x03, 0x08, 0x02, 0x09, 0x00, 0x09, 0x36, 0x00, 0x17, 0x36, 0x00, 0x14, 0x1C,
   0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0xaa, 0xbb, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, //uuid
   0x09, 0x01, 0x00, 0x09, 0x01, 0x00, 0x25, 0x06, 0x4A, 0x4C, 0x5F, 0x53, 0x50, 0x50, 0x00, 0x00,
   };
** 起华
   6956F-FF216软件完成，
   R5-6936D电流声，需要硬件看，
   F8-6936D还在调
** 猫王
   PVX修改open_mic提示音音量，直接修改提示音文件
** 汉欣诺695X
   串口接收，一段时候后，接收到的数据变成0，字节数却是对的，还没看

* 20200330
** 起华6936D
   mic扩音助听器功能
   3代的机子通话不行
** 汇杰芯692X
   长文件名获取
   memset(g_lfn_buf, 0, sizeof(g_lfn_buf));
   fat_set_lfn_buf(g_lfn_buf);
   memset(&music_file_info, 0, sizeof(music_file_info));
   file_operate_get_file_info(obj->fop, &music_file_info);

* 20200328
** 科普豪
   欧智通对耳，距离短，内核电压底层库判断是F版后就不抬电压了

* 20200327
** 起华
   要换66A代码
** 猫王6926C
   PVX项目失真，基本可以确定是芯片内部干扰造成DAC输出失真，暂无处理方式
** 科普豪6936D
   欧智通对耳案子，距离短，处理中

* 20200326
** 猫王6926C
   PVX项目，芯片输出PWM后造成低频失真，改成20khz，客户反馈更差
** 起华6936D
   改2版程序，已发出
** 汉欣诺6925B
   BLE beacon案子，调试中
   adv_type = 3; ///只广播，不接受连接
   改成类型3后，广播间隔无法低于100ms，底层库限制

* 20200325
** 巴达木6959B
   省电容方式，通话无声，小声等问题，demo板能复现，寄珠海处理
** 尚凌6956D
   省电容方式，通话电流声低噪声，软件无法处理，改成固定好mic做主机方式
** 汉欣诺692X和695X
   BLE  beacon，
   和串口问题，还没处理
** 猫王6926C
   PVX项目，改了呼吸灯后，造成声音失真，还没处理
** 威益德690X
   车机连海外版三星手机，通话后卡音，明天客户带机子，直接去珠海处理

* 20200324
** 巴达木6959B
   通话概率无声，修改软件后客户测试没有出现无声，但是声音会变小，
   这边测试公版，SDK的mic偏置是有问题的，珠海还没看
** 尚凌6956D
   通话电声，目前只能做到。不说的时候没有电流声，一说话，就跟着声音一起出来

* 20200323
** 起华6956A
   3个程序，已发出
** 巴达木6959B
   通话无声，支持中

* 20200321
** 起华6936D
   SL353项目开发，还差个提示音问题，处理中
** 汇杰芯6959B
   mic口PC6，会漏电，关机功耗大，珠海反馈无法改，只能改板

* 20200320
** 起华36D和56A
   2款程序，已发出
** 汉欣诺692X串口升级
   uboot升级途中停住，直到看门狗复位，怀疑栈被改，原因还未知，
   客户在测试先切换到idle，再响应升级，测试中
** 猫王6926C
   P5音量低休眠后反馈无法定时唤醒，还没测到

* 20200319
** 猫王6926C
   P5要进入sleep睡眠，要切换系统时钟为160M
   192M进入睡眠会唤醒不了
   P5改4个问题，PVX改5个问题，待发出
** 源创杰692X
   AI的SDK进sleep唤不醒，要换成猫王的库power_manage_lib.a
   set_lowpower_pd_ldo_level(0x01, 0x01, 0x07, 0x01);
** 汉欣诺692X
   串口升级死机问题，珠海改了带打印的库，在uboot看门狗复位，原因还未知

* 20200318
** 猫王6926C
   P5低电放电曲线，改了一版给客户测试
** 起华6936D
   ET2充电灯乱闪，改了一版给客户
** 汉欣诺692X
   串口升级有几率在uboot直接复位，
   怀疑是MP5的串口波特率有波动，长包会错位，客户试着改MP5

* 20200317
** 猫王6926C
   P5低电关机后，无法开机，处理中
** 猫王6926C
   PVX反馈4个问题，还有2个确认中
** 起华6936D
   ET2项目，充电问题，还未处理

* 20200316
** 起华6936D
   3款板子，软件已发出
** 猫王6926C
   PVX项目断连测不到，P5低电关机后无法开机，要客户寄板子过来再处理
** 国华692X和695X
   反馈的5个问题，没有工程联系，未处理
   
* 20200314
** 汉欣诺692X
   电话本死机，珠海改库，测试可以
** 国华6928B
   升级问题，已处理
** 猫王6926C
   PVX项目，反馈断连又立马回连，还没测到，倒是测出音频链路声音出不来问题，处理中

* 20200313
** 猫王6926C
   PVX项目反馈2个问题，已发软件
** 恒大6926A
   修改BLE功能，已发出
** 起华6936D
   ET2项目，反馈2个问题，已发出
** 汉欣诺692X
   电话本死机问题，珠海发库待测试

* 20200312
** 国华6928B
   spp使用问题，发送的buf要static，已解决
** 起华6936D8
   换D4需要升级到066SDK，已发出
** 猫王6926C
   PVX项目反馈3个问题，测试中

* 20200311
** 猫王6926C
   PVX项目，问题修改已发出
** 猫王6926C
   P5项目，问题修改已发出
** 起华6936D
   6936D8换D4，有个特殊功能，要换库，只有066的补丁，需要更新SDK，处理中

* 20200310
** 695X
   能量值audio_output_data()
** 猫王6926C
   反馈3个问题，有一个需要动到loader.bin，等日新修改，待处理
** 锦亨源692X
   BLE的特征wirte_no_response和notify无法属性共存，
   应该是安卓手机7.0版本以下的共性问题，暂不修改

* 20200309
** 版本发出批处理
   #+BEGIN_SRC dos
   download-Release_Version.bat：
   //********************版本发布****************************//
   echo "请输入版本号:"
   set /p ver=
   set fw="jl_isd.fw"
   set bfu="updata.bfu"
   set filename="JL_MW_AC6926C_PVX_XIN_%date:~0,4%%date:~5,2%%date:~8,2%_%ver%_@@_.fw"
   echo %filename%
   if not exist Release_Version md Release_Version
   copy %fw%  .\Release_Version\
   copy %bfu% .\Release_Version\
   cd .\Release_Version\
   if exist %filename% goto yes_exist else not_exist
   :not_exist
   echo "是机型--使用key--重命名成%filename%"
   if exist %filename% del %filename%
   rename %fw%  %filename%
   ::rename %bfu%  %bfu%-%ver%
   rename %bfu%  updata-%ver%.bfu
   pause
   exit
   :yes_exist
   echo "有同名文件%filename%--中断退出--未进行重命名操作"
   pause
   exit
   //********************版本发布****************************//
   #+END_SRC

** 猫王6926C
   PVX项目反馈5个问题，已发出
** 汉欣诺692X
   传统蓝牙只开SPP升级开不了机，至少要开AVCTP才可以，已OK
** 汇杰芯693X
   音箱SDK-0.2.3，蓝牙回连是按照配对顺序，珠海没空搞，支持客户自己记VM方式，已OK
** 天浪6905C
   EDR+BLE同时开，蓝牙播歌距离短，音量无端自动降低，支持中

* 20200307
** 长文件名和中文路径
   新建立一个文件，保存在ANSI格式，再把要用到的中文路径放在那里。
** 猫王6926C
   1、要求拨动一次（目前是2次）切换上下曲
   2、要求在设备没有休眠前都要可以回连
   3、蓝牙名称需要改为"猫王·野性MINI-C"
   4、旋钮调节方向，待确定
** 科普豪6936D
   主从切换无法关闭也无法主动切换
   void tws_conn_switch_role();
   if(bt_tws_get_local_channel()!= 'L'){
       sys_timeout_add(NULL,tws_conn_switch_role,1000);
   }
   连接后立马放回仓后，会造成切换主从超时，就断开手机连接。
   底层默认刚连上是不让切换的。

* 20200306
** 汉欣诺692X
   HID多点触控
   苹果使用0号ID，而安卓不认0号ID，做了2份profile_data
   win10电脑多点触控需求，让客户参考微软硬件中心描述，先自己整
** 汇杰芯693X
   音箱0.2.3珠海找不到
   由于手机蓝牙地址可以打印到，是相反的，客户可以自己做VM回连一个设备
    __set_auto_conn_device_num(2);
   const u8 more_addr_reconnect_support = 1;控制回连多个设备
** 猫王PVX
   外挂flash用途？OTA升级用，升级完要回连，ota升级的时候不能擦除配置
   所有按键唤醒？PA1没高阻？PR2与普通IO都能唤醒？
   其他APP没有上下曲
   音量调节:顺时针旋转，音量增加。逆时针旋转，音量减少。设置反了

* 20200305
** 起华6936D
   ET2案子，改了一版给客户
** 猫王6926C
   PVX案子，调试中
** 汉欣诺692X
   安卓HID识别有问题，未处理

* 20200304
** 693X
   idle模式下,如果有定时器一直跑的,不要调用tws的任何接口
** 科普豪6936D
   对耳充电死机，在用064公版换珠海异常库，测试中
** 汇杰芯693X
   音箱023的SDK，回连2个问题，需要珠海搞，已发邮件
** 天浪690X
   蓝牙动态改名的，客户测试可以

* 20200303
** 起华
   远古新案子
** 科普豪6936D
   对耳问题调试，找不到问题点，给了一直修改方法给客户测试
** 迈瑞693X
   flash文件读写，第二页异常
   BLE的SDK添加flash文件按页循环读写demo，已发出

* 20200302
** 源创杰692X
   AI APP手机无法启动语音识别，是专门去掉的
** 汇杰芯693X
   有个苹果手机，播歌下，会一直判断成通话状态下
   看打印是一直循环打出电话挂断，原因未知
** 科普豪6936D
   耳机几个bug测试中
   对耳案子反馈5个问题，均未现，
   测试出其他3个问题，无法关机已处理，异常中断2次位置不一，充电死机，原因均未知

* 20200229
** 恒大6926A
   新的芯片，下载程序显示BR21-BLE蓝牙名，分析中
   客户发命令比692X上电快
** 伦茨693X
   华为P10手机没声音，已发补丁给客户
** 伦茨695X
   5V常在，充满电，一直维持7mA功耗
   降到3.7V后，就变为0mA了
** 科普豪693X
   反馈几个问题

* 20200228
** 源创杰692X
   发射器无法解码smp加密文件，改程序客户测试OK
** 汉欣诺692X
   DAC输出失真，客户硬件问题，IOS多点HID，改了一版给客户，有反应，但是延时较大，客户测试中
** 伦茨693X
   P10手机，寄给珠海有盼分析

* 20200227
** 汉欣诺692X
   HID触摸，feature report手机不读，找不到问题点，客户寄个样机来抓包
** 伦茨693X
   华为P10手机回连对耳，出现一边没声音，应用层改了不起作用，需要珠海处理
** 科普豪693X
   对耳调试，给了修改方法，客户测试中

* 20200226
** 开始上班
** 恒大6926A
   AT_VERS_N添加回应OK
   新打的板子，读取bt_cfg.bin失败，蓝牙名为BR21-BLE，原因未知
** 汉欣诺
   IOS多点触控
** 科普豪693X
   加了sniff晶振用24M
   改了mic电源为2.3V
   加了充满电点蓝灯
** 迈瑞
   flash擦除问题

* 20200118-20200226
  春节放假

* 20200117
** 起华
   6925音箱修改
** 汉欣诺
   IOS多点触控，测试不行

* 20200116
** 思必驰692X
   蓝牙发射器有爆破音，底噪，消音等问题，
   根源在于客户那辆试验车的车机功放解mute会有爆破音导致，
   手机测试也有这种现象，后续修改，最多只能做到手机的效果
** 恒大6926A
   BLE模块，报文格式协议修改，已发出

* 20200115
** 恒大6926A
   主控无法和GD32F407共用晶振
   主控加了普利金的key

* 20200114
** 起华AD135
   小概率死机问题，打补丁发程序给客户测试
** 源创杰692X
   BLE透传，需要缓存大量UART数据，改了个demo给客户
** 汇杰芯6936D
   BLE广播问题支持

* 20200113
** 科普豪6956D
   内置充电问题，音箱SDK0.0.1版本不支持内置充电，改了个程序给客户，
   插卡卡音，公版SDK测试没问题

* 20200110
** 华巨芯6936D
   中控耳机电流声,功率降2级,MIC电源提高,mic加EQ滤高频,改成LDO电源
** 华巨芯4601B
   32K晶振不跑,rtc读寄存器会出错,导致PR3被设置成输出或下拉
   在所有的PORTR函数里,都初始化PR3的对应位
   输入关上下拉

* 20200109
** 汉欣诺692X
   苹果HID多点触控,改成White_board+Finger，客户测试中
** 博创昱6936D
   PA8有个3V到4V连续脉冲波，导致触摸IC死机
   SDK在LDIN_ERR没有charge_close，客户测试中
** 起华6936D
   按键提示音修改，入离耳滤抖，客户测试中

* 20200108
** 起华6936D
   KXD368触控耳机案子,加离耳不响应按键
** 起华6925A
   音箱案子,低音调节旋钮,声音很奇怪
   
* 20200107
** 恒大6926
   BLE蓝牙模块，客户文档协议封装测试可以
** 也杨6901
   spi外挂flash录音，剩flash分区录音问题，转了个珠海邮件给客户，客户回去自己先搞
** 起华6936D
   在065上打补丁，开不了机，处理中

* 20200106
** 恒大6926
   BLE蓝牙模组，协议封装中
** 源创杰692X
   点阵屏繁体显示乱码
   国内下载的歌词文件，都是ANSI编码，用记事本转换成UTF16-LE，客户测试可以
   预测国外下载的，肯定不会是ANSI，应该是UTF16-LE
** 芯运6936D8
   测试盒升级死机
   客户芯片批次号为UAK731-36D8，用064的SDK测试出现百分百死机
   替换之前处理TH flash的ota.bin，客户测试几个芯片，都可以
** 新时代692X
   有其他方案能做到在一个连接事件内传送40包以上
   692X只能传输10包以下,需要敏贤支持

* 20200103
** 695X
   开发板PA9、PA10短路
** 汉欣诺695X
   串口UART1 TX和RX改任意映射，客户测试OK
** 起华A3-6936D
   生产不良，部分dvdd电压偏低，升级SDK给客户，
** 起华AD138
   无线充关机后耗电3mA，充电IC型号选错,应为CHARGE_IC_LP4060_LP6235
** 起华R5-6936D
   改用KXD368,发给客户测试了

* 20200102
** 请假1天

