#+TITLE:       JL work diary record
#+AUTHOR:      辛佳斌(lawrence)
#+DATE:        [2017-02-13 周一 16:31]
#+EMAIL:       lawrencejiabin@163.com
#+KEYWORDS:    the page keywords, e.g. for the XHTML meta tag
#+LANGUAGE:    language for HTML, e.g. ‘en’ (org-export-default-language)
#+TODO:        TODO

#+SEQ_TODO: TODO(T!) | DONE(D@)3  CANCELED(C@/!)  
#+SEQ_TODO: REPORT(r) BUG(b) KNOWNCAUSE(k) | FIXED(f)
   #+BEGIN_SRC c
   #+END_SRC


* 20201230
** 63烧录想MAC地址自增
   目前一拖二不支持保持原有的蓝牙地址
   一拖八可以
** USB report数据包大于8需要修改端点的长度
   #define     MAXP_SIZE_HIDOUT            9//8
   #define     MAXP_SIZE_HIDIN             9//8
** 春苗6958B
   生产5K有20个开不了机，4%比例，初步分析flash损坏，寄给珠海分析
** 德科创6368B
   USBdangle，死机跟上传report数据异常，已处理
** 联巨兴695X
   32K晶振计时，软关机2分钟后开机，时钟复位，已处理

* 20201229
  出差1天
** 雅乐6983D
   dut测试难连接,灵敏度低

* 20201228
** 951/961功耗测试
   需要新的烧录座子 V2.1版本
   新版本的烧写器能将功耗超标的芯片挑选出来
** 春苗6951
   生产5K,有20个不开机，让客户寄出
** 文晟6369C
   生产挑测有部分芯片，不充电，让客户寄出
** 内部951
   数码管SDK，会概率复位，跟珠海在一起查
** 德科创6368A
   060的dongle断言死机，还没看
** 博建697X
   编译的app.bin比696X大100K，提示音放不下，让客户改AAC，客户说音质不行，处理中

* 20201225
** 蓝牙设备类型
   __change_hci_class_type(0x240424);
   __change_hci_class_type(0x10091c);
** 63功耗
   1系列 静态功耗：30uA
   5系列 静态功耗：180uA
   6系列 静态功耗：120uA
   7系列 静态功耗：60uA
** 636X关机前有打印会死机导致看门狗复位
   void board_set_soft_poweroff(void)
   JL_UART0->CON0 = 0;
   JL_UART1->CON0 = 0;
   JL_UART2->CON0 = 0;
** 猫王6926C
   P3项目EQ调试程序已发出
** 文晟6369C
   打补丁死机，珠海确定就是串口问题，关机前不能有任何打印
** 云康宝6368A
   改LVD导致OTA升级中断，040公版就会，其他版本不会，珠海处理
** 天浪6368
   OTA升级失败，处理中

* 20201224
** 文晟6369C
   关机死机看门狗复位，已处理
** 猫王6926C
   换EQ，功放，已处理
** 雅乐6983D
   多个问题，处理中

* 20201223
  出差雅乐半天
** 6983D蓝牙断连
   AAC问题

* 20201222
** 淇诺8976
   ANC+ENC样机调试，已处理
** 德科创6368
   200uA功耗大，处理中

* 20201221
** 易路发697X
   复位源信息获取错误，已处理
** 联创视听696X
   外挂flash，插卡复位，已处理
** 德科创636X
   换sniff唤醒口，开机死机，已处理

* 20201217-20201218
  出差珠海2天
** 易鑫华睿695X多媒体充电仓
   处理多个问题

* 20201216
** 联巨兴695X
   200烧录文件，烧录器不认，已处理
** 猫王6926C
   P1E换脉冲功放，已发出
** 易鑫华睿695X
   智能多媒体充电仓，处理中

* 20201215
** 国华693X
   游戏手柄，摇杆晃动ADC不准，已处理
** 春苗695X
   ble-ota，搬630X的代码来用，测试可以，发给客户
** 猫王6926C
   P1E换功放，加4种脉冲模式，处理中

* 20201214
** VM大小位置
   ini的那个大小只是一个最小的大小，不是最终的大小，所以最终的大小是肯定要大于等于ini里面配置的大小的
   #VM_ADR=0;
   VM_ADR=0xFC000; //指定地址(4K对齐)
   VM_LEN=8K;      //指定大小
   VM_OPT=1;
** BLE-OTA升级
   升级前ex_cfg_fill_content()获取蓝牙名、广播包数据，写到VM上。
   进去uboot之后，就从VM读取数据出来
** 四博636X
   客户自定义广播协议引起OTA异常，已处理
** 春苗695X
   VM指定地址，已处理
** 鑫闻达608
   dac mute跟SD 开机cmd挂载失败，已处理
** 巴达木联奥696X
   5个问题反馈，已发3个，处理中
** 春苗695X
   APP OTA升级，珠海一直没看，让客户走邮件

* 20201211
** 卓越696
   对箱主机关机，不要主从切换，从机不能跟手机连接
   int bt_tws_poweroff()
   {
       log_info("bt_tws_poweroff\n");
       bt_disconnect_tws_conn();
       ....
   }
** 中翔达科奈信697X
   挂不断电话，测试1个钟，测不到，开打印客户那边也还没测到
** 天罡微697X
   主从切换，充满又继续唤醒充电等问题，已处理
** 巴达木6969
   蓝牙模块，单线通信，兼串口通信，已发demo，客户验证中
** 四博636X
   BLE OTA升级失败，处理中

* 20201210
** 新智造636X
   异常死机，将代码指定到ram，已OK，
   631X的串口跟功耗，PWM等问题，已给demo，客户验证中
** 猫王6926C
   P1E项目，功能修改，已发出
** 中翔达697X
   挂不断电话，客户测试中

* 20201209
** 鑫闻达697X
   213版本无法主从切换，已处理
** 中翔达科奈信961
   低电在3.4V临界无法休眠，测试不到，
   建议客户不要串电流表测试，会有升压失败导致频繁复位现象，跟进中
** 国华696X
   RGB能量灯，不建议客户用杰理之家的接口，自己写一套接口
** 云康宝636X
   自定义线程任务，已发demo给客户
** 新智造636X
   异常死机问题，客户明天过来处理

* 20201208
** 科普豪6369
   mesh案子开发培训，已处理
** 博创昱961
   用模拟电源，充电异常，支持中
** 四博636X
   20us的ADC功能，时间差很不准，处理中
** 中翔达科奈信961和697X
   充电功能不理想，无法改，建议让代理说服客户，最好不改
** 博建697X
   213版本，部分安卓手机，音量调小后，无法加上来，客户自己也测不到，让终端客户带手机过来

* 20201207
** 云康宝6368
   烧录报LVD错误，芯片只能烧录一次LVD
** 起华961
   USB无法充电，过流芯片被保护，改用1K电阻限流600mA，I = 600/R
** 中翔达科奈信961
   强制充电无法检测USB插拔，已发一版程序给客户，
   697X无法涓流充电，无法处理
** 联巨兴951
   不要按键功能，建议客户先找悬空脚处理
** 四博6369C
   20usADC功能，调试中
** 春苗695X
   lsb时钟过低，还没看

* 20201204
** 国华697X
   软件开发问题解答，已发出
** 爱尚637
   定时器中断，已发出
** 中翔达697
   ANC通话音量问题，已发出
** 春苗695X
   去掉声卡功能，已发出
   PC死机，珠海还没改库
** 联奥636
   2线低功耗串口，波特率115200，误码高，给个方式给客户验证

* 20201203
** 新联芯697X  AD138
   enc、无线充、UI几个问题，已处理
** 德凯芯6369F2
   P20第一次搜索无法连接，让客户寄友商机子给珠海分析
** 春苗695X
   PC模式异常死机，处理中
** 虹日695X  
   提示音混合播放问题，处理中

* 20201202
** 易鑫华睿695X
   多媒体充电仓发射器，已处理5个问题，剩余6个问题，寄给珠海处理
** 尚凌695X
   双EQ文件切换，已发出
** 联巨兴951
   案子UI修改，已发出
** 内部961
   不带霍尔，vcc在线耳机自动唤醒，跟珠海处理中

* 20201201
** 耳机LDOIN有两个唤醒源
   1、LDOIN和电池电压相比，从高到低，或者从低到高。会触发唤醒
   2、LDOIN和0.5V相比，从高到低，或者从低到高，会触发唤醒
** 易鑫华睿695X
   多媒体充电仓，客户带板子来复现问题，目前测试到8个问题，都跟底层有关联，难处理
** 中翔达科奈信961
   反馈有断充现象，给了个处理方式给客户，跟进中
** 淇诺697X
   测试盒蓝牙升级不了，珠海已复现，D版晶圆存在问题，珠海处理中

* 20201130
** 697X蓝牙时延
   const int CONFIG_A2DP_DELAY_TIME            = 200;
   const int CONFIG_A2DP_DELAY_TIME_LO         = 100;
** maskrom用到的IO
   用户手册，显示ROM中的，都是不能用的
** 国华6932E
   回连不上手机，珠海改库，测试OK
** 联奥636
   DM做唤醒脚，开机死机，改了一版给客户
** 易鑫华睿695X
   回连耳机没声音，这边改法测试正常，但是客户还是不行，让客户明天来处理
** 内部961
   不带霍尔，USB在线，耳机充满会自动唤醒，处理中

* 20201128
  值班1天
** 起华KY01-961
   案子调试

* 20201127
** 630N
   BLE判断区分安卓跟苹果
   搜索苹果的ANCS服务,来区分苹果
** 637X定时器
   timer0在SDK里是做局部延时的，可以用它来做微秒级延时
   timer1是系统节拍
   timer2在走低功耗流程时被用了
   timer3/4/5可以用随意使用
** 虹日695X
   外挂flash容量显示错误，已处理
** 国华6932E
   蓝牙HID戒指，回连手机不上，珠海处理
** 易鑫华睿695X
   彩屏发射器，又反馈2个蓝牙问题，
   之前蓝牙没声音，珠海没测到，跟珠海沟通中

* 20201126
** 易鑫华睿695X
   充电仓发射器连耳机没声音，已找到问题点，需要珠海处理
** 联奥集成6369
   BLE案子开发支持

* 20201125
** 杰飞达696X
   外挂flash录音播放，复位，找不到文件，文件系统损坏等问题，在公版上改了一版给客户
** 国华6932E
   蓝牙戒指功耗大，已处理
** 国华697X
   对耳充电复位，通话关机等问题，已处理

* 20201124
** 中翔达科奈信961
   0V充电功能，客户那边测试可以正常充电了，进一步测试中
** 联巨兴951
   已发一版SDK给客户测试
** 伦茨696X
   音箱加BLE HID，搜不到，断连，异常死机问题，已处理
** 杰飞达696X
   外挂flash录音重新播放，返回错误，还没看
** 国华6932E
   关机功耗大，还没看

* 20201123
** 中翔达科奈信961
   0V充电功能，基本功能已OK，
   存在3个无法避免的bug操作，已告知客户
** 猫王6926C
   P1E音质调试，已发出
** 国华6973
   左右耳有的机子会VDDIO LVD复位，支持客户查找
** 内部951
   不带霍尔兼容696X的耳机，测到触摸开机无法激活充电仓现象，处理中

* 20201120
** 组创6311
   要做11个IO的ADC，DP1无作用，已处理，
   1ms中断跟IO中断冲突，给一些建议让客户排查
** 德科创695X
   BLE的MTU无法改大，被库限制，找珠海处理中
** 中翔达科奈信961
   支持从0V电池开始充，目前还有2个异常情况，处理中

* 20201119
** 猫王6926C
   P1E调音质，支持中
** 国华6932E
   蓝牙戒指，升级死机，已处理
** 卓越6969E
   试产底噪大，给的建议都不行，等客户试产统计完，再拿来处理
** 中翔达科奈信961
   A980项目，反馈问题，处理中

* 20201118
** 中翔达科奈信961和697X
   A980项目反馈11个问题，处理中

* 20201117
** 愛瑞声697X
   自动配对带取消重新配对功能，已发出
** 汇杰芯636X
   100us中断例程，已发出
** 淇诺695X  961
   案子开发支持
** 春苗695X
   OTA功能，公版测试不行，跟珠海沟通

* 20201116
** 696X芯片版本
   CHIP Ver:0x5F0e
   04是E版，05是F版
** 易路发697X
   测试盒升级死机，已处理
** 源创杰6969D
   PA0用不了，双绑的mic无法设置高阻态。已处理
** 愛瑞声697X
   自动配对带按键配对，处理中

* 20201114
  值班一天
** 天罡微697X
   生产1%开机死机，同大康的现象一致
** 华炬芯696X
   3路PWM设置，功放mute问题
** 中翔达697x
   siri叠加wav提示音变调，时钟被设置成24M
   按照文档处理

* 20201113
** 联巨兴
   697X 升级会导致其他耳机唤醒,音量同步问题
   6963和951 充满后自动唤醒，处理中

* 20201112
** 联创视听696X
   播mp3提示音死机，已处理
   文档有写
** 剑锋961
   新的SDK，还有问题，处理中

* 20201111
** 禾声8976
   对耳回连超时，已处理
   ANC板级才会
   /* user_send_cmd_prepare(USER_CTRL_WRITE_SCAN_DISABLE, 0, NULL); */
   /* user_send_cmd_prepare(USER_CTRL_WRITE_CONN_DISABLE, 0, NULL); */
   注释这2句
** 国华636X 696X
   2个问题，已发代码给客户测试
   696X外挂flash，111使用2线，测试正常

* 20201110
** 源创杰6951C
   100版本蓝牙测试盒升级死机，珠海更新3个EXE工具，测试可以
** 众鸿6951
   车机项目，几个问题支持中

* 20201109
** 中翔达大康6973A
   开机死机，无法重新开关机，处理中
   #define TCFG_LOWPOWER_VDDIO_KEEP   1 //软关机是否保持VDDIO 电压
   功耗从4uA变成8uA

* 20201106
** 文晟6369C
   6369F换6369C，电压检测不准，无法对0V电池充电，已处理
** 中翔达961
   无线充电仓，功能正常，但是充电电压偏低，电流只有40mA，处理中
** 摩天6967
   来电铃声突然变小，加了几个音量同步的操作，待客户测试效果

* 20201104-20201105
  去珠海出差处理剑锋充电仓

* 20201103
** 猫王6926C
   3个案子功能修改，已发出
** 剑锋961
   充电仓问题，明天去珠海处理

* 20201102
** 剑锋961
   数码管充电仓，2个问题，处理中
** 芯中芯6976
   ENC机子，通话没声音，板子问题，已处理
** 猫王6926C
   P1E功能修改，还没改

* 20201030
** 华炬芯697X
   配其他方案MCU的充电仓，通信异常，这边测试可以，客户一直说不行，跟进中
** 剑锋961
   充电仓调试中

* 20201029
** 复位源信息    
   power_reset_src = power_reset_source_dump();
   r_printf("power_reset_src:0x%x -> %d", power_reset_src, power_reset_src);
   /*  0x00 -> 唤醒               */
   /*  0x01 -> VDDIO POR 上电复位 */
   /*  0x02 -> VDDIO LVD 上电复位 */
   /*  0x04 -> WDT 看门狗         */
   /*  0x08 -> VCM 硬复位         */
   /*  0x10 -> PPINR 长按8s复位   */
   /*  0x40 -> soft reset        */
** 爱尚636X
   红外跟sniff共用，已发出
** 云康宝636X
   复位源信息获取，已发出
** 巴达木697X
   几个问题，处理中

* 20201028
** 内置触摸
   我们696的内部触摸功能是高低电平模拟出来的，抗干扰性和性能不是很好，应用有局限。一般客户不建议用。
   可用AC695的代替或者外加触摸IC替换。跟AC692的是内部硬件触摸模块的没得比！！！！
** 爱尚636X
   红外跟sniff同时使用，调试中
** 国华636X
   BLE带HID连IOS会弹配对框，没法去掉
** 国华697X
   对耳mic曲线测试不过，改了一版程序，客户测试还是不行
** 云康宝636X
   复位源信息获取，待处理

* 20201027
** 国华6934
   蓝牙手柄，1%不开机，死在uboot调APP层，客户明天去珠海
** 联巨兴951
   充电仓不充满，处理中
   是697的LDOIN绑定的PP0的mos管被打穿
   现象是LDOIN改成IO状态，输入上拉，只有1V的电压，正常的芯片有3.3V
   万用表量内部上拉电阻，是接近导通状态，意味着LDOIN跟VDDIO近乎短路

* 20201026
** 剑锋961
   充电仓问题，充满不关机，功耗大，处理中
** 尚凌695X&696X
   3个问题支持，已发出
** 联巨兴695X
   内置充电影响到DPDM，已发出
   开了OTG_CHARGE_MODE导致的
** 爱尚636X
   红外跟sniff兼容问题，还没搞
** 吸铁石697X
   新210版本，无法修改唤醒边沿，还没搞

* 20201023
** pwm_led模块
   static void _led_pwm_output_logic_set(u8 pwm_inv_en, u8 shift_num)
   pwm_inv_en: 1：推低电平灯亮，0：推高电平灯亮；
   shift_num：一般用在单io推两个灯，配置为1，就是第1个周期低电平灯亮，在第二个周期硬件会自动切换到推高电平；
   一个周期内非推灯时间的状态时高阻
** TCL通力电子
   评估961芯片性能，指标文档缺失，需要珠海确认完善，再发给客户
** 剑锋961
   数码管充电仓改好3个问题，还剩一个关机功耗大，跟珠海对接中
** 众鸿6951
   007车机方案获取ID3，信息超长时会死机复位，最新的库是正常的，让客户同步测试

* 20201022
** 剑锋961
   反馈4个问题，处理中
** 国华6368
   BLE速率堆包，DP电压异常，已处理
   PA6跟DP双绑，开了PA5打印后，PA6被启动了
** 美师傅697X
   V211立体声声音异常，改了一个程序给客户
** 博建697X
   V211的BLE广播异常，测试公版没问题
** 华炬芯961
   UI修改，改了一个demo给客户
** 中翔达6963
   数字音量方式，最大提示音之后，无声音，处理中

* 20201021
** 彩荣6951C
   对箱配对无声音，断连等问题，客户自己改成发起配对前删除配对信息，工厂已经确认OK，具体原因未知
** 爱尚636X
   内置充电功能，已告知
** 吸铁石697X
   某个板级开BLE会开不了机，测试210正常，已发客户升级
** 华炬芯961
   案子UI修改，支持客户自己改

* 20201020
** 剑锋961
   充电仓项目，已发一版程序
** 彩荣6951C
   对箱没声音接着断连问题，realme容易出现，其他手机很难出现，处理中
** 慧杰6951+6956
   几个问题，处理中

* 20201019
** 剑锋961
   数码管充电仓，插USB再放耳机有概率会没升压，但软件是判断已升压，处理中
** 伦茨961
   带霍尔进充电自动配对功能，无霍尔放耳机要立即充电，已验证好，发给客户
** 彩荣9651C
   生产有机子会死机，PA14问题，换库可以，烧录第一次开机蓝牙连接问题，客户复现不到，跟进中

* 20201016
** 剑锋961
   数码管充电仓，调试中
** 德科创695X
   发射器带BLE主动切换，007目前问题很多，让客户走邮件，再看怎么处理

* 20201015
** 剑锋961
   数码管充电仓调试中
** 传音961
   充电仓，待调试
** 中翔达961
   A980项目NTC问题，已处理

* 20201014
** 猫王6926C
   PVXE、P1C项目已发出
** 剑锋961
   V8案子数码管带6个灯，调试中
** 科奈信961
   仓自动配对，影响耳机回连，公版测试不到，跟进中
** 汇杰芯6368
   AT工程OTA升级，已告诉客户修改方式
** 众鸿695X
   获取手机蓝牙缺失字符，珠海已改库，测试OK

* 20201012-20201013
  请假2天

* 20201010
  值班一天
** 中翔达AD138
   添加NTC功能
** 猫王6926C
   PVXE、P1功能修改
** 博建6936D
   搭配别人的智能充电仓，放一个耳机进去，会断连
   搭配AD138的就不会

* 20201009
** OTA升级安卓手机APP目录
   旧安卓系统：此电脑\NEM-UL10\内部存储\com.jieli.otasdk\upgrade\update.ufw
   Android 10:此电脑\nova 4e\内部存储\Android\data\com.jieli.otasdk\files\com.jieli.otasdk\upgrade\update.ufw
** 大康6973
   充电死机亮红灯，珠海改库，客户还是能测到一次，跟进中
** 剑锋961
   充电仓外挂充电IC，带数码管跟跑马灯，现有SDK还没法调试，跟珠海沟通中
** 众鸿695X
   上次珠海改的获取手机蓝牙名死机问题，客户测出，有些手机会漏掉最后一个字符，处理中
** 汇杰芯6368
   手机APP OTA升级解析失败，改了一个程序给客户测试

* 20201008
  出差一天
** 中翔达大康6973
   还剩3个问题，充电死机问题---对耳大小声---断连再秒连

* 20201001-20201007
  国庆放假7天
* 20200930
** 697X正弦波提示音
   #define SYS_DEFAULT_TONE_VOL     0//14
   #define SYS_DEFAULT_SIN_VOL    	16//8
   #define SINE_TOTAL_VOLUME        3355443 //6710886 //16106128 //26843546 //20132660 //26843546
** 631N用OTA升级
   需要留出65K的空间给OTA
** 鑫闻达6973D
   关打印开不了机，内置触摸无法开机，已处理
** 联巨兴6368
   串口丢数据，
   695X音箱BLE问题，已处理
** 中翔达6976
   正弦波提示音音量调节，wav叠加死机，已处理

* 20200929
** 6368烧录
   CHIP_NAME=AC636N;//8
** 起华6936D
   对耳不跳电，已发出
** 中翔达科奈信6976
   音量同步问题，用手机复现不到，
   反馈通话近端喇叭声学测试不过，沟通中
** 威益德690X
   开了HID触摸功能，连安卓有概率蓝牙mac被改，公版复现不到，协助客户测试中
** QCY
   无法配对
   可能是耳机没有加CRC的命令

* 20200928
** 出差一天
   处理中翔达科奈信961充电仓电压跳变问题

* 20200927
** 961参数
*** 电池电压表
   //3.20V == 0x00 == 0
   //3.30V == 0x0A == 10
   //3.40V == 0x14 == 20
   //3.50V == 0x1E == 30
   //3.60V == 0x28 == 40
   //3.70V == 0x32 == 50
   //3.80V == 0x3C == 60
   //3.90V == 0x46 == 70
   //4.00V == 0x50 == 80
   //4.10V == 0x5A == 90
   //4.20V == 0x64 == 100
   3.2V - 4.2V,1V的电压差,分成100档
*** IO口输出电压
    跟随系统最高电压
    只有电池的时候,IO口的电压，跟随电池电压，大概减0.2-0.3V
    有vcc充电时候,IO口电压,跟随VCC的电压5.0V，待测
    VCC在线，但不充电，关了PMU，跟随4.6V的电压,待测
*** NTC用ADC采集数据
    #define NTC0C_O    (350)//(330-80)
    #define NTC45C_O   (40)//(42-15)
    #define NTC_0_C    ((0xffc0 * NTC0C_O) / ( 100 + NTC0C_O))   //0xC6EA
    #define NTC_45_C   ((0xffc0 * NTC45C_O) / ( 100 + NTC45C_O)) //0x4912
    
    // 要是NTC上拉到VCC,只有在充电状态下才能用

    //科奈信NTC,室温100K,IO上拉100K,室温25度,满值电压的一半
    //0xFFC0 /2 == 0x7FE0
    //0xF7C0 /2 == 0x7BE0
    //只有上拉100K == 满值 == 0xF6C0 -> 0xF7C0(vcc)
    //       -1度 == 368K == 0xC2C0 -> 0xC2C0(vcc)
    //      25度  == 100K == 0x82C0 -> 0x8280(vcc) //示波器看刚好一半电压
    //      28度  ==  87K == 0x7280 -> 0x73C0(vcc) //ntc可能电阻变化了
    //      48度  ==  36K == 0x3EC0 -> 0x3EC0(vcc)
    // 下拉到地0   ==  0值 == 0x0000
*** 打印口
   使用P17打印时,不能开pmu_common.h的p_deg_char打印
   会导致充电异常,芯片烧掉
   建议使用P16打印,睡眠唤醒,进充电,都要重新初始化下IO

*** 不带霍尔的
**** 没有耳机插入的时候
    VOUTL、VOUTR默认是3.4V的电压
    睡眠后也是3.4V的电压
**** 耳机在线的时候
     插入耳机后,通信一段时间后,电压抬升到4.6V,进充电状态
     充满后,进睡眠,VOUTL、VOUTR电压为400mV
     耳机拿出会唤醒充电仓

* 20200926
** 科奈信
   加班一天
   出差科奈信处理961-A1018充电仓

* 20200925
** 961
   使用P17打印时,不能开pmu_common.h的p_deg_char打印
   会导致充电异常,芯片烧掉
** 中翔达科奈信961
   1080项目，处理中
** 猫王6926C
   PVXE项目，已发出

* 20200924
** 尚凌6965E
   音箱SDK几个问题处理，已发出
** 众鸿695X
   电话本串口跟线程demo，已发出，华为6s异常复位，帮珠海跟客户沟通
** 猫王6926C
   PVXE项目几个问题，准备看

* 20200923
** 尚凌696X
   喊话功能，走混响，去掉湿声增益即是原音
   reverb_api_obj->parm.wetgain = 0;//4096;	//湿声增益：[0:4096]
** 尚凌696X
   已处理3个问题，还剩sd死锁，蓝牙初始化卡住，等珠海修改
** 众鸿695X
   车机案子，串口、线程和蓝牙中断回调的协调处理demo，处理中

* 20200922
** 天浪690X
   玩具SDK做BQB认证不过，处理中
** 众鸿695X
   车机项目，死机重启断连连不上等问题，处理中
** 尚凌
   696X、6368  几个问题，待处理
* 20200921
** 巴达木961
   问题支持，已处理
** 天浪696X
   BLE、PWM，已支持
** 天浪690X
   BQB认证不过，处理中
** 蓝牙HCI错误码
   Vol 2 
   PartD ERROR CODES

* 20200918
** 猫王6926C
   PVXE、P1，2个新案子已发出
** 中翔达
   科奈信961-A1018
   基本完成，今晚发

* 20200917
** 猫王
   P1E、PVXE
** 恒大
   版本号格式、MAC地址写失败
** 科奈信
   961充电仓
** 众鸿
   6951车机，11个问题支持，还剩8个

* 20200916
** 淇诺
   697X、961问题支持
** 中翔达
   695写VM看门狗复位
   数码管扫描用的timer2,调用函数都要放到ram里面
   SDK的delay();没有放到ram,需要自己重写

* 20200915-20200914
  请假2天

* 20200911
** 中翔达合律美
   6936D通话没声音
   mic脚短路到地，原因未知
   打的回家

* 20200910
** 春苗695X
   007版本开BLE数传，切模式后开不了广播，已改好
** 中翔达961
   出差科奈信讨论充电仓功能，要改成961来做

* 20200909
** 伦茨6936
   069的SDK，数字音量来电不行，已改好给客户
** 伦茨6925
   电流声，关了自动mute一直有，建议客户先查查板子硬件
** 易路发6976
   爆空间，客户音源转PCM数组，有186K大，让客户用1M

* 20200908
** mesh
   BT_MESH_FEAT_PROXY  可以连手机
   BT_MESH_FEAT_RELAY  中继功能
** 晶振封装
   3225
   2016
** 伦茨961
   烧录不良，珠海要看烧录打印，协助中
** 联巨兴631X
   mesh应用，试了SDK能用，但是用不了sniff模式，需要客户提供详细需求，再找珠海改协议栈
** 广利达696X
   混响死机，珠海改库OK，录音死机，处理中
** 德芯成961
   3代UI，已烧芯片寄出

* 20200907
** 广利达696X
   025混响死机，公版能测到，找珠海处理中

* 20200904
** 倍思951
   S1充电仓死机，低电按键led无作用，已改一版程序给珠海
** 德芯成961
   呼吸灯等UI效果，调试中

* 20200903
** 倍思961
   S1充电仓，改了一版软件，珠海还测到低电有问题，还没测
** 德芯成961
   呼吸灯效果，调试中
** 广利达696X
   异常复位，杂音问题，处理中

* 20200902
** 爱尚692X
   小米手机BLE断连问题，珠海改库可以
** 巴达木6969
   BLE案子开发，已支持
** 倍思951
   充电仓问题，处理中

* 20200901
** 爱尚692X
   小米手机连接BLE，会有断连现象
   根本原因是手机蓝牙模组有问题
   珠海更新库
** 源创杰696X
   DM脚读状态不对，提高VDDIO到3.4V，就可以
** 海勤6368
   纽扣电池供电复位，灯一直抖动，处理中
   纽扣电池寄秉铨

* 20200831
** AC8976+951
   开了ANC功能,LDOIN必须配下拉电阻使能
   chargestore_get_f95_det_res(200);//1600
   200K下拉
   伦茨测试还是不行
** 华炬芯636X
   脚踏翻页器，report map获取，已发出

* 20200829
** 普利金6936D
   插某些空线USB，会频繁进退PC模式，原因未知，
   加了定时查询过滤再切换模式，测试可以
** 伦茨8973+ANC
   配951充电仓使用，拿不到充电仓电量，
   公版SDK默认开了LDOIN下拉导致，待确认是否会影响ANC
** 源创杰6969
   2M工程推PWM有问题，处理中

* 20200828
** 巴达木696X/693X
   3代的3个问题，转问下珠海
   来电提示音手机没播放，只有振动
   序列号留接口改
   pbg_config_user_feature影响到音量等级
** 爱尚6368
   功耗必须要烧录器烧录
   而6318不用烧录
   得确认1拖8烧录是否能正常

* 20200827
** 中翔达和天罡微697X
   复位源接口，已发出
** 爱尚6368
   蓝牙广播工作功耗大，6318只有700uA，6368有2.8mA，导致整体功耗偏高，处理中
** 春苗695X
   变速算法库，运算有问题，珠海也看不出啥原因，处理中
** 美师傅6311
   timer3做PWM输出有问题，更新问题文档，已发出
* 20200826
** 中翔达697X
   获取复位源，公版没有，得珠海改
** 春苗695X
   变速库，加了，不正常，还在看
** 美师傅692X
   串口导致linein杂音，客户想改板了
** 美师傅6311
   timer3没法任意映射出PWM，还没测

* 20200825
** QCY
   T7-961  功耗大，已处理
** 众鸿695X
   获取电话本死机，还在跟立辉测试，处理中
** 科美690X
   APP调EQ，第10段频点对不上，已复现，得珠海处理
** 美师傅692X
   串口RX影响到linein有杂音，uart跟lienin都是uart2的引脚，支持中
** 春苗695X
   变速功能，珠海发了个算法库，还得二次封装才能用，还没处理

* 20200824
** 众鸿695X
   电话本死机问题，珠海测不到，协助测试中
** 文晟6369F
   下载程序跑不起来，V4.0的软件问题，换芯片，更新下载器程序
** 倍思S1-951
   已完成
** QCY
   T8-961关机功耗大，现象跟珠海不一样，
   耳机不在仓功耗大，珠海查，
   耳机在仓功耗大，这边先查一下
* 20200822
  请假一天

* 20200821
** qcy
   关机功耗大
** 禾声AD138
   V05的SDK配8976是正常的，客户装机问题
** 631X
   const int config_btctler_le_rx_nums = 8;///8;//4;///接收write
   const int config_btctler_le_acl_packet_length = 27;///251;//27;//notify发
   const int config_btctler_le_acl_total_nums = 6;///8;//6;
** AC961
   SDK编译生成不了o文件
   要重新注册license

* 20200820
** 众鸿695X
   23个问题处理，遗留一个死机问题，2个需求，待处理
** 国华636X 
   APP OTA升级，已发给客户
** 内部961
   串口通信协议，测试中，再处理德芯成的961案子
   更新仓的程序，不修改耳机的程序

* 20200819
** AC951
   配693X，会出现长按配对不了现象，去掉减1
   /* read_len = (read_len>(__this->max_packet_size-1))?(__this->max_packet_size-1):read_len; */
   read_len = (read_len>(__this->max_packet_size))?(__this->max_packet_size):read_len;
   明文通信跟密文通信，最大包长度不一致导致
** 961无线充
   无线充线圈用15uH
** 697X
   030的SDK，用F95的充电仓配对不了
    /* write_len = (write_len >= len) ? len : write_len; */
    write_len = (write_len >= len) ? len-1 : write_len;

* 20200818
** 华炬芯AD138
   用在AC8976加密通信，开发板测试通信都正常的，客户样机不清楚为啥，客户回去查
** 吸铁石897X
   AI耳机问题支持

* 20200817
** 起华6956F
   通话电流声，没声音，省电容模式
   处理中
   4路DAC模式，不能用省电容模式？
** 老树开花6926A
   推灯IO改成了PD口导致的
** 猫王6926C
   提示音修改

* 20200815
** 猫王6926C
   提示音修改
** AC956
   整理文档
* 20200810-20200814
  出差珠海
* 20200808
** 国华6318
   功耗大,进不了sniff
   USB开了串口功能，不能把打印线和DMDP短接，初始化串口过不了
** 彩荣6951
   对箱功能3个问题
** 起华6936D
   更新补丁库，066版本换不跳电
** 汇杰芯6976D
   功耗大,重新烧录一颗芯片换上去就好
   原芯片为啥关机1mA,不清楚
** 猫王6926
   底噪大，客户寄板明天处理
** 中翔达大康6936d
   打完电话进sniff有哒哒声
   #+BEGIN_SRC c
   void sleep_enter_callback(u8  step)
   {  
       /* 此函数禁止添加打印 */
       if (step == 1) {
           dac_power_off();
       } else {
           if((JL_AUDIO->DAC_CON>>4 & 0xFF)!=0x08){
               SFR(JL_AUDIO->DAC_CON,4,8,0x08);
               /* dac_power_off(); */
           }
       }
   }
   #+END_SRC
* 20200807
** 微纳研究院
   等振荣开放底层接口给客户
** 中翔达6936D
   通话后进sniff有哒哒声,有时进sniff没有dac_power_off()
   通话静音铃声
   弹窗慢，改时间间隔
   dut被对耳连接,要复位后开可发现可连接
* 20200806
** 复位源
   VDDIO POR   (上电复位)
   VDDIO LVD   (低电复位)
   WDT     (看门狗复位)
   VCM     (按板子上的reset键复位)
   PPINR     (长按几秒复位引脚复位)
** 纵横世纪6368
   开发多个问题支持，已OK
** 尚凌6976D
   充满之后要关掉LDOIN下拉电阻，已OK
   充满后把__this->data->ldo5v_pulldown_en清零,底层会掉用
** 起华6963
   3款案子，处理中
* 20200805
** 纵横世纪6368
   开发多个问题支持，已OK
** 尚凌6976D
   充满之后要关掉LDOIN下拉电阻，已OK
   要直接清0变量__this->data->ldo5v_pulldown_en = 0;
** 起华6963
   3款案子，处理中
* 20200804
  出差巴达木华旭益一天
** 巴达木6963
   处理多个问题
* 20200803
** 杰辰芯6368
   芯片烧录跑不起来，是烧录工具V4.0的某个版本软件激活此现象，
   升级烧录工具程序可避免，芯片原因还未知
** 国华6318
   串口唤醒问题，改了一版程序给他
** 起华6963
   2个案子，调试中
* 20200801
** 科普豪6976D
   通话声音不正常，mic的问题，换mic处理
* 20200731
  出差1天
** 德芯成6936D
   066的SDK测试通话会出现死机现象
   加了一些保险手段进去预防
* 20200730
** 源创杰693X
   数字音量，通话调，会突然静音，改了一个版本，客户测试中
** 乐心631X
   FCC定频问题，珠海在改
** 组创631X
   IO中断，10us快速中断死机等问题，已OK
** 春苗695X
   TF卡IO供电升级死机，换ota.bin已OK
** 国华692X
   软关机后，重新开机PR1无作用
   设置PORTR_DIE(PORTR1,1);即可
* 20200729
** 虹日693X
   电表项目，还有2个问题，要华悦处理
** 虹日631X
   功耗跟功率问题，已ok
** 国华631X
   HID工程加透传功能，处理中
* 20200728
** 虹日693X
   电表2主3从协议开发中，需要华悦添加SMP协议
** 源创杰6936D
   调音量哒哒声，改数字音量，通话后声音大小不正常，处理中
** 威益德690X
   电话本卡20秒，卡原因未知，添加结束符判断机制，效果可以
** 爱尚631X
   高电平长按复位，已支持
* 20200727
** 蓝牙功率
   pwr：bredr 链接上、被发先 被链接 最大功率
   pg_pwr  ：bredr 回链最大功率
   iq_pwr：bredr 搜索最大功率
   ble_pwr：ble 最大功率
** 虹日693X
   国网电表2主3从功能开发中
** 源创杰693X
   数字音量加淡入淡出，还不行，处理中
** 威益德690X
   电话本卡时间，公版用客户的库，测试不到，协助测试客户程序
* 20207025
  请假一天
* 20200724
** 伦茨6936D
   播歌偶尔卡音，改了版程序给客户测试
** 伦茨6969
   收音提示音白噪声，换珠海库OK
** 起华6936
   6963 2款案子程序修改已发出
** 源创杰693X
   调模拟音量有哒哒声
   改数字音量加淡入淡出，未改完
* 20200723
** 美师傅696X
   timer3会死机，要清中断
   extern void bit_clr_ie(unsigned char index);
   bit_clr_ie(IRQ_TIME3_IDX);
** 也杨692X
   修改spp-UUID
   u8 user_spp_UUID[16]={65d6928c-9f17-4fcc-aa55-0bf0f45bcee1}; /*自己写成1byte1byte的形式*/
   extern u8 de_size_128_buf_dueros[];
   memcpy(de_size_128_buf_dueros,user_spp_UUID,16);
** 国华6318
   HID设备开发，已支持，客户回去开发
** 美师傅696X
   timer3死机，已OK
** 伦茨6936
   TWS配对提示音功能，处理中
* 20200722
** ANC
   anc要用的仪器的型号：兆华  CRY6151-ANC 降噪耳机产线校准测试系统
** 测试盒BLE升级
   const int config_update_mode = UPDATE_BT_LMP_EN | UPDATE_STORAGE_DEV_EN | UPDATE_BLE_TEST_EN;
** 淇诺697X
   培训
** 德科创631X
   EDR的HID设备，按键开机搜不到设备，SDK流程问题，少了个函数
** 芯中芯697X
   opus发送spp卡跟BLE卡，卡原因未知，加了一些其他的缓存处理
* 20200721
** 羽恒696X
   串口死机
** 德科创631X
   HID设备，荣耀6和10，当设备和蓝牙开关同时关，再开，无法回连
   原因未知
** 威益德690X
   蓝牙ID3，后台播歌，再主动返回，无信息，待确认
** 科普豪692X
   发射器开BLE，无法测试盒升级
   做2个模式，复位重启，只开EDR，关掉BLE初始化
* 20200720
** 博威6936D
   通话效果，调试中
** 美师傅631X
   USB当AD口，测试正常
** 组创631X
   OTA升级，030版本正常
** 猫王6926C
   开TWS，改696X来做
* 20200718
** 猫王6926C
   AI开TWS，连接会软复位，需要珠海协助
** 美师傅695X
   中控耳机内置充电一直在复位，改好发给客户
** 新时代692X
   APP连杰理，对比BK机子，通信速率慢，看抓包，搜索服务不一样，原因未知
* 20200717
** 猫王6926C-P1
   AI开TWS，目前能编译过，等客户寄板子过来测试
** 以色列
   培训老外631X开发
** 西米6976D
   充不满就提示充满
   烧录器烧录后正常
** 德凯芯695X
   020数传SDK，只开SPP在手机上设置界面连接
   EDR和BLE共MAC地址
   替换库可以
* 20200716
** 起华6936D
   JWT01通话电流声，改软件测试还可以
** 起华6936D
   TWS02M无端唤醒Siri，触摸IC少焊了一个灵敏度电容，客户已装机，得看客户打算怎么处理
** 国华AD138
   几个问题支持，内置充电无法仿真，开发板设计有问题
** 猫王6926C
   P1要带TWS，爆ram，看看要怎么搞
* 20200715
** 佳联芯AD138
   几个问题处理，
   剩一个华为无线充兼容性问题，珠海自己买产品测试，等珠海处理
* 20200714
** 起华6956A
   H3升级SDK，已发出
** 起华6936D
   JWT01案子，已发出
** 国华631X
   长按复位功能，客户测试还不行，支持中
* 20200713
** 春苗695X 
   点读笔2个死机问题，已OK
* 20200711
** 起华6963A
   VT耳机带功放，有啪声mute不到，暂时先关sniff处理
** 虹日6932C
   国网电表新协议开发，处理中
* 20200710
** 羽恒695X
   BLE打印机，时延跟打印问题，已OK
** 内部AC6311A2-TH
   新flash封装芯片测试，结果已发珠海
** 起华6963
   VT案子调试中
* 20200709
** 博建6928
   拔卡死机，改程序已OK
** 伦茨和春苗695X
   音箱充电死机，处理中
* 20200708
** AC6973D8
   USB下载不了,芯片DP跟PA5双绑,要关掉uboot的串口
   #UTTX=PA05;//uboot串口tx
** 联巨兴695X
   linein录音，给了方法客户了
** 也杨692X
   电话本功能，珠海改库，测试OK
** 德科创631X
   BLE认证，FCC可以，BQB不行
** 芯中芯7963D
   下载不了，PA5是uboot打印，和DP双绑
* 20200707
** 伦茨695X
   通话自动mute问题，左右声道调反，都给了demo程序给客户
** 恒大692X
   蓝牙断连问题，今天还没测到，明天再测一天
* 20200706
** 晶诚威696X
   几个问题，剩一个串口升级问题，得珠海处理
** 台德696X
   EQ音质问题，改了个版本给客户，测试中
* 20200704
** 台德6968
   音质反馈有新的问题，在确认客户所说问题点，再找珠海
** 乐心631X
   创建线程，创建队列等功能，改了个demo给客户
** 乐心631X
   配对绑定功能，每次连接输配对码，加了PnP属性，已OK
** 虹日6933C
   国网电表项目，处理中
* 20200703
** 羽恒695X
   音箱SDK-BLE连不上测试盒
   const int config_btctler_single_carrier_en = 1;
** 低压档位
   6318 LVD 烧写 最低档 155V
   6968 LVD 烧写 最低档 190V
   6318 配置 ini 用户设置 最低档 155V
   6968 配置 ini 用户设置 最低档 190V
** BLE配对绑定功能
   只要第一次输入,回连不输
   ble_sm_setup_init(IO_CAPABILITY_DISPLAY_ONLY, SM_AUTHREQ_BONDING, 7, TCFG_BLE_SECURITY_EN);
   #if 1   // authentication
   10, 0x00,   0x00, 0x00,    0x1A, 0x00,     0x00, 0x28,     0x0A, 0x18,                                     //primary service declaration
   13, 0x00,   0x02, 0x00,    0x1B, 0x00,     0x03, 0x28,     0x02, 0x1C, 0x00, 0x50, 0x2A,                   //characteristic declaration
   15, 0x00,   0x02, 0x04,    0x1C, 0x00,     0x50, 0x2A,     0x02, 0x8A, 0x24, 0x66, 0x82, 0x34, 0x36,       //PnP ID
   #endif
** 也杨697X
   030,sbc提示音复位，暂不支持
** 羽恒695X
   测试盒无法连接006的BLE，已OK
** 台德696X
   音质问题，客户已确认

* 20200702
** 锦亨源692X
   BLE卡到蓝牙播歌，调整串口的中断优先级
** 伦茨695X
   siri按键音，加个打断的参数标志，没测到，发给客户验证
** 台德696X
   限幅器问题，反馈失真大，达到5%，了解情况中，再转给珠海
** 汇杰芯630X
   注册定时器导致异常中断
   sys_timeout_add的注册函数里，不能用sys_timeout_del，只需要把变量置0
* 20200701
** 起华6936D
   2个案子调试，还有1款处理中
** 春苗695X
   变速变调，不能变速，处理中
** 羽恒695X
   单模BLE，连测试盒，发了测试盒升级程序
* 20200630
** 出差1天
** 大康6936D
   烧录器烧的是LVD--2.5V
   VDDIO校准要先关LVD
   #+BEGIN_SRC c
    P33_CON_SET(P3_VLVD_CON, 6, 1, 1);
    P33_VLVD_EN(0);
    u8 vddiom = GET_VDDIOM_VOL();
    u8 vddiow = GET_VDDIOW_VOL();
    VDDIOW_VOL_SEL(VDDIOW_TRIM_IDX);
    udelay_osc(200);
    VDDIOM_VOL_SEL(VDDIOM_VOL_20V);
    udelay_osc(100);
    for (int i = 0; i < 10; i++) {
        while (!(JL_ADC->CON & BIT(7))) { //wait pending
        }

        vbg_value_w  += JL_ADC->RES;
        JL_ADC->CON |= BIT(6);
    }
    VDDIOM_VOL_SEL(vddiom);
    VDDIOW_VOL_SEL(vddiow);
    P33_VLVD_EN(1);
   #+END_SRC
* 20200629
** 打的回家
** 中翔达6936
   充电功耗大
   芯片一直在VDDIO_LVD复位，adc_api.c注释掉一段代码
   避免VDDIO设置的比LVD还低
** 中翔达696X
   切换配对码，U盘SD卡复用等问题，已发客户
** 美师傅696X
   linein复位问题，立体声只能走模拟
** 伦茨6936
   充电充满死机，给了改法
* 20200628
** 春苗695X
   删除文件操作，珠海给的方法会复位，变速变调，一个声道变音一个声道正常，还没看
** 台德6968
   eq限幅器问题，珠海评估中
** 中翔达696X
   配对按键功能，处理中
* 20200624
** 出差一天
   巴达木华旭益调试
   6969对耳案子，通话效果客户已确认，
   6963中控耳机，功能已确认，开机噗声待优化
   （用隔电容接喇叭对地方式，客户评估是改用6966还是拿生产喇叭再优化）
* 20200623
** 中翔达696X
   升级、断点，已完成，eq问题，EQ还没头绪，其他问题还没看
** 中翔达695X
   升级死机，没试到，让客户在开发板不加key试试
   006用U盘升级有兼容性问题，替换珠海ota.bin
** 汇杰芯6313
   烧1.55V，配置错误，换个硬件板子烧录器OK，原因未知
* 20200622
** 伦茨6969D
   linein看门狗复位，注册定时器清狗
   吱吱声JL_AUDIO->DAC_CON &= ~0xf000000;
** 中翔达696X、695X
   7个问题
* 20200620
** 起华6936D
   通透模式，跟IOS配置设置，第一次开机配对，通道被改，没查到
* 20200619
** 起华6936D
   带光感和通透的功能，已发出
** 631X
   问题处理文档和SDK介绍文档，在写
* 20200618
** IOS-BLE-连接参数
   latency限制是30
   timeout限制是100
   interval * 1.25 * latency = 1s
** 虹日6313
   关机后，铁板靠近，功耗会升高，改软件OK
   关机必须设置gpio_dieh(GPIOA, 0, 16, ~porta_value, GPIO_AND);
** 伦茨6969
   ADkey复用推灯，灯常亮为微闪，改成占空比最高，变成IO推灯，已OK
** 起华6936
   耳机配对连接会弹确认框，手机原因，无法去掉
** 恒大6926
   煲机断连，目前改成latency最大被IOS限制成30，以此参数测试中
* 20200617
** 631X
   idle模式进入power_down,睡眠时间不能超4s,看门狗复位时间
   功耗在30uA左右
** 虹日6313
   power_off之后，会复位现象，改软件OK
   关机功耗，手靠近会有功耗波动，要设置dieh寄存器
** 尚凌6976
   EQ问题，已处理
* 20200616
** 德科创6313
   乐心客户培训，血压计蓝牙透传产品评估，功耗跟启动时间达不到客户要求，建议客户做成常待机
** 易路发6318
   蓝牙遥控器，蓝牙断连，无法强升，瞬态电流时间过长等问题，处理中
** 科普豪692X
   亚马逊认证，连苹果手机，音量同步问题无法解决，给了个修改方式给客户避免被终端发现
** 汇杰芯6936D8
   064的SDK无法测试盒升级，珠海更新ota.bin已OK
* 20020615
** 欣瑞声6969A
   生产20%充电充满后，反复激活
   是触摸IC傻掉了
** 虹日6313
   LVD烧录1.55V,实际是1.75V复位
* 20200613
** 欣瑞声6969D
   生产20%机子充满电后会反复激活充电仓，
   初步判断是VDDIO切换的时候导致触摸傻掉,触摸输出为变为0，唤醒了主控，
   主控重新开机，功耗会大，导致激活5V
   待珠海改库测试
* 20200612
** 欣瑞声6969
   升级V014的SDK，充满后反复唤醒，工厂升级100台，还有20台会，明天客户带过来
** 华炬芯692X
   QCC连692X的BLE，断连、复位问题，处理中
   QCC会认gatt的几个标准复位0x1800、0x1801，否则会断连
   V2.5.1会复位，是有一个未知的le层命令，断言复位,V2.6.3正常
** 起华6936D
   生产2个项目有问题，还没搞
** 互诺6313
   FCC认证问题，还没测
** 虹日6313
   LVD烧1.85V异常问题，处理中
* 20200611
** 伦茨6969D
   DAC声音有沙沙声，公版SDK就有，给了客户避免的方法，原因要珠海找
** 鑫闻达6966
   对耳支持低时延模式，珠海说不支持
** 汉欣诺6951A
   串口动态调高低音，已发客户
* 20200610
** 天浪690X
   BLE在收数据时，关机会死机，支持中
** 源创杰690X
   硬件PR2被外围锁定成低，U盘升级会复位造成死机，已处理
** 德科创6318
   定时关机后，立马又重启，已处理
** 伦茨6969
   播歌杂音，连测试盒复位，无端切模式，mcpwm输出不了等问题，已OK
** 鑫闻达6963
   2个IO推灯，低时延对耳断连，处理中
* 20200609
** 易路发6318
   关机功耗大，已OK，
   瞬态电流14mA时间过长，暂不处理
** 爱尚6303
   PWM输出，用户手册介绍有误
** 华炬芯630X
   内置充电，处理中
** 新智造6318
   换了几个芯片都提示下载flash错误，让客户寄板子过来
** 威益德690X
   串口升级卡40s，已OK，
   pin_code跟蓝牙名A开头，会不弹框，还没测试
** 伦茨693X
   安卓BLE弹窗，需要修改广播类型，填充rsp，已OK
* 20200608
** 虹日6313A
   替换nordic模块，功率无法调节，需珠海协助
** 易路发6318
   工作功耗已OK，关机功耗处理中
** 华炬芯6303
   长按复位已OK，内置充电，还没看
** 爱尚6303
   PWM功能，还没调
* 20200606
  请假1天
* 20200605
  请假1天
* 20200604
** 华炬芯693X
   音箱双模SDK，数字音量杂音，按键音变调，给了改法，至于死机问题，客户那边也复现不出，待处理
** 科普豪692X
   亚马逊平板兼容性问题，海华在263的SDK上，新加了HSP、HID协议，已OK，跟客户沟通，升级SDK处理，旧的SDK不更新
** 汉欣诺695X
   6x11断码车机屏，已点亮，SDK驱动没做好
** 汇杰芯、德科创6318
   功耗大，秉铨改库，还没测
** 西米697X
   AI的SDK死机问题，还没测试新发的SDK
* 20200603
** 科普豪692X
   亚马逊平板，HFP连不上,没有走HFP-AG协议，
   走的是HSP的流程，SDK没有做这个，海华协助处理
   HSP只支持sco，效果较差，所以没做
** 华炬芯693X
   双模音箱SDK，反馈3个问题，主要的死机测试不到，
   其他小问题，测试了好几个，处理中
** 台德692X
   dut功率低，珠海改库，测试可以
* 20200602
** 起华6936D
   带光感的板子，有部分机子，无法开盖开机，处理中
   起华下面方案商培训
** 易路发6303
   自拍遥控器，抓包，发的是音量加的命令
** 伦茨6936D
   分离度，隔电容，crosstalk串扰才能测试到-60dB
   VCOMO接法，测试不到
* 20200601
** 631X
   启动电压要用烧录器烧录，LVD用1.85V档位
   要不然要2.8V才能启动
   LDO的功耗，只能做到250uA级别
   DCDC才能改到60uA级别
** 起华6936D
   2款机子，功能功能修改，已发出
** 羽恒695X
   006的SDKBLE功能开发，改了个demo给客户
** 德科创6318
   功耗问题，hid的工程较低，透传的工程很高，还在查找中
* 20200530
** 请假1天
* 20200529
** 德科创6318
   功耗问题，需要珠海协助，处理中
** 汉欣诺695X
   电话本问题，已ok，普通hid是可以的，hid触摸问题，还在支持中，
** 西米697X
   讯飞AI，opus编码复位，需要珠海处理
** 华巨芯693X
   双模的SDK，几个问题，还没看
** 起华6936D
   A3功能修改，还没改
** 伦茨6936D
   mic频响曲线，067加了限幅器，改库可以，天师改
   DAC等响度等问题，自动mute有问题，少文改
* 20200528
** 威益德690X
   字符串转UTF编码，分包串口发送，客户测试可以
** 德科创6318
   广播工作低功耗只能到700uA，6303A却正常，让客户寄板子过来
** 汉欣诺695X
   006的SDk多个问题，还没看
* 20200527
** 动态传profile数据
   void att_set_db(uint8_t const *db);//change profile_data
   也可直接修改profile的数据,重新连接会自动更新
** 起华6936D
   2款功能修改，已发一款，还有一款还没改
** 西米6972A
   科大讯飞AI耳机，功能调试，支持中
** 德科创、汇杰芯
   63的案子  支持开发中
** 汉欣诺695X
   在电话本回调函数，调用串口，会导致电话本中断，和发送数据不对，试了几个改法，客户都说不行，还没空看
* 20200526
** 出差恒大一天
   处理6926A低温-20°C下BLE丢包断连问题，现场未复现
   留了2套方案给客户测试，
   一个改软件提高内核电压，晶振强驱
   二是改硬件，改用外部电容
** 德科创、汇杰芯
   6303A  工作低功耗的改法
   USB有2组口，要设置成高阻态，要不然漏电400uA
** 爱尚6318
   瞬态电流大，珠海改库后
   6303A跑LDO第一次上电52mA，第二次上电14mA
* 20200525
** 爱尚6318
   瞬态电流大，刚开始说DCDC可以，改成LDO又说不行了，还没测
** 德科创6303
   动态修改profile，连接参数等，还空搞，让客户自己先试
** 汇杰芯6956
   提示音后sbc卡音，更新SDK019可以解决
** 伦茨6936D
   充电一直没充满，6959灵敏度差，dac左右不平衡，通话杂音等，还没处理
   充满电流截止电流5mA，有3%机子永远无法充满
* 20200523
** 盛鑫源6903A
   sniff断言失败，改了一个流程给客户，未反馈
** 德科创6303A
   动态修改广播间隔参数，异常中断，解决
** 爱尚6318
   瞬态功耗高，测试数据跟珠海一致，目前只能到21mA，达不到客户需求
* 20200522
** 锦芯6936D
   没有放关机提示音,导致没有提示音结束的消息，导致没有实际关机，把机子耗没电
** 摩天6936D
   关机流程：先提示音结束，灯才灭，等按键松手，再关机
* 20200521
** 630X
   硬件复位,PB2有个短按即复位的功能
    //< close short key reset
    p33_and_1byte(P3_PR_PWR, ~BIT(3));
    //< close long key reset
    p33_and_1byte(P3_PINR_CON, 0);
** 盛鑫源6303A
   sniff和串口通信，冲突死机，给了一个方法给客户，客户还没测试
** 爱尚6318
   瞬态电流大，秉铨改了几个库，测试都不行
** 尚凌692X
   录音大容量U盘有问题，测试到2个问题，得珠海协助
** 联巨兴690X
   linein录音丢音，测试1K测试不到，测试音乐歌曲能测到，不知道客户要怎么对比，暂不处理
* 20200520
** 串口
   波特率9600,电脑端的发送间隔不能太小,理想是50ms
   要不然容易出现,超时时间未到,导致几个包合在一起
** 锐一690X
   id3死机问题，已处理，又提了几个播歌异常的歌曲等问题，拒绝客户处理，让客户换695X
** 恒鼎荣692X
   BLE随EDR一起断开，串口0的B口死机等问题，改了个版本给客户
** 科普豪6956A
   串口升级不了，ota.bin读取key时，固定有一个bit读错，寄珠海
** 博建6936
   充电仓左右反，已支持
* 20200519
** 盛鑫源6303A
   串口双向流控，已OK
** 联创视听692X
   无线遥控syn480R波形解析，借用红外模块处理，
   客户抓逻辑分析仪波形，给建议处理中
* 20200518
** 晶振
   负载电容应用12pF的
** 起华6966A
   I22程序已发出
** 盛鑫源6303A
   串口流控demo，调试中
* 20200516
** 起华6966A
   I22调试中
** 羽恒692X
   改繁体库后小写字母文件名出错，是FAT只认大写，而繁体的编码值落在小写字母上，让客户自己应用层小写转大写，已解决
** 德科创6303A
   串口不稳定，sniff模式造成，暂时先关掉处理，后面再看怎么优化
** 春苗695X
   双SD卡同时启用，目前SDK不支持，等006再说
* 20200515
** 起华6936D
   连苹果，不进低功耗，已OK，充电仓左右反，耳机程序还没改好
** 起华6966
   案子调试，还没调
** 羽恒692X
   繁体乱码，珠海改库OK
** 恒大692X
   蓝牙断连，珠海改库，发给客户抓log
** 德科创6303A
   串口接收不稳定，偶尔乱码，支持中
* 20200514
** 起华6936D
   程序进入sniff后，功耗还有2mA，是功能上加了个10ms的定时器导致，已处理
** 春苗695X
   蓝牙发射器死机，复位等问题，已处理
** 美师傅693X
   光感驱动调试，支持中
** 铬元692X
   Beacon主机扫描，获取rssi需求，支持中
** 羽恒692X
   创建繁体的文件夹，乱码问题，还没看
* 20200513
** 起华6936D
   R5部分机子无端耗电，充不满，改了2个地方给客户测试
** 起华6936D
   搭配F95充电仓，改了一版程序给客户
** 盛鑫源6303A
   周立功替换模块，调试中
** 科普豪690X
   ble广播包，动态填充，已OK
** 也杨692X
   ble蓝牙名显示不完整，buf溢出问题，去掉不必要广播字段，已ok
* 20200512
** 起华6936D
   R5板子异常，已完成
** 盛鑫源6303A
   周立功替换模块，调试中
** 源创杰6936D
   SC7A20敲击异常，不灵等问题，偶尔还会异常，让客户找敲击原厂
** 尚凌692X
   发射器连BK耳机，声音卡，寄珠海
* 20200511
** 猫王6926C
   P1、P5、PVX都出现重启后状态对不上，是因为APP协议有改动，
   没有告知，客户还没确定是否要改，待确定
** 盛鑫源630X
   周立功BLE模块，串口能接收，协议功能还没时间搞
** 尚凌692X
   BLE notify发送大量短包，偶尔会出现卡30ms，处理中
* 20200509
** BLE长包
   const int config_btctler_le_features = LE_ENCRYPTION | LE_DATA_PACKET_LENGTH_EXTENSION;
   const int config_btctler_le_acl_packet_length = 251;///27;
** 灵奥690X
   发射器机子出现死机无法长按8s复位，107公版rtc睡眠后无法长按复位，
   SDK的bug，看客户沟通，再看是否要找珠海处理
** 组创6933C
   死机问题，客户不接受解释
** 猫王6926C
   P1功放噗声，P5重启后APP获取状态对不上，都在处理中
** 科普豪695X
   LE层长包，已告知珠海
* 20200508
** 起华6936D
   A3没声音，和H3-LW620触摸，2款程序已发出
** 猫王6926C
   P1添加配对提示音，已发出
** 组创6933C
   BLE按摩器死机，只有客户的代码在他的电脑编译才能复现，无法处理，
   只关了总打印处理，死机后能立马复位
** 天地宏695X
   音箱调试3个问题，处理中
* 20200507
** 猫王6926C
   PVX、P5、P1，3款机型程序已发出，还有个低电复位的，处理中
** 组创6933C
   BLE按摩器，出现死机，目前只有客户的烧录文件会出现，
   重新编译后复现不了，客户想过来验证
** 中翔达6936D8
   VDDIO没贴电容，导致开机一直复位，开机前设置PB5输出0，客户测试可以
** 汉欣诺6951A
   底噪问题，新的SDK，客户测试改善很大，待测试完整功能程序再确认
* 20200506
** 猫王6926C
   P5生产2个问题，改了个程序给客户测试
** 组创6933C
   死机的机子，收到，还没处理
** 汉欣诺6951A
   4声道DAC底噪问题，处理中
** 威益德690X
   推IC波形，导致卡音，改了个demo给客户
** 盛鑫源6303A
   SDK引脚设置有问题，珠海还没回，基本还没调
* 20200505
** 起华6956A
   T905反馈7个问题，已改好发出
** 猫王6926C
   P5反馈断连问题，协助远强测试中
* 20200504
** 起华A3-6936D
   通话没声音，用056的程序生产，没有自动校准，偏置都到1V以上，改软件配置可以
** 汉欣诺6951A
   4路dac车机做法，底噪大，声音失真等，公版SDK就能测到，需珠海处理
** 晶一692X
   pincode太简单，有部分手机，会自动连上，因为手机有默认密码组表，无法处理
* 20200430
** 猫王6926C
   P5淘宝出货机子，10几个用户投诉蓝牙断连问题，这边跟猫王都测试不出，等猫王寄机子
** 组创6933C
   按摩器，有一个机子从国外寄回，估计会死机，
   开了打印就不死机，原因未知，处理中
** 汇杰芯692X
   发射器发射主机插播提示音，发给音箱，由于解码接口要做互斥，
   SDK默认没做，不好搞，跟客户说做不了
** 源创杰692X
   华为跑步机，BLE连接调快后，卡到传统蓝牙播歌，又把时间间隔调低回来
** 联巨兴690X
   linein录音wav格式，第一次录30s会卡音，换个库，客户测试不到，
   但是终端反馈还是有，建议客户换U盘
* 20200429
** 起华6956A
   JWT01案子调试，已发出
** 新联芯695X
   AD按键检测，组合键，长按过滤，已改一版程序给客户
** 汉欣诺690X
   vivo iQOO Neo手机A2DP链路已连接，但是声音从手机出来，协助中
** 华巨芯692X
   BLE主机要做1拖4连接，做不了，已拒绝
* 20200428
** 源创杰692X
   BLE跑步机对接华为运行健康APP，出现卡3s读不到数据现象，改了一版程序，
   现象还是有，能砍到接近参考样机的水平，卡1s多一点，客户觉得可以发给终端测试
** 春苗695X
   玩具案子，识别不到外挂flash，播歌复位，播歌杂音，指定路径播放复位等问题，均已处理
** 雄思692X
   NTC检测，电池电量检测，波动很大，支持中
** 起华6956A
   对耳案子JWT01，未调

* 20200427
** 猫王6926C
   PVX项目，调灯效果，已发软件
** 源创杰692X
   BLE对接华为APP读取信息不完整，处理中

* 20200425
** 起华6956A
   T905已发一版给客户测试
** 欣瑞声696X
   013的SDK不开TWS，没声音，已解决

* 20200424
** 起华6936D
   FF216功能修改，已发出
** 起华6936D
   R5光感驱动检测，已OK
** 起华6956A
   T905案子，调试中
** 猫王6926C
   呼吸灯效果，改一版程序已发出
** 威益德690X
   指令延时做法，各模式不准，给客户开定时器延时
** 源创杰692X
   BLE read回调在刚连接卡3s左右，还没看

* 20200423
** 猫王6926C
   出差一下午
   呼吸灯效果，声音失真，EQ效果，出差处理中

* 20200422
** 芯连心6956A
   中控耳机开发支持
** 中翔达6956A
   中控耳机一边没声音，改了一组参数给客户，SDK库有问题，珠海还没改库
   自动mute的参数,应用层定义是u16,底层是u8
** 美师傅6951C
   SD0用A组口，读不了卡，公版原理图就有问题
** 猫王6926C
   PVX音量大失真，呼吸灯效果等，改了2版程序，明天还出差客户调试
** 欣瑞声6901
   48K-wav死机，没看
   替换wav_dec_lib.a测试OK

* 20200421
** 蜜连695X
   动态修改蓝牙名跟pin_code，已发出
** 春苗695X
   MIC当AD-key按键，可以用，但是ADC满值电压跟其他IO不一样，
   建议客户不要用
** 中翔达695X
   中控立体声输出，音量小容易被mute，珠海改的库，
   就算自动mute阈值改很低，还是不行，得珠海处理

* 20200420
** 起华6936D
   H3客户UI修改，还有个没改
** 汇杰芯AI8009
   修板唤醒功能，客户测试OK回去
** 猫王6926C
   P1新项目，在P5上修改，已发出

* 20200418
** 695X反汇编
   const int config_asser         = 1;//打开异常中断
   #if 0//def CONFIG_RELEASE_ENABLE ///开启log_e的打印
   #undef __LOG_LEVEL
   #define __LOG_LEVEL 0xff
   #endif
   log_e和log_info，是不一样的打印
   异常中断看下面2个打印,对应反汇编位置
   rets : 0x01E56E44 
   reti : 0x01E56E14 
** 起华6936D
   R5出货有6个问题，蓝牙名被误改，单边没声音，测不到，其他的问题，改了一版给客户
** 威益德690X
   双工通话，远端听到有断音，无法解决，车机的回声大，就是这样子
** 鑫凌波692X
   对箱带混响，只能做到跟精博德一样的做法，对箱一连上，只能改成喊话功能，断开才能切换成混响
** 中翔达695X
   最小音量提示音，改了个程序给客户测试
** 汉欣诺695X
   异常复位问题，还没定位到问题点

* 20200417
** 蜜连695X
   SPI推刷卡机，系统会死机，改了一个demo给客户
** 威益德690X
   不同苹果手机系统，Siri状态异常，客户手中苹果手机问题，重启后正常
** 起华6936D
   去掉特殊功能，做一版普通对耳，已发出
** 汉欣诺695X
   切换fm模式会软复位，还没看
** 汇杰芯692X
   已出货机子，开不了机，软件误判复位源，部分芯片会这样，已出国机子得看客户怎么沟通处理
** 新联芯695X
   中控耳机开发，支持中

* 20200416
** 联巨兴695X
   蓝牙ID3获取，已处理
** 汉欣诺695X
   电话本，系统时间，珠海改库中，串口升级，HID触摸，有待珠海评估后续怎么处理
** 汇杰芯692X
   发射器SD卡bfu升级不了，客户程序问题，公版没问题
** 雄思692X
   客户工程SDK培训，已完成
** 老树开花692X
   发射器SCO对接功能，mic没声音，需要关闭之前sbc通道，改了一个版本给客户
** 起华6936D-KXD368
   批量生产，测出6个问题，还没改，6936D-FF216，案子调试，已发出
** 科普豪693X
   AISDK无后台，切模式，蓝牙异常，还在测试中
   耳机的SDK只能关机，没做切换模式，搬音箱的代码后，多切几次会死机
   无法处理
** 威益德690X
   测试siri对多款苹果的兼容性

* 20200415
** 汉欣诺695X
   4声道调数字音量和模拟音量
   #+BEGIN_SRC c
   void user_volume_set(u8 volume)
   {
       g_printf("user_volume_set:%d  %d",volume,dig_vol_table[volume]);
       audio_dac_set_volume(&dac_hdl, volume, volume, volume, volume);
       audio_dac_set_analog_vol_support4way(&dac_hdl, volume, volume, volume, volume);
       __this->digital_volume = dig_vol_table[volume];
       audio_dac_set_L_digital_vol(&dac_hdl,  dig_vol_table[volume]);
       audio_dac_set_R_digital_vol(&dac_hdl,  dig_vol_table[volume]);
       audio_dac_set_RL_digital_vol(&dac_hdl, dig_vol_table[volume]);
       audio_dac_set_RR_digital_vol(&dac_hdl, dig_vol_table[volume]);
   }
   #+END_SRC
** 汇杰芯692X
   动态调节传统蓝牙名，珠海改库可以
   memset(host_name,0x00,LOCAL_NAME_LEN);
   #define NAME2  "2X-modify"
   memcpy(host_name,NAME2,strlen(NAME2));
   puts(host_name);puts("\n");
   __set_host_name(host_name, sizeof(host_name));
   user_send_cmd_prepare(USER_CTRL_CMD_RESERVE_INDEX3, 0, NULL);
   临时使用那个命令做改功能，不标准
** 起华6936D
   56F芯片没货，FF216换36D，调试中

* 20200414
** 威益德690X
   升级p4-opp版本，蓝牙断连无声已解决，
   播歌爆ram跳曲等问题，处理中

* 20200413
** mic增益
   AC695x，AC696x以及以后的系列，无特殊说明，mic的增益级数只有14级，每级2dB
   而AC693x及之前的是31级，每级0.9dB左右
** 695X--EQ版本
   0.4.1.0 才有drc
** 起华6936D-LW620
   客户UI修改，已发出
** 新时代692X
   BLE被CC2640连，没有profile扫描过程，
   直接对某个handle做操作不兼容问题，已处理
** 威益德690X
   升级p4-opp版本，爆ram问题，已解决，
   但是出现蓝牙断连无声音等问题，客户明天过来处理
** 汉欣诺695X
   车机做法，多通道EQ，动态EQ调节，等响度，环绕声等需求，
   让客户先了解全志跟凌阳的做法，再看怎么跟珠海沟通

* 20200411
** 反汇编
   新版编译器的llvm-objdump.exe已经不支持输出反汇编信息。
   file:c:/Users/Administrator.PCOS-1707211525/Desktop/objdump/
   目录里有llvm-objdump.exe
   拷贝工程下载目录的汇编文件,到本目录
   ./llvm-objdump.exe -print-imm-hex -d 695X/sdk.elf >> 695X/005-1.txt
   就可以把反汇编信息导出到txt文件
** 起华6936D
   2款程序，已发出
** 源创杰692X
   输出us级波形，代码指定到ram，用delay的方式，客户测试OK
** 威益德690X
   爆ram问题，给的建议，客户测试不行

* 20200410
** 猫王6926C
   PVX项目，升级异常，偶尔断连，偶尔回连不上等问题，处理中
** 鑫闻达693X
   外部中断，065国斌改库测试可以
** 汇杰芯8009
   耳机无法唤醒，已OK回客户了
** 源创杰692X
   5us控制功放,把代码放在ram用delay做延时翻转IO

* 20200409
** 猫王6926C
   PVX跟P5，升级界面跟音箱流程对不上，对接中，
   死机问题，一直测不到，还不知道怎么处理
** 起华6936D-LW620
   2代提几个需求，还没改
** 汉欣诺692X
   HID触摸，iPhoneX以上版本，不起作用，让客户测试原先抄机的机子先
   
* 20200408
** 起华6936D-H3
   客户UI修改，已发出
** 猫王6926C
   PVX项目，反馈4个问题，改了2个，另外2个还没测到

* 20200407
** 起华R5-6936D
   通话电流声问题，改了一版程序给客户，6936D助听器案子，调试中
** 灵奥695X
   获取长文件名，珠海改库，测试OK
** 汉欣诺695X
   串口接收变成0数据，接收数据长度超帧长度后，就会出现，客户测试OK
** 猫王6926C
   PVX项目，煲机24h出现死机，客户寄机子过来测试

* 20200403
** 起华H3-6936D
   改2版程序，FF216-6956F，通话回音，已发出，还有一个助听器没搞
** 猫王6926C
   PVX项目改几个问题，已发出，剩一个进sleep后死机，要珠海远强协助，还没搞
** 汉欣诺695X
   车机串口，发送频率小于10ms后，会出现，一直0数据，还没验证

* 20200402
** 696X
   DCDC需要配合 CLOCK_MODE_IGNORED
   ldo 就设置   CLOCK_MODE_ADAPTIVE 
** 起华6936D-R5
   通话电流声问题，处理中
** 猫王6926C
   PVX项目3个问题，和煲机死机问题，还没看

* 20200401
** 696X
   PB4，PC3，PC4，USBDP，USBDM。
   在芯片开机系统复位起来过程中会默认输出0状态，导致G-sensor供电拉低，无法触摸开机。
** 起华
   6936D-F8 程序已发出，AD138 UI修改已发出
** 猫王6926C
   PVX项目，提示音跟失真问题，客户还在测试
** 汉欣诺692X-HID
   安卓back键部分手机失效，由ESC改成AC back，只剩荣耀6不兼容，暂时这样处理
** 汉欣诺695X
   串口接收数据变成全0问题，还在测

* 20200331
** spp修改UUID
   /*128 bit uuid:  11223344-5566-7788-aabb-8899aabbccdd  */
   const u8 sdp_test_spp_service_data[96] = {
   0x36, 0x00, 0x5B, 0x09, 0x00, 0x00, 0x0A, 0x00, 0x01, 0x00, 0x04, 0x09, 0x00, 0x01, 0x36, 0x00,
   0x11, 0x1C, 
   0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0xaa, 0xbb, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, //uuid
   0x09, 0x00, 0x04, 0x36, 0x00, 0x0E, 0x36, 0x00, 0x03, 0x19, 0x01, 0x00, 0x36, 0x00,
   0x05, 0x19, 0x00, 0x03, 0x08, 0x02, 0x09, 0x00, 0x09, 0x36, 0x00, 0x17, 0x36, 0x00, 0x14, 0x1C,
   0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0xaa, 0xbb, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, //uuid
   0x09, 0x01, 0x00, 0x09, 0x01, 0x00, 0x25, 0x06, 0x4A, 0x4C, 0x5F, 0x53, 0x50, 0x50, 0x00, 0x00,
   };
** 起华
   6956F-FF216软件完成，
   R5-6936D电流声，需要硬件看，
   F8-6936D还在调
** 猫王
   PVX修改open_mic提示音音量，直接修改提示音文件
** 汉欣诺695X
   串口接收，一段时候后，接收到的数据变成0，字节数却是对的，还没看

* 20200330
** 起华6936D
   mic扩音助听器功能
   3代的机子通话不行
** 汇杰芯692X
   长文件名获取
   memset(g_lfn_buf, 0, sizeof(g_lfn_buf));
   fat_set_lfn_buf(g_lfn_buf);
   memset(&music_file_info, 0, sizeof(music_file_info));
   file_operate_get_file_info(obj->fop, &music_file_info);

* 20200328
** 科普豪
   欧智通对耳，距离短，内核电压底层库判断是F版后就不抬电压了

* 20200327
** 起华
   要换66A代码
** 猫王6926C
   PVX项目失真，基本可以确定是芯片内部干扰造成DAC输出失真，暂无处理方式
** 科普豪6936D
   欧智通对耳案子，距离短，处理中

* 20200326
** 猫王6926C
   PVX项目，芯片输出PWM后造成低频失真，改成20khz，客户反馈更差
** 起华6936D
   改2版程序，已发出
** 汉欣诺6925B
   BLE beacon案子，调试中
   adv_type = 3; ///只广播，不接受连接
   改成类型3后，广播间隔无法低于100ms，底层库限制

* 20200325
** 巴达木6959B
   省电容方式，通话无声，小声等问题，demo板能复现，寄珠海处理
** 尚凌6956D
   省电容方式，通话电流声低噪声，软件无法处理，改成固定好mic做主机方式
** 汉欣诺692X和695X
   BLE  beacon，
   和串口问题，还没处理
** 猫王6926C
   PVX项目，改了呼吸灯后，造成声音失真，还没处理
** 威益德690X
   车机连海外版三星手机，通话后卡音，明天客户带机子，直接去珠海处理

* 20200324
** 巴达木6959B
   通话概率无声，修改软件后客户测试没有出现无声，但是声音会变小，
   这边测试公版，SDK的mic偏置是有问题的，珠海还没看
** 尚凌6956D
   通话电声，目前只能做到。不说的时候没有电流声，一说话，就跟着声音一起出来

* 20200323
** 起华6956A
   3个程序，已发出
** 巴达木6959B
   通话无声，支持中

* 20200321
** 起华6936D
   SL353项目开发，还差个提示音问题，处理中
** 汇杰芯6959B
   mic口PC6，会漏电，关机功耗大，珠海反馈无法改，只能改板

* 20200320
** 起华36D和56A
   2款程序，已发出
** 汉欣诺692X串口升级
   uboot升级途中停住，直到看门狗复位，怀疑栈被改，原因还未知，
   客户在测试先切换到idle，再响应升级，测试中
** 猫王6926C
   P5音量低休眠后反馈无法定时唤醒，还没测到

* 20200319
** 猫王6926C
   P5要进入sleep睡眠，要切换系统时钟为160M
   192M进入睡眠会唤醒不了
   P5改4个问题，PVX改5个问题，待发出
** 源创杰692X
   AI的SDK进sleep唤不醒，要换成猫王的库power_manage_lib.a
   set_lowpower_pd_ldo_level(0x01, 0x01, 0x07, 0x01);
** 汉欣诺692X
   串口升级死机问题，珠海改了带打印的库，在uboot看门狗复位，原因还未知

* 20200318
** 猫王6926C
   P5低电放电曲线，改了一版给客户测试
** 起华6936D
   ET2充电灯乱闪，改了一版给客户
** 汉欣诺692X
   串口升级有几率在uboot直接复位，
   怀疑是MP5的串口波特率有波动，长包会错位，客户试着改MP5

* 20200317
** 猫王6926C
   P5低电关机后，无法开机，处理中
** 猫王6926C
   PVX反馈4个问题，还有2个确认中
** 起华6936D
   ET2项目，充电问题，还未处理

* 20200316
** 起华6936D
   3款板子，软件已发出
** 猫王6926C
   PVX项目断连测不到，P5低电关机后无法开机，要客户寄板子过来再处理
** 国华692X和695X
   反馈的5个问题，没有工程联系，未处理
   
* 20200314
** 汉欣诺692X
   电话本死机，珠海改库，测试可以
** 国华6928B
   升级问题，已处理
** 猫王6926C
   PVX项目，反馈断连又立马回连，还没测到，倒是测出音频链路声音出不来问题，处理中

* 20200313
** 猫王6926C
   PVX项目反馈2个问题，已发软件
** 恒大6926A
   修改BLE功能，已发出
** 起华6936D
   ET2项目，反馈2个问题，已发出
** 汉欣诺692X
   电话本死机问题，珠海发库待测试

* 20200312
** 国华6928B
   spp使用问题，发送的buf要static，已解决
** 起华6936D8
   换D4需要升级到066SDK，已发出
** 猫王6926C
   PVX项目反馈3个问题，测试中

* 20200311
** 猫王6926C
   PVX项目，问题修改已发出
** 猫王6926C
   P5项目，问题修改已发出
** 起华6936D
   6936D8换D4，有个特殊功能，要换库，只有066的补丁，需要更新SDK，处理中

* 20200310
** 695X
   能量值audio_output_data()
** 猫王6926C
   反馈3个问题，有一个需要动到loader.bin，等日新修改，待处理
** 锦亨源692X
   BLE的特征wirte_no_response和notify无法属性共存，
   应该是安卓手机7.0版本以下的共性问题，暂不修改

* 20200309
** 版本发出批处理
   #+BEGIN_SRC dos
   download-Release_Version.bat：
   //********************版本发布****************************//
   echo "请输入版本号:"
   set /p ver=
   set fw="jl_isd.fw"
   set bfu="updata.bfu"
   set filename="JL_MW_AC6926C_PVX_XIN_%date:~0,4%%date:~5,2%%date:~8,2%_%ver%_@@_.fw"
   echo %filename%
   if not exist Release_Version md Release_Version
   copy %fw%  .\Release_Version\
   copy %bfu% .\Release_Version\
   cd .\Release_Version\
   if exist %filename% goto yes_exist else not_exist
   :not_exist
   echo "是机型--使用key--重命名成%filename%"
   if exist %filename% del %filename%
   rename %fw%  %filename%
   ::rename %bfu%  %bfu%-%ver%
   rename %bfu%  updata-%ver%.bfu
   pause
   exit
   :yes_exist
   echo "有同名文件%filename%--中断退出--未进行重命名操作"
   pause
   exit
   //********************版本发布****************************//
   #+END_SRC

** 猫王6926C
   PVX项目反馈5个问题，已发出
** 汉欣诺692X
   传统蓝牙只开SPP升级开不了机，至少要开AVCTP才可以，已OK
** 汇杰芯693X
   音箱SDK-0.2.3，蓝牙回连是按照配对顺序，珠海没空搞，支持客户自己记VM方式，已OK
** 天浪6905C
   EDR+BLE同时开，蓝牙播歌距离短，音量无端自动降低，支持中

* 20200307
** 长文件名和中文路径
   新建立一个文件，保存在ANSI格式，再把要用到的中文路径放在那里。
** 猫王6926C
   1、要求拨动一次（目前是2次）切换上下曲
   2、要求在设备没有休眠前都要可以回连
   3、蓝牙名称需要改为"猫王·野性MINI-C"
   4、旋钮调节方向，待确定
** 科普豪6936D
   主从切换无法关闭也无法主动切换
   void tws_conn_switch_role();
   if(bt_tws_get_local_channel()!= 'L'){
       sys_timeout_add(NULL,tws_conn_switch_role,1000);
   }
   连接后立马放回仓后，会造成切换主从超时，就断开手机连接。
   底层默认刚连上是不让切换的。

* 20200306
** 汉欣诺692X
   HID多点触控
   苹果使用0号ID，而安卓不认0号ID，做了2份profile_data
   win10电脑多点触控需求，让客户参考微软硬件中心描述，先自己整
** 汇杰芯693X
   音箱0.2.3珠海找不到
   由于手机蓝牙地址可以打印到，是相反的，客户可以自己做VM回连一个设备
    __set_auto_conn_device_num(2);
   const u8 more_addr_reconnect_support = 1;控制回连多个设备
** 猫王PVX
   外挂flash用途？OTA升级用，升级完要回连，ota升级的时候不能擦除配置
   所有按键唤醒？PA1没高阻？PR2与普通IO都能唤醒？
   其他APP没有上下曲
   音量调节:顺时针旋转，音量增加。逆时针旋转，音量减少。设置反了

* 20200305
** 起华6936D
   ET2案子，改了一版给客户
** 猫王6926C
   PVX案子，调试中
** 汉欣诺692X
   安卓HID识别有问题，未处理

* 20200304
** 693X
   idle模式下,如果有定时器一直跑的,不要调用tws的任何接口
** 科普豪6936D
   对耳充电死机，在用064公版换珠海异常库，测试中
** 汇杰芯693X
   音箱023的SDK，回连2个问题，需要珠海搞，已发邮件
** 天浪690X
   蓝牙动态改名的，客户测试可以

* 20200303
** 起华
   远古新案子
** 科普豪6936D
   对耳问题调试，找不到问题点，给了一直修改方法给客户测试
** 迈瑞693X
   flash文件读写，第二页异常
   BLE的SDK添加flash文件按页循环读写demo，已发出

* 20200302
** 源创杰692X
   AI APP手机无法启动语音识别，是专门去掉的
** 汇杰芯693X
   有个苹果手机，播歌下，会一直判断成通话状态下
   看打印是一直循环打出电话挂断，原因未知
** 科普豪6936D
   耳机几个bug测试中
   对耳案子反馈5个问题，均未现，
   测试出其他3个问题，无法关机已处理，异常中断2次位置不一，充电死机，原因均未知

* 20200229
** 恒大6926A
   新的芯片，下载程序显示BR21-BLE蓝牙名，分析中
   客户发命令比692X上电快
** 伦茨693X
   华为P10手机没声音，已发补丁给客户
** 伦茨695X
   5V常在，充满电，一直维持7mA功耗
   降到3.7V后，就变为0mA了
** 科普豪693X
   反馈几个问题

* 20200228
** 源创杰692X
   发射器无法解码smp加密文件，改程序客户测试OK
** 汉欣诺692X
   DAC输出失真，客户硬件问题，IOS多点HID，改了一版给客户，有反应，但是延时较大，客户测试中
** 伦茨693X
   P10手机，寄给珠海有盼分析

* 20200227
** 汉欣诺692X
   HID触摸，feature report手机不读，找不到问题点，客户寄个样机来抓包
** 伦茨693X
   华为P10手机回连对耳，出现一边没声音，应用层改了不起作用，需要珠海处理
** 科普豪693X
   对耳调试，给了修改方法，客户测试中

* 20200226
** 开始上班
** 恒大6926A
   AT_VERS_N添加回应OK
   新打的板子，读取bt_cfg.bin失败，蓝牙名为BR21-BLE，原因未知
** 汉欣诺
   IOS多点触控
** 科普豪693X
   加了sniff晶振用24M
   改了mic电源为2.3V
   加了充满电点蓝灯
** 迈瑞
   flash擦除问题

* 20200118-20200226
  春节放假

* 20200117
** 起华
   6925音箱修改
** 汉欣诺
   IOS多点触控，测试不行

* 20200116
** 思必驰692X
   蓝牙发射器有爆破音，底噪，消音等问题，
   根源在于客户那辆试验车的车机功放解mute会有爆破音导致，
   手机测试也有这种现象，后续修改，最多只能做到手机的效果
** 恒大6926A
   BLE模块，报文格式协议修改，已发出

* 20200115
** 恒大6926A
   主控无法和GD32F407共用晶振
   主控加了普利金的key

* 20200114
** 起华AD135
   小概率死机问题，打补丁发程序给客户测试
** 源创杰692X
   BLE透传，需要缓存大量UART数据，改了个demo给客户
** 汇杰芯6936D
   BLE广播问题支持

* 20200113
** 科普豪6956D
   内置充电问题，音箱SDK0.0.1版本不支持内置充电，改了个程序给客户，
   插卡卡音，公版SDK测试没问题

* 20200110
** 华巨芯6936D
   中控耳机电流声,功率降2级,MIC电源提高,mic加EQ滤高频,改成LDO电源
** 华巨芯4601B
   32K晶振不跑,rtc读寄存器会出错,导致PR3被设置成输出或下拉
   在所有的PORTR函数里,都初始化PR3的对应位
   输入关上下拉

* 20200109
** 汉欣诺692X
   苹果HID多点触控,改成White_board+Finger，客户测试中
** 博创昱6936D
   PA8有个3V到4V连续脉冲波，导致触摸IC死机
   SDK在LDIN_ERR没有charge_close，客户测试中
** 起华6936D
   按键提示音修改，入离耳滤抖，客户测试中

* 20200108
** 起华6936D
   KXD368触控耳机案子,加离耳不响应按键
** 起华6925A
   音箱案子,低音调节旋钮,声音很奇怪
   
* 20200107
** 恒大6926
   BLE蓝牙模块，客户文档协议封装测试可以
** 也杨6901
   spi外挂flash录音，剩flash分区录音问题，转了个珠海邮件给客户，客户回去自己先搞
** 起华6936D
   在065上打补丁，开不了机，处理中

* 20200106
** 恒大6926
   BLE蓝牙模组，协议封装中
** 源创杰692X
   点阵屏繁体显示乱码
   国内下载的歌词文件，都是ANSI编码，用记事本转换成UTF16-LE，客户测试可以
   预测国外下载的，肯定不会是ANSI，应该是UTF16-LE
** 芯运6936D8
   测试盒升级死机
   客户芯片批次号为UAK731-36D8，用064的SDK测试出现百分百死机
   替换之前处理TH flash的ota.bin，客户测试几个芯片，都可以
** 新时代692X
   有其他方案能做到在一个连接事件内传送40包以上
   692X只能传输10包以下,需要敏贤支持

* 20200103
** 695X
   开发板PA9、PA10短路
** 汉欣诺695X
   串口UART1 TX和RX改任意映射，客户测试OK
** 起华A3-6936D
   生产不良，部分dvdd电压偏低，升级SDK给客户，
** 起华AD138
   无线充关机后耗电3mA，充电IC型号选错,应为CHARGE_IC_LP4060_LP6235
** 起华R5-6936D
   改用KXD368,发给客户测试了

* 20200102
** 请假1天

