#+TITLE:       JL work diary record
#+AUTHOR:      辛佳斌(lawrence)
#+DATE:        [2017-02-13 周一 16:31]
#+EMAIL:       lawrencejiabin@163.com
#+KEYWORDS:    the page keywords, e.g. for the XHTML meta tag
#+LANGUAGE:    language for HTML, e.g. ‘en’ (org-export-default-language)
#+TODO:        TODO

#+SEQ_TODO: TODO(T!) | DONE(D@)3  CANCELED(C@/!)  
#+SEQ_TODO: REPORT(r) BUG(b) KNOWNCAUSE(k) | FIXED(f)


* 20181229
** 博建6928B音箱
   博建6928B硬开关音箱，开不了机，客户拿了12个机子。
   11个插充电线，就能开机，拆机5个，电压均在3.2V一下。
   剩余1个，开不了机，板子VDDIO和RTCVDD接一起，对地短路，是SD卡座电源脚短路，芯片换到其他板子，正常开机。
   隐患：拨码开关，OFF档会卡住，导致有时关不了机，直到耗完电。
** 广利达692X
   在V2.5.1上SD卡复用AD，ADK复用灯，有杂音,
   灯会闪，需要将adc_soft_irq_resume中断频率改快。
   
* 20181228
** 博建 691X和692X
   获取linein能量谱，改好，已发出
   如果linein只有一边有声音，就会采不到能量值。
** 羽恒 690X
   在idle模式下，一直循环播放提示音会出现没声音，改好，客户确认ok

* 20181227
** 692X的IIS
   //PA7(MCLK) PA9(SCLK) PA10(LRCLK) PA11(CHL0) PA13(CHL1) PA7(CHL2) PA8(CHL3)
   //PB6(MCLK) PB0(SCLK) PB1(LRCLK)  PB2(CHL0)  PB3(CHL1)  PB4(CHL2) PB5(CHL3)
** 华炬芯692X对箱
   是澳特爱的机子，需要业务沟通确认
** 威益德690X
   切模式回来获取音乐总时间为0，替换MP3库。
   flac下无法操作ble，是p2和p3的问题，p4的没问题，得找珠海改对应SDK的库

* 20181226
** 源创杰692X蓝牙和linein同时出声音
   #+BEGIN_SRC C
   void aux_open(void)
   {
       puts("aux_open\n");
       if (LINEIN_CHANNEL == DAC_AMUX0) {
           JL_PORTB->DIR |= BIT(4) | BIT(5);
       } else if (LINEIN_CHANNEL == DAC_AMUX1) {
           JL_PORTA->DIR |= BIT(3) | BIT(4);
       } else if (LINEIN_CHANNEL == DAC_AMUX2) {
           JL_PORTB->DIR |= BIT(6) | BIT(3);
       }
       dac_mute(1, 0);
       sound_automute_set(0, -1, -1, -1); // 关自动mute
       linein_channel_open(LINEIN_CHANNEL, 1);
       linein_gain_en(1);
       /* ladc_mic_gain(mic_gain, mic_gx2); */
       aux_2_dac(1, 1);
       extern void delay_2ms(u32 delay_time);
       delay_2ms(100);
       dac_mute(0, 0);
   }
   
   void aux_close(void)
   {
       puts("aux_close\n");
       dac_mute(1, 0);
       sound_automute_set(AUTO_MUTE_CFG, -1, -1, -1); // 开自动mute
       linein_channel_close(LINEIN_CHANNEL, 0);
       aux_2_dac(0, 0);
       delay_2ms(100);
       dac_mute(0, 0);
   }
   #+END_SRC
** 汇杰芯6919B
   烧录问题，已OK
   6919B顶板V1.1能用，新的烧录器加入校验芯片是OTP还是flash版。
   OTP的程序只能烧otp的芯片，用flash会报版本错误。

** 博益友690X
   linein下混响各种问题，硬件问题，已OK
   左右声道幅值一致，左右声道串音是共地原因。

** 羽恒690X
   AI的SDK，用华为荣耀10、华为畅想8P、华为A10连接不上，
   无手机验证，先跟客户沟通，让他确认情况先再说

* 20181225
** 对箱连接状态
   BT_STATUS_BT_TWS_CONNECT_CMD
   第一条lmp命令就来这里了，如果需要立马断开，直接发送
   user_send_cmd_prepare(USER_CTRL_DISCONNECTION_HCI, 0, NULL);
   就会走reason 0x13
   有时会失灵。
** 伦茨692X
   蓝牙通话录音，只能录一边，需要在ladc耦合到dac那边去，再录音。
** 源创杰692X
   蓝牙下开linein通道，待调。

* 20181224
** 起华对耳双通
   调691X双通的版本
** 起华R208-6916A
   对耳双通版本调试，基本能用，细节没测
** 科普豪新时代690X
   BLE连接比别的方案慢，珠海解释说，芯片蓝牙IP本身限制，导致发现服务比较慢，无法优化，让客户换用692X
** 港芯微691X
   开发板的flash和芯片都坏了，给客户修板了，待寄客户
** 联巨兴691X
   公版SDK红外用不了，默认优先级没有设置最高导致
** 鑫闻达691X对耳
   提起开机有唤醒源不对问题。

* 20181221
** 华立S11C-4603
   低电会死机，芯片绑定的是恒硕5E6014，电压要在2.6V以上正常
   低电的时候，功放会扯到VMCU电压到2.6V一下。
   后续要修改串连电阻为2.7R或4.1R
** 芯运692X
   RTC有时唤醒不了，系统跑192M，进入睡眠之前，先降频为120M，再进入RTC睡眠。

* 20181220
** 铭源 6911A
   异常死机问题，寄给珠海处理
** 华立S11C-4603
   明天客户寄机子过来处理
** 联巨兴691X
   需要很准的50us中断，由于底层会关中断原因，回客户没法做到很准
** 威益德46
   需要加一个播放模式，播放设备所有文件后停住，告知客户，客户验证中
** 美师傅692X
   连电脑卡音，客户测试，改善很大，先这样
** 汇杰芯690X
   发射器保留所有搜索设备，支持中

* 20181219
** 692X的mic有-12dB衰减
   MIC_NEG12：MIC -12dB增益放大控制位
   当mic的增益0时，声音还是很大，可以设置这个
** 宇恒692X
   AMR格式可以播放
** 铭源6911A
   蓝牙手柄，异常死机，找志彬在看，堆栈被改，处理中，后续还要加个低功耗idle模式
** 广利达6925E
   有IO异常出现PWM波，和呼吸灯功能没做好，已改好
** 港芯微691X
   开发板一直跑不起来，让客户寄板子来看
** 宇恒692X
   有些wav播不了，是32bits，回客户支持不了
** 中兴达  692X  
   linein左右声道画反，还在和珠海沟通中
   无法调换DAC左右声道
** 科普豪  692X   
   AI识别英文，能识别英文，但是能不能拿到英文的资源，就是资源提供商的问题了

* 20181218
** 港芯微691X
   开发板不正常，对了下电压，应该在uboot状态，一直进不去flash，估计要客户寄板子过来修
** 铭源691X
   蓝牙手柄，有几个需求和问题，在看
** 起华FF216-6916A
   改通话和音量，给客户，最大了还闲低，软件没得改
** 汇杰芯691X
   BLE的SDK，UART DMA例子，已发出，SDK的串口结构体定义有bug
** 汉欣诺690X
   BLE HID苹果手机触摸，支持中

* 20181217
** 出差恒颖超一天
   改6926A的案子。
   噗噗声，功放mute，按键，EQ，提示音已解决

* 20181215
 加班一天
** 巴达木恒颖超6926A
*** 音质问题
    最大声播歌，低频有杂音。
    最大声之后，增益不能加太多，只能降增益，再往上补
    要不然越界的频点，就会有杂音。

* 20181214
** 请假2个钟
** 巴达木恒颖超6926A
*** 插卡或频繁按按键死机
    复现不出，静电不过-4K

* 20181213
** 威益德6901
*** 文件列表的问题
    短文件名也在长文件名的buf，但是长度为0
*** 录音完成后立即播放录音的文件
    通过文件路径去播放
    记录的都是文件句柄
    usb:00099eb0
    sd0:00082fc0
*** BLE蓝牙名称长度问题
    现在长度超过12个字符就会显示不出来
    改成DYNAMIC，会以广播包去填充。不用在profile_data里面去写死。

* 20181212
** 源创杰46
   1.4.1ms升级复位，珠海改库，客户测试OK
** 彩荣690X
   HFP下BLE容易掉线，改了连接超时，测试OK，已送样
** 培训港芯微
   培训客户691X的BLE，客户要做蓝牙信标，得找珠海支持
** 出差汉欣诺
   客户想做手机投屏后，车机触摸板坐标能回传手机，Android能通过USB，苹果得走BLE，他们有客户能做这个，培训他们怎样使用690X的BLE
** 威益德690X
   蓝牙库获取电话号码，有问题，发邮件给珠海了
** 铭源691X 蓝牙手柄
   有个蓝牙状态抓不对，支持中

* 20181211
** 彩荣690X
   ac690x_toy_sdk_v211 启用HFP会导致BLE断线，
   改大连接参数，现在是要10s以上才会断，有优化但还是会断，
   APP端是可以优化这个问题，让他们改改APP，加入自动重连机制
** 源创杰46
   升级复位，珠海国炜改的库不行，测试OK
** 铭源6921a
   蓝牙手柄，有消息堆积现象。改了程序，给客户测试。

* 20181210
** 铭源6911A 蓝牙手柄
   支持客户开发，目前硬件有问题，那边在修板验证中
   关不了机
** 联巨兴 
   支持开发691X的BLE和692X的AI
** 源创杰460X
   1.4.1MS卡升级复位，要找珠海改库

* 20181107
** 起华JD212
   6919A修改按键功能和充电灯，已发出
** 铭源691X
   加了一个消息机制，用于本地的消息推送处理
   广播状态和蓝牙连接，测试正常
** 通话噪音
   如果推灯和mic地没分好，推灯会有电流变化时，
   会干扰低，导致mic有噪音。

* 20181206
** 奋达691X
   自动化程序，已发出
** 科普豪692X
   小度蓝牙的百度，不开放，由珠海开发。
   要开发版的APP，测试后，向百度认证才能使用。
** 铭源691X
   蓝牙手柄，功能调试，协助中
** 威益德690X
   蓝牙状态设置，客户已验证OK
** 联巨兴691X
   BLE案子开发，支持中
** 汉普6902A
   华为Android 8.0的手机搜不到蓝牙
   修改广播包已发出

* 20181205
** 奋达691X
   自动化程序，添加晶振VM
   MAC地址没有依赖配置文件，要下载时，要加-format cfg擦除
   蓝牙MAC地址没有VM记忆
** 汇杰芯6916A   
   老鼠APP修改连接参数，改善时延，客户测试中。
** 威益德690X
   修改获取电话号码，会有空格符号(16进制0x20)出现，要过滤

* 20181204
** 铭源6911A
   蓝牙手柄出了一个版本
   默认有2个HID通道，consumer通道为0x0043

* 20181203
** 威益德690X
   有一个手机拨号，获取电话号码只有前3位。
** RTC复位时间
   判断12月不应该有等于号，所有SDK都有问题

* 20181130
** 爱尚692X文件浏览
   要开点阵屏。才能用文件浏览的接口
   开BLE和后台，编译不过。
** 奋达691X   
   自动化调试

* 20181129
** 威益德690X
   待机下断开蓝牙，并关闭蓝牙可发现可连接
   有一个手机获取不到电话号码
   换曲信息，通过判断ID3信息，处理
   有一个开机死机问题，是malloc问题，还难复现，改了dac的buf给客户测试
** 奋达691X
   自动化调试

* 20181128
** 联创视听
   6901A搭配原先炬力的APP。
   spp通信需要新建一个任务来做处理。
   要不然会卡住蓝牙和main。
** 起华FF216-6916A
   在FF221上修改管脚改动：音量减PB5改为DP，音量加是PC5
   在V204上开发，低功耗下要修改VDDIO档位高于2.6V
** 华炬芯奋达
   691X自动化工程
** 汉普酷走皇马
   Android 8.0搜不到蓝牙

* 20181127
** 起华R208-6904D  
   提起开机问题，硬件接错
** 起华JD212-6919A  
   灯异常，硬件没焊好，调了通话参数给客户测试了
** 永泰胜6919A  
   重烧问题，寄机子给棉鸿处理
** 起华JD1903A-6919A  
   珠海改过充满电灭灯，原本加起华的key，
   客户想下单给中翔达，但是珠海找不到程序了，无法改变key，客户生产自己安排了
** 铭源6921A蓝牙手柄
   寄机子给柏康调HID了，目前案子比较急，这边还得验证硬件环境
   客户将VBAT和VDDIO接在一起了，得割线飞线处理，影响AD功能。

* 20181126
** 起华JD212-6919A   
   案子开发，还有个问题，这边正常，明天客户过来
** 起华R208-6904D
   提起开机，PR1拉不低，还没找到问题点
** 铭源6911A蓝牙手柄
   调试中

* 20181124
  加班
** 鑫闻达6916A死机
   有2款机子，
   1款是开机死机，在board_main()里任意加函数就会好，问题点未知
   另一款power_down死机，怀疑是低功耗下，VDDIO为2.0V，有操作flash可能。

* 20181123
** 永泰胜6919A0
   修改key过滤机制，VDDIO和RTCVDD电压提到1，给客户测试了
   测试OK。
** 起华FF206
   用V203版本的SDK，通话有杂音，要打补丁。
   V203-p2比较稳定。

* 20181122
** 永泰胜6919A0
   生产发现最大声播歌，会自动跳下一曲。
   AD检测不准，软件处理key流程有bug。
** 铭源6911A
   蓝牙手柄调试

* 20181115
** 692X对箱功能
   消息同步有个bug。
   typedef struct {
    u8 idx;
    volatile u8 busy;
    volatile u16 mask;///这个16bits要改成u32
    } tws_cmd_var;
** 编译器
   新版的编译器只有更新包，没有完整包。
** 中翔达6905A AI音箱
   BT127案子功能暂时OK，先移交给施强。

* 20181114
** 芯运690X
   发射器在linein下，本地也出声音。
   在插播提示音时，ladc和dac的采样率对不上，会搞死提示音播放。
   music播放和发射模式死机问题，ladc close传参出错。
   linein发射和music切换，导致没声音，要加打开蓝牙通道的操作
** 广利达 6928B
   U盘挂载超时，卡住延时太久，暂时只能缩减到20s左右

* 20181113
** 得辉达
   和剑锋、卓添出差

* 20181112
** BTMate带葡萄牙语
   已发出。
** 天罡微6905音箱
   打电话没声音，修改音量设置成FADE_OFF，测试没出现
** 天罡微6903B
   头戴式耳机关不了机，P管电压不正常，原因未知，换管正常
** 鑫闻达691X
   连接后，酷狗播放器底下，会有一个弹窗，会导致PP键响应慢。

* 20181109
** BTMate带葡萄牙语
   修改中
** 伦次6904D
   充电开不了机问题。
   系统时钟跑192M，设置DVDD为1.0V会死机。
   要在降频后才能设置DVDD电压低一点。
** 鑫闻达6916A
   中控耳机VCOMO串音，进入power_down之后出来，重新设置dac_on
   而串音函数里有些标志没有清除。

* 20181108
** 华炬芯6921A无线充
   用料过于苛刻。
   换了线圈，换了NOP电容，换了采样电阻0.05R，效率才正常。
** 威益德690X
   电话本用在IOS 12.0上，有个联系人允许框有问题。不弹出。
   RDA没问题。给珠海处理。

* 20181107
** 华炬芯6921A无线充
   硬件上更换3个料，无线充距离灵敏度能达到5mm。
   等珠海的板子，再来验证接收器的灵敏度。
** 鑫闻达691X
   连接后按PP键，有延迟，对比690X慢1-2s，692X没有此问题。
** 得辉达小米音箱
   用新的1拖6工具升级，静置10分钟，没有出现开不了机的。
   但是用读版本的工具，还是能出现，更新了新的工具。

* 20181106
** 源创杰690X
   按键音固定音量大小
   改用数字音量，将添加按键音的函数，放到数字音量控制之后。
   客户验证中。
** 德科创690X点阵屏
   点阵屏显示，用西班牙之类，要换font_lib.a库。
** 汇杰芯6916A
   电压检测在低电不准。
   主控供电VMCU低于3.3V之后，VDDIO也会跟着变，导致电压检测不准。
** 联创视听690X用spp
   改了一个demo给客户，测试spp传输，未出现连接断开的现象。
   用客户的APP，就会出现断开现象。

* 20181105
** 得辉达
   出差处理烧录问题。
   升级后摆一会才能开机，国炜修改loader，减少检测时间。
   1拖6工具升级默认擦除flash，利龙修改工具，去掉默认选型
   遇见1次，停留在loader不复位，长按8S能复位，后面测试1百多次，复现不了
   明天工厂要拉一条产线测试2千台，统计之前问题改后的几率

* 20181103
** 加班
   搞得辉达小米音箱升级开不了机问题。

* 20181102
** 华炬芯6921A无线充
   SDK有指针没有4个字节对齐，修改sdk.ld即可。
   接收器功率不高，充电电流小，会导致苹果手机拒绝充电。
** 联巨兴6905A发射器
   刘行修改usb.a库，去掉mic_class和speaker_class的音量控制，测试OK
   客户测试OK
* 20181101
** 爱尚690X用IIC从机
   在从机接收时，发送地址后，读数据之前，中间插入START信号，
   会被误读取成一位。
   正常的话，如果在CLK为高时，DAT脚有变化，要舍弃之前的采样位，硬件没有这个机制。
   现改成iic关了，延时40us，在重起，现在勉强可以通讯了。
** 鑫闻达6905B插linein会重启
   苹果手机最大声播放时，插入过程中，DAC声道接触检测脚。
   相当于给检测脚接了一个负电压。
   导致产生上电复位。
** 华炬芯6921A无线充板子
   SDK跑不起来。

* 20181031
** 联巨兴690X发射器
   通过type-C连接Android手机，进PC模式，发射音频
   mic会导致，手机通话时，转换成发射器上面，但是样机不带mic，出现通话没声音，
   USB枚举要去掉这个mic的class。
   speaker默认带音量控制，导致存在HID的描述。
   手机有些系统会误认为有HID键盘，导致手机界面输入法无法弹出键盘，speaker_class要去掉这个功能。
** 华炬芯690X—tws-2013
   打PR补丁编译不过。海杨改个新补丁。

* 20181030
** 文件浏览补丁
   修改music模式下，共用MUSIC_OP_API变量。
** 爱尚智慧
   692X测试盒ble补丁已发出
** 睿博690X
   文件浏览功能，处理了music模式冲突问题，已发出
** 华炬芯691X
   对耳，单耳使用搜索慢，会影响对耳连接，跟客户解释不能太小，
   通话参数，调了一版，客户说效果好，回去再验证
** 华立S11B和S33B
   46程序修改需求，发给客户了

* 20181029
** 华立  
   改S11B和S33，46的程序，已发出
** 内部691X-ble
   发现的bug，都已修复，新版本待发
** 汇杰芯HLX18142-6916A
   改用flash版，已挪好，测试正常，已发给客户使用
** 爱尚智慧692X
   测试盒测试BLE，SDK根本没有做这个功能，测试都无法连接上，志彬处理中
* 20181026
** 起华R208-6904D
   提起开机，功能OK，功耗OK，等赖工改板
** 起华FF165-6919A
   客户烧的芯片，距离只有3米不到，这边烧芯片验证，板子，程序都对比过，正常，
   客户芯片烧出来的距离超短，原因未知，后续让客户再继续测试
** 汇杰芯HLX18142-6916A
   程序挪到flash版SDK，测试功能正常，等SDK的bug修复
** 内部691X-BLE  
   BLE-flash版SDK，加key无法升级，
   珠海找到，是烧写器的bug，那边还在改
   无法更新蓝牙名，原先是读配置文件，后面改成读配置区

* 20181025
** 源创杰  690X AI加频谱
   没有改成5段，改为dac中断50次，才算一次频谱，基本听不到杂音，客户暂时先送样
** 起华FF206
   死机问题，用我台式机就会，用笔记本下载，测试不到，找不到原因
   改用V203版本的SDK。
   用V204进低功耗之后，有可能异常中断，或软复位，或看门狗复位。
** 起华FF165
   蓝牙距离短，初步怀疑芯片问题，拿我们的芯片烧录，距离正常
** 汇杰芯  
   691X  flash版本SDK，还有2个问题，志彬在处理中

* 20181024
** 691X进power_down死机问题
   V204版本会死机，晓威的又不会
   改用V203版本了

** 蓝牙伴侣APP开发
   #+BEGIN_SRC Java
   public static final byte JL_COMMAND_MUSIC_DEV = -94; 
   mJLBluetoothRcsp.sendCommandToDevice(
        new byte[]{JL_COMMAND_MUSIC_DEV}, new byte[]{1,JL_COMMAND_MUSIC_DEV,1},
        new JL_BluetoothRcspRespond(){
            @Override
            public void onRespond(int ret, int data) {
                Log.e(TAG," onRespond" + " ret:" + ret + " data:" + data);
                super.onRespond(ret, data);
            }
            @Override
            public void onRespond(byte[] data) {
                Log.e(TAG," onRespond2" + data);
                super.onRespond(data);
            }
        }
        );
        jlBluetoothRcsp.sendCommandToDevice(
            new byte[]{JL_COMMAND_MODE_SET, (byte) (index - 1)}, new byte[]{2,JL_COMMAND_MUSIC_DEV,2},
            new JL_BluetoothRcspRespond() {
                    @Override
                    public void onRespond(int ret, int data) {
                        super.onRespond(ret, data);
                        Dbug.e(TAG,"sendCommandToDevice switch mode onRespond");
                        if (0 == ret) {
                            setCurrentMode(index, false);
                        } else {
                            if (0x20 == data) {
                                JL_MessageBox.showConfirmation(view, R.string.msg_no_device);
                            } else {
                                // JL_MessageBox.showConfirmation(view, R.string.msg_switch_mode_failed);
                            }
                        }
                    }

                    @Override
                    public void onRespond(byte[] data) {
                        super.onRespond(data);
                        Dbug.e(TAG,"sendCommandToDevice switch mode onRespond data");
                    }
                });
    import java.util.Arrays;
    private JL_BluetoothRcspCallback mCommandCallback = new JL_BluetoothRcspCallback() {
            @Override
            public boolean onDeviceCommand(byte[] command, byte[] data) {
                Log.e(TAG,"JL_BluetoothRcspCallback:" +"command:"+ Arrays.toString(command)
                      +"data"+ Arrays.toString(data));
                      }
    }
   #+END_SRC

* 20181023
** 源创杰691X
   ble可以控制进不进低功耗模式。
   柏康支持，已改好。
** 天地宏
   培训AI用法

* 20181022
** 奋达
   出差奋达，处理蓝牙测试仪测试问题

* 20181019
** 得辉达小米音箱
   出差得辉达，处理小米音箱连接BT168测试仪
   一直重复连接，由于复位后，link-key对应不上
   通话没声音现象

* 20181018
** 源创杰691X-ble
   低电检测要打开ADkey，才会扫描检测。
   不需要AD-key，要做下处理。
** 奋达6923A
   合并的程序，能测试。
   但是客户每次进蓝牙都要重新写一遍osc的VM。
   客户自己要加的。
** 起华FF206-6916A
   耳机的底噪经过功放会放大，出现白噪声。
   要调低功放的增益档次，不能用最高。
** 起华FF165-6919A   
   进入低功耗后，容易跟苹果手机断开连接
   RTCVDD加入退耦电容即可。

* 20181017
** 德科创690X
   AI的SDK，调试问题。
   客户用SCO链路，APP又是翻译软件。
   建议不要用AI的SDK，改用p4的音箱程序。
** 德科创690X
   有个BLE案子，配对苹果会出现，断开后重新回连。
   SDK没有问题，客户程序有问题。
** 奋达6923A
   发了个程序给客户合并了。

* 20181016
** 奋达6923A
   出差珠海，找立辉
   处理8852B仪器问题。
   需要替换bluetooth_lib.a
   测试灵敏度时，要加屏蔽罩，避免蓝牙干扰，导致错包。

* 20181015
** 奋达6923A
   蓝牙测试仪8852B，无法测试，计划明天拿给立辉分析
** 博建6928B
   低电影响ADkey，没有按键却检测有按下，和长按变短按，
   暂时无法同时解决2个问题。
   等客户板子，再看是否有优化空间
   天师已解决
** 德科创690X  
   AI音箱，自定义命令导致死机，程序问题，已解决
** 嘉兴科美692X
   对箱连接问题，已OK
** 彩荣692X  
   对箱aux，插入无声音问题
   SDk测试没问题。

* 20181013
** 加班
   搞奋达

* 20181012
** 汇杰芯6916A
   老鼠APP玩具，改了一个版本给客户，客户测试中
** 美师傅6916A
   耳机功耗大，改了程序。目前正常播歌，功耗基本一致，
   但是测试1KHz，0dB时，比不了BK方案，BK方案测出有特殊处理，
   在和珠海沟通中
** 爱迪尔690X
   固件上传给APP，给客户方法，客户验证中

* 20181011
** 源创杰
   建立线程处理功耗
   客户验证OK。
** 物联网
   AT指令的GPRS模块（SIM800和SIM900系列、安信可的GA6、GA7）

** 奋达
   频偏校正，+偏差，电容值往大的调，偏差减小
              -偏差，电容值往小的调，偏差减小

* 20181010
** 得辉达华庄
   出差一天
   处理一拖8工具，蓝牙名乱码和蓝牙地址跳码等问题。
   等利龙更新工具

* 20181009
** 请假
* 20181008
** 请假

* 20180930
** 奋达6923A
   linein通道打开后，没有关闭，只关闭ladc。
** 汇杰芯6916A
   改成只有2个PWM，通过映射，映射到4个IO上。
** 源创杰6919B
   ble关闭广播包后，功耗高。
   比较难改，珠海改不完，节后再发。
** 伦茨692X
   Timer用作PWM，要关闭Timer_CON的PWM_EN位。
   默认IO才不会有波形输出。
   芯片内部上拉10K误差有正负20%，做AD_key，无法做太多按键。

* 20180929
** 源创杰6919B
   ble关闭广播包之后，无法进入sleep，维持高功耗。
   广播广播包后，蓝牙不跑了。
   而power_down依赖于蓝牙中断，导致无法进入。
** 691X增加晶振强驱
   SFR(WLA_CON8, 8, 5, 0x8);
   时钟初始化之后调用。
** 起华FF165
   修改按键功能
** 起华FF226
   案子调试，给客户测试了。

* 20180928
** 汇杰芯6916A
   老鼠APP，PWM会影响到蓝牙性能
   和客户说明改板
** 起华FF165
   用6919A省料，改LDO_2声音小。
   SFR(JL_AUDIO->DAA_CON0, 2, 2, 2);
** 奋达6923A
   出差奋达，处理自动化机台，
   机台电源无法一直供电，得上位机工程配合改
   节后再处理

* 20180927
** 金康特发射器
   出差金康特，演示发射器demo
** 汇杰芯6916A
   PWM影响到蓝牙性能，导致ble都搜不到

* 20180926
** 691X-ac691x_sdk_le_v101_C_release无法下载
   ble的V101版本SDK，只能下载空片，下载目录多一个文件br20loader.bin，
   删除掉才能刷新程序
** 金康特发射器
   换用6905A  发射器demo，调试中
** 奋达6923A
   检测进test.app
   要在uboot里面做检测才行，避免软开关机的操作。

* 20180925
** 691X电机PWM
   MCPWMCH0_H  PA0    MCPWMCH0_L   PA3
   MCPWMCH1_H  PC1    MCPWMCH1_L   PC5
   MCPWMCH2_H  PB5    MCPWMCH2_L   PB0
   设置MCPWMCH1_H_OPPOSITE就变成两个都是反向
   设置MCPWMCH1_L_OPPOSITE就变成两个都是同向
   设置0的话就是H为正向，L反向
   底层bug导致。
** 汇杰芯6916D
   老鼠APP，程序开发
** 金康特6904发射器
   加入串口，demo演示

* 20180921
** 奋达6923A
   已发出测试版本给客户
*** 检测U盘是否有test.bfu
    开机挂载的时候就要检测，不能进音乐模式扫描才检测    
** 起华FF165
   用AC6919A，省物料
   改用LDO_1供电，在开发板会没有声音。
** 巴达木6925D
   生产20K，概率出现自动开机，插拔SD卡无反应，升级无反应等情况
   程序bug，已改好。

* 20180920
** 慧杰6929C 
   音质调试，音量31会失真
   DACVDD只有3.05V，DAC的输出要控制在3V以下
   音箱版，要用DAC_ISEL5U,否则隔直后，低音不过
** 起华R208
   玩吃鸡游戏，开启通话语音，背景音效会被削。
   aec_interface.argv_params(2 ,1000, 0 , 64 , 256, 0 , 0 , AEC_REDUCE);//Advance
   第三个参数，原本50，会削dac出来的声音，改成0，就不会。
** 奋达6923A
   测试工程和样机工程
*** 测试工程
    需要修改sdk.ld
    code0(x)        : ORIGIN = 0x1000000+0x7D000,       LENGTH = 16M
    修改代码的分布。
    样机工程的sdk.app，不能超过500K
*** 样机工程
    替换使用isd_download_with_test_app.exe
    -test_app test.app
    -faline sdk.app,0,0x7d000,0
    #+BEGIN_SRC C
    static const u8 test_mode_str[] = {"test_mode"};
    void enter_test_mode(void){
        u8 *updata_backup = UPDATA_FLAG_ADDR;
        ///RAM 变量传递
        //step 1: disable irq
        irq_global_disable();
        irq_clear_all_ie();
        OS_ENTER_CRITICAL(); //关总中断， 防止 back_up 内存被修改
        memcpy(updata_backup, test_mode_str, sizeof(test_mode_str));
        #if 1
        updata_enter_jump(0); //跳到 MASKROM， IO 口状态不变
        #else
        updata_enter_reset(0); //芯片复位， IO 口状态改变
        #endif
    }
    #+END_SRC

* 20180919
** 奋达6923A
   自动化协议bug修改
*** IO输出设置
    高低相反
*** 挂载SD卡和USB
    会死机，去掉task_common的调用
*** mic、linein、FM的能量值
    修改能量值范围，mic接地的时候，软件开启mic，要5s的时候稳定，采样数据
    才会变为0
*** 蓝牙名和地址
    加入配置文件的读取，去掉VM的操作
*** 串口脚RX和TX都要映射
    TX为PA12，RX为PC2
*** ADC检测无效
    AD-key引脚设置

* 20180918
** 天浪6905C
   PC4和PC5口上电有1V尖波脉冲，vdd上电慢于VDDIO导致
   软件不发修改，让客户加电阻分压，处理
** 义语AI的APK
   打包少jar包，编译不过，珠海已重新发新的
** 威益德690X
   文件浏览死机问题，已改好
   在music模式下，用task_music的mapi变量。
** 源创杰691X  
   ble的SDK，没有PR口函数，PR1拉不高，在处理中
** 起华FF206
   软件加入EQ，处理高音重问题

* 20180917
** APP
   图灵的不做，换成义语的APP
   义语，英文名叫deepbrain
   故事机APP
** 起华JY115
   用6919A-OTP版本，已发出
** 起华E23
   改用中翔达的key，烧录厂就不会换烧录架
** 欣瑞声6905A
   带义语APP，已发出一版，给客户测试

* 20180914
** 奋达6923A
   最小工程，只能到172K，达不到ram：128K的限制。
   目前不知道该怎么弄。
** 天地宏6905A带AI
   改了一版UI给客户试用
** 德科创690X带老树APP
   用旧版的APP，在进入设备连接界面，会自动断开现有的蓝牙连接。
   新版的APP，没有此问题。
** 欣瑞声6902A-Q1带义语APP
   珠海还在整理资料
   先搞一版老树的。

* 20180913
** 天地宏6905A带AI样机
   触摸一直输出高，触摸太灵敏。
** 德科创690X带APP
   客户自己写的APP，蓝牙连接要重新刷新服务，不断重连
   writeCharacteristic要检查返回值，重复写。
** 奋达6923A
   串口选脚出错，要映射RX。

* 20180912
** 中翔达6925D
   在FM模式下，插卡，功耗降不下来。
   重新初始化蓝牙，功耗才降下来。
   沈沛修改fm_lib.a即可，通用库。

** 巴达木6919C
   做蓝牙音箱，无DCDC下，开power_down，功耗在0-7mA左右。
   PR1进低功耗后，维持不住，会变成输出0

* 20180911
** 出差奋达AC6923A
   自动化程序需求。
   应用程序与自动化程序，分离。
   启动进入测试模式，改用U盘
   增加频偏纠正。
** 中翔达690X
   开启对箱，打开ladc采样mic
   采样率不能高，44.1kHz就会导致从机卡音。设置16kHz
   由于DAC和LADC共用一个中断，导致暂停后再播歌，dac默认以16kHz播放。
   都是杂音，需要清数据。
   在dac_int_disable();dac_int_enable()设置标志，在中断里面清除数据。

* 20180910
** 692X的V2.5版本
   在DAC加入串音mute的动作。
   函数内的局部变量，要定义成u32，要不然会死机。
** 中翔达690X扩音器限幅
   mic有接收的dB值限幅，超过即失真。
   最大声压级
   
* 20180907
** 690X文件路径指针
   #+BEGIN_SRC C
   r_printf("fs_hdl:%d\n",d_mapi->fop_api->cur_lgdev_info->lg_hdl->fs_hdl);
   r_printf("file_hdl:%d\n",d_mapi->fop_api->cur_lgdev_info->lg_hdl->file_hdl);
   r_printf("ui_fhdl:%d\n",d_mapi->fop_api->cur_lgdev_info->lg_hdl->ui_fhdl);
   /* _FIL_HDL *f_h = (_FIL_HDL *)(d_mapi->fop_api->cur_lgdev_info->lg_hdl->file_hdl); */
   /* FIL *pf = (FIL *)(f_h->hdl); */
   /* _FS_HDL *f_h = (_FS_HDL *)(d_mapi->fop_api->cur_lgdev_info->lg_hdl->fs_hdl); */
   /* FATFS *pf = (FATFS *)(f_h->hdl); */
   _FIL_HDL *f_h = (_FIL_HDL *)(d_mapi->fop_api->cur_lgdev_info->lg_hdl->ui_fhdl);
   FIL *pf = (FIL *)(f_h->hdl);
   r_printf("FIL:%d\n",pf);   
   r_printf("cur_path:%s\n",pf->fs_n.tpath);
   r_printf("cur_sclust:%d\n",pf->dir_info.dj.clust);
   r_printf("deepth:%d\n",pf->fs_msg.deepth);
   r_printf("cur_sclust:%d\n",pf->f_dj[1].clust);
   r_printf("start_sclust:%d\n",pf->f_dj[1].sclust);
   #+END_SRC

** 威益德690X
   文件浏览接口，封装OK，已发出
   蓝牙灯效，只发一个demo，给客户参考
** 起华6926A声霸
   已确认，改了2个提示音版本，已发出。
** 巴达木DAC串音
   691X按照天师方式，已解决
   692X用V2.5的SDK，测试没问题
** 汉欣诺690X电话本
   打来电补丁，获取手机蓝牙名，会多出6个字节的长度。
   电话本蓝牙名长度，不限长，为UTF8编码。

* 20180906
** 汉普车机回声
   客户的车机，延时有100ms左右，只能改成单工。
** 起华FF221-6916A
   做一版中文的提示音，已发出
** 起华R208-6904D
   做一个中英文提示音切换的功能,三击下切换

* 20180905
** 起华6926A声霸
   修改假关机挂载设备
** 天地宏6905A
   AI音箱调试完成
** 起华FF221
   要改中文提示音
** 威益德6901A
   文件浏览，接口封装

* 20180904
** 嘉兴科美BTMate
   连接后无法跳入蓝牙界面。

* 20180903
** 690X文件浏览器功能
   已完成一版，已发出，等客户测试再完善。
** 欣瑞声6902A带BLE传文件
   工厂工程有一个小米手机，有兼容性问题：
   1.服务获取有一定概率为空。
   2.蓝牙上传数据到app，小米手机读取第二个文件时中断。
** 起华FF221-6916D
   VCOMO开启，通话时，差分输出无声音。
** 起华6926A声霸
   改了一版问题点。

* 20180901
** 起华6926A声霸
   功放开mute会噗一声，无解，客户找功放厂商。
   改了问题，发出一版程序。

* 20180931
** 起华R208-6904D
   修改2版提示音，开机声音，有2个处理。
   要看终端客户取舍哪一版
** 起华6926A声霸
   修改问题点

* 20180830
** 中翔达692X断点记忆
   在半秒处，每隔5秒记忆，有时断电后，重新开机读不到断点。
   公版做法，播歌后都会清除秒的记忆，只记忆首，改成把秒也记忆。
   低电U盘会掉线，让客户把声音降1-2级，是听不出来的。

* 20180829
** 起华FF206
   板子虚焊导致噪声
** 欣瑞声6902A带BLE
   传输一段时间后，会出现BLE断开的现象。

* 20180828
** 起华声霸6926A
   完成，等客户测试。
** 默认红外表
   #+BEGIN_SRC C
   const u8 IRTabFF00[] = {
   NKEY_00, NKEY_01, NKEY_02, NKEY_03, NKEY_04, NKEY_05, NKEY_06, NKEY_07, NKEY_08, NKEY_09, NKEY_0A, NKEY_0B, NKEY_0C, NKEY_0D, NKEY_0E, NKEY_0F,
   NKEY_10, NKEY_11, NKEY_12, NKEY_13, NKEY_14, NKEY_15, NKEY_16, NKEY_17, NKEY_18, NKEY_19, NKEY_1A, NKEY_1B, NKEY_1C, NKEY_1D, NKEY_1E, NKEY_1F,
   NKEY_20, NKEY_21, NKEY_22, NKEY_23, NKEY_24, NKEY_25, NKEY_26, NKEY_27, NKEY_28, NKEY_29, NKEY_2A, NKEY_2B, NKEY_2C, NKEY_2D, NKEY_2E, NKEY_2F,
   NKEY_30, NKEY_31, NKEY_32, NKEY_33, NKEY_34, NKEY_35, NKEY_36, NKEY_37, NKEY_38, NKEY_39, NKEY_3A, NKEY_3B, NKEY_3C, NKEY_3D, NKEY_3E, NKEY_3F,
   NKEY_40, NKEY_41, NKEY_42, NKEY_43, NKEY_44, NKEY_45, NKEY_46, NKEY_47, NKEY_48, NKEY_49, NKEY_4A, NKEY_4B, NKEY_4C, NKEY_4D, NKEY_4E, NKEY_4F,
   NKEY_50, NKEY_51, NKEY_52, NKEY_53, NKEY_54, NKEY_55, NKEY_56, NKEY_57, NKEY_58, NKEY_59, NKEY_5A, NKEY_5B, NKEY_5C, NKEY_5D, NKEY_5E, NKEY_5F,
   };
   #+END_SRC

** 中翔达692X断点记忆一直记
   有人做过5s,但是有风险
   
* 20180827
** 起华FF221-6916A
   底噪和距离都不行
** 起华声霸6926A
   调试中
** 起华FF206-6916A
   开关机按键有问题，导致开机后按键不正常。

* 20180824
** 起华FF221-6916A
   更新SDK到V204版本，解决底噪问题
** 起华FF206-6916A
   带功放,按键有问题
** 源创杰6901A   
   CD机挂载有问题。
   第一次挂载失败后，以后每次都可以
   第一次挂载成功，以后都不行

* 20180823
** 起华6916A-R208
   高频声处理中。
** 修改BLE的MTU
   JL_Bluetooth的库
   setBleDataBlockSize()
   默认是20B，可以适当调大。
** 欣瑞声带BLE
   在传送notify的时候，会出现Fail。
   有可能是内存泄漏。

* 20180822
** 得辉达6926C
   给客户去掉mute，测试板子底噪
   CSR发射器，旧款连不上，海华买了个新款，连接一直正常。
   反馈一些不稳定现象问题，珠海处理
** 起华6916A-Q5
   程序修改，还有通话回声问题。
** 中翔达691X
   flash版本的SDK，播放otp提示音app.res文件
   出了一个版本给客户了。
   
* 20180821
** 得辉达6926C
   用CSR的蓝牙发射器，连过手机之后一直连不了。
   修改长按4s功能。
** 起华FF202  
   出了一个版本可以测试，没有加入音量同步。
** 华钜芯690X电话本
   phonebook_packet_handler回调函数有个type，里面有类型的区分。0是电话号码，1是拨出号码。2是来电，3是未接来电
   void __set_phone_history_call_num(u8 num);可以设置获取通话记录的条数
   USER_CTRL_PBAP_READ_PART命令获取通话记录条数

** 起华6916D对耳
   有概率性出现收不到蓝牙

* 20180820
** 欣瑞声6902A带BLE
   底层notify的反馈机制，有些手机有兼容性问题。
   现在多加了2种方式，一个超时，一个判断streamer，一个notify反馈，
   3者都起作用。主要是streamer，是否能接收消息的反馈。
** 威益德6905C概率不开机
   同一批次概率出现，烧写会出现 Flash Id Error。
   将RTCVDD的电容，由105改成104就可以了。
** 起华6916D
   对耳程序基本OK，卡音mute，声音渐变没有。
** 起华6904D
   对耳视频延时，会影响到蓝牙距离，不敢改太多。

* 20180817
** 得辉达小米音箱
   调试一版UI给客户测试，发给吴旭了。
** 合科芯690X
   蓝牙伴侣APP，在点播APE和FLAC的时候，会退出。
   p3版本就有，p4已改好，与APP无关。

* 20180816
** 爱瑞声6902A带BLE传文件
   完整流程OK，已发出测试程序，和文档。
** 起华6904D对耳
   要改三击siri功能，拿起开机等功能，待改
** 起华6916D对耳
   距离测试，bd_set_max_pwr(rf_power_max);貌似有调用的限制。
** 合科6901用APP点播无损APE/PLAC
   APP有退出设备播放现象

* 20180815
** 得辉达6926C小米
   EQ调试基本OK。
** 爱瑞声6902A带BLE
   调试上传接口。基本OK。
** 中翔达科迈通6916D对耳
   pin2pin，贴上，距离不行。
** 起华6916D对耳
   功率调节，距离测试

* 20180814
** 得辉达小米BM1120
   客户反馈加入EQ后，播歌会忽大忽小
** 合创SPI录蓝牙正常播歌声音
   调试OK，发给客户了。
** 芯运692X--SPDIF
   做输入，是否需要单独开一个模式

* 20180813
** 得辉达小米BM1120
   去客户那里调试

* 20180810
** 联创视听6901A带APP
   给客户搭了个框架，客户回去，继续调试。

* 20180809
** 也杨
   lighting耳机，在手机锁屏后，隔几分钟后会断电，测试其他的方案的不会。
*** ble在设置界面连上后，APP无法连接
    可以调用rcsp_check_app_connection()判断APP是否连接，累积一段时间，
    就调用ble_hci_disconnect(ble_conn_handle);断开ble的连接。
** 天浪690X获取文件名
   没有打开UI，默认是无法没有获取文件名
   要参考lcd_music_ui重新，为tpath分配空间
** 汇杰芯发射SDK
   在linein下无法调节音量，需要自己加数字音量的处理，参考BT14的程序。
   
* 20180808
** 合创外挂flash录音
   外挂flash的SDK，在蓝牙下录音，底层会内存泄漏。
   这个SDK不维护，让客户改用玩具的SDK。

* 20180807
** 爱瑞声6902A蓝牙音箱带BLE传文件
   上板程序已OK，可以正常工作。
   发给客户使用了。

* 20180806
** 爱瑞声6902A
   修板，板子一定要预留PC模式。

* 20180803
** 请假半天
** 威益德处理底噪
   收音芯片的音频输出脚，走过屏，如果音频脚偏置掉电，
   干扰就会盖不住
   在其他模式下，收音芯片的复位脚不能复位，收音也不能进入睡眠模式。
   
* 20180802
** 威益德6901车机
*** USB在standby之后电流没降低
    不能操作USB口为普通IO口
*** VM_write写申请不到空间死机
    加个判断，id3的大小，大于6K不分配。
    #+BEGIN_SRC c
    if(len < 6 * 1024)
    	id3_buf = malloc(len);
    #+END_SRC
*** 抄机软件有噪音
    在linein下，有高频声。

* 20180801
** 中翔达
   mic扩音器限幅，发了个版本给客户。

* 20180731
** 起华FF206
   换用6916D的芯片。
** 中翔达反馈问题
*** 获取第一次连接
   BT_STATUS_CONNECT_WITHOUT_LINKKEY:
   info[4] == 1,第一次配对
*** 删除蓝牙信息操作 
   USER_CTRL_DEL_ALL_REMOTE_INFO :删除手机，不包括对箱
   USER_CTRL_TWS_CLEAR_INFO:删除对箱
   要删除所有就要2个都调用。

* 20180730
** 小米音箱
   替换提示音，把回声算法去掉。
** 巴达木
   培训691X的BLE
** 中翔达
   问题点跟进中

* 20180728
** 小米音箱
   出差得辉达。
   BM2110有硬件问题。
   
* 20180727
** 起华J8耳机
   修改红蓝灯的方式
** 小米音箱
   出差得辉达
   完善BM2110的功能。
* 20180726
** 小米音箱
   修改BM1120的bug。
   提供一个BM2110的版本调EQ。
* 20180725
** 小米音箱
   完善BM1120的功能。

* 20180724
** 得辉达小米音箱
   调试一个版本
   出差客户，提供一个版本调EQ。

* 20180723
** 实捷DAB
   修改删除蓝牙连接后，还会自动重连的问题
   开机回连还是有，难修改。
** 汇杰芯690X
   用错EQ工具版本，导致连接测试盒，有很大的噪声。
** 起华V8
   在J8上面修改。
   中文的开机，是截取的，导致2个声音，有点停顿。

* 20180721
** 芯运692X
   linein转AD后，无法左右分离。
** 澳特爱692X
   三星手机，以前缺失HFP有一项属性Voice recognition，
   导致使用的是手机的mic。
** 也杨690X带APP
   EQ前五段有作用，后五段无作用，振荣修改中
   其他APP问题，让客户测试最新的APP。
** 中翔达微信语音
   安卓的微信语音走的是HFP
   苹果走的是音乐
   而后台返回时，对音乐有过滤包处理，导致短的语音难返回。
   打补丁“AC690N音箱耳机V2012-P4后台时间跳转可调节-V2”
** 起华J8案子
   调换红蓝灯，长按2s启动siri，长按4s关机

* 20180720
** 澳特爱6925B对箱
   三星手机S voice语音识别差
   ac69_sdk_v2012 这个可以，后面的SDK就不行。
** 微信语音
   苹果手机走的是音乐链路，底层有自动mute判断，导致有判断延时问题
   692X的没问题
   extern void set_mask_a2dp_data_time(u32 time);

* 20180719
** 嘉兴格优69调EQ
   EQ的Normal只有前面5段有效果，后面5段无效。
   振荣处理中
** 澳特爱6925B
   启动siri会关自动mute，关闭siri又没有打开。
** 起华6904D-J8
   改一版程序，调换红蓝灯。
** 69玩具SDK支持中文路径点播
   目前测试中文名和中文路径点播都不行。
   待远强确认。
   文件编码问题。
** 获取目录信息
   file_bs_entern_dir()
   参考点阵屏的接口
   func_browser_reflash()

* 20180718
** 起华6904D对耳
   ram-buf定义了2组，导致一播歌就ram不够，复位
** 起华6919A
   修改蓝牙名，烧录100PCS
** 本脉蓝牙伴侣
   fm模式点播频点有问题
   修改APP的源码，即可。
** 691X的BLE程序
   在初始化PR2的引脚上，要放在后面，底层会初始化唤醒IO，
   导致之前的设置被改，static void bt_task_init(void);函数尾就不会

* 20180717
** 澳特爱6925B对箱
   和志英出差一天，问题基本确认
   剩一个充电检测问题，少鸿跟进中。

* 20180716
** 澳特爱6925B对箱
   和志英在深圳办，处理主机回连从机的问题

* 20180714
** 奥特爱6928B对箱
   在深圳办和志英，处理对箱连接问题。差一种状态，要回连手机和从机。
   目前只能回连一个设备。
   设置idle时间问题，不是很合理。
** 泰奇通6919B
   BLE能用测试盒，测试按键。

* 20180713
** 澳特爱6925B对箱
   和志英出差澳特爱，处理对箱问题。

* 20180712
** 澳特爱6925B对箱
   和耀聪出差澳特爱，硬件性能OK。

* 20180711
** 起华对耳
   修改测试模式下，蓝牙名和MAC地址，和正常模式一样。
   改成红灯常亮指示为测试模式。
* 20180710
** 跟中翔达出差奥特爱
   处理对箱连接问题
   主机一直处于回连状态，从机处于可发现可连接，避免主从切换问题。
   志英修改底层没有地址，回连对箱会自动发起搜索。
   打完电话，主机不回连，底层修改，应用层就不需要延时处理了。

* 20180709
** 起华J8耳机
   修改提示音。
** 中翔达692对箱
   回连问题，有2个回连命令，有不同的问题。

* 20180706
** BLE传文件
   整理了一个SDK给客户了。
** 起华J8耳机
   同时长按音量+-，删除设备信息。

** 下午请假半天

* 20180705
** 华炬芯客户对箱连接
   开机不回连对箱，回连手机，要2个机子都按配对键，才会进行配对处理。
   替换铜霭改的2个库，程序代码也对应修改。
** 威益德6901车机
*** 录音死机
    客户原本V2012-p1版本的SDK，有此问题
    替换成p4的版本的encode_lib.a库。可以编译。
*** 69的PR口复位电平
    软复位：PR0为输入高阻，PR1口为输出0。
    RTC睡眠：RTC电压不掉电，寄存器值会保留，不为复位为默认值。
** 欣瑞声BLE传文件
   fat12_lib.a库有问题，对512B的数据时，会出现写不进的情况。
   新发了个库spifat1_lib.a库，待测试。

* 20180704
** 起华J8耳机
   蓝灯和红灯，共电阻接地。
   PWM推蓝灯时，红灯会有交流电通过，导致很微弱的亮度。
   改成了高低电平推。亮度偏大。
** 起华对耳
   刚开机有概率性会大声一声，突然间变低。
   修改了判断对耳数据量低的条件。
** 欣瑞声BLE传文件
   远强发了个fat12_lib.a库
   可以写文件了。
   写了个BLE传文件的文档。

* 20180703
** 华炬芯触摸板
   USB数据量太大，ble有时发不过来。
** 威益德6901车机
*** 快退到文件头
    暂停播放，松开播放当前文件。
*** 软复位后malloc无法对齐
    dac环形缓冲获取6912B失败，改成固定数组形式。强制对齐。
*** 卡带模式录音
    linein转AD，music通道，dac中断获取录音接口，ladc判断任务模式合进dac
** 源创杰6901-AI音箱
   很低概率出现搜不到EDR蓝牙，只能在半秒里面一直打开可发现可连接接口。
** 中翔达692X从机沙沙声
   志英发了个蓝牙库，替换即可。

* 20180702
** 中翔达6925B 
   打电话挂断后，有概率性出现EQ表被改的情况，导致沙沙声。
   志英在看。
** 徳凯芯6925B
   混响模式，要在每个模式下，单独开启
   linein支持混响功能。
** 徳凯芯6901
   低电声音在充电下，不播放。加标志位。

* 20180630
** 中翔达6925B
   开EQ之后，不停打电话，会出现从机变成沙沙声。
   V2.2版本的SDK，就有这个问题。
   //user_send_cmd_prepare(USER_CTRL_TWS_START_CONNECTION, 0, NULL);///会有配对过程
   user_send_cmd_prepare(USER_CTRL_START_CONNECTION, 0, NULL);///没有配对过程
   user_send_cmd_prepare(USER_CTRL_START_CONNEC_VIA_ADDR, 6, addr);///有配对过程

* 20180629
** 中翔达692X对箱
   音量同步会跳变
   因为在播提示音的时候，采用默认音量导致。
   #+BEGIN_SRC C
    static int get_dac_vol()///样机同步手机
    {
        printf("get_dac_vol:%d\n",sound.vol.sys_vol_l);
        printf("sound.tmp_sys_vol_l:%d\n",sound.tmp_sys_vol_l);
        if((sound.vol.sys_vol_l == TONE_DEFAULT_VOL)&&
        ((sound.tmp_sys_vol_l == MAX_SYS_VOL_L)||(sound.tmp_sys_vol_l == 0))){
            puts("tmp_sys_vol_l\n");
            return (sound.tmp_sys_vol_l * 127 / MAX_SYS_VOL_L) ;
        }else{
            puts("sys_vol_l\n");
            return (sound.vol.sys_vol_l * 127 / MAX_SYS_VOL_L) ;
        }
    }
        case BT_STATUS_CALL_VOL_CHANGE:
    #if BT_PHONE_VOL_SYNC
            sound.vol.sys_vol_l = (info[4] * aec_param.dac_analog_gain / 15) ;
            sound.phone_vol = info[4];
            log_printf("CALL_VOL:%d,phone_vol:%d\n", sound.vol.sys_vol_l, info[4]);
            sound.vol.sys_vol_r = sound.vol.sys_vol_l;
            set_sys_vol(sound.vol.sys_vol_l, sound.vol.sys_vol_r, FADE_OFF);
    #endif
        case MAD_ERROR_FILE_END:
            music_player_puts("music_tone END ok\n");
            if (tone_var.rpt_mode == 0) {
                mutex_resource_release("tone");
                msg = SYS_EVENT_PLAY_SEL_END;
                task_post_msg(NULL, 1, msg);
            } else {
                tone_var.status = 0;
            }
            printf("sys_vol_l:%d\n",sound.vol.sys_vol_l);
            printf("sound.tmp_sys_vol_l:%d\n",sound.tmp_sys_vol_l);
            if(sound.vol.sys_vol_l == TONE_DEFAULT_VOL){
                sound.vol.sys_vol_l = sound.tmp_sys_vol_l;
                sound.vol.sys_vol_r = sound.tmp_sys_vol_r;
                sound.tmp_sys_vol_l = 0xFF;
//                dac_channel_on(DAC_DIGITAL_CH, FADE_ON);
            }
            printf("sys_vol_l:%d\n",sound.vol.sys_vol_l);
            printf("sound.tmp_sys_vol_l:%d\n",sound.tmp_sys_vol_l);
//            music_tone_end();
           break;
   #+END_SRC

* 20180628
** BLE传文件
   接口s16 rec_file_delete(RECORD_OP_API *rec_op_api);
   在p4下不能使用，玩具的SDK，可以用
   #+BEGIN_SRC C
    typedef void (*btstack_packet_handler_t)(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size);
    extern void s_att_server_register_packet_handler(btstack_packet_handler_t handler);
    #define HCI_EVENT_PACKET                            0x04
    #define ATT_EVENT_CAN_SEND_NOW                      0xB7
    #define HCI_EVENT_NUMBER_OF_COMPLETED_PACKETS       0x13
    #define DAEMON_EVENT_HCI_PACKET_SENT                0x6C
    static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size)
    {
        int mtu;
        switch (packet_type) {
        case HCI_EVENT_PACKET:
    //        printf("HCI:%x\n",packet[0]);
            switch (packet[0]) {
            case ATT_EVENT_CAN_SEND_NOW:
                puts("N--\n");
                //streamer();
                break;
            case DAEMON_EVENT_HCI_PACKET_SENT:
                puts("+");
                break;
            case HCI_EVENT_NUMBER_OF_COMPLETED_PACKETS:
                puts("-");
                break;
            }
        }
    }
   #+END_SRC
   接口extern u16 rec_file_write(RECORD_OP_API * rec_op_api, u8 *buf, u32 len);
   在写SD卡是正常的，但是写flash不正常。

* 20180627
** BLE传文件
   目前可以传文件。
   AI音箱不能初始化flash文件系统。
   只能用玩具的SDK。
* 20180626
** 源创杰6919B
   蓝牙一靠近电机旁边，就会出现蓝牙信号被覆盖，导致播歌卡，甚至搜不到。
   将天线焊到机子外壳上。
** BLE传文件
   改APP源码测试中

* 20180625
** 华炬芯6908A触摸板
   没有解析触摸板的report
   用keyboard变量写立即数为2
** 源创杰6919B
   电机影响到蓝牙性能

* 20180622
** 科普豪6908C耳机通话效果
   软件改参数，听起来一直很闷
   最后在mic那个多焊了个102的电容，通话就清晰了。

** BLE传文件
   在github找了个APP的源码，来测试
   可以分包发送，不限于只有20个字节。

* 20180621
** BLE传文件
   在公版的SDK-V2012-p4版本上加，先用SD卡测试，

* 20180620
** 获取手机时间
   user_send_cmd_prepare(USER_CTRL_HFP_DATE_TIME,0,NULL);
   void get_phone_time(char *data , u16 len)
   {
       puts("get_phone_time:\n");
	     put_buf((u8 *)data , len);
	     puts(data);
   }

* 20180619
** 起华J8中控耳机
   加入充电关机
   音乐跟通话的音量同步，做了个音量映射表。
   可调节只有16级，但是实际音量有25级。

** 爱瑞声692X
   播提示音会抖动，关掉打印
   用SD卡升级，要改成调地址形式，不能用复位形式。

** 爱瑞声6901用ble传音频
   要珠海沟通，是否做传音频文件的操作。

* 20180615
** 威益德6901用ID3内存不够
   修改ID3编码统一为Unicode
   改ID3的内存为malloc(),
   要不然内存不够，在播music的时候，打电话会死机。

* 20180614
** 触摸板
   抓包给日新分析。
** 起华6904D中控耳机FF209
   带功放，

* 20180613
** 起华6904D中控耳机J8
   基本OK，给客户测试了
** 威益德6901
   判断长文件名不为0，长文件名为Unicode
                  为0，为ASCII
   ID3信息编码有问题。
** 起华对耳测试回连距离异常
   手机回连样机，手机当主机，距离远
   样机回连手机，样机当主机，距离近

* 20180612
** 科普豪69获取电话本
   获取电话本时，来电会导致btmsg线程挂起，原因是播放提示音时，
   需要资源申请时失败导致。
** 起华6904D中控耳机J8
   调试中。

* 20180611
** 金华AI音箱
   储存speex语音的spx文件，应该没有文件头的。
   调用public static void setIsLog(boolean log);可以开启底层库的打印。
** 其他方案的对耳
   络达AB1526
   风动WT200M/S
   炬力ATS2829
   都是class 1的功率。

* 20180609
** 起华6904D对耳问题
   出差华强北测试69对耳的问题。
   见邮件
** 金华AI音箱
   修改static u16 speex_encode_write_cbk(void *hdl, u8 *buf, u16 len);里的发送函数，
   为自定义属性的发送函数。
   打开void ladc_isr_callback(void *ladc_buf,u32 buf_flag,u32 buf_len);里的
   speex_encode_ladc_isr_callback(ladc_buf, buf_flag, buf_len);函数执行，才会有发送语音。
   APP端,new SpeechAiManager()，就会新建一个spx文件，用于储存speex的语音数据。
   speex和通用的开源不一样，珠海修改过。
   再调用mSpeexManager.decodeFile()解码成16kHz 16bits的PCM数据。

* 20180608
** 无线云图6904D出现机子开不了机
   有4种情况。见邮件。
** 金华AI音箱
   将le_server_smart.c替换为le_server_module.c文件，写回调才能上抛。
   le_server_smart.c只能用于杰理的AI的APP。要连接正常后，才能上抛数据。
   le_server_module.c用于自定义gatt profile。

* 20180606
** 设置对耳播放声道
   __set_soundtrack_compound(1);///主机播放左声道
   __set_soundtrack_compound(2);///主机播放右声道

** 博建6908C
   目前测试VMCU换成226，才行。
   VDDIO的电压，比VBAT的电压，上升比较慢。

** 联巨兴6904D充电LDOIN漏电
   以后强制LDOIN要加二极管，和对地2M的电阻。

* 20180605
** 博建6908C开不了机
   停在uboot 1.0里出不来，插USB，弹出盘符，下载时，提示读不到flash。

* 20180604
** 芯运6902用MAC电脑拷贝会出现2个文件
   一个是原文件，一个是AppleDouble，文件名后缀名都一样，但是是隐藏文件，无法播放
   默认SDK，没有去掉隐藏文件，会显示出来，但是播放不了，会跳过。
   extern void hidden_file(u8 flag);
   hidden_file(1);///在进music_task设置一下就行。
** 起华6904D改sbc码率
   sbc码率改成27后，距离能达到水果那边的窗口。
   要是54的时候，只能在老板的门口。

* 20180601
** JBL 串口协议
   基本能用，写了一些基本的命令，后续需要测试再加新的命令。
** 起华6904D对耳
   信号差，就mute，测试可以，
   加了出声音，慢慢变大的操作。

* 20180531

* 20180530
** 科普豪6908C对耳
   iPhone X手机，所有样机都卡。

** JBL音箱自动化测试协议
   目前切换测试模式正常。

* 20180529
** 新子K歌宝SD卡掉线
   CMD脚的检测，可以直接放到key_drv_ad.c文件里，直接检测。
   扫描函数里要开上拉才行。
** 起华6904D对耳先回连从机再回连手机
   铜霭发了2个库，做了版V2013版本的程序
** 起华W302对耳固定左耳当主机
   软件已改好，V2013版本的。

* 20180528
** 新子K歌宝播放SD卡卡音
   由于SD的CMD脚和DATA脚复用做AD检测导致，想办法优化。
** 起华6904D-W302固定左右耳
   可以检测，功能还没做。
** JBL音箱
   开LDO模式，SW脚的电感要换成0R电阻。

* 20180525
** 测试692X普通IO推灯效果
   PB口只有8mA，推屏不行。
   PA口可以。
** JBL程序兼容正常模式和测试模式
   修改成变量，不用宏包含。
** 6919的BLE的程序广播包参数
   修改广播包参数，不起作用，一直是5ms以内。
   69的SDK是可以的。
** 起华6904D对耳
   先回连从机再回连主机，铜霭发了2个库，测试OK。

* 20180524
** 起华6904D--R208对耳
   通话效果，只能把增益调高，声音变清晰，但会引入环境噪音，
   在嘈杂的环境下，无法使用。
** 起华6904D改先回连从机再回连手机
   铜霭发了个蓝牙库，测试还是不行。

* 20180523
** 源创杰46歌词加密无法点播MP3
   通过目录项里的簇号，无法找到文件。
   刘行发了补丁库dev_mg_lib.a，客户测试OK。
** 起华6904D对耳
   客户想改成先回连样机，再回连手机，测试不行
   铜霭说，底层做了限制，不能这样操作，具体原因未说明。

* 20180522
** 芯运6902外挂flash播放
   播报提示音有间隙。德科创的程序，就可以，但是是用提示音播放的。
   
** 华炬芯6901用IIC从机接收
   主机iic是5V输出，要改成3.3V供电才行。
   iic的打印要去掉，影响时序。

* 20180521
** 无线云图6904D
   耳机通话，客户确认中。
   充电问题，解决不了。
** 源创杰4601点播MP3
   通过簇号，播放不了。国炜处理
** 芯运69玩具
   无间隙播放，mp3文件剪切不干净。明秋说，怎能听效果。
* 20180518
** 出差三诺
   处理JBL音箱的认证，仪器问题，立辉处理

* 20180517
** 6919-BLE用sniff模式
   默认SDK会复位，要改成PWR_DCDC15模式。

* 20180516
** 出差无线云图6904D对耳
   测试盒连接慢，要避免测试盒进入搜索设备状态，会导致测试盒连接慢。
   板卡测试，只需要快速测试即可。

* 20180515
** 无线云图6904D对耳
   5V充电唤不醒问题，不能在充满电之后，调用soft_poweroff()函数，有隐患。
   串连问题，复现不了。

* 20180514
** 出差无线云图6904D对耳
   5V充电唤不醒，是有问题，待会分析。
   串连复现不了。

* 20180511
** 691X的开发板
   PR0是短接到地的，flash口是PB0-PB4
** 中翔达wav 32bits断电播放异常
   从头播放正常，断点播放异常。
** 692X按键音播放哒哒响
   69的按键音，比较小声，比较难听出来。
* 20180510
** 威益德69系列spp发送
   放在main线程，因为会pending住，会导致死机
   放在优先级低的，就不会有事，但会卡住当前线程。
   建议新建一个线程，专门用于发送spp数据。
   底层是会pend，发送完之后再返回的。
** 科普豪69推大屏的数码管
   由于每一段都有2个灯，需要修改驱动。
** 芯运69玩具SDK单曲无间断播放
   伟文发了一个库，发给客户测试了。

* 20180509
** 威益德69获取收音立体声
   printf("get_fm_stereo:%d\n",get_fm_stereo());
** 微源功放
   mute脚控制脉冲要大于60ms，才能正常。

* 20180508
** 小霸王6905A升级成图灵APP
   用测试盒烧录认证码，显示AU超时，吴旭处理中
   改用USB工具烧录
** 艾玛威6901A点阵屏耳机
   调试界面，基本OK。
* 20180507
** 威益德用恒大智通蓝牙测试盒
   第一次连接，通话会出现卡5s左右，才有反应，海华分析中。
   由于“AT+CMEE”指令，测试盒没有响应。
** 威益德spp发送数据给APP
   在main线程发送，由于main线程优先级较高，会卡死蓝牙线程。
   在music模式下测试，不会卡死，会卡住一段时间，只能减少发送频率。
   客户写的编码器，会累积一堆音量加减消息，等待执行，需要去掉这一部分。
** 泰芯为69带BLE
   特征同时带读写属性，句柄是一样，需要同时在read、write回调执行。
** 艾玛威6901A带点阵屏
   调试中，修改界面。
* 20180505
** 联巨兴6901A
   点阵屏点不亮，配置IO口不对。
** 联巨兴6904D对耳
   快速插拔充电，会无法充电。
   在关机的时候会有一段时间，关闭了充电唤醒，如果在这期间，产生上升沿，会导致电平丢失。
** 艾玛威6901A带点阵屏耳机
   屏点亮，板子硬件调通。界面待改。
** 科普豪6901A收音底噪
   用QN8035收音，用升压5V给HT1628芯片供电，会带来底噪滋滋声。
   分析是因为升压5V供电不足，多并了一个芯片4004，但是客户测试还是不行。

* 20180504
** 宇恒69AI想兼容其他APP
   之前有“火火兔讲故事”的APP，想做到69AI上面。
** 69点播MP3
   #+BEGIN_SRC C
 	 u32  music_play_by_path(MUSIC_OP_API *mapi)
 	 {
		u32 err;
	//    u8 *path;
		const char path[]="/1*.mp3";
		puts("1\n");
	//    path="/音乐/";
		mapi->fop_api->fop_init->filepath = (u8*)path;
	//    printf("file path : %s  \n",path);
	//    err = music_play_api(mapi,DEV_SEL_CUR,0,PLAY_FILE_BYPATH,&(mapi->dop_api->file_num));
		err = music_play_api(mapi,DEV_SEL_SPEC,0,PLAY_FILE_BYPATH,&(mapi->dop_api->file_num));
		return err;
   }
   #+END_SRC
** 科普豪6901-8035收音底噪
   4004的升压IC，推灯的亮度，电池的电源位置，都有点影响。

* 20180503
** 秦齐发射器死机
   发射器切模式进idle，再回到发射模式，会死机。
   让客户改用SDK的流程，不要自己自定义流程。

* 20180502
** 天罡微69系列vivo X6A无法连接pin code
   用p4测试过，也会，其他vivo没有问题。
   不设置pin code就能连接。
** 宇恒69系列普通SDK回连导致BLE异常
   之前AI的SDK，回连样机当主机，手机当从机，会影响BLE的发送。
   普通的SDK，也会有这样的问题。
** 源创杰69019B-BLE烧录不了C版晶圆
   替换otp_ver.bin，修改日期为20171201，就可以烧录。
   原先A版晶圆为20170701
** 诚谦LC6904C低电LVD复位
   客户用纽扣电池供电，没有加升压iC，后续生产可能会有问
   
* 20180428
** 源创杰6919B烧录不了
   升级烧写器到2.11.1版本
   BLE的SDK不支持C版晶圆的问题。

** 692X异步唤醒问题
   异步唤醒底层库都为空函数，没有执行。
   
* 20180427
** 博益友6905B K歌宝
   推RGB灯，会有底噪声。
   客户板子没分地，mic的电路距离主控太远。
   改板处理。

* 20180426
** 博建6901A生产不良
   VMCU有4V供电，但是其他电压都没有。
   正常情况下，VMCU有供电，那RTCVDD电压就一定要有输出。
   问题是批次不良，换主控。
** 德科创6904D待机功耗高
   耳机要连上手机，手机不播歌，隔一段时间才会进入power_down模式。
   功耗为1mA-1.5mA之间。
   DAC输出频响不好，失真度高，无解。
   
* 20180425
** BLE标志
   indicate比notify多了一个应用层的GATT_MSG_EVENT通知。
   Notification快，因为indication要等回复才能发下一个包。
   indicate本来就是耗时的，担心耗时就用notify。
** 起华FF208调音质
   调试一个低音版本给客户。
** 巴达木692X非PR口唤醒
   SDK有对应函数，但是和690X一模一样，钧仟先对数据手册。
** 诚谦LC6904C
   生产一百个，有一个会LVD复位，
   客户不会焊板子，要过来，让他五一之后再来。

* 20180424
** 不同手机BLE发包数据间隔
   安卓最低7.5ms，苹果是20ms。
** 也杨翁工linein录音
   69系列在linein单声道模式下，录音成双声道，会出现左右声道不对称。
   测试没有发现。
** 6919-BLE的SDK
   OTP只剩余6-7K空间。
** 69系列浮点运算
   不支持，只有52支持。
** 天罡微69-p3开启pin code
   用vivo X6A手机连接不上，目前找不到该手机。

* 20180423
** BLE传输速度，不同手机的速率
   Android 4.3 设备： < 2KB/s
   Android 4.4 设备: 4-5KB/s
   Android 5、 6、 7 设备: 5-8KB/s（ 部分手机可超过 20kB/s）
   IOS 8.3 设备: 3-4KB/S
   IOS 10、 11 设备:6-8KB/s

* 20180421
** 博建6901开不了机
   LDOIN有电池供电3.8V，但是其他电压都没有。
   RTCVDD电压一定要有，晶振才能起振。

* 20180420
** 69系列消息池
   void key_msg_sender(char *name, u32 msg);中
   os_taskq_count(name, &cnt);获取的是消息池的剩余空间

* 20180419
** 69系列修改pin code
   #+BEGIN_SRC C
    extern void bt_pin_code_spec_deal_handle_register(void (*handle)(char *pin_code));
    void set_bd_pincode(char *pincode)
    {
        char tmp[] = "1279";
        printf("len:%d\n",sizeof(tmp));
        memcpy(pincode,tmp,sizeof(tmp));
        printf("pincode:%s\n",pincode);
    }
   #+END_SRC
** 起华6904D对耳充电
   设置了80分钟充满，但是电池如果电量太低，80分钟充不到4.3V。
   会导致一直在耗电，关不了机。
** 起华6908C--FF108
   使用p4的SDK，没有测试通话效果。
** 针对对某个按键做长按时间处理
   #+BEGIN_SRC C
    void key2msg_filter(u8 key_status, u8 back_last_key);中添加
    {
        ///长按3s关机。///
        static u8 key_delay = 0;
//        printf("key_status:%d...back_last_key:%d\n",key_status,back_last_key);
        if(((KEY_LONG == key_status)||(KEY_HOLD == key_status))&&(0 == back_last_key))
        {
            if(0xFF != key_delay){
                if( key_delay > 11){
                    key_delay = 0xFF;
                    key_status = KEY_LONG;
                    back_last_key = 0;
                }else{
                    key_delay++;
                    return;
                }
            }else {return ;}
        }else{
            key_delay = 0;
        }
    }
   #+END_SRC

* 20180418
** 宇恒69AI回连APP出现兼容性问题
   APP主动连接对箱，手机EDR做主机
   样机重启回连APP，样机EDR做主机
   解决办法，要将回连后，将样机主机调整为从机，才不会影响到BLE。
** 针对对延时时序控制严格
   在临界区内，不要出现调用函数，尽量在临界区外，获取索引，
   转换成指针形式，才能控制好时序不会跳动。
** Android打印byte[]
   #+BEGIN_SRC java
   public static void printHexString(String hint, byte[] b)
   {
        Log.d(TAG, hint);
        for (int i = 0; i < b.length; i++)
        {
            String hex = Integer.toHexString(b[i] & 0xFF);
            if (hex.length() == 1)
            {
                hex = '0' + hex;
            }
            Log.d(TAG, hex.toUpperCase() + " ");
        }
   }
   #+END_SRC

* 20180417
** 69系列PB3引脚
   开机就输出高，没有上拉。
   maskrom程序写死，无法修改。

* 20180416
** 玩具SDK挂载外置Flash
   spifat1_ctrl_open(1, 1);///第一个参数设置成1，每次进PC，会格式化Flash的文件系统。
   生产一定要改成0.
** 出差中翔达-科迈通处理对耳
   客户用音魅电子的测试盒，有一个测试盒连不上，要机子连接手机之后才能连接。
   高频声，要装壳之后，就会有，小概率性出现。
   带触摸的机子，灵敏度不是很好。
* 20180413
** 69APP通信机制
   设置发送数据的心跳包mJLBluetoothRcsp.setDeviceInquireTimeInterval(500);单位ms。
   小机这边无法发送数据给手机，必须有手机发送命令，样机再回应数据给手机。
   小机发送流程：
   1.rcsp_report_status(x)
   2.u8 rcsp_event_cbk_send_process(int send_allow_flag)
   3.自定义填充数据函数，post_....(),参考Post_Radio_StartInfo_to_rcsp()
** 宇恒69AI要做常连接状态低功耗
   不支持。要等智能耳机SDK。

* 20180412
** 汉普功能
   固件没有连接手机的时候，发起siri,通过HFP发送一段语音“打开酷走车机”，
   由系统识别，并打开软件，连接样机。

* 20180411
** 69系列连接BLE获取MAC地址
   在连接成功有buffer反馈，16字节。
	 前面2byte是handle，接着1byte的role，1byte的addr_type，然后就是6byte的peer_addr。
   手机蓝牙MAC地址可以改的，EDR和BLE的地址是不一样的。
* 20180410
** 宇恒69AI
   V100版本，部分安卓手机APP重连后，固件发送数据后，APP没有回调。
   卓成分析，语音数据没有产生回调，具体原因分析中。
** 汇杰芯69对箱
   主机100ms发送消息给从机，在连接从机后，发这些消息会导致底层同步丢失。
   后面客户删除提示音后，又会出现这个问题。
   铜霭反馈，是有这样的问题，无法修改。
   让客户自己修改应用层的流程。

* 20180409
** 芯运69玩具SDK
   外挂flash，要CS定义好，接上IO，初始化识别要用到
** 实捷BT15、BT65D
   修改频点881-1079。
** 宇恒69AI
   AI_SoundBox_v100修改过IOS重连重启的bug后的软件,
   在OPPO_A79的机型上装客户端软件,在手机不操作时,
   板子开机重连后出现对话无法识别的bug。
 
* 20180408
** 老树开花6901A
   RGB用定时器去推，调不好，播歌之后，会有问题。
   改用延时推灯，目前半秒推1次9盏灯，测试正常，播歌也不会卡。

** 汇杰芯69对箱
   主机以100ms发送消息给从机。在从机关机后，主机会有延时断开，导致消息池累积消息，
   下次连接有导致消息同步问题。
   如果以500ms发送就不会有事。
** 嘉兴科美69对箱
   对箱连接不上，频偏有很大影响。
   其他程序问题，修改软件问题。
** 光交锁
   日新新发的uboot.bin，测试正常，可以升级。

* 20180404
** 汇杰芯69对箱
   从机关机后，主机发送数据，会卡死在底层，导致下次连接后，同步有问题。
** 嘉兴科美69对箱
   下载程序之后，很难连接对箱。
    #define    TWS_SLAVE_WAIT_CON         0

* 20180403
** 光交锁Uboot工程
   日新发的库，测试还是不行，错误码为-12，后面又发了一个新的，还没测试。
** 老树开花XR871-H2案子
   基本功能都OK，剩下灯还没推，灯的效果未定义。
** 汉普6904D耳机
   开启回声消除，通话会突然间没声音。
   进不了低功耗，珠海还没整。

* 20180402
** 起华6908C单耳调试
   E23采用6908C，调试功能，基本正常。
   E25有一个机子不行，通话很模糊，一个机子通话正常。
* 20180330
** 宇恒69AI-V100
   V100-SDK和V200-SDK不通用，V100在重启连接APP，打开发送speex语音，会导致重启。
   初步判断，是库有个断言导致重启。
   吴旭知道，在改库。
** 69AI的SDK
   V100用于客户自己有资源，自己开发APP。
   V200专用于连接老树服务器。
** 起华69对耳
   修改提示音。
* 20180329
** 起华R208对耳音质调试
   样机原本没低音，声音太散。
   喇叭厂，更换喇叭，喇叭前后密封(音量变大，低音变重)，前面加防尘网，人声变清晰，不失真。
   目前播放告白气球，时不时会有很小的噗声。
* 20180328
** 起华69对耳
   修改双击上一曲，三击下一曲，关机提示音，双击上一曲和搜索设备同时起作用。
** 光交锁安卓手机usb升级
   需要在uboot 2.0加2个命令。
** 威益德6905C
   电话本获取sim卡的联系人，会发2次，一个是名字和号码，一个是序号和名字。
   目前建议客户判断号码是否为数字，进行过滤。
   开机默认进蓝牙，关闭蓝牙可发现可连接，会导致蓝牙栈卡死。

* 20180327
** 出差国华
   broadcom20738 ble低功耗
   EDR支持4M包
   ble有分真ble，和假ble
   假ble为软件协议层模拟。
** 光交锁6905D
   测试USB升级apk，荣耀6X点击下载没有反应。
   测试发现在maskrom的uboot1.0是可以，在Uboot2.0不行。
** 69系列擦除flash
   -format 0-1024
* 20180326
** 起华69对耳进入低功耗哒哒声
   进入低功耗模式，DAC和VCOMO会随DCDC产生1秒2次电平跳动噪声。
   跳动大概80mV电压。
   解决办法：
   #+BEGIN_SRC C
		case MSG_DAC_ON:
			puts("main_dac_on\n");
			set_pwrmd(PWR_DCDC15);
			dac_on_control();
			break;
		case MSG_DAC_OFF:
			puts("main_dac_off\n");
			dac_off_control();
			set_pwrmd(PWR_LDO15);
			break;
   #+END_SRC
** 汉普6904D耳机带ble
   功能正常，开不了power_down状态。
* 20180323
** 中翔达69发射器录音
   SDK的录音流程是缺失的，参照p4添加，有部分函数，连接不到。
   替换库，又会导致其他函数，没定义。
   目前有文件，有声音，但都是杂音。p_ladc_rec变量获取不到。
** 光交锁6905D连测试盒死机
   是因为晶振原因，频偏太大就会。
** 起华对耳V2013通话调试
   远端近端，都有哒哒声。
** 69AI的V200APK
   V200.apk安装到手机刷新不出资源。
* 20180322
** 中翔达发射器录音
   没空看。
** 光交锁6905修板子
   测试盒，畅玩6X，华为Novo，连接不上，其他手机可以。
   测试盒连接会导致重启。
   没有pcb，无法查看。
** 起华6904D对耳
   通话时，就算不说话，也会哒哒声。
   用V2012-p2版本，就不会。
   通话参数，2个版本是一样，不同的是dac的中断改动，处理延时加的。

* 20180321
** 华炬芯6904D耳机改用数字音量
   改用数字音量，会有底噪声。使用数字音量，模拟音量默认最高，导致的。
   可以降低模拟音量的最大等级，要降到21级才可以，但是这时整体音量会变低。
** 杰飞达69系列spp协议
   客户测试发现，p4版本，如果按照公版，关闭1拖2，就会导致，手机拿远之后，再回来，就搜索不到蓝牙。
   打开1拖2，就正常。
**  汉普X8-6901A
   U盘接口，兼容有充电功能。
   屏幕接反，180度反向。
   晶振频偏大，晶振太远，蓝牙天线太长，绕了屏幕。
   发射底噪大，杂音、电流声太强。

* 20180320
**  天浪
   工程交流。
** 光交锁tea加密库
   测试新的加密库，正常。
** 杰飞达69用spp
   客户用spp和APP通信，走远回来后，会导致蓝牙搜索不到。
   测试p4版本，正常。
** 鑫闻达调节按键音大小
   #+BEGIN_SRC C
    void key_voice_init(void)
    {
        memset(&key_voice,0,sizeof(_key_voice));
        key_voice.vol = 2000;
    }
   #+END_SRC
* 20180319
** 美师傅6919B死机问题
   buf没有溢出检查，会死机。
** 光交锁tea加密库
   存在类型转换，会死机。
* 20180316
** 起华6904D中控耳机
   带3个按键。
** 69系列
   	芯片序号标签  printf("chip index =%x \n",get_chip_index());  开发板打印chip index =7
	  芯片ID         printf("CHIP_ID =%x \n",JL_SYSTEM->CHIP_ID);   开发板打印CHIP_ID =5300
    内核电压      SFR(JL_SYSTEM->LDO_CON, 15, 3, 0b101);     // 3.3 -> 1.2 DVDD set to 1.0v
                   110(0.9V)/101(1.0V)/011(1.2V)/010(1.3V)/001(1.4V)
** 起华6904D耳机测试蓝牙距离
   DVDD、BTAVDD、VDDIO电压改动，对蓝牙距离影响不大，差不了一步的距离。
** 6919耳机SDK
   开关DACVDD，调用LDO1_EN(0/1);
* 20180315
** 69临界区操作
   临界区代码，如果cache命中不了，会从flash中读取，会导致执行时间不一样。
   #+BEGIN_SRC C
     //接下来的函数代码存放段测试。
     //不要内联
    void open_critical(u8 cfg) __attribute__((section(".ramx_code"))) __attribute__((noinline));
    void open_critical(u8 cfg)
    {
    //    puts("open_critical\n");
        CPU_SR_ALLOC();
        OS_ENTER_CRITICAL();
        JL_PORTB->DIR &= ~BIT(0);
        JL_PORTB->OUT |=  BIT(0);

        u8 i = 50;
        while(i--){
            __asm__ volatile ("nop");
            __asm__ volatile ("nop");
            __asm__ volatile ("nop");
            __asm__ volatile ("nop");
            __asm__ volatile ("nop");
        }
        JL_PORTB->DIR &= ~BIT(0);
        JL_PORTB->OUT &= ~BIT(0);

        OS_EXIT_CRITICAL();
    }
   #+END_SRC
** 汉普6904D耳机
   调试OK，距离可以。
** 汉普6901煲机异常
   未测试到。
* 20180314
** 小树开花RGB灯环
   RGB灯WS2812B，单线控制协议。纳秒级精度。
   http://blog.csdn.net/tangxing1212/article/details/42964417
   http://blog.csdn.net/zoomdy/article/details/54730618
   http://blog.csdn.net/darren2015zdc/article/details/52262197
** 69系列一拖2不支持ble
   天师说，固件开1拖2，不支持ble。
   测试发现，开机进入蓝牙后，蓝牙栈就卡死了。
   耳机SDK，不支持ble，没有包含对应的C文件。
** 69系列蓝牙获取手机的ID3信息
   在V2012-P3版本测试，可以获取到，但是兼容性问题无法保证。
** 69蓝牙对讲机
   只支持A2DP协议，单向发送，不支持同时的双工。
** 宙心WiFi-9601
   耳机座子和linein座子，接法是，其他一个音频接1K下拉，没插入检测脚跟他短路为低。
   插入之后，开路，检测脚上拉，检测为高。
** 6919-ble使用USB当串口
   搬耳机版的程序，测试OK。
   #+BEGIN_SRC C
	 #ifdef UART_USBP_USBM
		JL_USB->CON0 = 0;
		JL_USB->CON1 = 0;
		JL_USB->IO_CON0 = 0;
		JL_USB->CON0 |= BIT(0) ;
		JL_USB->IO_CON0 |= BIT(11) ; //USB_IO_MODE

		JL_IOMAP->CON1 |= BIT(3) | BIT(2);
		JL_USB->CON0 = BIT(0) ;
		JL_USB->IO_CON0 = (BIT(11) | BIT(10) | BIT(9)); //USB_IO_MODE	//DMDIE	//DPDIE
		JL_USB->IO_CON0 |= BIT(0); //TX DP
		JL_USB->IO_CON0 |= BIT(3);//RX DM
		JL_USB->IO_CON0 &= ~BIT(2);//tx dp

		JL_USB->IO_CON0 &= ~BIT(5);//DM下拉
		JL_USB->IO_CON0 &= ~BIT(7);//DM上拉
	//    JL_USB->IO_CON0 |=  BIT(4);//DM下拉
	//    JL_USB->IO_CON0 |=  BIT(6);//DM上拉
   #endif/*UART_USBP_USBM*/
   #+END_SRC
* 20180313
** 源创杰6919B测试盒升级不了蓝牙名
   蓝牙名测试盒升级不了，是因为程序写死了。
   #define ADV_NAME_EN         1            //广播包是否填充名字信息
   宏置1后，才会使用配置文件。
** 汉普6904D耳机
   进入power_init()函数出不来，BTAVDD电压5V，VDDIO电压为0.7V。
   查不出其他原因，板子废了。
* 20180312
** 华炬芯6904D挂脖式耳机
   开关机，播提示音切dac通道，有噗噗声。
   将VCOM换成104电容，软件上用加大dac上电时间，dac_power_on_time()。
   蓝牙通道使用数字通道，在执行dac_channel_off(BT_CHANNEL, FADE_ON);会有杂音。
   可以通过dac_mute处理掉。
   但是有一些杂音，播提示音，概率性出现。
** 宙心WIFI-6901
   RGB灯，是共阳，板子是共阴
   linein和耳机，检测拉低不了。
** 伦茨6919A隔推会有噗噗声
   6919默认用直推，使用了dac开关dac_toggle(1)，所以在dac关，就有噗声
   可以改成dac_mute();
   DACVDD控制高mute功放，关机会噗声，加电容处理掉，过滤脉冲。
* 20180309
** 源创杰6919B蓝牙名升级不了
   铜霭发的测试盒程序，客户测试会出现conerr。
   铜霭说是，升级相同的蓝牙名，就会出现这样。
   客户星期一拿样机给我测试。
** 中翔达6908C单耳通话调试
   机内有腔体，会有震荡回声。通话声音小，不清晰。
   改通话效果就可以。
** 芯运69--IIS调EQ
   程序有问题，重新初始化eq导致，
   开启软件EQ，会死机。
** 美师傅6919B-ble使用UART2的PA3打印不了
   AD-key默认使用PA3，需要注释掉，开启IO-key即可。
** 宙心WiFi
   IIS的格式改为通道数：2，通道位宽：16，采样频率：44.1
   设置为每帧32bits。
* 20180308
** 宙心WiFi
   添加WiFi模式播放iis。
   添加串口协议。
** 彩荣测试盒替换sbc语音
   转成wav文件Windows PCM，格式32K， 16bits， 单声道。
* 20180307
** 益丰6904C烧录不了&&IIC从机
   晶振封装搞错，接地了。
   刘行，发资料，测试一下。
** 美师傅6919B串口通信
   串口接收要用hex显示，发送要以ASCII格式发送。
** 起华科技69对耳
   升级SDK到p4版本，待测试。
* 20180306
** 宙心MTK-WIFI和BT
   板子修好，串口和IIS，待调试。
   DAC单声道，耳机却双声道。
   2个RGB灯，没法推，无法输出6个PWM。
** 起华科技死机
   6904有概率性在power_init死机
   要更新到V2012-p4版本才行
   优化程序，一直打印，方便以后生成问题跟踪。
* 20180305
** 6919-ble
   做了一个ble蓝牙模块的例子。
** 源创杰6919B升级蓝牙名
   测试盒要升级到AC690x_1T2 测试盒 V1.0.7 版本，才能使用6919的。
** 汉普6905A电池电压检测异常
   电池4V，但是LDOIN的电压检测是8V。
   因为电量检测的宏，没有打开。
** 起华科技开不了机
   跟民宗确认，开机的时候，power_init会初始化所有电源，导致电源都存在。
   DCDC电源SW脚，和BTAVDD电源短路在一起。

* 20180302
** 飞灵特Novolink蓝牙模块
   支持ble模块开发，UART通信。
* 20180301
** 瑞知光交锁
   ADC的检测，放在电磁铁之后，电磁铁电阻30R左右，会耗光5V的压降。
   关锁状态，电压3.0V，开锁状态，电压0V。
   USB和蓝牙的开关锁，功能正常。
** 汉普6905A
   LDOIN测量出来的电压，是8V，误差太大。具体原因未知。


* 20180228
** 诚谦LC6904A
   socket板子，USB的限流电阻，2.4R变成100R，导致供流不足，会不停复位。
   有一颗芯片，初始化电源之后，就跑不下去。
* 20180227
** 4110直播声卡
   影志说，寄回给振荣搞。
* 20180226
** 光交锁
   USB的通信，熟悉USB的协议流程
** 4110直播声卡
   linein通道和LADC的采样通道，对应不上。
   钧仟帮忙看看。
* 20180224
** 光交锁
   蓝牙的通信，可以，待发给客户测试。
* 20180223
** 4110直播声卡
   开会讨论，在music模式下，耦合linein和mic的采样，再输出。
** 光交锁
   调试客户协议程序流程。
* 20180222
** 4110直播声卡
   调试led，按键功能。



* 20180208
** 起华69对耳
   改用PR1，上升沿唤醒，测试正常，双击OK。
** 直播声卡4110
   用玩具的SDK，能开机正常工作。

* 20180207
** 起华69对耳触摸
   触摸电压高，接近电池，要3.9V，会导通bangding的二极管，造成20uA的耗电。
   PR2不支持默认下拉到地，uboot下升级不了。

* 20180206
** 总结问题点
*** ble切模式死机
    死机问题，是切换的链表释放问题，与ble无关。
    FAT16，也能测试出来，ble连接之后切模式，也能测试出来。
*** ble回调死机问题
    ble回调函数，不能处理延时操作，会导致蓝牙栈卡死。
*** ble发送notify数据
    需要由其他线程调用，不能由回调函数调用。
*** 充电问题
    充电充不满问题。
*** power_down引起乱中断
    6919B--ble power down，会改动引脚，引起乱中断现象。

* 20180205
** 博建69对耳iPhone X通话
   通话隔个头，对线放后裤袋，就会卡。

* 20180202
** 源创杰6919B
   烧录不了，是因为用release版本的fw文件，大小为66K。
   烧录器无法烧录flash。
   旧的样片，bangding有问题，180度反向了。
** 源创杰6905C
   EDR、ble的蓝牙名和MAC地址一样，有问题。
   广播包的flags设置，
   flags为0x06正常，但是赖工手机搜不到。
   flags为0x0A不正常，安卓手机都无法连接ble。

* 20180201
** 蓝牙游戏手柄
   一定要进入安卓模式，才可以用。
** 光交锁
   spp和ble定时收发数据。
** 诚谦69车机
   空间不够，会导致能下载，但是跑的不正常。
** 6919-ble
   图标显示，显示成HID，是因为广播包的字段填充导致。
   //    0x03, 0x03, 0x12, 0x18,
   1812是HID的UUID.
* 20180131
** 光交锁
   插着下载器，隔一会会复位重启，是因为PR2接1K电阻到地。
** 源创杰6919B
   蓝牙MAC地址，有otp工具生成的cfg文件。debug版本复制release版本的文件。
   选择随机地址后，由烧录器自动改写cfg文件。
** 伦茨69对耳
   修改功能，固定右耳为主机，参考灼坤程序编写。
* 20180130
** 6919--串口通信
   频繁的中断，是因为sleep模式导致，进入sleep后引脚状态被改。
   每次接收中断，会有2个中断，一个是接收，一个是超时。
   JL_UART1->CON0 |= BIT(10);///超时中断
   要么设置超时计数，JL_UART1->OTCNT = 0xffffffff;
** AI-69SDK添加自定义命令
   命令定义参考 CBW_CMD_SPEEX_WAIT_OK， 范围在 0xA0 以上没有被使用的值， 
   并要求接收 到 app 的 命 令 不 要 在 bt_smart_rcsp_command_recieve 中 直 接 处 理 ， 
   通 过 发 送 消 息 中 转 到bt_smart_msg_deal 中处理。
   安卓APP修改 mJLBluetoothRcsp.sendCommandToDevice(new byte[]{(byte) 0xa5}, null);
** AI-69添加传统蓝牙判断手机系统
   extern void feedback_manufacturer_handle_register(void (*handle)(char *msg,u8 len));
   void manufacturer_handle(char *msg , u8 len )
   {
       puts(msg);
       putchar('\n');
   }
   在static void bredr_handle_register() 中调用feedback_manufacturer_handle_register(manufacturer_handle);
** 中翔达46在U盘播放下开混响，拔出U盘后混响停止不了
   err = os_sem_pend(echo_sem,0) ;///0改成1，作为超时释放信号量。
   待考量是否正常。是否有隐患。
** 光交锁PCB
   使用Allegro，以 brd 文件结尾

* 20180129
** DAB案子
   开机噗声。加默认上拉mute，延时1.5s开机。
** 6919--串口通信
   PB0-PB1是SPI flash的通信脚。
   UART1，频繁的中断，掺杂很多异常数据。

* 20180126
** DAB案子
   改板，加mOS管mute声音。
** 源创杰6919-ble
   串口通信未整。
** 汉普6902A播提示音
   播提示音会死机。
   函数music_prompt_play()和music_play_api()有冲突，嵌套执行会死机。
** 小树开花WiFi音箱
   低电关机，加入开机计时后，才执行。

* 20180125
** 起华科技69对耳通话音量同步
   华为荣耀6x，打电话不会同步，按音量才会同步，如果最大音，音量+，不会同步。
   华为Nova，如果上次电话音量为0，会同步一个音量0，导致样机音量设为0，再次调节音量，无法再加大声音。
   游总iPhone 7，手机配对连接，就会回调通话音量同步，此时不是通话状态，导致误改了音乐的音量。
   赖工iPhone 6，手机配对，每次打电话不会音量同步，断开回连，每次打电话就会音量同步。
** 小树开花WiFi音箱
   添加WiFi模式休眠
   关机会有pop声，怀疑断电瞬间，mute不受控，功放放电导致。
* 20180124
** 起华科技69对耳
   iPhone 7 连接蓝牙就会回调一次call_vol_change()，导致系统音量被改变。
** 小树开花WiFi音箱
   处理反馈问题
** 实捷
   S33B修改手动播放。
   BT58修改通话下一分钟关闭发射问题。
** 光交锁
   安卓手机枚举USB
* 20180123
** 小树开花WiFi音箱
   蓝牙、music、linein下功放mute功放。

* 20180122
** 起华科技69对耳
   通话的时候，调音量没声音。
   设置音量的时候，不能用FADE_ON，突变设置会没声音。
   开始打电话，要判断VM通话音量，是否为0，会导致没声音。
** 汉普6901A车充
   蓝牙收不到，查不出啥原因。屏幕显示不正常，还没搞定。
** 小树开花wifi音箱
   uart协议增加PAmute控制，供WiFi主控使用，能mute掉开始的爆破音。
   音频播完的掉电，无法mute，需要改板。

* 20180119
** 小树开花WiFi
   增加WiFi模式，增加协议WiFi状态。
** 汉普6901A车充
   支持邓工调试。
* 20180118
** 起华科技对耳
   充电板拔出USB，充电电压会有掉电现象，掉电到4.0V一下，会导致误判充电线拔出。
** ble描述符
   不会生成0x2901
   CHARACTERISTIC_USER_DESCRIPTION, READ,
** ble的notify配置
   notify不能和write_without_response一起配置，会导致notify配置handle时，没有回调产生。
** 小树开花WiFi和蓝牙
   利用“我要长大机器人”公众号，连接WiFi音箱
   还差WiFi——up脚，不让输出串口TX波形。
   创建linein任务。
** 合成语音
   百度语音在线合成
   http://tsn.baidu.com/text2audio?tex=wifi%E6%A8%A1%E5%BC%8F&lan=zh&cuid=f6532074500827f24995f36699b11abc&ctp=1&tok=25.d440799ee39656414071490090cce5ae.315360000.1817018727.282335-9279783
   http://tsn.baidu.com/text2audio?tex=wifi模式&lan=zh&cuid=f6532074500827f24995f36699b11abc&ctp=1&tok=25.d440799ee39656414071490090cce5ae.315360000.1817018727.282335-9279783
   替换tex=的文本即可
   
* 20180117
** 起华科技69对耳
   拔出USB，直充变成升压，会导致LDOIN电压掉电到4.0V以下，软件判断为拔出充电线。
   软件需要做过滤操作。
   检测到掉电后，调低电流档为0档。
   延时检测5V拔出，1秒多，再关机，会导致，开机时间变长。
* 20180116
** 起华科技充电充不满
   电池在3.9V-4.0V之间，电压不会有波动，判断阈值0x7400L
   电池在4.08V-4.10V之间，电压不会有波动，增大判满时间。
** 汉普6902A
   支持邓工调试。

* 20180115
** 起华科技外置充电
   充电IC的charge点灯脚，一接主控脚，就会拉低。
   在2ms中断，不能调用太多PR口的函数，会导致延时过长，超过2ms。
** 彩荣反馈69发射器连接1拖2耳机有哒哒声
   验证发射器105的SDK，连接1拖2的公版程序，播放1KHz的音频，很容易听到哒哒声。
** 汉普6902A
   支持邓工调试。
* 20180112
** 发射器连不上炬力对耳
   连接认证失败。
** 起华科技
   出烧录程序版本。
** 鑫闻达洗刷刷
* 20180111
** 出差充电IC公司
   调试对耳充电和充电板的检测。
   充满之后，降低VBAT的电压档。为0档。
* 20180110
** 天博智4602
   代码区末尾有部分被修改，怀疑是VM操作错误，误修改了。
* 20180109
** wifi加69bt案子开发
** 源创杰修改ble
   帮客户修改ble协议，未改。
** 天博智4602样机开不了机
   之前分析过，无法弹出uboot，烧录器可以重新烧写。
** 起华通信
   69对耳调试，我的手机荣耀6X，通话距离特别短，手机有问题。
   系统频率跑160M，通话数字增益放大，加大mic的声音。
*** 切记不可用新的编译器编译，通话效果有差异
** 天地宏蓝牙能量灯
   闪频太快，get_dac_energy_value()函数只能获取瞬间能量值，需要自己做过滤取平均值。
   否则会造成切换颜色太快。
** 汉普69车充样机
   借客户一个升级工具。
** 源创杰朗琴开EQ功能
   协助卓添
* 20180108
** 串口通信
   460800波特率，在蓝牙下播歌，会丢数据。
   受蓝牙中断影响，导致中断被阻塞。
   9600波特率就不会出现丢数据。
** 中断优先级
   board.c里的irq_index_2_prio_tab数组，定义了优先级0-3。
   3为最高。
   但是底层可能有关中断的操作，导致中断的丢失。
** 起华69对耳
   在太多人和设备的环境下，从机会卡。
   在空旷的地方，通话不行。         
* 20180105
** 对箱闪灯方式
   #+BEGIN_SRC C
	void stereo_led_deal()
	{
	//    printf("get_total_connect_dev:%d\n",get_total_connect_dev());
	#if BT_TWS
	   if(BT_CURRENT_CONN_PHONE==get_bt_current_conn_type())//当前只有手机连接上，对箱没有连接
	   {
		   puts("BT_CURRENT_CONN_PHONE\n");
			if(BT_MUSIC_STATUS_STARTING == a2dp_get_status()){
				puts("BT_MUSIC\n");
				led_fre_set(0xFF,0);
			}
			else if(BT_STATUS_TAKEING_PHONE == get_bt_connect_status()){
				puts("bt_phone\n");
				led_fre_set(0,0);  ///常亮
			}
			else{
				 puts("bt_other\n");
				led_fre_set(30,1);
			}
	   }
	   else if((BT_CURRENT_CONN_STEREO_MASTER==get_bt_current_conn_type()))//||(BT_CURRENT_CONN_STEREO_SALVE==get_bt_current_conn_type()))
	   {  //当主机，只在没有连接手机进
		   puts("BT_CURRENT_CONN_STEREO_MASTER\n");

	//      puts("master\n");
			led_fre_set(30,1);
	   }
	   else if(BT_CURRENT_CONN_STEREO_SALVE==get_bt_current_conn_type())//当从机，任何状态都进
	   {
		   puts("BT_CURRENT_CONN_STEREO_SALVE\n");
			if(BT_MUSIC_STATUS_STARTING == a2dp_get_status()){
				puts("BT_MUSIC\n");
				led_fre_set(0xFF,0);
			}
			else if(BT_STATUS_TAKEING_PHONE == get_bt_connect_status()){
				puts("bt_phone\n");
				led_fre_set(0,0);
			}
			else{
				 puts("bt_other\n");
				led_fre_set(60,0);
			}
	   }
	   else if(BT_CURRENT_CONN_STEREO_MASTER_PHONE==get_bt_current_conn_type())//当主机，先连对箱，再连手机
	   {
		   puts("BT_CURRENT_CONN_STEREO_MASTER_PHONE\n");
			if(BT_MUSIC_STATUS_STARTING == a2dp_get_status()){
				puts("BT_MUSIC\n");
				led_fre_set(0xFF,0);
			}
			else if(BT_STATUS_TAKEING_PHONE == get_bt_connect_status()){
				puts("bt_phone\n");
				led_fre_set(0,0);
			}
			else{
				 puts("bt_other\n");
				led_fre_set(60,0);
			}
	   }
	   else if(BT_CURRENT_CONN_STEREO_PHONE_MASTER==get_bt_current_conn_type())//先连手机，在连对箱，当主机
	   {
		   puts("BT_CURRENT_CONN_STEREO_PHONE_MASTER\n");
			if(BT_MUSIC_STATUS_STARTING == a2dp_get_status()){
				puts("BT_MUSIC\n");
				led_fre_set(0xFF,0);
			}
			else if(BT_STATUS_TAKEING_PHONE == get_bt_connect_status()){
				puts("bt_phone\n");
				led_fre_set(0,0);
			}
			else{
				 puts("bt_other\n");
				led_fre_set(60,0);
			}
	   }
	   else
	   {
		   puts("BT_CURRENT_CONN_else\n");///手机，对箱都没有连接
		   led_fre_set(7,1);
	   }
	#endif
	}
   #+END_SRC
** 汉普6902车充
   协助邓工修改程序。
** 威益德69串口丢数据
   采用波特率460800做通信接口，接收数据会丢失。
   是否支持全双工，待验证。
** 起华科技
   蓝牙功率改为9。
** 联巨兴
   RGB和白灯，要用一个电机的PWM。
** 降低系统时钟
   20M可以，低于20M就不行。
* 20180104
** 美师傅69K歌宝喊话有嘶声
   通过改mic的模拟增益，微调数字增益。
** 变声变调
   pitch_coff(128);//原声模式
   pitch_coff(64);//男声
   pitch_coff(160);//女声
   pitch_coff(200);//童声
   pitch_coff(90);//变音
** 起华科技对耳
   关机红灯亮，替换振荣的cpu_lib_ac690x.a改善通话效果。
** 天罡微spp测试
   一次接收448字节可以，bt_spp_send_data()发送也可以。
** 博益友iPod搜索不到HID设备
   #+BEGIN_SRC C
	 __change_hci_class_type(BD_CLASS_WEARABLE_HEADSET);/*改变蓝牙设备类型，可以改变连接成功显示图标*/
	 extern void __change_hid_class_type(u32 class);
	 __change_hid_class_type(BD_CLASS_WEARABLE_HEADSET);
   extern void __bt_set_hid_independent_flag(u8 flag);
   __bt_set_hid_independent_flag(0);
   #+END_SRC

* 20180103
** 汉普6905B乐放音箱
   修改蓝牙设备图标
** 起华科技对耳
   修改对耳的闪灯方式
** iPod无法搜索到HID设备
   电量图标也无法显示
* 20180102
** IIS文档
   已发出
** 汉普6902A车充底噪
   对比样机360车充，采用的是QN8007发射，底噪会小很多，发射功率弱很多。
** 起华科技69对耳
   客户采用络达的芯片，声音有渐变的过程。
   播歌的时候，灯原本会闪亮，改为灭灯。
* 20171229
** SPP蓝牙串口数据量
   SPP返回数据量，最多一次性500字节。
** 起华通信对耳
   单键触摸IC，TTP233D，TTP233D-HA6，直接高低电平控制。
** 艾玛威69调EQ
   #+BEGIN_SRC C
	///软件EQ模式
	void eq_mode_change(int mode)
	{
		tbool ret;
		switch(mode)
		{
			case 0:
				///标准
				///puts("eq_0\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE,sizeof(eq_dbg_online_t));
				break;
			case 1:
				///摇滚
				///puts("eq_1\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_ROCK,sizeof(eq_dbg_online_t));
				break;
			case 2:
				///puts("eq_2\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_COUNTRY,sizeof(eq_dbg_online_t));
				break;
			case 3:
				///puts("eq_3\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_POP,sizeof(eq_dbg_online_t));
				break;
			case 4:
				///puts("eq_4\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_CLASSIC,sizeof(eq_dbg_online_t));
				break;
			case 5:
				///爵士
				///puts("eq_5\n");
				///eq_set_eq_bypass_flag(0);
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_JAZZ,sizeof(eq_dbg_online_t));
				break;
			case 6:
				///重低音
				///puts("eq_6\n");
				ret = read_cfg_file((u8*)eq_dbg_online,(u8 *)EQ_CFG_FILE_LOW,sizeof(eq_dbg_online_t));
				///eq_set_eq_bypass_flag(0);
				break;
		}
		///printf("EQ_Read_ret:%d\n",ret);
		///printf("EQ config file,eq_type:%d\n",eq_dbg_online->eq_type);
		eq_config_api( eq_dbg_online->eq_filt_0 ,
					   eq_dbg_online->eq_filt_1 ,
					   eq_dbg_online->eq_filt_2 ,
					   eq_dbg_online->eq_filt_3 ,
					   eq_dbg_online->eq_filt_4 ,
					   eq_dbg_online->eq_filt_5 ,
					   eq_dbg_online->eq_filt_6 ,
					   eq_dbg_online->eq_filt_7 ,
					   eq_dbg_online->eq_filt_8 ,
					   (int (*)[10])eq_dbg_online->eq_freq_gain ,
					   eq_dbg_online->eq_gain ,
					   !USE_SOFTWARE_EQ);
		soft_eq_set_segment_num(eq_dbg_online->eq_cnt);
		eq_mode_sw(eq_dbg_online->eq_type );
	}
   #+END_SRC
** 众芯达69设置成数字音量
   音量设置成0时，底层貌似会调用dac_mute(1,1);
** 科普豪69的IIS
   音乐模式播放歌曲，音量调大，声音会断断续续。
** 博润威69播提示音滋滋声
   由于dac的隔直电容太大，导致上电时间长，从而影响dac校准。
   通过延长dac上电时间，可以解决这个问题。
   //dac_vcm_rsel_set(0);
   这个函数影响dac上点速度，0为上电慢，1为上电快。默认为快速上电。
   #+BEGIN_SRC C
	void dac_power_on_time(u8 mode) 
	{ 
		if(mode == 2) { 
			puts("dac_off_delay\n"); 
			os_time_dly(15); 
			//delay(0xAFFF*70);//120ms 
		} 
		else if(mode == 1) { 
			puts("dac_power_on quickly\n"); 
			//delay(0xAFFF*70);//120ms 
			os_time_dly(40); //这个值跟进实际调整，经测试目前这个值应该比较合适
		} 
		else { 
			/*如果打开了dac_vcm_rsel_set(0);则需要延长这里的时间，增加250ms即可*/
			puts("dac_power_on slowly\n"); 
			//delay(0xAFFF*300);//600ms 
			os_time_dly(70); 
		} 
	}   
   #+END_SRC
* 20171228
** 瑞荣达BLE培训
   APP端BLE升级，不行。
   蓝牙自组网，不行。
   蓝牙地址滚式递增地址，待确认。
** 汉普乐放音箱
   增加通话功能。
** 众芯达69扩音器
   开ladc，做检测，mic的自动mute，背景音自动调低。

* 20171227
** 科普豪鑫和乐4602插linein死机
   测试不出来，打静电，打地线都死机。
   46死机有3种现象：
   1.不能复位
   2.一直不断复位
   3.复位后正常开机，但是电池电压会被拉到3.3V以下，芯片发烫。

* 20171226
** 博润威6905A做耳机
   在播放提示音的时候，会有滋滋声。
   VCOM用106,就有杂音出现了,换用105,部分芯片有,换用104,会好点。
* 20171225
** 串口代码
   #+BEGIN_SRC C
    __uart_handle *user_uart_handle;
    #define USER_UART        uart2_handle
    #define USER_UART_PORT   UART_TXPA3_RXPA4
    #define USER_UART_NAME   UART2_HARDWARE_NAME
    #define USER_UART_BAUD   115200
    static void user_uart_isr_callback(u8 uto_buf, void *p ,u8 isr_flag)
    {
        putchar('S');
        if(UART_ISR_TYPE_DATA_COME == isr_flag)
        {
            put_u8hex(uto_buf);
        }
    }
    void user_uart_init(void)
    {
        u32 status = 0;
        puts("-----user_uart_init\n");
        user_uart_handle=NULL;
        status=uart_module_open(&USER_UART,USER_UART_NAME);
        if(!status)
        {
           __uart_param uart_param;
           memset(&uart_param,0,sizeof(__uart_param));
           uart_param.baud_rate=USER_UART_BAUD;
           uart_param.io=  USER_UART_PORT;
           uart_param.workmode=UART_WORKMODE_NORMAL;
           uart_param.custom |= (BIT(14)|BIT(3));
           status=uart_module_init(&USER_UART,&uart_param);
           uart_reg_isr_callback_fun(&USER_UART,5,user_uart_isr_callback);
           if(status)
           {
               puts("uart_module_init err\n");
           }
           if(!status)
           {
               status=uart_module_start(&USER_UART);
               if(!status)
                   user_uart_handle=&USER_UART;
           }
        }
    }
    void user_uart_write(char a)
    {
        if(user_uart_handle)
        {
            user_uart_handle->putbyte(user_uart_handle,a);
        }
        else
        {
            puts("user_uart_write err\n");
        }
    }
    void user_uart_write_repeat(u8 *data,u8 len)
    {
        u8 tmp;
        if((len == 0)||(data == NULL)) return;
        for(tmp = 0;tmp < len; tmp++)
        {
            user_uart_write(*(data+tmp));
        }
    }
   #+END_SRC
   接收串口中，调用打印串口，打印数据时，2组串口的波特率不能一样，
   会导致误以为接收数据丢失。
   打印串口的波特率，要大于接收串口的波特率才行，差距越大越好。

** DAB案子 
   串口接收没有判断数组越界，存在死机风险。

* 20171222
** 源创杰扩音器开关mic
   void microphone_open(u8 mic_gain,u8 mic_gx2);
   void microphone_close(void);
** 实捷BT66-8027
   改用linein音量21级。
** 威益德客户处理问题
   USB串口中断，软件要选择成ASCII发送。
   通话关闭mic声音，通过清空ladc的buff。

* 20171221
** 爱瑞声6905A卡掉线死机
   卡掉线，是layout拉线太长，导致波形不稳定，卡座CLK脚加10K上拉。
   卡上下曲死机，替换志彬cpu_lib_ac690x.a库，解决切模式链表没有清干净。
** 实捷BT66
   替换蓝牙库，空间超了，修改图片资源文件。
   替换VM补丁库，蓝牙会死机，未替换，用回原先的。
   linein失真杂音，未处理，25级。
   #+BEGIN_SRC C
   降音量做法。
            case MSG_SET_LOW36V_MAXVOICE:
                puts("MSG_SET_LOW36V_MAXVOICE\n");
                set_max_analog_vol(MAX_SYS_VOL_L-2,MAX_SYS_VOL_R-2);
                printf("maxl=%0d\n",dac_var.max_analog_vol_l);
                set_sys_vol(dac_var.cur_sys_vol_l, dac_var.cur_sys_vol_r, FADE_OFF);
                break;
            case MSG_SET_HIGH36V_MAXVOICE:
                puts("MSG_SET_HIGH36V_MAXVOICE\n");
                set_max_analog_vol(MAX_SYS_VOL_L,MAX_SYS_VOL_R);
                printf("maxl=%0d\n",dac_var.max_analog_vol_l);
                set_sys_vol(dac_var.cur_sys_vol_l, dac_var.cur_sys_vol_r, FADE_OFF);
                break;
   #+END_SRC
** 汉普6905A样机
   功能修改，培训客户邓工，客户要用新板。
** 鑫闻达69闹钟不醒
   闹钟设置后，不唤醒，复位后才行。
* 20171220
** 爱瑞声6905A插卡死机
   卡为FAT16，格式化之后就可以。
   卡掉线，波形不正常，待查。
** 科普豪U盘挂载失败
   69下正常，46下等待30s后，挂载失败，查不出打印。寄给钧仟。
* 20171219
** 汉普6902A音箱
   测试功能正常，寄给客户了。
** 实捷BT66-8027添加RDS个Siri
   参考灼坤程序，修改，数据为小端。
   替换蓝牙库，可以用。
** 科普豪4602耳机插拔linein死机
   静电原因，软件无法处理。
* 20171218
** 实捷BT66-8027添加RDS和siri
   添加好了，等机子测试，还要加Siri界面。
* 20171215
** 汉普6905A音箱
   出了一个版本给客户测试。
** 华炬芯6905D插充电线唤醒不了
   #+BEGIN_SRC C
   void set_poweroff_wakeup_io()
   {
	     u8 wakeup_io_en = 0;
	     u8 wakeup_edge = 0;
       wakeup_io_en |=  WAKE_UP_PR2;
       wakeup_edge |= EDGE_PR2;     //failling edge
	     soft_poweroff_wakeup_io(wakeup_io_en , wakeup_edge);      
	     charge_mode_detect_ctl(1);///此句会影响到睡眠后，插充电线，唤醒不了
   }
   #+END_SRC
* 20171214
** 汉普6905A音箱
   调试一半
** FCC测试
   V2012-p3版本，BLE测试，频点会偏移2M。替换志彬的库，测试OK。
   公版的FCC，发射功率会小于-6dB，不符合标准，用起华的下载包，能达到接近0dB。
** 汉普乐放音箱
   include_lib文件夹，头文件被改了。
   修改程序，添加BLE特征，用作授权认证。

* 20171213
** 汉普6905A音箱
   鑫凌波--博建--开发。
** 嘉兴格优6901对箱
   第一次开机，配对不上从机。
   改成一定进入配对状态，不能发起回连命令，会导致搜索不到设备。
** 汉普语音识别BLE唤醒APP
   添加语音识别。
** 汉普6905音箱
   添加UUID属性。
* 20171212
** 鑫闻达洗涮涮
   调试摇动灵敏度，
   牙刷摆放，没有固定位置，无法确定固定坐标系。
** 巴达木PC麦
   1.音量值16位，要调整大小端位置，发下来是0x15cf,上传改为mic_vol = 0xcf15;
   2.对局部变量取值，VM的函数，取值一定要是全局变量。

* 20171211
** 尚凌69对箱音质问题
   量DAC输出频响，幅值dB，会有变化。

* 20171208
** 尚凌69对箱
   做全功能蓝牙对箱音箱，第一次连接对箱播歌正常，切模式回连后，音质就会变。
   原本充实变得散了。
** 源创杰ble地址获取错误
   原因是蓝牙配置工具，ble的地址分配配成了random，
   应该用public，这时ble的地址参考EDR地址，才能用程序获取并打印出来。
* 20171207
** 测试盒更新音频文件
   测试盒更新音频文件,wav,32K,16bits,单声道。
** 调节数字音量
   #+BEGIN_SRC C
   #define BT_CHANNEL         DAC_DIGITAL_DVOL///DAC_DIGITAL_AVOL
    void custom_digital_vol_tab(u8 flags)
    {
        u8 i = 0;
        if(flags == 1){
            for( i = 0; i <= DIGITAL_VOL_MAX_L; i++){
                digital_vol_tab_dynamic[i] = digital_vol_tab[i];
            }
    //        memcpy(digital_vol_tab_dynamic, digital_vol_tab, DIGITAL_VOL_MAX_L+1);
        }else{
            for( i = 0; i <= DIGITAL_VOL_MAX_L; i++){
                digital_vol_tab_dynamic[i] = digital_vol_tab[i] * 3;
                ///最大4倍，用5倍时，31级的值会溢出，变为0///
            }
    //        digital_vol_tab_dynamic[30] = 46384;
        }
        for( i = 0; i <= DIGITAL_VOL_MAX_L; i++ ){
            printf("digital_vol_tab_dynamic[%d]:  ",i);
            put_u16hex(digital_vol_tab_dynamic[i]);
            puts("\n");
        }
    }
//    reg_digital_vol_tab((void *)digital_vol_tab);
    reg_digital_vol_tab((void *)digital_vol_tab_dynamic);
   #+END_SRC
* 20171206
** 汉普6902A
   如果定义函数和底层库函数重名，会导致覆盖库里的函数，调用成应用层的函数。
   crc16();底层就有一个。
** 测试盒没有NFC功能
   硬件环境有留，软件没有做。
** APP
   V2.0之后，安卓APP走的是BLE通道，之前走的是SPP通道。
** 海科通话
   蓝牙通话的声音，在30级的时候，还是偏小。
   改用数字音量表
* 20171205
** 威益德获取电话本
   使能pin code之后，配对连接获取不到，回连可以。
   铜霭，改了一个库。
* 20171204
  请假
* 20171201
** 汉普6902
   修板3块
* 20171130
** 汉普6902A车充
   发射芯片没焊好。
** DAB
   蓝牙发射，切换同一个通道，会有POP声，需要添加延时，清空LADC数据。
* 20171129
** 汉普6902A车充
   添加BLE电话功能，17字节校验码存储功能
* 20171128
** wifi--iis输入
   #+BEGIN_SRC C
   dac_channel_on(MUSIC_CHANNEL, FADE_ON);
	 audio_link_init();
	 //audio_link_close(1);
	 dac_set_samplerate(44100,1);
    #if 1
        dac_write((u8 *)buf_addr0,DAC_BUF_LEN);
    #else
        extern int soft_eq_run(u8 *buf, u32 len);
        soft_eq_run((u8 *)buf_addr0, DAC_BUF_LEN);
		    cbuf_write_dac((short*)buf_addr0, DAC_BUF_LEN); //DAC 实时播放
    #endif
    #+END_SRC
* 20171127
** DAB案子
   切模式会串音，是因为自动解mute，ST程序不会一直发送mute导致。
* 20171124
** DAB
   切模式串音问题，BT播放模式，切换一圈后进入FM/DAB，蓝牙播放音乐串音到FM/DAB
** 汉普6902A车充

* 20171123
** DAB
   dac_AmuxGain_en(1);放大linein声音一倍。
   linein声音输入源幅度太小，可设置此项。只能固定放大一倍。
* 20171122
* 20171121
** 汉普车充
   SD和IIC复用，在SD播放高码率的文件，会有掉线情况，此时要限制发送消息的数量。
   避免一下子发送太多，累积在消息池中。
* 20171120
** 汉普车充
   6902A的SD和iic复用，当在sd播放的时候，操作iic时，要等待sd空闲后，才能关闭sd控制器，才操作iic。
* 20171117
** 汉普车充
   12V检测，最多只能做到0.1V的精度。
* 20171116
** BLE发送数据量
   static u32 app_data_send(u8 *data,u16 len)
   底层会有2K的空间，进行分包发送，每包20字节。
   但是不建议使用太大数据量。
   发送速度，跟时间间隔有关。
* 20171115
** 汉普车充
   在调频点的时候，暂停音乐播放。
* 20171114
** 汉普车充
   SD卡和IIC复用，待处理。
** 发射器SDK
   C版晶圆需要打补丁，才能支持无线升级。
* 20171113
** 实捷C26S发射没声音
   QN8027有一分钟自动关闭发射的功能，在初始化的时候会有关闭此功能。
   但是由于I2C同时外挂QN8027和AD2523，发送给QN8027的数据存在AD2523的命令字时，
   data会被AD2523控制到，导致发送给QN8027的数据出错，写错寄存器。
* 20171108
** DAB案子
   切换linein通道，会有上一个通道的尾音，可能底层有个buf没有清除。
   目前改成，在切换通道先发一段静音的buf。
   #+BEGIN_SRC C
   void ladc_isr_callback(void *ladc_buf,u32 buf_flag,u32 buf_len)
   {
      extern u8 switch_aux_channel_flag ;
      if(switch_aux_channel_flag)
      {
        putchar('l');
        for(i=0;i<DAC_SAMPLE_POINT;i++)
        {
            ladc_l[i] = 0;
            ladc_r[i] = 0;
        }
      }
   }
   #+END_SRC
** 威益德死机
   __attribute__((aligned(4)));
   强制地址对齐，方便底层指针转换。

* 20171107
** 伦茨海科46点烟器通话调试
   46配8007，在通话双方同时说话的时候，回声压制不住，会有漏音，听起来有点卡顿的感觉。
   通话回声参数，配3和1400，效果OK
   有一个手机，远端能听到回声尾音，其他手机就没事，此问题客户忽略处理。
* 20171106
** DAB案子
   IIS接收还是不行。
* 20171103
** 汉普音箱
   测试MIX2910功放，3.3V直流偏置正常，没有掉电情况。
** USB-HID
   #+BEGIN_SRC C
   typedef enum
   {
 	     DEVICE_DESCRIPTOR_STR = 0x0,
 	     CONFIG_DESCRIPTOR_STR,
 	     MSD_CONFIG_DESCRIPTOR ,
 	     AUDIO_CONFIG_DESCRIPTOR,
       SPEAKER_CONFIG_DESCRIPTOR,
       MIC_CONFIG_DESCRIPTOR,
 	     HID_CONFIG_DESCRIPTOR,
 	     HID_REPORT_DESCRIPTOR,
 	     LANGUAGE_STRING,
 	     IMANUFACTURE_STRING,
 	     IPRODUCT_STRING,
       ISERIAL_NUMBER_STRING,
 	     AUDIO_VOL,
 	     MIC_VOL,
       MAX_STRING = 14,
   }USB_DES;
   u32 user_set_descriptor(USB_DES index, void * pstring, u32 len);
   ///默认HID按键是调用以下函数：
   {
       os_mutex_pend(&mass_mutex, 0);
       usb_hid_control((u32)*((u32 *)parm));
       os_mutex_post(&mass_mutex);
   } 
   ///函数体是：
   void usb_hid_control(u32 key)
   {
       usb_hid_key(key);//默认发送2byte 码值
       usb_hid_key(0);
   }
   结构体声明：
   extern OS_MUTEX mass_mutex AT(.usb_buf);
   #+END_SRC

* 20171102
** ARGUN
   协议有改动，更改程序，已发出
** 汉普音箱
   触摸按键增加电话控制功能，电量获取换算成百分比，触摸按键灵敏度调到300。
* 20171101
** 汉普音箱
   MIX2909功放会有噗噗声，是在IN脚，维持3.3V的时候，会有1V左右的掉电，后又升回3.3V导致。
   功放产商寄2910的芯片来测试。
* 20171031
** DAB发射器
   出差实捷，调试功能，基本功能都有了，细节问题处理还未解决。
*** 切换模式会有噗声
    切换到DAB模式，会有3声噗声，切换到FM模式，也会有噗声，需要软件处理mute掉。
*** 蓝牙发射突然没有声音，只能重启
    概率很低，很难测试到，其他操作都正常，切换通道都不行。
*** 46的机子回连时，link-key会丢失，导致回连不上
    目前做法是，开机的回连，做成5次。但是会导致进入搜索设备变慢。

* 20171030
** ARGUN
   区分配对状态和连接状态的广播包，修改蓝牙名和MAC地址。
   摇杆数据，没反应，客户更新APP，已OK。
   函数app_data_send()涉及信号量，在没有连接的情况下，会导致调用该函数的线程挂起。
** DAB蓝牙发射器
   选取设备列表，断开重连等功能，还没调试。
* 20171027
** ARGUN
   connect_interval的单位是1.25ms，如果发送太快，可能会导致底层积压数据包，等到间隔时间到了，才一起发送出去。
   adv_interval的单位是0.625ms，
** 汉普BLE音箱
   替换蓝牙库bluetooth_lib.a，不会死机，但是回连不上，手机主动连接，会卡死，取消连接，重新连，能正常。
   替换以前对箱的库cpu_lib_ac690x.a，解决回连不上问题。
* 20171025
** 汉普BLE音箱
*** 汉普音箱在EDR和BLE同时连上后切模式回到蓝牙模式死机
   在初始化蓝牙后，发送蓝牙回连命令死机。
*** 触摸误触
    提高触摸按下门槛，避免干扰。
* 20171024
** 实捷DAB案子
*** 蓝牙再次搜索异常
    __set_inquiry_again_flag(0);///此函数底层没做好，只能置0
    在应用层自己添加，BT_STATUS_INQUIRY_COMPLETE，反馈时，再次搜索就行。
    #+BEGIN_SRC
    case BT_STATUS_INQUIRY_COMPLETE:
		   puts("BT_STATUS_INQUIRY_COMPLETE\n");
		   /*search bluetooth device again*/
       if(BT_STATUS_WAITINT_CONN == get_bt_connect_status()){
          puts("BT_STATUS_WAITINT_CONN\n");
          user_send_cmd_prepare(USER_CTRL_SEARCH_DEVICE,0,NULL);
       } 
		break;
    #+END_SRC
** 汉普车充
*** 在14V供电的情况下打电话时死机
    应该是LDO降压模块，压差太大，从14V降到5V，导致不稳定。
* 20171023
** 实捷DAB案子
*** 蓝牙搜索连接link-key丢失
    第一次连接上后，再次搜索配对连接时，就会出现，重新下载程序，也不行。
    更新振荣发的bluetooth_lib.a，可解决。
** 汉普ble音箱
*** 触摸按键和AD按键分开检测发送
    触摸按键，时不时会反馈，导致AD按键检测不准。
** 飞灵特ARGUN
   更新product-key，生成时用，可用于发行版APP
   #+BEGIN_SRC
   NAME  ：ARGunPro
   VID   ：0xFFFC
   KEY   : 0x3e, 0x9b, 0x7d, 0xb9, 0xbe, 0x69, 0xc2, 0xa5, 0x7c, 0x6c, 0x18, 0x34, 0xb, 0xd9, 0xdf, 0xfe
   MAC   ：FF:FF:00:00:00:01~FF:FF:00:00:00:FF
   #+END_SRC
* 20171020
** 汉普ble音箱
*** 苹果搜索ble名字显示unknown
    由于广播包的数据，不正常导致。
** 实捷DAB案子
*** IIS通信声音不正常
    参考：极性CPOL和相位CPHA，修改IIS的设置。
* 20171019
** 实捷DAB案子
*** IIS通信声音变调
    由于缺失MSCK，DAB自己外挂晶振，和主控自己产生的MSCK，会有相位差，导致声音不同步。
    DAB芯片改用，从主控24M引线，还是不行。

* 20171018
** 实捷DAB案子
*** IIS从机接收不正常
    69系列IIS做从机，必须输出SCLK、LRSCK时钟给其他芯片，不支持输入时钟，
    可理解为只能主动接收数据，不支持被动接收数据。
** 德科创ble部分手机会掉线
   苹果的5、5s、6、6p、红米1s、oppo r11，在连接了2.1后，ble的4.2连接会容易掉线。

* 20171017
** 汉普触摸音箱
   焊点引线到外壳，需要贴块铜皮，增大电容效应的面积，增强抗干扰能力。
** 实捷DAB蓝牙发射
*** 发射伴随哒哒声
    由于串口发送数据太多太过集中，while循环时间过长，导致发射数据卡顿。
*** 蓝牙搜索时获取蓝牙名包出错
    有些方案，在搜索的时候，未连接时，获取的蓝牙名包不正常，振荣处理中。
*** IIS输出板子又有模拟输出
* 20171016
** 实捷DAB蓝牙发射配其他方案音箱会有哒哒声
   寄给振荣分析
*** IIS通信的时钟输出
    目前为stm32输出。可能主控这边不能匹配。16bits数据。
** 汉普6905B蓝牙音箱带触摸
   触摸的引线，经过喇叭和电池，灵敏度会受到影响。
   按键有一个焊盘，应该悬空，但是接地，要改板
   原理图用成6905A的引脚图，DACR对应PA1。
   512K的空间不够，可以修改提示音为单声道，提醒客户后期语音，不能太长。
* 20171014
** 中翔达69蓝牙耳机通话效果
   靓颖电子4款蓝牙耳机通话效果，和建荣的对比。
   比较注重清晰度，音色比建荣较差。
* 20171013
** 汇杰芯蓝牙对箱连接问题
   未连接时，要一直处于能背搜索的状态。
   在匹配过蓝牙对箱后，函数get_total_connect_dev()会一直返回1，导致蓝牙不能被搜索到，
   可改成判断get_bt_connect_status()的蓝牙状态。
* 20171012
** 汉普车充6905C
   在app_server_read_callback()中，会调用2次，第一次调用buffer = 0，buffer_size = 0，要返回buffer_size的大小。
   第二次调用会以上次的buffer_size，填充buffer的内容。
** 狂热者APP开发
   带时钟、闹钟功能的APP。我们提供数据对接，APP开发由客户处理。
   使用TI BLE USB Dongle协议分析抓包，配合电脑端SmartRF Packet Sniffer进行显示。

* 20171011
** 飞灵特6909B用3.3V推灯
   主控3.3V驱动能力较弱，接三极管推灯，可能会影响到电源。
** 汉普车充6905C
   采用新的BLE协议，带频点的设置和读取，电量检测等功能。
* 20171010
** 晶科USB描述符
   区分读卡器名称和声卡名称
   属性--总线已报告设备描述--值
   如果之前识别过，需要先把br17卸载掉，再重启电脑，才就能重新挂载，显示出字符串来。
** 汉普车充
   采用AC6905C + QN8027,带BLE协议。
   耳机检测，电阻改用0R。
** 中翔达i7-6904C对耳蓝牙距离短
   充电座的电线会穿过蓝牙天线，需要用胶纸，将电线紧贴在板子上。
   贴纸刚好盖住蓝牙天线上，不要贴在元件上面。
* 20171009
** 晶科多国语言
   69系列添加多国语言，日语、繁体都可以。
   但是西班牙、阿拉伯的，不行，初始化成功，但是屏幕啥都没显示。
   替换国炜发的font_lib.a，已解决。
   英语之后的语言，采用的都是Unicode小端编码。
* 20170930
** 飞灵特ARGUN
   调试OK
** 飞灵特SuperAR
   增加反馈机制
* 20170929
** 飞灵特ARGUN
   BLE发送是异步操作的，加了个队列发送，上一个发送成功才发送下一个。
   摇杆数据采用AD检测，数据不知道如何组织，发送给APP。
   取值0到0xff，摇杆没动的时候，发的是0x7f。
   采用IO上拉电阻10k,误差比较大。
* 20170928
** 实捷DAB的IIS从机接收
   客户stm32还没有做好，无法调试
** 公司编译器处理中文
   根据.c文件的编码格式，会以文件的编码格式，填充数组。
   可新建文件，保存为Unicode编码，再定义中文数组，就会以Unicode填充该数组。
* 20170927
** 飞灵特ARGUN
   ARGUN协议，没有按照蓝牙标准，发送enable notify给从机，导致我们底层notify通道没有打开。
   而客户用telink主控，支持这样的操作。
*** descriptors
    CHARACTERISTIC_USER_DESCRIPTION, READ,

    CHARACTERISTIC_USER_DESCRIPTION     -->0x2901
    CLIENT_CHARACTERISTIC_CONFIGURATION -->0x2902
    SERVER_CHARACTERISTIC_CONFIGURATION -->0x2903

* 20170926
** 下载工具无法升级
   下载工具需要5V供电，笔记本电压可能达不到5V。
   下载工具挂一个大电容，电阻改大2.7R，可防止板子扯到电源。
** 实捷DAB案子
*** IIS从机输入
** 飞灵特ARGUN
   无法获取notify的句柄，无法发送数据
* 20170925
** BLE读回调执行2次
   app_server_read_callback()调用2次是需要的，
   第一次需要返回正确的长度回去，
   第二次判断buffer指针是否为空，不为空才给buffer赋值。
** 动态修改pin码和蓝牙名
   #+BEGIN_SRC c
   static void bredr_name_custom_handle(char *name)
   {
	     printf("bredr name:%s, len:%d\n",name,strlen(name));
   
       name[0] = 'X';
       name[1] = 'I';
       name[2] = 'N';
       name[3] = '\0';
       __set_pin_code("3693");
   }
   #+END_SRC
** APP发起连接蓝牙2.1 
   用了一个反射的方法实现。
   这个方法在国外的贴子上找到的，可以让客户先上网找一找。
** 69_V2012_p2版本SDK对箱连接
*** 开机自动连接从机
    void bt_discon_complete_handle(u8 *addr , int reason)
    ----reason == 0x04
        ----user_send_cmd_prepare(USER_CTRL_START_CONNEC_VIA_ADDR_STEREO,0,NULL);注释此句，即可不自动连接
*** 概率性连接不了从机
    每隔12秒，发送MSG_BT_STEREO_SEARCH_DEVICE消息，即可。
    搜索时间最长为12秒。

* 20170922
** 飞灵特ARGUN
   AES128 ECB加解密，替换br16_ccm_aes.a，添加aes_ecb_encrypt.c文件。
* 20170921
** 汉普乐放音箱ble协议
   ble协议已调通，音箱功能未确认
** 实捷DAB案子BT_ES
   和stm32采用串口1通信，定义了一个通信的简化版本。
   收音还是没有声音。
** 飞灵特ARGUN
   手动修改profile_data[]，每行第一字节为长度，
   如果需要value，可以在行尾自己加十六进制值，同时修改每行第一个字节为相应长度。

* 20170920
** 汉普乐放音箱ble协议
   ble通信调通。
*** 函数app_server_read_callback() 
   每次获取会执行2次，
   第一次buffer_size为0，实际没有发送数据，
   第二次buffer_size为上一次return的值，实际发送数据
** 实捷DAB案子BT_ES
*** SPI2中断号 #define IRQ_SPI2_IDX       44
    没有SPI通信，实际用串口通信
    收音还是没声音

* 20170919
** 汉普乐放音箱Gatt协议
   定义好协议，抓了profile截图给客户
** 实捷DAB案子BT_ES
   采用STM32+SI4684+AC6901A做蓝牙发射器带DAB数字广播
   调通2个linein通道的发射，蓝牙连接功能
   linein蓝牙发射，如果一个通道没声音，会导致发射完全没声音
   板子收音有问题

* 20170918
** 对箱连接手机播歌后无法配对从机
   V2012-p2版本，有此问题
   替换铜霭发的cpu_lib_ac690x.a，可解决
** 汉普酷走车机BLE音箱
   不能按照小精灵的协议开发
   要重新设计新的协议，待验证
** 对耳蓝牙距离短
   减低sbc的码率，可适当提高
** 内置充电IC充不满
   替换库文件，替换charge.c文件
* 20170916
** IIS播第一个提示音噗一声
   由于IIS传输，需要变采样，变采样的开始阶段，buf数据异常。
   IIS默认44.1kHZ
** 酷走车机BLE
   软件不认我们的设备，连接不上
* 20170915
** 源创杰69对象配对
   v2012-p2版本，连接播歌后，无法再配对从机，需要切换模式才行
   v2011版本无此bug
* 20170914
** 汉普--酷走车机--BLE控制
** 菲林特ARGUN
*** 启赋superAR
*** 先智ARGUN
* 20170913
** 永胜泰6904耳机蓝牙断开，灯状态没改变
   调整设置灯的函数，在每个消息的后面，立马执行。
   可能由于任务切换、中断，导致执行丢失。
** 鑫闻达6905机子linein检测不到
   不同芯片VDDIO在3.3V-3.6V之间，一致性不到。
   LDO_ref的电压永远为1.24V左右，而VDDIO电压为，AD满值，即0x3FF
   可通过判断 LDO_ref 的值大小，即可推出VDDIO电压大小。
   VDDIO为3.3V，LDO_ref为0x178左右。
   VDDIO为3.6V，LDO_ref为0x160左右。
   AD复用linein检测时，最好对LDO_ref分4个区间判断。
* 20170912
** 天地宏69系列RGB灯影响红外
   RGB灯用2ms频率pwm波，推动红灯时，会影响到红外接收。

* 20170911
** 晶科46系列PB9在开机时有数个脉冲
    打VM提示音补丁，可以解决。
** 伦茨耳机开机灯不亮
   采用outputchannel0，没有设置DIE寄存器，默认值有时会不一致导致。
** 晶科69获取文件夹数目
   尝试使用循环下个文件夹，累计文件夹数目。
*** 当前文件夹的序号
    ../../tff.h
    ((*(FIL *)((_FIL_HDL *)(music_operate_mapi->fop_api->cur_lgdev_info->lg_hdl->file_hdl))->hdl).fs_msg.musicdir_counter)

* 20170908
** 输出PLL-12M时钟
    JL_IOMAP->CON1 &= ~(BIT(10)|BIT(9)|BIT(8));
    JL_IOMAP->CON1 |=  (BIT(10)|BIT(9));
	  JL_PORTB->DIR &= ~BIT(0);
	  JL_PORTB->PD  |=  BIT(0);
	  JL_PORTB->PU  |=  BIT(0);
	  JL_PORTB->DIE &= ~BIT(0);
** 动态修改蓝牙名
   static void bredr_name_custom_handle(char *name)
   {
	     printf("bredr name:%s, len:%d\n",name,strlen(name));
       name[0] = 'X';
       name[1] = 'I';
       name[2] = 'N';
       name[3] = '\0';
   } 
** 菲林特AR枪协议
*** 协议1：super AR

*** 协议2：AR GUN

* 20170907
** 科普豪6905C
   U盘和SD卡复用，有部分卡不读，容易掉线
*** 优化方法
    检测前开SD-CLK脚 ~下拉~,修改速率为4(原先为5)。
    硬件上 ~复用脚加对地30p~,CLK脚对地10p，均可。
*** 客户采用复用脚加33p电容对地

* 20170906
** 汉欣诺电话本死机
*** 替换铜霭更新的bluetooth_lib.a，测试已OK
** 巴达木EQ调试没效果
   uart_init(UART_BAUD_RAE);不能在audio_init();之后调用，会导致无法中断接收。

* 20170905
** 汉欣诺
*** 获取电话本出现死机和乱码
    只要改动user_ctrl_prompt_tone_play()就会出现，铜霭处理中

* 20170904
** 内置充电IC外挂大容量电池
*** 改精度，调阈值，不起作用
    #define BUILD_POINT_THRESHOLD_VALUE   2
    #define CHARGE_MAX_CNT                110 * 60 * 2
*** 改用充满计数，计数5次以上，才认为充满
    可能电池充电，电压上升不线性导致
    对charge_full_deal();函数的执行，进行计数5次以上，才能执行
** 汉欣诺6901车机
*** 蓝牙获取电话本出现死机和乱码
*** TODO 获取手机拨打电话出去的号码
     - State "TODO"       from ""           [2017-09-04 周一 19:24]

* 20170831
** 笔记本电脑win8win10蓝牙连不上
** 洗刷刷LSM6DS3驱动
*** 静止时的数据，和样机基本一样
*** 摇动的数据，难对比

* 20170830
** 爱瑞声6907C内置充电外挂大容量电池
软件按固定间隔检测电压变化，大容量电池的电压变化很慢，调整电压检测分辨率
** 蓝牙电感料，会影响到sniff的功耗

* 20170829
** 华炬芯6904A耳机
*** 进power down死机问题
PR1做充电唤醒，PR2做按键唤醒，同时开2个唤醒脚，
会导致有些芯片出现进power down死机
*** 开机吱声
振荣修改cpu_lib_ac690x.a解决
*** TODO low_pwr_deal函数在蓝牙没连接时会执行
- State "TODO"       from ""           [2017-08-30 周三 18:54]
但是公版SDK测试，不会执行到

* 20170828
** 华炬芯6904耳机死机、开机吱声
*** 死机是因为 *BT_LOW_POWER_MODE* 模式引起
*** 开机吱声，开机初始化 *dac_init_api* 的电源时引起


* 20170817
** 联巨兴：人声消除，导致低音消失

* 20170818
** 鑫闻达：QN8035收音效果差，功放D类影响，晶振引时钟15p
** 科普豪：1621推屏，模拟SPI，时序延时要加大
** TODO TODO：
- State "TODO"       from ""           [2017-08-19 周六 11:03]
联巨兴：人声消除效果确认？
电影协会
宿舍安排

* 20170819
** TODO 人声消除低音处理
- State "TODO"       from ""           [2017-08-19 周六 11:02]
低音炮内部电路 始终要把双声道输入耦合成单声道的 那样立体感才强
可尝试加入EQ处理生成2.1声道
** 天博智4602按键不起作用
机子用一段时间后，机子开不了机，USB无法识别。
用烧写器重烧后，正常工作。
待查软件问题

* 20170821
** 鑫闻达BLE洗刷刷项目
使用DA380三轴加速度传感器，跟视频的停车守卫采用一样。
搭建DA380的驱动代码
** 华立S36
修改呼吸灯的控制

* 20170822
** 人声消除低音消失
寄机子给影志,山景的机子需要修板
** 鑫闻达BLE洗刷刷项目
抓包，调试BLE连接，BLE连接成功

* 20170823
** 鑫闻达数据包发送
原本使用ST的LSM6DS3芯片，陀螺仪和加速度一体
DA380缺失陀螺仪数据，目前填包处理

* 20170824
** 联巨兴人声消除
板子修好，寄给影志，处理低音效果
** 鑫闻达洗刷刷
调试DA380的采样频率，量程，发送数据的大小，优化效果
6909的板子，已修好

* 20170825
** 鑫闻达洗刷刷
准备2款传感器，ST的LSM6DS3和invensense的MPU6050
调试功耗，和蓝牙名与蓝牙地址处理
*** 功耗注意点
1.系统48MHz
2.DAC关
3.Bredr关，只开BLE
4.FM关
5.DA380设置为低功耗模式
6.电源DCDC模式
7.自动关机处理
8.推灯亮度处理
*** 升级问题
无线升级没有做好
*** 4.2的sleep模式
还没有做好
*** 低压flash
用纽扣电池供电，需认批次，选用低压flash，才能正常

