#+TITLE:       JL work diary record
#+AUTHOR:      辛佳斌(lawrence)
#+DATE:        [2017-02-13 周一 16:31]
#+EMAIL:       lawrencejiabin@163.com
#+KEYWORDS:    the page keywords, e.g. for the XHTML meta tag
#+LANGUAGE:    language for HTML, e.g. ‘en’ (org-export-default-language)
#+TODO:        TODO

#+SEQ_TODO: TODO(T!) | DONE(D@)3  CANCELED(C@/!)  
#+SEQ_TODO: REPORT(r) BUG(b) KNOWNCAUSE(k) | FIXED(f)
   #+BEGIN_SRC c
   #+END_SRC



* 20210316

* 20210315
** BLE低功耗唤醒
   sniff的唤醒退出延时，待测试
   唤醒后重新进入sniff的延时，在1ms左右，范围会波动，最高10ms，是无法改动的
** 四博696X
   音箱SDK-OTA功能，没做
** 春苗695X
   音频跟歌词，合在一个文件里DRF后缀
   在audio_dec_file里插入信号量控制文件指针方式
   TF卡剩余容量，珠海改库，fget_free_space("storage/udisk0/C", &space);
   总容量参考PC模式msd.c
   
* 20210312
** 中翔达科奈信
   有机子搜不到蓝牙，打印是trim异常，烧录器挑不出来，比例未知，寄珠海
   长按6s不回连手机，会自动配对上其他机子，程序流程问题，已处理。
** BLE的MTU修改
   目前MTU的大小不可配，编译生成的,有宏，但关联地方比较多，静态的，一般为248
   client默认是会主动发起MTU交换
** 天浪6369F2
   080的SDK开了pb-gatt，出现偶尔1-2秒scan不到包，跟珠海沟通
   高温RF补丁，ble_disable_wait_enable为0，为影响到硬件timer-pwm的输出抖动，为1正常，未验证
** 春苗695X
   DRF文件，音频跟歌词在同一个文件里。

* 20210311
** 博创昱
   珠海改程序给客户测试，目前可以，但又引入新的问题，关机功耗大

* 20210310
** 天浪6369F2
   高温scan不到包，080补丁已发出
** 春苗695X
   获取tf卡容量还有剩余容量的，等珠海接口
** 博创昱961
   短接VOUT到地会出现烧芯片现象
   分2种情况:
   1、关盖下已升压短路，直接烧芯片
   2、开盖下一直短路知道超时进入关盖准备升压，烧芯片

* 20210309
** 保留电池图标不要通话功能
   __set_disable_sco_flag(1);
** 科奈信961
   案子代码已发出
** 天浪6369F2
   商务沟通是否需要换货
   RF问题，寄板子给华悦
** 汇杰芯63
   缓存buf的读写流程会数据会乱
   缓存buf跟读写buf，要分开
** 春苗695X
   SPI推屏跟解码音乐冲突,任务优先级问题跟手表一样，还会
   查SPI DMA方式

* 20210308
** 天浪6369F2H
   天猫精灵灯，灯泡温度会上升到120度以上
   出现搜不到遥控器包数据，天猫精灵连接不上等现象,重新上电又可以了
   珠海协助中
** 科奈信961
   调试中
** 四博6969
   120的SDK,客户的安卓手机播歌走48KHz，这边复现不到

* 20210306
  加班出差一天
** 巴达木伽德仕6976D
   内置触摸出现放久无反应，自动开关机，反应不灵敏
   弹片接触问题，变形跟氧化，用导电胶水测试

* 20210305
** 蓝牙芯片性能
   高温测试能支持到105度不断连
   AC6[3]13 A [2] [H]
   -----|---------|---|-->[H] Temperture H = -40～105℃ / T = -40～125℃ / 空 = -40～85℃
   -----|---------|
   -----|---------|----->[2] Flash Size 2 = 2Mbits / 4 = 4Mbits
   -----|
   -----|--------------->[3] Flash Voltage : 1.8V / 9 : 2.4V
   现有的芯片高温版本，只有AC6368A2H和AC6369F2H。如果有其他型号需要用高压版本，请反馈。
** 天浪6369F2
   高温断连，周一过来处理

* 20210304
** 中翔达科奈信961
   强充改成通信失败多少次，才启动
   呼吸灯，灯效果已OK
   NTC已OK
   charge_err_timer = sys_timeout_add(NULL, charge_err_delay_deal, 30 * 1000);///测到有关机命令撞见开机状态,导致不关机

* 20210303
** 中翔达科奈信961
   A1027不带霍尔的仓功能调试
   强充过程无法检测耳机插拔
** 曲速6369C
   遥控器发的包，搜不到
   客户自己改了遥控器的发射代码，已OK
   珠海查的原因，是发射前端杂散太大。

* 20210302
  请假一天
  考驾照

* 20210301
** 曲速636X
   pwm输出，无映射固定IO输出的，修改duty为0，会有一周期高电平
   gpio_set_direction(hw_port, 1);
   JL_TIMERx->CNT = JL_TIMERx->PRD;

* 20210226
** 杰理之家
   693系列后通用，692不支持ai，且没有部分692的功能
** 德科创HID
   636的多媒体遥控器，建业支持
   692X的USB-hid，应该是dma大小配置错误了,等珠海改库
** 科普豪692-AI
   没有HFP协议断开的命令，等海华处理

* 20210225
** 源创杰
   692X对接天天酷跑，10分钟后，会反应慢，还没看
   6969透传的，UUID无法接收数据，建议客户先用NRF看
** 科普豪692X
   AI的SDK，没有断开再重连的命令
** 曲速6369
   mesh多加2个元素，就会爆ram，但是ram的空间还剩很多
   [Error] :[MESH-buf]net_buf_alloc_len():171: Failed to get free buffer
   #define MESH_ADV_BUFFER_COUNT           10//3
   珠海建议改这个，没测试

* 20210224
** BLE物理层LE
   LE 1Mbps
   LE 2Mbps
   LE Coded：Bluetooth Long Range(BLR) :外加天线+空旷地方+s8+br18+连接状态 可以稳定200米，极限500米
   Mesh现只支持1M uncoded，其它ble应用支持全PHY（1M/2M/S2/S8）
** 汉欣诺695X
   音箱带彩屏，暂无可用的SDK
   IIS和BLE的编译问题，已发方法给客户
   杰理之家的APP，已发客户
** 文晟智能6369C
   生产有部分芯片，开机搜不到蓝牙，但是烧录器挑选不出来，寄珠海分析
   有些芯片，全擦重新下载程序，可以搜到了
   几乎所有芯片都有-30K的频偏

* 20210223
** 羽恒635X
   传图像的时候，30ms的频率，偶尔会有100ms的卡包时间
   const uint64_t config_btctler_le_features = LE_ENCRYPTION | LE_DATA_PACKET_LENGTH_EXTENSION;
   const int config_btctler_le_acl_packet_length = 251;//27;
   const int config_btctler_le_slave_conn_update_winden = 2500;//range:100 to 2500
   #define CONFIG_BT_NORMAL_HZ	            (160 * 1000000L)

* 20210222
** USB批量传输流控
   usb_disable_ep(usb_id, MSD_BULK_EP_OUT);//关闭端点，挂起端点
   usb_enable_ep(usb_id, MSD_BULK_EP_OUT);
   usb_g_bulk_read(usb_id, MSD_BULK_EP_OUT, buffer, len, 1);//不调用获取当前包，下一包就会自动回NAK
** 腾进达6954C
   屏跟TP的驱动，已完成

* 20210219
** 63系列双备份升级
   https://github.com/Jieli-Tech/fw-AC63_BT_SDK/blob/master/doc/%E6%9D%B0%E7%90%86%E5%8F%8C%E5%A4%87%E4%BB%BD%E5%8D%87%E7%BA%A7%E4%BB%8B%E7%BB%8D.md
** 国华6368
   遥控器被连接后，还能广播数据
   2个sever的做法，底层有bug，需要将hw_num改成3，才能2个手机连上，暂不处理
   目前改成，被连接后，改成beacon的做法，不让第二个手机连接

* 20210218
** TPlink 6368
   主机client读server没有数据反馈
   SDK接口正常，写了个demo已发出

* 20210204-20210217
  春节放假

* 20210203
** BLE流控
   att_server_flow_enable
   只针对write，对write_without_response和notify，不起作用
** 曲速6369
   mesh低功耗流程demo，已发出
   暂时关闭mesh时，可进入低功耗。

* 20210202
** 立米6954C
   gsensor硬件IIC读不到数据,循环几次处理，可能是上电不稳定导致
** 腾进达6954C
   gsensor驱动不起来，逻辑分析仪抓取波形都正常，芯片不响应

* 20210201
** 腾进达6954C
   TS10使用3线双通道9bits的屏，目前不支持SPI 9bits的屏
   可以使用4线双通道8bits的屏
** 佳琪6954C
   打电话死机，ram不够
   要把TP驱动的代码数组写上const，指定到flash上

* 20210131
** 恒大6926A
   红米note8连接BLE，会出现配对失败，自动断连，概率约5%
   测试友商方案，2个HID的样机，也有概率出现
** 腾进达6954C
   屏驱动还没调好

* 20210129
** 友商手表功耗
   纯BLE的200多 两颗芯片的1MA左右
** LCD屏脚
   有些屏脚 RS/DCX/A0
** 腾进达TS10
   板子驱动调试，TP已经可以
   屏是双通道的，还没好
** 佳琪LJ728
   功耗，UI，灭屏时间等功能

* 20210128
** 猫王6926C
   部分机子蓝牙性能差
   提供了dut程序给客户，客户去天线厂尝试处理天线匹配效率
** 佳琪6954C
   LJ728样机板子功耗处理，目前能达到1mA，已提供给客户
   处理其他反馈的软件问题
   更换DCDC型号，TP驱动需要修改睡眠指令
   友商双蓝牙方案，一个BLE加一个EDR的产品。也是1mA左右的功耗

* 20210127
  出差半天
** 腾进达6954C
   帮客户处理编译下载问题，更换4M的flash
** 佳琪6954C
   处理功耗，TP睡眠命令不起作用，已处理
   功耗还有1.5mA
   连续反馈端口唤醒会导致异常中断

* 20210126
** 芯鸿光636X
   BLE同时主从，敏贤更新库，还没测试
** 曲速6369F
   性能测试，功率测试，频偏测试，已处理
   公版SDK，4010的性能测试不过，需要珠海搞
   天猫精灵加gatt，灯模型，待跟珠海沟通

* 20210125
** 芯鸿光636X
   获取传统蓝牙手机的rssi，敏贤更新库，客户测试OK
   BLE同时主从，单独连可以，第二个连会丢失事件。

* 20210122
** 63系列spp添加pin_code
   extern void __set_simple_pair_flag(u8 flag);
   __set_simple_pair_flag(0);/*提供接口外部设置配对方式,1使能简易配对。0使用pin code, 会使用配置文件的值*/
** 曲速6369F
   5路pwm的demo,已发出
   PC4上电会会高一下，是maskrom中的IO，无法修改
** 巴达木6351D
   按键按下，芯片正常工作，功耗高，达5-7mA
   跑LDO的状态，就是这个功耗
   加DCDC，可以降低，但是达不到样品的功耗
   样品功耗，打字状态300uA，常连接不打字是9uA。

* 20210121
** 尚凌 6368
   抖音神器，拍照录音视频键值，各个iPhone型号无法兼容，暂不处理，后续有样机再调试
** 乐众云 6351D
   pr口使用，已发出
** 巴达木 6351D
   按键不松开也能进sniff，已支持

* 20210120
** 6351D键盘功耗
   BLE功耗是100uA，对应2s的发送间隔
   现在edr和ble的功耗是差不多的
   按键按下，正常工作，功耗达到5mA-7mA，无法处理
** 佳琪6954C
   案子调试，对接客户的APP，还在搭框架

* 20210119
** 佳琪6954C
   APP对接中
* 20210118
** 63验证
   6369F，PWM5到底是哪个口
   仿真，调试，烧录，升级方式
** TPlink
   支持客户开发
** 浩博高
   6368B USB BLE音频dongle
** 腾进达6954C
   手表培训

* 20210115
** 佳琪6954C
   修板子，验证驱动，着手搞APP

* 20210114
** 云康宝6368A4
   双区备份
** 天浪6368A2
   单区备份剩余空间
   file:E:\63\1Bug\OTA\OTA计算空间
** 芯鸿光636
   HID，获取传统蓝牙RSSI，下个版本留接口
** 云然6351
   RTC，用音箱的SDK
** 浩博高6368A
   BLE语音过USB评估
** 巴达木6351D
   键盘按键倒数第二个row扫描不到有问题
   PC6有问题，需要改标准原理图

* 20210113
** 手表UI图片
   png、bmp图片，UI工具都会转换成rgb565的格式，再进行压缩，整体的平均压缩率范围大概是30%~40%
   比如一张240x240的图片，保存为rgb565格式，一个像素点占2字节，不压缩的话大小是240x240x2=115200,大概115k左右，
   rgb565经过压缩后大小跟像素的颜色有关系，颜色单一的话，压缩率比较高，颜色比较丰富的话，压缩率比较低
** 佳琪695X
   LJ728驱动已完成，功能支持中
** 组创636X
   OTA断连需要点2次，已完成
** 猫王6926C
   P3项目，功能修改，已发出
** 天浪6368
   MAC地址递增烧录，还没验证
   烧录器在线更新到V2.23.3
   1拖2支持

* 20210112
  出差1天
** 佳琪LJ728
   案子驱动调试

* 20210111
** 63系列
   通用邀请码授权码：sAWDI4l1-rhF8mZYE-WFmU2C1w-75vDs2wy
** 组创690X
   LG手机BLE连不上，已OK
** 天浪636N
   内置充电跟按键冲突，处理中
** 新智造6933C
   outputchannel 2异常重启，协助中

* 20210108
** 猫王6926C
   PVXE项目，做样，出现开不了机，验证是内部flash坏了
** 汇杰芯697X
   anc板级通话音量调0，下次通话没声音，调不了音量，已处理
** 博建697X
   敲击耳机放回仓，会误触发双击发起Siri，改了个demo给客户，验证中

* 20210107
** 巴达木联奥6969
   天猫精灵灯模型，还是不行
** 猫王6926C
   PVXE项目，做样，出现开不了机，寄机子过来在查
** 内部951
   强充流程，跟珠海在验证中

* 20210106
** 组创6933C
   生产有5个芯片搜不到蓝牙，IQ失败，RF引脚绑定不正常，已告知客户
** 组创6366C
   替换6311的案子，出现几个问题，已处理
** 组创690X
   连LG手机，NRF的软件测试生产固件是正常的，客户APP还连不上，联系APP工程处理
** 易路发692X
   PC mic录音，20s后会有杂音，换库处理，客户验证中
** 巴达木联奥636X
   天猫精灵灯模型，验证中

* 20210105
** 猫王6926C
   P3功能修改，已发出
** 威益德690X
   单模BLE案子苹果手机连不上，无法开关BLE，已处理
** 组创690X
   LG手机连BLE会自动断连，公版已改好，但是客户那边反馈还不行，跟进中
** 组创6366C
   检测不到电量，还没看
** 巴达木联奥6369
   mesh还没看
** 也杨961+6976
   低电无法充电，还没看
* 20210104
** 请假1天

