#+TITLE:       Git use record
#+AUTHOR:      辛佳斌(lawrence)
#+DATE:        [2017-02-13 周一 16:31]
#+EMAIL:       lawrencejiabin@163.com
#+KEYWORDS:    the page keywords, e.g. for the XHTML meta tag
#+LANGUAGE:    language for HTML, e.g. ‘en’ (org-export-default-language)
#+TODO:        TODO

#+SEQ_TODO: TODO(T!) | DONE(D@)3  CANCELED(C@/!)  
#+SEQ_TODO: REPORT(r) BUG(b) KNOWNCAUSE(k) | FIXED(f)

* 下载
  网页上按F12，看源代码，找下载网址URL
  如https://github.com/git-for-windows/git/releases/download/v2.15.0.windows.1/Git-2.15.0-64-bit.exe
  使用迅雷下载。

* 安装
  看网络教程，使用git bash即可。

* 配置
** SSH
*** $ ssh-keygen -t rsa -C "lawrencejiabin@163.com"
   open C:\Users\Administrator.PCOS-1707211525\.ssh\id_rsa.pub 文件
   将文件内容添加到github。
*** $ ssh -T git@github.com
   验证是否连通。
*** C:\Users\Administrator.PCOS-1707211525\.gitconfig
    [credential]
	      helper = store
** git本地账户配置 
   $ git config --global user.name "lawrencejiabin"
   $ git config --global user.email "lawrencejiabin@163.com"
   $ git config --list
** git bash显示
   支持UTF-8格式文件，其他格式文件会显示乱码。

* 本地仓库
** $ git init
   新建本地仓库。
** $ git remote add origin https://github.com/lawrencejiabin/GTD-org.git
   将本地仓库和远程仓库，建立同步。
** $ git push -u origin master
   第一次推送master分支时，加上了 –u参数，
   Git不但会把本地的master分支内容推送的远程新的master分支，
   还会把本地的master分支和远程的master分支关联起来。

* 远程仓库
  在github自己建仓库。
  记住仓库URL：https://github.com/lawrencejiabin/GTD-org.git
** $ git clone https://github.com/lawrencejiabin/GTD-org.git 
   远程仓库克隆到本地仓库

** README
   每个仓库，最好在根目录保留README文件。

* 同步文件
** $ git status
   查看本地仓库，修改记录
** $ git add operating-record.org
   添加要同步的文件
** $ git add study/*
   添加目录
** $ git add xxx
*** $ git add -A .
    一次添加所有改变的文件。注意 -A 选项后面还有一个句点。 
*** $ git add -A
    表示添加所有内容， 
*** $ git add . 
    表示添加新文件和编辑过的文件,不包括删除的文件; 
*** $ git add -u 
    表示添加编辑或者删除的文件，不包括新添加的文件
** $ git commit -m "create repositories"
   提交到暂存区
** $ git push origin master
   推送到远程仓库
** $ git log
   查看log信息。
* 抓取远程仓库
** 本地无更新
*** git fetch origin master
    从远程的origin仓库的master分支下载代码到本地的master
*** git merge origin/master
** 本地有更新
*** git fetch origin master:temp 
    从远程的origin仓库的master分支下载到本地并新建一个分支temp
*** git diff temp
    比较master分支和temp分支的不同
*** git merge temp
    合并temp分支到master分支
*** git branch -d temp
    删除temp
** 分支抓取
*** git fetch origin branch1:branch2
    首先执行上面的fetch操作，使用远程branch1分支在本地创建branch2(但不会切换到该分支),
    如果本地不存在branch2分支, 则会自动创建一个新的branch2分支,
    如果本地存在branch2分支, 并且是`fast forward', 则自动合并两个分支, 否则, 会阻止以上操作.

* 查看log-diff
** $ git diff git.org
   可查看目前文件，与最后一个版本的差异。

* 版本回退
** $ git log -–pretty=oneline
   每个log，只要1行显示。
** $ git reflog
   获取版本号。
** $ git reset --hard 版本号
   通过版本号，回退到某个版本上
** $ git reset  --hard HEAD^ 
   回退到上一个版本
*** $ git reset --hard HEAD^^
    那么如果要回退到上上个版本只需把HEAD^ 改成 HEAD^以此类推。
*** $ git reset --hard HEAD~100
    如果要回退到前100个版本的话

* 撤销删除
** $ git checkout -- readme.txt  
   把readme.txt文件在工作区做的修改全部撤销,撤销修改就回到添加暂存区后的状态
** $ git reset HEAD <file>
   文件已经add到暂存区，还没提交到仓库中，可使用此命令撤销，暂存区的内容。
   不会改变本地文件的内容。
** $ rm <file> ; git commit -m "";
   删除本地文件，再执行提交就可以了，就彻底从版本库中删掉了此文件。
** $ rm <file> ; git checkout -- <file> ;
   删除本地文件，还没有commit，就可以用checkout，从仓库中恢复本地文件。

* 分支
  HEAD指向的就是当前分支,master才是指向提交的分支。
** $ git checkout -b branch1 
   命令加上 –b 参数表示创建并切换到分支branch1。
   等同于 _$ git branch branch1; git checkout branch1;_
** $ git branch
   查看分支，会列出所有的分支，当前分支前面会添加一个星号。
** $ git merge branch1
   用于合并指定分支到当前分支上。
   先执行 _$ git checkout master_,再执行此命令，就会将branch1合并到master。
** $ git branch –d branch1
   删除分支branch1。
** $ git merge branch1; 出现合并冲突
   $ cat file_name;查看文件内容。
   用<<<<<<< ，=======，>>>>>>>标记出不同分支的内容，
   其中<<<< HEAD是指主分支修改的内容，>>>>>branch1 是指branch1上修改的内容
   $ git log; 查看合并后的log，为2个分支的log合并。
** 分支管理
   通常合并分支时，git一般使用”Fast forward”模式，在这种模式下，删除分支后，会丢掉分支信息.
*** $ git merge --no-ff -m "messages" branch1
    $ git branch -d branch1,删除branch1后，会保留branch1分支的log，合并到master中。
*** $ git log --graph --pretty=oneline --abbrev-commit
    以树图显示log，包含分支log。

** 分支策略
   首先master主分支应该是非常稳定的，也就是用来发布新版本，一般情况下不允许在上面干活。
   干活一般情况下在新建的分支上干活，
   干完后，或者说分支代码稳定后可以合并到主分支master上来。
   master分支是主分支，因此要时刻与远程同步。
   一些修复bug分支不需要推送到远程去，可以先合并到主分支上，然后把主分支master推送到远程去 .

** 远程分支
*** $ git remote -v
    查看远程分支信息
    远程库的默认名称是origin
*** $ git push <远程主机名> <本地分支名>:<远程分支名>
    $ git push origin DAB06:DAB06;将本地分支推送到远程分支上。
*** $ git branch -vv   
    查看当前的本地分支与远程分支的关联关系.

** 抓取分支
*** $ git checkout –b dev origin/dev
    创建远程的origin的dev分支到本地来。
    就可以在本地dev分支上做开发了，开发完成后把dev分支推送到远程库时。
*** $ git branch --set-upstream dev origin/dev
    $ git branch --set-upstream-to=origin/dev
    $ git branch -vv
    指定本地dev分支与远程origin/dev分支的链接
*** $ git pull
    抓取远程分支，到本地分支上。
    冲突的地方，会合并到本地文件中，需要我们手动编辑文件。
*** $ git push origin dev
    解决冲突后，推送到远程分支dev上。

** 隐藏工作现场
   比如在开发中接到一个404 bug时候，我们可以创建一个404分支来修复它。
   但是，当前的dev分支上的工作还没有提交，并不是我不想提交，而是工作进行到一半时候，我们还无法提交。
   Git还提供了一个stash功能，可以把当前工作现场 ”隐藏起来”，等以后恢复现场后继续工作。
*** $ git stash
    将当前分支的工作现场隐藏起来，就不需要commit，也能保存起来。
    $ git status;查看当前分支时，就会变成是干净的。
*** $ git checkout master;git checkout -b issue-404
    首先我们要确定在那个分支上修复bug，比如我现在是在主分支master上来修复的，现在我要在master分支上创建一个临时分支。
    即可在临时分支上修改,修改后提交即可。
    $ git checkout master;git merge --no-ff -m "merge bug fix 404" issue-404;git branch -d issue-404;
    合并到主分支之后，就可以删除这个临时分支了。
    $ git checkout dev;回到当初隐藏工作现场的分支上。
*** $ git stash list 
    查看隐藏工作现场列表。
*** $ git stash apply
    恢复后，stash内容并不删除。你需要使用命令git stash drop来删除。
*** $ git stash drop
    删除stash list内容。
*** $ git stash pop
    恢复的同时把stash内容也删除了。

* 忽略文件.gitignore
